### ISSUE TITLE
Split up TS catalog function packages

### ISSUE THREAD

**Issue by frankfarzan** [GoogleContainerTools/kpt#1026]
Currently there's a single NPM package for all TS functions in the catalog:
https://github.com/GoogleContainerTools/kpt-functions-catalog/tree/master/functions/ts

There are good reasons to split it up into multiple packages:

1. Distinguish 1st party vs contrib functions. Example of latter: https://github.com/GoogleContainerTools/kpt-functions-catalog/pull/101
2. Make dependency management easier. For example, the in the above PR, one function depends on `rw`, but it requires changing Dockerfile for other functions.

**Comment by mikebz** [comment]
CC @mengqiy

**Comment by mengqiy** [comment]
This is already done.
