### ISSUE TITLE
Evaluate best merge strategy for kpt pkg update

### ISSUE THREAD

**Issue by mortent** [GoogleContainerTools/kpt#1033]
We currently use 'fast-forward` as the default update strategy. We should consider if `resource-merge` is a more appropriate default as it leverages the openapi schema for better merge.

**Comment by phanimarupaka** [comment]
@mortent Isn't `resource-merge` the obvious choice?

**Comment by mortent** [comment]
We have made a decision that `resource-merge` will be the default.
