### ISSUE TITLE
`kpt pkg get` ignores some files when downloading the package

### ISSUE THREAD

**Issue by janetkuo** [GoogleContainerTools/kpt#1044]
The [`.gitlab-ci.yml`](https://github.com/GoogleCloudPlatform/solutions-modern-cicd-anthos/blob/app-delivery/starter-repos/app-template/.gitlab-ci.yml) file is missing from the downloaded [package](https://github.com/GoogleCloudPlatform/solutions-modern-cicd-anthos/blob/app-delivery/starter-repos/app-template) file. 

To reproduce:
```
$ kpt pkg get https://github.com/GoogleCloudPlatform/solutions-modern-cicd-anthos.git/starter-repos/app-template@app-delivery .
$ cat .gitlab-ci.yml
cat: .gitlab-ci.yml: No such file or directory
```

@frankfarzan

**Comment by mortent** [comment]
This is a problem where kpt tries to avoid copying the `.git` folder during `kpt pkg get`, but end up ignoring all files/folder that start with `.git`. I have a fix in https://github.com/kubernetes-sigs/kustomize/pull/3030
