### ISSUE TITLE
"config.kubernetes.io/x" annotation documentation lacking

### ISSUE THREAD

**Issue by yhrn** [GoogleContainerTools/kpt#1064]
I'm having some trouble understanding how kpt treats the `config.kubernetes.io/x` annotations:

1. I can't find an exhaustive list on what annotations the various kpt commands care about
1. I can't find a complete specification for the schema for the value of `config.kubernetes.io/function`
1. The release notes for kpt 0.34.0 says that kpt live now respects `config.k8s.io/local-config` but I can only get it to respect `config.kubernetes.io/local-config`

**Comment by mortent** [comment]
@yhrn We are working on providing better documentation. The mention of `config.k8s.io/local-config` in the release notes is a typo. I have corrected it now. Thanks for reporting it.

**Comment by bgrant0607** [comment]
@mortent There's a test in cli-utils that references config.kubernetes.io/local-config:
https://github.com/kubernetes-sigs/cli-utils/blob/dd1b1986577af7506376b963e6b821edbe575633/pkg/config/initoptions_test.go#L58

But, yes, searching for "local-config annotation" doesn't yield anything relevant, so documentation would help

**Comment by droot** [comment]
We added reference docs for all the annotations [here](https://kpt.dev/reference/annotations/). So closing this issue.
