### ISSUE TITLE
Environment variables not available in fn container

### ISSUE THREAD

**Issue by yhrn** [GoogleContainerTools/kpt#1065]
According to the [documentation](https://googlecontainertools.github.io/kpt/reference/fn/run/#environment-variables) "`kpt` exports all local environment variables except the TMPDIR variable when launching a docker container", however if I list all environment variables from inside the container there are only a few set (PATH, HOSTNAME, LOG_TO_STDERR, STRUCTURED_RESULTS, HOME) when running the function, imperatively or declaratively.

I also can't find any way of explicitly set environment variables to pass to the function so I'm not sure how this is supposed to work or if I'm misunderstanding something.

I'm writing a Go function, btw.

**Comment by Shell32-Natsu** [comment]
A flag `-e/--env` has been added to `kpt fn run` .
```
-e, --env stringArray       a list of environment variables to be used by functions
```

The doc hasn't been updated. Will update it soon.
