### ISSUE TITLE
Blueprint use case with kustomize does not apply

### ISSUE THREAD

**Issue by blaggacao** [GoogleContainerTools/kpt#1075]
I kind of expected this, though it would be interesting to know if this is on the radar:

```console
$ kpt live apply .
Error: can't find scope for resource Kustomization.kustomize.config.k8s.io
```

I'm following roughly this layout: https://googlecontainertools.github.io/kpt/guides/producer/blueprint/

Even if it would work, how would I be able to tell kpt to use `instance` and _not_ `upstream`?

**Comment by mortent** [comment]
@blaggacao Yeah, this is something we are aware of and we want to fix. We do support the `config.kubernetes.io/local-config` annotation that will cause the `kpt live` commands to ignore the resource. But I found out today that kustomize doesn't seem to allow a `metadata.annotations` section in the `kustomization.yaml` file, so we do need to handle kustomization files special.

**Comment by blaggacao** [comment]
@mortent I think rather kustomize should compky to k8s resource spec! I've seen another issue related but caouldn't find it any more. The gist of it also was: Kustomization resources should allow to deklare `meta`.

/cc @monopole - not sure whom is really to ping.

**Comment by yhrn** [comment]
I'm also interested in having Kustomize integrated with `kpt live`, e.g. point to a kustomization instead of a directory for apply/preview. I found an old umbrella isse #407 and also #845, which may or may not be related. Has there been any recent progress on this?

**Comment by mortent** [comment]
@blaggacao I have created an issue in the kustomize project to allow `metadata.annotations`: https://github.com/kubernetes-sigs/kustomize/issues/3043. Regardless, we probably want to ignore ignore the kustomize group+kind combination in kpt so users don't need to annotate `kustomization.yaml` files.

We are working on a better integration between kustomize and kpt. I don't think we will want to support using `kpt live` against a kustomization like what is possible with kubectl. We do want to have composable tools that can be used together, so I think doing something like `kustomize build <folder> | kpt live apply` is more aligned with that philosophy. And this works today. If there any issues with this that I'm not aware of, I would be interested in learning more.

**Comment by blaggacao** [comment]
@mortent I have tried piping and I agree that it seems more in line with kpt philosophy. If I remember correctly, the problem I encountered was that at the sitenof invocation, the inventory file was not detected. Since kustomize _seems_ to also flitlrt with the `live` subcommands I fugured I would rather just wait for things to arrange and stars to align.

**Comment by blaggacao** [comment]
More precisely:

```console
$ kustomize build deploy/playground | kpt live apply   ⎈ ➜ k3d-playground|default

Fatal error: Package uninitialized. Please run "init" command.

The package needs to be initialized to generate the template
which will store state for resource sets. This state is
necessary to perform functionality such as deleting an entire
package or automatically deleting omitted resources (pruning).
```

I have placed files all over the place

```console
$ tree deploy                                          ⎈ ➜ k3d-playground|default
deploy
├── Krmfile  # kustomize Krmfile
├── playground
│   ├── inventory-template.yaml  # inventory template
│   ├── Kptfile # Kptfile
│   ├── kustomization.yaml
│   └── README.md
└── upstream
    ├── aedir-ui
    │   ├── deployment.yml
    │   ├── kustomization.yaml
    │   └── service.yml
    ├── component
    │   ├── component.yml
    │   ├── kustomization.yml
    │   └── service.yml
    ├── consumer
    │   ├── kustomization.yaml
    │   └── namespace.yml
    ├── kustomization.yaml
    └── provider
        ├── kustomization.yaml
        └── namespace.yml
```

**Comment by mortent** [comment]
So it looks like you have the inventory-template.yaml file among the resources. If you just run `kustomize build deploy/playground`, do you see the inventory-template.yaml resource in the output? If it is there, this should work.

**Comment by blaggacao** [comment]
@mortent Negative:

```console
$ kustomize build playground | rg inventory
```

(I also double checked with naked eye)

**Comment by blaggacao** [comment]
I think you are right! Thank you! My previous comment was bogus. So as for this issue, it looks as if the only actionable thing would be to document it?
