### ISSUE TITLE
Support Starlib for Starlark runtime

### ISSUE THREAD

**Issue by yhrn** [GoogleContainerTools/kpt#1083]
I'm trying to write a Starlark Kpt function and realized I needed regex and md5 support. [Starlib](https://github.com/qri-io/starlib) seems to have what I need but I can't load the modules:

```python
load("re.star", "re")
```
just yields "error: load not implemented by this application".

Is this something you might consider supporting?

I'm sorry if this is already supported, I'm new to Starlark so I might be missing something.

**Comment by halvards** [comment]
I came across the same issue while trying to manipulate yaml in a block string (nested yaml) using Starlark.

Example: Set values in the `data.mesh` field in this ConfigMap: https://cloud.google.com/traffic-director/docs/set-up-gke-pods-auto#configuring_the_sidecar_injector
