### ISSUE TITLE
helm-template becomes helm-inflator

### ISSUE THREAD

**Issue by monopole** [GoogleContainerTools/kpt#1089]
in https://github.com/GoogleContainerTools/kpt-functions-catalog/tree/master/examples/helm-template

helm-template becomes helm-inflator

image name, directory name, catalog entry etc.

per

https://docs.google.com/document/d/1ttiXl1aM_doIpSIfMvKYZbeSurPclW8mz4okchppdzQ/edit#heading=h.mtn7cmif2y6

**Comment by Shell32-Natsu** [comment]
Will do this after #945
