### ISSUE TITLE
Unable to pull packages from master branch?

### ISSUE THREAD

**Issue by bmenasha** [GoogleContainerTools/kpt#1102]
The blueprint walkthrough says this command should work: 

> kpt pkg get https://github.com/GoogleContainerTools/kpt.git/package-examples/mysql-kustomize mysql
error: failed to clone git repo: failed to clone git repo: trouble fetching submodules for master, please run 'git clone <REPO>; stat <DIR/SUBDIR>' to verify credentials: exit status 128

It does when I supply a version tag: 

> kpt pkg get https://github.com/GoogleContainerTools/kpt.git/package-examples/mysql-kustomize@v0.34.0 mysql

But fails when that tag is not supplied or is supplied as @master which kpt says is the default

> kpt pkg get https://github.com/GoogleContainerTools/kpt.git/package-examples/helloworld-set@master helloworld
error: failed to clone git repo: failed to clone git repo: trouble fetching submodules for master, please run 'git clone <REPO>; stat <DIR/SUBDIR>' to verify credentials: exit status 128

i'm running kpt  0.34.0
thanks

**Comment by StarpTech** [comment]
Related https://github.com/GoogleContainerTools/kpt/issues/1115. @bmenasha Please check if the `master` branch really exists. Github changed `master` to `main`.

**Comment by StarpTech** [comment]
What are you trying? You forgot to pass the full qualified URL `https://github.com/GoogleContainerTools/kpt.git`

**Comment by StarpTech** [comment]
I think the reason is that the kpt repository contains submodules. They don't use `--recurse-submodules`. I'd use a different repo for demo purposes.

**Comment by shawnho1018** [comment]
Also encounter the same issue. Look forward to the solution +1.

**Comment by phanimarupaka** [comment]
https://github.com/GoogleContainerTools/kpt/releases/tag/v0.35.0
