### ISSUE TITLE
Declare autosetters for subpackages

### ISSUE THREAD

**Issue by yhrn** [GoogleContainerTools/kpt#1107]
This relates to #1051 and the proposed design referenced there.

It would be able to declare a setter in a parent package to act as a autosetter for descendant packages.

An example use case for this is when you, by conventions, have a resource name suffix or namespace exposed as a setter with some specific name for all your packages. Then it would be nice if you could just specify this value once in a top level "umbrella" package that depends on multiple other packages.

I guess you can achieve something similar with environment variables but that wouldn't be very declarative.

**Comment by phanimarupaka** [comment]
This feature has been implemented and released. https://googlecontainertools.github.io/kpt/concepts/setters/
