### ISSUE TITLE
Kpt and JSON Patches.

### ISSUE THREAD

**Issue by opsroller** [GoogleContainerTools/kpt#1112]
When using kpt to do anything setter related, the tool throws exceptions if you have yaml file with jsonpatch entries.

My current solution has been to rename the jsonpatch files to *.patch, however when I do this is breaks my ability to add setters to the patch files.

**Comment by phanimarupaka** [comment]
@opsroller Thank you for filing the issue. Could you please provide with detailed examples of your yaml files(with json patches) and your command flow to reproduce the error.

Setters depend on yaml comments and json doesn't allow comments. There is some friction in this area.

**Comment by phanimarupaka** [comment]
Closing this issue due to no response. Please refer to new version of setters(https://catalog.kpt.dev/apply-setters/v0.1/). Reopen the issue if you still have questions.
