### ISSUE TITLE
Fallback to main when master isn't available.

### ISSUE THREAD

**Issue by StarpTech** [GoogleContainerTools/kpt#1115]
https://github.com/github/renaming#new-repositories-use-main-as-default-branch-name

Fallback to main when master isn't available.

Maybe https://git-scm.com/docs/git-symbolic-ref is an option.

**Comment by StarpTech** [comment]
Related https://github.com/GoogleContainerTools/kpt/issues/1102

**Comment by phanimarupaka** [comment]
https://github.com/GoogleContainerTools/kpt/releases/tag/v0.35.0
