### ISSUE TITLE
Feature or doc request

### ISSUE THREAD

**Issue by yelhouti** [GoogleContainerTools/kpt#1124]
Hi I didn't fine a way to specify the default strategy for kpt update in the kptfile, is this possible? If so please how, I found nothing here https://googlecontainertools.github.io/kpt/api-reference/kptfile/ 
And if not can we add this feature please if no strategy is specified in the command line.

**Comment by mortent** [comment]
@yelhouti You are correct that there is no way to set this on a Kpt package today. I agree that it would be useful if this was part of the Kptfile so it wouldn't need to be specified on the command line every time.

**Comment by yelhouti** [comment]
@mortent thanks for adding this to the backlog, I see that there is a whole one for config as data which sounds great. Good luck :)

**Comment by droot** [comment]
Closing this since we addressed this in current version of kpt.
