### ISSUE TITLE
Support Kpt setters for Skaffold

### ISSUE THREAD

**Issue by irvifa** [GoogleContainerTools/kpt#1129]
type: feature Request
Description:
Currently Kustomize does not support any templating like this and Skaffold doesn't have any other suitable mechanism for doing this. It'll be a good feature if Skaffold gaining support for Kpt setters with templated values.

**Comment by mikebz** [comment]
@irvifa I'd love to understand exactly what you are trying to do.  Are you running kpt or kustomize ?  What templates are you looking to use?

**Comment by irvifa** [comment]
I run skaffold to create overlay and then use the kpt to create template for several different environments, eg: prod, test, dev.

**Comment by yuwenma** [comment]
The Skaffold v2 accepts kpt setters. close this issue
