### ISSUE TITLE
Migrate off deprecated travis-ci.org

### ISSUE THREAD

**Issue by prachirp** [GoogleContainerTools/kpt#1153]
Both kpt and kpt-functions-sdk use travis-ci.org, which is deprecated. We should migrate off, taking into account guidance from the Github Admin team.

**Comment by prachirp** [comment]
Will keep this open to address travis + kpt-functions-sdk

**Comment by mikebz** [comment]
@prachirp can you tell me where there are traces of travis in that repo?  I don't see it...
I also checked the function catalog and nothing there either.

Thank you for your help 🙇

**Comment by prachirp** [comment]
@mikebz You're right, I also verified that we don't use travis in that repo. 🙂
