### ISSUE TITLE
apply should support continuing on error

### ISSUE THREAD

**Issue by mortent** [GoogleContainerTools/kpt#1161]
kpt live apply currently errors out if something goes wrong, for example if a resource can't be applied.

**Comment by seans3** [comment]
I believe this will be fixed once we upgrade to include a newer version of `kubectl` (>= 1.18) in `go.mod`.

**Comment by mortent** [comment]
See also https://github.com/kubernetes-sigs/cli-utils/issues/266

**Comment by Liujingfang1** [comment]
The implementation for continuing on error is done via https://github.com/kubernetes-sigs/cli-utils/pull/286.
There are some follow up changes that need to be done.
- Add e2e test to show it can continue applying when encountering errors  /cc @seans3 
- Skip wait tasks for resources that failed in apply https://github.com/kubernetes-sigs/cli-utils/issues/290
