### ISSUE TITLE
Hermetic helm function

### ISSUE THREAD

**Issue by frankfarzan** [GoogleContainerTools/kpt#1181]
It's desirable to run functions hermetically and have all dependencies baked in a self-contained docker image. This issue is to explore and design this for helm generator functions.

**Comment by mortent** [comment]
This blog post is interesting: https://squaremo.dev/posts/using-helm-with-kpt/

**Comment by natasha41575** [comment]
I believe this is resolved by the new render-helm-chart function. Please reopen if I'm mistaken.
