### ISSUE TITLE
Release ts-functions-v0.1.3

### ISSUE THREAD

**Issue by prachirp** [GoogleContainerTools/kpt#1182]
Getting some errors running helm e2e tests related to the refactor. Suspect there's a bug in parsing arguments.

testcase: kpt_helm_template_remote_imperative_expected_args
fetching package example-configs from https://github.com/GoogleContainerTools/kpt-functions-sdk to example-configs
[ERROR] Helm template command results in error: Error: expected at most two arguments, unexpected arguments: bitnami/redis, chart-repo, bitnami, chart-repo-url, https://charts.bitnami.com/bitnami

cc @Shell32-Natsu

**Comment by Shell32-Natsu** [comment]
What the arguments are you using for the function?

**Comment by prachirp** [comment]
I just ran e2e tests in kpt-functions-catalog on Mac using kpt 0.35.0

Multiple tests show errors. The error above is in the `kpt_helm_template_remote_imperative_expected_args` test.
`./tests/helm_template.sh`

**Comment by Shell32-Natsu** [comment]
Are you using the latest helm function image? I am not sure is it released. I cannot reproduce the issue on my linux.

**Comment by prachirp** [comment]
Good point, I was not using the new image. Let's repurpose this issue. Can you do a catalog ts-functions-v0.1.2 release?

**Comment by Shell32-Natsu** [comment]
Will try to do it today.

**Comment by Shell32-Natsu** [comment]
Done. Please try latest image. @prachirp
