### ISSUE TITLE
Identify dev lifecycle of a kpt function

### ISSUE THREAD

**Issue by droot** [GoogleContainerTools/kpt#1196]
Identify the day0 and day-n steps in the dev/test/publish lifecycle of a kpt function and figure out a way to organize code, unit tests, e2e tests and CI/Publishing pipeline steps.

**Comment by mikebz** [comment]
What are the remaining items here?  The title seems like a research spike but I think we have done almost all of the documentation already.  Maybe rename and add the list of items that we have done and yet to do?
