### ISSUE TITLE
Curated function catalog: policy-controller-validate

### ISSUE THREAD

**Issue by mengqiy** [GoogleContainerTools/kpt#1199]
Catalog: Validation

Migrate function policy-controller-validate from the sdk repo to the catalog repo.
Ensure it has:
- [x] Enough test coverage
- [x] CI
- [x] Building and publishing pipeline
- [x] Documentation

It enforces OPA constraints on input objects. The constraints are also passed as part of the input to the function.

**Comment by mikebz** [comment]
@mengqiy I have updated the bullet list to a check list.
