### ISSUE TITLE
Support Meta Function

### ISSUE THREAD

**Issue by mengqiy** [GoogleContainerTools/kpt#1202]
Meta functions operate on the pipeline declaration.
We need to have a detailed design for it.

**Comment by mikebz** [comment]
adding also area/hydrate because this I believe affects both.
cc @droot

**Comment by mikebz** [comment]
@droot since we have this in the v1alpha2 milestone via #1494, does this also need to be slated for alpha2?

**Comment by mengqiy** [comment]
This task is done.
