### ISSUE TITLE
Curated function catalog: set-annotation

### ISSUE THREAD

**Issue by mengqiy** [GoogleContainerTools/kpt#1205]
Catalog: Basic Transformation

After https://github.com/kubernetes-sigs/kustomize/issues/3095 is done, we should be able to use the converter to get the fn.
But we still need to have the build and publish pipeline for it.

**Comment by mikebz** [comment]
Kustomize ticket is done now.

**Comment by Shell32-Natsu** [comment]
https://github.com/GoogleContainerTools/kpt-functions-catalog/pull/164
