### ISSUE TITLE
create a provider for a given *rest.Config

### ISSUE THREAD

**Issue by Liujingfang1** [GoogleContainerTools/kpt#1212]
This is to support the ConfigSync, the kpt live apply library should be able to create a provider for a given `*rest.Config`.

**Comment by Liujingfang1** [comment]
I dig more into the code and figure out a working approach for the current apply library in ConfigSync. It is not necessary to create a provider/applier for a given *rest.Config.

1. When ConfigSync reconciler is run in a pod, the current apply library can set up the incluster kubeconfig correctly.
2. During unit test for ConfigSync, we can bring up a test environment from `controller-runtime`. It gives us a `*rest.Config`. Then we apply some hacks to convert the `*rest.Config` to a local kubeconfig file. This kubeconfig file is used through setting the environment variable `KUBECONFIG`.

Since this logic is more lated to ConfigSync testing, it will be put into the ConfigSync repo.

/cc @mortent  @seans3

**Comment by mikebz** [comment]
@Liujingfang1 does it make sense to keep this open?  Is the hack above temporary?

**Comment by Liujingfang1** [comment]
I think we can close it. The working approach is not a hack. We just need to figure out a proper way for testing this.
