### ISSUE TITLE
Design proposal for consumption of OpenAPI

### ISSUE THREAD

**Issue by phanimarupaka** [GoogleContainerTools/kpt#1235]
Use Cases for consumption of OpenAPI document, this includes (but probably not limited to):
1. Use by functions require type information (e.g. setNamespace). Such functions also require additional metadata such as ref maps which is related to this discussion.
2. Use by kpt package merging strategies
3. Search/Replace

**Comment by natasha41575** [comment]
will be covered by https://github.com/GoogleContainerTools/kpt/issues/1521
