### ISSUE TITLE
Question: Recommended pattern for dealing with inventory-template files when publishing kpt packages?

### ISSUE THREAD

**Issue by jlewi** [GoogleContainerTools/kpt#1236]
When publishing kpt packages what is the recommended pattern for dealing with the inventory template files?

I can think of two

1. Don't check in the inventory-template files and require users run `kpt live init`
1. Check in the inventory-template file parameterized by kpt setters so that each instance of a package gets a unique inventory file

Any suggestions about which pattern is better?

**Comment by frankfarzan** [comment]
As the publisher of an upstream package meant to be wildly reused (as opposed to a package customized for a specific team's use), I would recommend approach 1 above. In general, we intend for different functionality in kpt to be decoupled as much as possible. For example, you can take advantage of the packaging functionality, but use a different mechansim for apply (e.g. using `kubectl` or server-side applier, etc.).


@seans3 @mortent

**Comment by frankfarzan** [comment]
Please reopen, if this didn't answer your questions. Also feel free to use other channels for questions:

https://googlecontainertools.github.io/kpt/contact/
