### ISSUE TITLE
The `helm-template` links are broken

### ISSUE THREAD

**Issue by yuwenma** [GoogleContainerTools/kpt#1250]
All "Example", "Source", "Typescript SDK" result in 404 page not found for "helm-template".
https://googlecontainertools.github.io/kpt/guides/consumer/function/catalog/generators/#generator-functions

**Comment by yuwenma** [comment]
Is [helm-inflator](https://github.com/GoogleContainerTools/kpt-functions-catalog/tree/master/examples/helm-inflator) the new link?

**Comment by Shell32-Natsu** [comment]
There is a PR for it https://github.com/GoogleContainerTools/kpt/pull/1226. But we haven't released the helm-inflator yet so the merge is held.

**Comment by Shell32-Natsu** [comment]
helm-inflator has been released and the doc has updated.
