### ISSUE TITLE
Build a simple e2e test tool for function catalog

### ISSUE THREAD

**Issue by Shell32-Natsu** [GoogleContainerTools/kpt#1259]
Part of #1251. Blocker for #1253

**Comment by seans3** [comment]
Have a look at what `kpt live` uses. It's simple with `createTestSuite` bringing up a cluster with helper functions `assertContains` to check output strings. Contact me if you have questions:

https://github.com/GoogleContainerTools/kpt/blob/master/e2e/live/end-to-end-test.sh

**Comment by Shell32-Natsu** [comment]
Thanks, will take a look!
