### ISSUE TITLE
Reorganize TS functions in catalog

### ISSUE THREAD

**Issue by Shell32-Natsu** [GoogleContainerTools/kpt#1262]
Now we have 4 TS functions in the functions catalog repo. Per repo structure that we desire, these functions should be put into different directory and make each function self-contained.

Functions:
 - helm-inflator
 - istioctl-analyze
 - kubeval
 - sops

**Comment by mengqiy** [comment]
We should be able to easily build a single TS function. Currently we rely on kpt-functions-sdk to build [all of the functions with the same tag](https://github.com/GoogleContainerTools/kpt-functions-sdk/blob/030b943e718af706b354ffd6ad5e3de583398984/ts/create-kpt-functions/src/cmd/docker_create.ts#L63-L75). There is no way to build a specific TS function with a tag.
We can do that for golang functions. e.g. `CURRENT_FUNCTION=set-namespace TAG=v1.2.3 make func-build`.

**Comment by Shell32-Natsu** [comment]
I think split the TS functions to separate directory may make building single function work.
