### ISSUE TITLE
error: yaml: mapping values are not allowed in this context when setting a value that ends with ":"

### ISSUE THREAD

**Issue by taisph** [GoogleContainerTools/kpt#1297]
When I attempt to set a value that ends with ":" like below, I get the error "error: yaml: mapping values are not allowed in this context".

```
kpt cfg set . my_prefix "prefix:"
```

The value is used in a deployment manifest environment variable like below, which is perfectly valid.

```yaml
env:
- name: MY_PREFIX
  value: "prefix:"
```

Attempting to quote the value given to kpt adds the quotes to the env value as well, causing the app consuming the value to complain.

kpt version 0.36.1 (gcloud sdk)

**Comment by mikebz** [comment]
@natasha41575 @runewake2 can one of you take a quick look at this and see if this repros for you?

**Comment by mikebz** [comment]
the issue here might be in the lower level libraries that kpt is using.

**Comment by natasha41575** [comment]
issue is reproducible, I'm looking into it

**Comment by natasha41575** [comment]
This has been fixed in the underlying kyaml library and will be available in the next release.
