### ISSUE TITLE
Regression: pruning fails for ResourceGroup inventory object

### ISSUE THREAD

**Issue by seans3** [GoogleContainerTools/kpt#1306]
* After a recent PR: https://github.com/kubernetes-sigs/cli-utils/pull/291, pruning fails for `ResourceGroup` inventory object after migration.

Steps to reproduce:
1. set environment variable `export RESOURCE_GROUP_INVENTORY=1`
2. start/restart cluster with kind: `kind delete cluster; kind create cluster`
3. setup the "app": `cp -f e2e/live/testdata/template-rg-namespace.yaml e2e/live/testdata/migrate-case-1a/inventory-template.yaml`
5. apply the "app" with ConfigMap inventory: `kpt live apply e2e/live/testdata/migrate-case-1a`
6. migrate the "app" to ResouceGroup: `kpt live migrate e2e/live/testdata/migrate-case-1a`
6. copy Kptfile to next version: `cp -f e2e/live/testdata/migrate-case-1a/Kptfile e2e/live/testdata/migrate-case-1b`
7. apply/prune the next version of the "app":  `kpt live apply e2e/live/testdata/migrate-case-1b`

Output:
```
namespace/test-rg-namespace unchanged
pod/pod-b unchanged
pod/pod-c unchanged
pod/pod-d created
4 resource(s) applied. 1 created, 3 unchanged, 0 configured, 0 failed
pod/pod-c prune skipped
pod/pod-b prune skipped
pod/pod-a prune skipped
namespace/test-rg-namespace prune skipped
0 resource(s) pruned, 4 skipped, 0 failed
```

All the resources are erroneously `prune skipped`

Expected Output:
```
namespace/test-rg-namespace unchanged
pod/pod-b unchanged
pod/pod-c unchanged
pod/pod-d created
4 resource(s) applied. 1 created, 3 unchanged, 0 configured, 0 failed
pod/pod-a pruned
1 resource(s) pruned, 0 skipped, 0 failed
```

Reason: It looks like a new `CanPrune` function is erroneously identifying all resources as having a different inventory object
```
I1215 16:24:38.369507 1266578 prune.go:230] skip pruning object that doesn't belong to current inventory: 5b339645-7b28-4de2-a1f9-5f5ce0763140
pod/pod-c prune skipped
I1215 16:24:38.371694 1266578 prune.go:230] skip pruning object that doesn't belong to current inventory: 1c16ea30-5583-499a-a0ea-1283e4292f13
pod/pod-b prune skipped
I1215 16:24:38.373388 1266578 prune.go:230] skip pruning object that doesn't belong to current inventory: 506cc2ed-6aba-4d7c-a55c-966a21d4b8cf
pod/pod-a prune skipped
I1215 16:24:38.374488 1266578 prune.go:230] skip pruning object that doesn't belong to current inventory: 02c9183e-7903-4b35-9af1-986b5eb0154a

```

**Comment by Liujingfang1** [comment]
Since the `owning-inventory` annotation is added, we need to update the value for this annotation during migration.
