### ISSUE TITLE
KPT live apply assumes no status is successful

### ISSUE THREAD

**Issue by fsommar** [GoogleContainerTools/kpt#1312]
We've seen instances where `kpt live apply` assumes that a resource is successfully created and reconciled, when in reality it is not. What I believe happened was that the resource was created and due to a controller slowdown, the status subresource was never set. Thus, without any status field, KPT assumes the resource to have been successfully reconciled. Normally the status subresource would be populated with the ready condition unset, and KPT treats that resource as unreconciled as expected.

My expectation is that `kpt live apply` should block reconciliation until the status is ready for resources that have a ready condition. I understand, however, that it's non-trivial as having a conditions field in the status subresource doesn't guarantee that there's a ready condition (nor reconciling/stalled). This is somewhat related to #452 where the ready condition was first acknowledged by KPT.

Am I correct in my interpretation of the [recommendation for CRDs](https://googlecontainertools.github.io/kpt/reference/live/apply/#recommendations-for-crds) that having an `observedGeneration` field in the status would automatically solve this? Or is it still timing-dependent on first creation, when the status has not been set yet? If KPT reads the CRD to figure out what status fields to expect, then I'd assume there's no dependency on timing (but only observed generation would work; not conditions since they're not cemented in the CRD).

This interaction happened to be between [KCC](https://github.com/GoogleCloudPlatform/k8s-config-connector/) and KPT, but it can happen to any resource.

---

Here's an ordered list to clarify the chronology of the events:

1. `kpt live apply .`
2. *MyResource my-resource is created*
3. KPT reads `my-resource.status` and there are no conditions that indicate problems
4. *MyResource my-resource is current*
5. The MyResource controller starts reconciling and sets a non-ready condition.

The 5th step needs to happen before step 3, otherwise we end up in this state where the reconciliation thinks the resource is current.

**Comment by mikebz** [comment]
@seans3 @mortent you are the experts here I believe.

**Comment by mortent** [comment]
@fsommar So the challenge here is that `kpt live` doesn't have any way to discover which conditions (if any) are used by a resource. The openapi schema can tell us whether the resource has a `conditions` field in the status object, but it doesn't contain information about which conditions will be set by the controller or the semantics of those conditions.

So what `kpt live` does today, is to assume that any resource without any conditions (and that isn't a "known" type) is already reconciled. This is to make sure that resources that doesn't have conditions doesn't end up being stuck in `InProgress` forever. But as you have discovered, the challenge with this is that it becomes a race between the controller adding conditions and `kpt live` polling the resource. The solution to this is to use the `observedGeneration` pattern, as it allows `kpt live` (or any other observer of the resource) to know whether the controller have seen the latest changes to the resources and therefore have updated the status. 

Every resource has the `metadata.Generation` field that is set to 1 the first time the resource is created and then incremented every time there is a change to the `spec` of the resource. With the `observedGeneration` pattern, the controller just copies the value from `metadata.Generation` into `status.ObservedGeneration` on every reconcile. For `kpt live` on newly created resources, it means that if it sees that the `metadata.Generation` is 1 and the `status.ObservedGeneration` is 0, then we know the controller hasn't seen the resource yet and thus the status must be `InProgress`.

We are aware that there are some issues when using KCC resources with `kpt live` and we are working with the KCC team to find a solution.

**Comment by fsommar** [comment]
@mortent Using the `observedGeneration` pattern would avoid the race since `kpt live` looks up the structure of the resource to determine whether it has a `status.observedGeneration` field? If that's already the case, then I believe we can close this and follow up on the changes for KCC elsewhere.

**Comment by mortent** [comment]
@fsommar Yeah, kpt do check the `observedGeneration` field on the resource.
