### ISSUE TITLE
Package Publishers

### ISSUE THREAD

**Issue by sbellan** [GoogleContainerTools/kpt#1313]
The command in the image says `kpt init` but the correct command is `kpt pkg init`

<img width="613" alt="image" src="https://user-images.githubusercontent.com/428882/102584172-c51c6800-40ba-11eb-931a-fbde4128821b.png">

**Comment by mikebz** [comment]
@etefera can you please take a look and fix?

**Comment by etefera** [comment]
Thanks for noticing! There's a PR out now to fix that.
