### ISSUE TITLE
create arm64 binary 

### ISSUE THREAD

**Issue by jstrachan** [GoogleContainerTools/kpt#1319]
any chance we could have a `kpt` binary release for arm64 too please?

**Comment by mikebz** [comment]
@runewake2 is this something you can help with?

**Comment by Shell32-Natsu** [comment]
Here is the PR that added ARM builds to kustomize https://github.com/kubernetes-sigs/kustomize/pull/3088

**Comment by mortent** [comment]
I created a PR to add arm64 arch to goreleaser: https://github.com/GoogleContainerTools/kpt/pull/1320
