### ISSUE TITLE
Handling of hidden directories in kpt get

### ISSUE THREAD

**Issue by msonnleitner** [GoogleContainerTools/kpt#1323]
When using `kpt pkg get` it seems that hidden directories are ignored.

As an example, I tried to include some Github Actions into a package, which are by convention located in `.github/workflows`. Locally it works without problems, as Github workflow files are just YAML files, which can be used and edited with `kpt`

So I have two issues:

- As I am new to kpt, I thought it might be good idea to include some Github workflows into the package. Is is OK to do that or an abuse according to `kpt`?
- If it is not an abuse, is there any possibility to fetch hidden directories such as `.github`?

This is probably related to https://github.com/GoogleContainerTools/kpt/issues/517, just in this case I want to "un-ignore" hidden directories.

I have created a repo, which can be used to reproduce this if needed:
https://github.com/msonnleitner/kpttest

**Comment by mortent** [comment]
@msonnleitner There shouldn't be any reason why files in `.github/workflows` should be ignored, so I think this is a bug. I will take a look.

**Comment by msonnleitner** [comment]
added a repo to reproduce if needed

**Comment by mortent** [comment]
@msonnleitner I tried this with the latest version of kpt (v0.37.1) and it does fetch the hidden `.github` directory. Can you tell me which version of kpt you are using?
I know we had an issue a while back that might related to this, where we tried to exclude the `.git` folder, but ended up excluding every older starting with `.git`. But that was fixed a month or two ago.

**Comment by msonnleitner** [comment]
@mortent Maybe it is an OS-related issue, on my MacOS machine it is not working, tried it with 0.34.0 and 0.37.1.

However, using Google Cloud Shell, (which has Linux and 0.36.1), it works as expected.

**Comment by msonnleitner** [comment]
oh well, It tried it again, it works after all. Sorry for that, it seems I just had a problem with my shell aliases :S

**Comment by hdoinfodation** [comment]
Hi @mortent, not sure if I should create a new issue or not. But I tried to fetch the .github/workflows directory directly, but always ended up fetching the whole parent directory before it or the command even fails. This only applies for folders that starts with '.git' other hidden folders do not have this problem.
Example:
```
kpt pkg get https://github.com/GoogleContainerTools/kpt/.github/workflows ./
fetching package hub/workflows from https://github.com/GoogleContainerTools/kpt to workflows
error: missing subdirectory hub/workflows in repo https://github.com/GoogleContainerTools/kpt at ref master
: lstat /tmp/kpt-get-782815941/hub/workflows: no such file or directory
```

**Comment by mikebz** [comment]
@hdoinfodation it seems to me that .git is something that can be special cased.  My guess is that the reason why that is bombing out is that .git got yanked out.

**Comment by mikebz** [comment]
@runewake2 might be a fairly small PR for you to tackle here.  LMK when you have cycles to check this out.

**Comment by natasha41575** [comment]
I can pick this up, I've found the relevant area of code
