### ISSUE TITLE
gcloud.core.project autosetter failing in v0.36.x and v0.37.x

### ISSUE THREAD

**Issue by sidpalas** [GoogleContainerTools/kpt#1337]
I was trying to use kpt as a part of the kubeflow setup (https://www.kubeflow.org/docs/gke/deploy/management-setup/) and ran into some errors associated with the gcloud.core.project autosetter.

Specifically, this command:
```
kpt pkg get https://github.com/kubeflow/gcp-blueprints.git/management@v1.2.0 /PATH/TO/DIR
```

returns the error:
```
failed to set "gcloud.core.project" automatically in package "management" with error: setter "gcloud.core.project" is not found
```

Reverting to v0.35.0 fixes this error. 

This is my first time using `kpt`, so hopefully it is not just user error on my part!

**Comment by phanimarupaka** [comment]
@sidpalas Are you on the latest version on kpt ? Make sure you are using v0.37.1 https://github.com/GoogleContainerTools/kpt/releases/tag/v0.37.1

**Comment by sidpalas** [comment]
Hi @phanimarupaka -- I am on `v0.37.1`:

```
➜  kpt-test kpt version
0.37.1
➜  kpt-test kpt pkg get https://github.com/kubeflow/gcp-blueprints.git/management@v1.2.0 ./
fetching package /management from https://github.com/kubeflow/gcp-blueprints to management
failed to set "gcloud.core.project" automatically in package "management" with error: setter "gcloud.core.project" is not found
```

**Comment by phanimarupaka** [comment]
@sidpalas Strange. I am on the same version on kpt but not able to reproduce it.

```
$ kpt version
0.37.1
$ kpt pkg get https://github.com/kubeflow/gcp-blueprints.git/management@v1.2.0 ./
fetching package /management from https://github.com/kubeflow/gcp-blueprints to management
```

I think this might be because of some issues with environment. Can you restart your shell and try again.

**Comment by sidpalas** [comment]
Hmm... I just reinstalled from source with:

```
GO111MODULE=on go get -v github.com/GoogleContainerTools/kpt@v0.37.1
```

and used that binary and got the same error...

I'm on MacOS Catalina 10.15.7 in case that matters.

**Comment by phanimarupaka** [comment]
@sidpalas Can you try the following and see if it works fine.

`kpt pkg get https://github.com/kubeflow/gcp-blueprints.git/management/instance@v1.2.0 ./`

**Comment by sidpalas** [comment]
Hi @phanimarupaka -- that does work without issue!

However, it only gets the content in the `/management/instance` subdirectory. Here is a comparison of the file tree:

```
➜  kpt-test tree management
management
├── Kptfile
├── Makefile
├── README.md
└── instance
    ├── Kptfile
    ├── README.md
    ├── cluster
    │   └── kustomization.yaml
    ├── cnrm-install-iam
    │   └── kustomization.yaml
    ├── cnrm-install-services
    │   └── kustomization.yaml
    ├── cnrm-install-system
    │   └── kustomization.yaml
    └── managed-project
        ├── README.md
        └── iam.yaml

6 directories, 11 files
➜  kpt-test tree instance
instance
├── Kptfile
├── README.md
├── cluster
│   └── kustomization.yaml
├── cnrm-install-iam
│   └── kustomization.yaml
├── cnrm-install-services
│   └── kustomization.yaml
├── cnrm-install-system
│   └── kustomization.yaml
└── managed-project
    ├── README.md
    └── iam.yaml

5 directories, 8 files
```

**Comment by phanimarupaka** [comment]
@sidpalas Yes. I am trying to debug the issue on your end. Can you paste the output of this command.

`printenv | grep KPT`

**Comment by sidpalas** [comment]
No environment variables are returned when I run `printenv | grep KPT`

**Comment by phanimarupaka** [comment]
@sidpalas I am not sure what's going on for following reasons
1. Me and other team members did the same thing as you but could not reproduce the issue.
2. If it was a global issue, then kubeflow team would have already escalated it which they didn't. 

Wondering what could be the issue.

**Comment by sidpalas** [comment]
Hmm... yeah not sure what is going on here. I can confirm that at least one other user also encountered this error while attempting to set up Kubeflow (based on a discussion in the Kubeflow Slack).

I also was able to run `v0.37.1` in a container and did not get any error:
```
docker run \
  -v $PWD/:/tmp \
  gcr.io/kpt-dev/kpt:v0.37.1 \
  pkg get https://github.com/kubeflow/gcp-blueprints.git/management@v1.2.0 ./tmp
```

Anyways, thanks for the efforts to try and track down the issue!

**Comment by sidpalas** [comment]
In case this helps future debugging efforts:

I saw this error for:
v0.36.x, v0.37.x (installed from source)
v0.37.1 (installed with homebrew)

I did not see this error:
v0.35.0 (installed from source)
v0.37.1 (running official docker image `gcr.io/kpt-dev/kpt:v0.37.1`)

**Comment by susan-shu-c** [comment]
Hi, yes I encountered this as well, this was my output at the time, using:

`kpt 0.37.1`
`yq 4.2.1`

```
foo@stage:~/kf-deployment$ kpt pkg get https://github.com/kubeflow/gcp-blueprints.git/management@v1.2.0 "${MGMT_DIR}"
fetching package /management from https://github.com/kubeflow/gcp-blueprints to management
failed to set "gcloud.core.project" automatically in package "management" with error: setter "gcloud.core.project" is not found
foo@stage:~/kf-deployment$ kpt version
0.37.1
```

I was on 
Debian GNU/Linux 10 (buster)

**Comment by Bobgy** [comment]
I'm from Kubeflow team. I also reproduced this issue

```
$ kpt version
0.36.1
# kpt pkg get https://github.com/kubeflow/gcp-blueprints.git/management@v1.2.0 ./management

fetching package /management from https://github.com/kubeflow/gcp-blueprints to management
failed to set "gcloud.core.project" automatically in package "management" with error: setter "gcloud.core.project" is not found
```
I'm also on on MacOS Catalina 10.15.7

The kpt was installed using `gcloud components install kpt`.

**Comment by Bobgy** [comment]
I wonder if it could be related to gcloud setup, when you reproduce the issue, did you install `gcloud` and set a default project?

**Comment by Bobgy** [comment]
I tried unsetting default gcloud project and the error goes away
```
$ gcloud config unset project
$ kpt pkg get https://github.com/kubeflow/gcp-blueprints.git/management@v1.2.0 ./management
fetching package /management from https://github.com/kubeflow/gcp-blueprints to management
```
@phanimarupaka can you try to reproduce again after you install `gcloud` and set a default project?

**Comment by phanimarupaka** [comment]
@Bobgy It works for me even in both the cases, project set and unset. So only couldn't reproduce the issue on my end. Can you try to upgrade the kpt version to 0.37.1 and try.

**Comment by phanimarupaka** [comment]
@Bobgy @sidpalas @susan-shu-c Can any of you try to run the command from your `$HOME` directory and let me know if you still see the issue.

**Comment by sidpalas** [comment]
Sure @phanimarupaka -- I just ran using kpt 0.37.1 within my home directory and saw the same results as @Bobgy:

```
~ kpt version
0.37.1
~ gcloud config list --format "value(core.project)"

~ kpt pkg get https://github.com/kubeflow/gcp-blueprints.git/management@v1.2.0 ./management
fetching package /management from https://github.com/kubeflow/gcp-blueprints to management/management
~
~ gcloud config set project foo
Updated property [core/project].
WARNING: You do not appear to have access to project [foo] or it does not exist.
~
~ rm -rf ./management
~
~ kpt pkg get https://github.com/kubeflow/gcp-blueprints.git/management@v1.2.0 ./management
fetching package /management from https://github.com/kubeflow/gcp-blueprints to management
failed to set "gcloud.core.project" automatically in package "management" with error: setter "gcloud.core.project" is not found
```

**Comment by susan-shu-c** [comment]
I tried it start from when the project is set. However my `unset` doesn't seem to be working, or it is the incorrect command (searching through documentation suggested it is correct, however).

```
~$ gcloud config list --format "value(core.project)"
foo-project
~$ kpt pkg get https://github.com/kubeflow/gcp-blueprints.git/management@v1.2.0 ./management
fetching package /management from https://github.com/kubeflow/gcp-blueprints to management
failed to set "gcloud.core.project" automatically in package "management" with error: setter "gcloud.core.project" is not found

~$ gcloud config unset project
Unset property [core/project].
~$ gcloud config list --format "value(core.project)"
foo-project
```

The above is weird, I believe unset is the correct command but it still shows core.project

```
~$ rm -rf ./management
~$ kpt pkg get https://github.com/kubeflow/gcp-blueprints.git/management@v1.2.0 ./management
fetching package /management from https://github.com/kubeflow/gcp-blueprints to management
failed to set "gcloud.core.project" automatically in package "management" with error: setter "gcloud.core.project" is not found

~$ kpt version
0.37.1
```

Debian GNU/Linux 10 (buster)

**Comment by phanimarupaka** [comment]
Had a debugging session with @Bobgy. The issue is related to the way kpt caches openapi information regarding setters. The fix already in there so the next kpt release would fix it.
