### ISSUE TITLE
Implement function that returns function chain for given pipeline

### ISSUE THREAD

**Issue by droot** [GoogleContainerTools/kpt#1346]
Main ask here is to implement a function (refer to this [PR](https://github.com/GoogleContainerTools/kpt/pull/1321/files)) that return a function chain as slice of kio.Filter that can be provided to a `kio.Pipeline` to execute.

Copying the placeholder function from the [PR](https://github.com/GoogleContainerTools/kpt/pull/1321/files). Function will read the function specs specified in the `validators, generators, transformer` section and convert that to corresponding kio.Filter (builtin, docker-runtime etc.)

```Go
// fnFilters returns chain of functions that are applicable
// to a given pipeline.
func fnFilters(_ *Pipeline) []kio.Filter
```

**Comment by Shell32-Natsu** [comment]
A list of `functionConfig` is also needed to be returned.
