### ISSUE TITLE
Cleanup usage of latest tag in kpt fn catalog tests

### ISSUE THREAD

**Issue by mengqiy** [GoogleContainerTools/kpt#1368]
We have tests in the kpt-fn-catalog repo that use docker images with `latest` tag.
We plan to eventually move away from tag `latest` since it doesn't provide any compatibility guarantee.
Instead, we are going to support semver (e.g. v1.2.3) and short versions of semver as "moving tags" (e.g. v1.2 and v1).

To cleanup up our tests, we may want to use tag names like dev, unstable, master and etc.

**Comment by Shell32-Natsu** [comment]
Notice that the tests are combined with examples.
