### ISSUE TITLE
Bug: Inscrutable resource-merge update error (not logged by default)

### ISSUE THREAD

**Issue by karlkfi** [GoogleContainerTools/kpt#1376]
```
$ kpt pkg update . --strategy resource-merge
updating package .
error: failed to clone git repo: original source: failed to clone git repo: trouble hard resetting empty repository to 41e589f4fb3448f088ed4d1824b0a35c6175f294, please run 'git clone <REPO>; stat <DIR/SUBDIR>' to verify credentials: exit status 128
```

I managed to trace down the root cause of this one: The kpt package had been pulled from a local file URI after making a local commit. The commit DID exist locally, but was amended before being pushed, so it was available but not in the history of the branch. Workaround was to manually change the commit sha in the kptfile to one that was actually in the branch history and re-run the update.

However, this was only debuggable after compiling kpt from scratch with a modification to print out the stdout/stderr from the git command executed by kpt. The code as exists upstream squelches the output logging on error, probably because the code that calls that function calls it a second time with different inputs if the first call errors. This needs refactoring to properly log the git command failure only if both the git command executions fail.

Also, this error string is really hard to understand... I suggest using the git Go client, instead of shelling out to the git command. Then you might get better error messages.

**Comment by mortent** [comment]
This has been addressed in the `next` branch, i.e. the new design for kpt. We now capture the output from git to stdout and stderr, include that in the error returned, and print it as part of the error message to the user. 

We do eventually want to move to use the Go client for git. It just isn't the top priority right now.

**Comment by mikebz** [comment]
@karlkfi can you please try your scenario with kpt `next` build and let us know how you like the output.  Thank you!
