### ISSUE TITLE
Bug: Inscrutable remote diff output

### ISSUE THREAD

**Issue by karlkfi** [GoogleContainerTools/kpt#1377]
```
$ kpt pkg diff --diff-type remote
Only in /tmp/kpt-602117789: kpt-gen.sh
Only in /tmp/kpt-602117789: tenant.yaml
```

What does this output mean? 
Does it mean "these files are only remote or only local"?

If so, can we name the temp file directory local-<suffix> and remote-<suffix> so it's possible to tell which is which?

**Comment by runewake2** [comment]
Hi Karl, I've put together a change that hopefully adds some extra context around what the `diff` command is doing. There's two parts to the change:

The first prints out where the information in these directories is being sourced from before the diff results: 
`Staging https://github.com/kubernetes/examples/staging/cockroachdb:master at /tmp/kpt-upstream-examples-cockroachdb-master-161806574`

The second changes the directory names we use to be more descriptive: `kpt-12348765` -> `/kpt-upstream-examples-cockroachdb-master-12348765` for example.

In your case your output might look like:

```txt
$ kpt pkg diff --diff-type remote
Only in /tmp/kpt-upstream-githubProject-parentDirectory-master-602117789: kpt-gen.sh
Only in /tmp/kpt-upstream-githubProject-parentDirectory-master-602117789: tenant.yaml
```

Do these changes help clarify the results of a `kpt pkg diff`? Is the output this shows clear now or are there other changes that would help improve the experience here (for example: is the new directory name too long or the "Staging..." text helpful)?

**Comment by mikebz** [comment]
@runewake2 is there a way to inercept `/tmp/kpt-upstream-githubProject-parentDirectory-master-602117789` and just make it `upstream`?

**Comment by runewake2** [comment]
Yes, I think we could do that but it wouldn't catch all issues. `pkg diff` uses the local diffing tool and that varies across systems. That behavior can also be overwritten if you'd prefer a graphical diff like [`meld`](https://meldmerge.org/), replacing stdout output would have no effect on these graphical tools.

If we are transforming diffs output I think we'd want to include that in addition to the changes mentioned above.

The change you describe might look like:

```txt
Only in local: deployment.yaml
Only in upstream@master: tenant.yaml
Only in upstream@ProjectVersion: pod.yaml
```

> we can not just use `upstream` here because `remote` and `3way` diffs will calculate the diffs between two different versions of the upstream repository.

Or something like

```txt
diff local/deployment.yaml upstream@ProjectVersion/deployment.yaml
```

With the default Mac tool.

If we make that change we'd need to be careful that the directory names we replaced did not exist in any of the compared contents. Otherwise the results we print would not be accurate and potentially misleading.

**Comment by karlkfi** [comment]
Feels like just "/tmp/kpt-local-${random}" and "/tmp/kpt-remote-${random}" would be sufficient. 

Tho with 3-way diff you might want "/tmp/kpt-local-${random}" "/tmp/kpt-remote-new-${gitshortsha}-${random}" and "/tmp/kpt-remote-old-${gitshortsha}-${random}".

**Comment by runewake2** [comment]
You would prefer the git SHA over the branch name or a representation of the current version (I've used `PackageVersion`) in your Kptfile?

**Comment by karlkfi** [comment]
The upstream branch name is in the Kptfile. It doesn't change. I don't need it in every diff.

**Comment by runewake2** [comment]
I've updated the behavior so a remote diff that is based on master will compare two directories named:

* `/tmp/kpt-upstream-75f116a-943454749`
* `/tmp/kpt-upstream-master-246571466`

Branch names and git-sha's here would both only show the first 7 characters in the name (this does mean that if your using `hello-world` as your branch that we'd use `hello-w` here).

In this case of a remote diff `75f116a` would be the sha of the current `Kptfile` version and `master` would represent the current version of the `master` branch.

> Note: The local package will appear at `/tmp/kpt-local-040839398` (with no sha/branch attached).

Are these results more in line with what you'd expect?

**Comment by karlkfi** [comment]
close.

One gotcha tho is that it's not obvious that the `75f116a` sha is the one in my Kptfile... That's why i was suggesting "new" vs "old". But I guess new/old isn't technically accurate because the sha in the kptfile doesn't even need to be on the same branch...

Do we have the branch name we pulled from in the Kptfile?

If so... maybe:
```
- `/tmp/kpt-kptfile-${KPTFILE_BRANCH}-${KPTFILE_SHA}-${RANDOM}`
- `/tmp/kpt-remote-${KPTFILE_BRANCH}-${HEAD_SHA}-${RANDOM}`
- `/tmp/kpt-local-${LOCAL_BRANCH}-${LOCAL_GIT_SHA}-${RANDOM}`
```

**Comment by runewake2** [comment]
The original branch name should be listed in the `Kptfile` (under `upstream/git/ref`). Does the use of `kptfile` in your first example make it clear that the source is pulled from a remote repository?

Right now our code is designed to use either a reference SHA or a branch name, let me see what is required to create this experience.

**Comment by karlkfi** [comment]
> Does the use of kptfile in your first example make it clear that the source is pulled from a remote repository?

Debatable. I'm open to other suggestions. I just want the UX to be obvious and intuitive. 

new/old was the best i could come up with, but that's another specifier that wont be in the local name, and it's only technically accurate if they came from the same branch (which is probably the 80% case). 

> Right now our code is designed to use either a reference SHA or a branch name, let me see what is required to create this experience.

If there's no branch specified (just a sha), the usual git term for the ref is `detached`. Use that as the ref if no branch is specified in the kptfile or if the local commit is detached. 

That said, if there's no ref in the Kptfile... how do you do a diff? Do you have to specify a branch or sha when running the command?

**Comment by karlkfi** [comment]
Another thing:
If you make a parent directory for the folders, then they an all share a single random tmpdir suffix:

```
/tmp/kpt-${RANDOM}/kptfile-${KPTFILE_BRANCH}-${KPTFILE_SHA}
/tmp/kpt-${RANDOM}/remote-${KPTFILE_BRANCH}-${HEAD_SHA}
/tmp/kpt-${RANDOM}/local-${LOCAL_GIT_BRANCH}-${LOCAL_GIT_SHA}
```

If there are local changes, you may also need to mark the local with a `-dirty` suffix, because it wont match the git contents.

And lastly, there's some git jargon that might be useful here:

- **tip* - the most recent commit on a branch
- **head** - reference to the tip of a branch
- **HEAD** - the commit you currently have checked out

**Comment by runewake2** [comment]
Thanks, I really appreciate the detailed feedback! I've adopted the parent tmp directory suggestion. The other changes will require some refactoring that I'm still working through right now. I'll share the results once I have a working example.

**Comment by runewake2** [comment]
After the changes the directory layout will appear like this:

```
/tmp/kpt-165532019/local-master-75f116a
/tmp/kpt-165532019/remote-master-75f116a
/tmp/kpt-165532019/target-master
```

There are a few differences here from what you described above.

The `target` directory is created when a `remote`, `3way` or `combined` diff is run and represents the target upstream version. By default this will be the main/master branch at HEAD but can be overwritten by passing in a target version. That version can be a commit sha or branch name. If a version is provided the directory would be named `target-{{Version}}` instead.

For example:

```txt
kpt pkg diff package@9e4e0f41f75b844e094d0a1673f3e32384742dcc --diff-type=remote
```

Would cause the package to be staged at `/tmp/kpt-165532019/target-9e4e0f41f75b844e094d0a1673f3e32384742dcc`. *I do not shorten the commit sha/branch name here.*

I've used `local`, `remote` and `target` to represent `yours`, `old` and `new` respectively (I believe in your example this would align to `local`, `kptfile` and `remote`).

The results of a diff with this pattern might look like this (in this case from a "combined" diff):

```txt
diff /tmp/kpt-157412012/local-master-75f116a/project-statefulset.yaml /tmp/kpt-157412012/target-9e4e0f41f75b844e094d0a1673f3e32384742dcc/project-statefulset.yaml
68c68
< foo
---
> bar
```

Do these changes make the behavior clear to you? If so, is the behavior clear enough to eliminate the need for the "Staging github.com/some/project at /tmp/kpt/local" messages?

**Comment by runewake2** [comment]
Hi Karl, we've merged the directory name changes I mentioned above and these changes should be present in the next version of `kpt`. I'm going to close this issue for now. If there are other improvements you'd like to see us make here please re-open the issue and I can follow up.
