### ISSUE TITLE
Bug: kpt cfg set isn't recursive

### ISSUE THREAD

**Issue by karlkfi** [GoogleContainerTools/kpt#1386]
When you kpt pkg get a sub-package under a package it automatically inherits the setters from the parent package.
But when you kpt cfg set on the parent package, it doesn't automatically inherit the setter to the sub-package.

Maybe this is a feature request, but I consider it a bug because the behavior is inconsistent.

**Comment by karlkfi** [comment]
I found `--recurse-subpackages`, but I kind of expected it to be default, since the inheritance is default when checking out sub-packages.

**Comment by mikebz** [comment]
seems like a reasonable request.  Heads up @frankfarzan @droot  - forwarding to you for design / UX decision here.

**Comment by morgante** [comment]
+1 to making recursive the default, since it's the default when adding a new package.

**Comment by mikebz** [comment]
@phanimarupaka @frankfarzan @mortent is the `next` branch recursive by default?

**Comment by phanimarupaka** [comment]
Yes. It will be recursive by default. Not just for setters but for all the other functions.

**Comment by phanimarupaka** [comment]
Closing this issue as we do not intend to change the behavior in current versions of kpt and is addressed in https://catalog.kpt.dev/apply-setters/v0.1/
