### ISSUE TITLE
Standardize structured function results (ResourceList.results)

### ISSUE THREAD

**Issue by frankfarzan** [GoogleContainerTools/kpt#1390]
- [x] Finalize and publish ResourceList.Results as part of function Spec. A function should still be able to use coarse-grained exit codes to communicate failure.
- [x] Modify TS and Go clients to use the standard. See [1] [2]
- [x] Modify kpt CLI to output the aggregated results as a KRM resource (`--results`).

[1] https://pkg.go.dev/sigs.k8s.io/kustomize/kyaml/fn/framework/#Result
[2] https://github.com/GoogleContainerTools/kpt-functions-sdk/blob/3232610/ts/kpt-functions/src/types.ts#L375

**Comment by Shell32-Natsu** [comment]
Should we define the complete result schema in the spec or we just define a `results` field in the output list? The `functionConfig` is defined in latter way.

**Comment by frankfarzan** [comment]
There are two different things:

1. Wire format `ResourceList.results`, this is not a separate KRM.
2. Output of the kpt CLI `FunctionResults` which is a KRM.

**Comment by droot** [comment]
Linking a comment where we discuss confusion about two formats of results: https://github.com/GoogleContainerTools/kpt/pull/1923#discussion_r628604165

**Comment by droot** [comment]
@Shell32-Natsu Can you pl. audit both the SDKs and update the status on the second item in the checklist.

**Comment by droot** [comment]
This has been already addressed so closing this.
