### ISSUE TITLE
package.json vars breaking change since npm 7.0.0 breaks kpt-fn-sdk docker build and push workflow

### ISSUE THREAD

**Issue by mengqiy** [GoogleContainerTools/kpt#1394]
We read the value of [`npm_package_kpt_docker_repo_base`](https://github.com/GoogleContainerTools/kpt-functions-sdk/blob/a13666a1b0f8d87bfee2ca1fb264d45003d09bfc/ts/create-kpt-functions/src/cmd/docker_create.ts#L56-L59) in kpt-funtions-sdk when users run `npm run kpt:docker-build -- --tag ${TAG}` or `npm run kpt:docker-push -- --tag ${TAG}`.
With npm version `<=6.*.*`, `npm_package_kpt_docker_repo_base` is set by npm since it has prefix `npm_package_`.
However, with npm version `>=7.0.0`, npm [no longer sets env vars `npm_package_*`](https://github.com/npm/cli/blob/latest/CHANGELOG.md#all-lifecycle-scripts). The [reason behind it](https://github.com/npm/rfcs/blob/latest/implemented/0021-reduce-lifecycle-script-environment.md).
This is going to breaking users of kpt-functions-sdk, when they upgrade to npm 7.0.0+. We need to come up with a plan.

**Comment by mengqiy** [comment]
At the very minimum, what we can do is:
When users run into this issue, they google search it and find this GH issue or our updated document that instructs them to manually set env var `npm_package_kpt_docker_repo_base`.

cc: @Shell32-Natsu @frankfarzan

**Comment by frankfarzan** [comment]
@mengqiy What's the alternative for passing package.json fields to script?

**Comment by mengqiy** [comment]
There are a few possible alternatives:
1. Move `.kpt.docker_repo_base` into the config object in `packge.json`.
Quote from the [RFC](https://github.com/npm/rfcs/blob/latest/implemented/0021-reduce-lifecycle-script-environment.md#detailed-explanation):
>`npm_package_config_*` Each key in the config object will be included, but npm will not override values with a `<pkgname>:<keyname>` config value if one exists.

2.  kpt-functions-sdk expect env var `npm_package_kpt_docker_repo_base` to be set. We can try to do something like `"kpt:docker-build": "npm_package_kpt_docker_repo_base=$(jq -r .kpt.docker_repo_base package.json) kpt docker-build",`. This will require the user to have `jq` installed.

3. kpt-functions-sdk can process the package.json by itself and extract the container registry name.
Quote from the [RFC](https://github.com/npm/rfcs/blob/latest/implemented/0021-reduce-lifecycle-script-environment.md#detailed-explanation):
>Provide a new field, npm_package_json, with the path to the package.json file.

**Comment by mengqiy** [comment]
IMO we need to fix this issue, but it doesn't have to be right now. Because this issue only affect the function produce while our top priority is targeting the function consumers. We can get back to this after we build the kpt-fn-catalog.

**Comment by bgrant0607** [comment]
This is pretty annoying. Please at least update the typescript guide.
https://kpt.dev/sdk/ts-guide
