### ISSUE TITLE
Log filename and/or Object identifier when running into issues applying resources

### ISSUE THREAD

**Issue by viglesiasce** [GoogleContainerTools/kpt#1395]
I've exported many resources using the `config-connector` binary. Some of the names of those are not valid because they included underscores (`_`).

Kpt rightly errors out but does not provide enough info to figure out which file is at fault.

```
> kpt live apply .
error: invalid characters in object name: vic-goog_cloudbuild
```

In this case I'd also like to see the filename and object type so that I can more easily fix the problem.

**Comment by viglesiasce** [comment]
It turned out that this was not an issue with the files on disk NOR objects in the cluster. Rather, the inventory config map contained the invalid names. Not sure what to make of that but either way this was very difficult to debug.

**Comment by viglesiasce** [comment]
I believe the way to reproduce the specific issue I hit is:

1. Create a YAML with an invalid object name and one with a valid name
2. Apply the yaml with `kpt live apply .` (it fails) 
3. Remove the yaml with the invalid name and try to apply (it fails but the configmap has the invalid name in it)

**Comment by mikebz** [comment]
@viglesiasce if you can share your particular yaml directory that'd be best.  You can send it privately as well.

**Comment by Liujingfang1** [comment]
This failure is caused due to some invalid names were added to the inventory object. I believe @seans3 has a fix for that. https://github.com/kubernetes-sigs/cli-utils/pull/319

**Comment by mikebz** [comment]
@seans3 if you feel like the rightful owner of this can you please assign it to yourself and put it in progress?

**Comment by viglesiasce** [comment]
Thanks! That linked issue does indeed look like it would fix this.

Let me know when the update lands here and I'll give it a try.

**Comment by seans3** [comment]
Also: an end-to-end test case which proves this now works: https://github.com/GoogleContainerTools/kpt/pull/1370

**Comment by seans3** [comment]
Fixed in latest `kpt` at master. The fix will be in the next `kpt` release. Closing.
