### ISSUE TITLE
Why kpt pkg update doesn't allow absolute paths

### ISSUE THREAD

**Issue by karlkfi** [GoogleContainerTools/kpt#1406]
For some reason, kpt pkg get accepts absolute paths, but kpt pkg update does not. 
Does this inconsistency have a reasons? Seems arbitrary.

I would like kpt pkg update to take absolutes so it's easier to automate.

**Comment by karlkfi** [comment]
```
kpt pkg update /workdir/environs/dev/project --strategy resource-merge
error: package path must be relative
```

**Comment by Shell32-Natsu** [comment]
@phanimarupaka @mortent Can you take a look at this?

**Comment by phanimarupaka** [comment]
@karlkfi That is intentional. kpt needs the parent folder to be checked in to git so that when there is a failure while doing an update, users can fall back to git in order to stash those changes. For example, --strategy=force-delete-update would first delete the package and fetch it from remote. In case delete succeeds but fetch fails, the package will be gone. So to avoid that, kpt requires the parent folder checked in to git and accepts only relative paths.

**Comment by karlkfi** [comment]
I'm not sure why the requirement for being a git folder requires specifying a relative directory.

I see two workarounds to allow absolute directories:

1. cd into the parent dir before deleting the package directory, to avoid executing git without a workdir (requires one of the parent dirs to be a git repo)
2. change kpt pkg get to allow checking out into the current dir (https://github.com/GoogleContainerTools/kpt/issues/1407), then don't delete the whole directory (for --strategy=force-delete-update), only its contents (excluding the .git dir). Then you can repopulate the package without needing to change directory.

**Comment by mortent** [comment]
As part of the new implementation of kpt packaging, we are trying to address both of the issues here.
We will make kpt use absolute paths consistently internally, and convert user provided paths that are relative to absolute paths within the cobra command.
We are also changing how we implement some of the update strategies. This means we will no longer completely delete directories, but instead handle it on a file-by-file (and subdirectories) basis. The delete directory approach doesn't handle subpackages correctly, so we need to replace it anyway.

**Comment by phanimarupaka** [comment]
This has been addressed in the next branch.

**Comment by mikebz** [comment]
@karlkfi 

```
 ~/src/sandbox » kpt pkg update /Users/mikebz/src/sandbox/mysql

Package "mysql":
Fetching upstream from sso://user/mikebz/blueprints@main.
From sso://user/mikebz/blueprints
 * branch            main       -> FETCH_HEAD
Fetching origin from sso://user/mikebz/blueprints@main.
From sso://user/mikebz/blueprints
 * branch            e59fa3473c45904b50c6c24dcc0ca3e9ddccd42d -> FETCH_HEAD
Updating package "mysql" with strategy "resource-merge".

```

This is how it works.  LMK if that solves your problem.

**Comment by karlkfi** [comment]
:+1: Thanks!

This should make it easier to run a pkg update from inside a script and containerize.
