### ISSUE TITLE
`kpt pipeline run` should filter out function config resources 

### ISSUE THREAD

**Issue by droot** [GoogleContainerTools/kpt#1410]
function config should not be mutated during the pipeline execution and good way to ensure that will be to not provide them as input to the functions.

**Comment by natasha41575** [comment]
Adding a comment to summarize conversation I had with Sunil: 

Moving this back to TODO because we are not sure yet if we want to implement this. If a file is meant to be an input to a function it is possible that the user either expects it to be mutated by the functions or doesn't
