### ISSUE TITLE
`kpt fn render` should support out-of-place sink-mode

### ISSUE THREAD

**Issue by droot** [GoogleContainerTools/kpt#1412]
Currently `kpt fn render` supports in-place sink-mode. It should support for `out-place` and `stdout` mode.

**Comment by phanimarupaka** [comment]
@droot I can pick this up.

**Comment by droot** [comment]
> @droot I can pick this up. Do you mean `kpt fn render` ? Should we support this now ? I am not sure if this qualifies to be added to m2. I think its cleaner if we just support in-place hydration first, gather feedback and pick this up. `kpt fn eval` already supports this #1710
> 
> cc @mikebz

Yes, we do want to support out-of-place mode for `kpt fn render`. I do agree that it is not highest priority. But being able to dump the output of `fn render` in a separate directory helps with being able to diff the changes without having to depend on `git`. Also supporting dumping the output in a separate directory requires very little change in the code.

I will keep this in `m2` with low priority for now.

**Comment by phanimarupaka** [comment]
Ack. I will work on it.

**Comment by mikebz** [comment]
I think given that we are now short on resource I suggest we move this out to M3.  This is a P2 feature and we should focus on getting a full E2E experience with in place hydration.

**Comment by phanimarupaka** [comment]
Yes. Moving it to M3.

**Comment by natasha41575** [comment]
@droot I can pick this up in the next sprint
