### ISSUE TITLE
Implement pipeline definition changes

### ISSUE THREAD

**Issue by droot** [GoogleContainerTools/kpt#1413]
We recently revised the `pipeline` definition with two major changes:

- dropped `sources` field (no major code change except this will be now a private field and not read from the config file)
- function grouping changes. Now `pipeline` supports only two groups: `mutators` and `validators`.

Another change is that `pipeline` itself is now part of `Kptfile`, but I think we can do that separately because I expect to be a bigger change.

**Comment by Shell32-Natsu** [comment]
Will change the pipeline and pipeline functions from OOP style to function style after #1417 being merged.

**Comment by Shell32-Natsu** [comment]
https://github.com/GoogleContainerTools/kpt/issues/1431 should be done at the same time.
