### ISSUE TITLE
Embed pipeline in Kptfile

### ISSUE THREAD

**Issue by droot** [GoogleContainerTools/kpt#1415]
We recently revised the `pipeline` design and made its definition to be part of the `Kptfile`. The task here is to implement that.

**Comment by frankfarzan** [comment]
I'm working on a unified Kptfile schema that includes the Pipelines. Once that lands, we can refactor existing code.

**Comment by frankfarzan** [comment]
Depends on #1422

**Comment by Shell32-Natsu** [comment]
I think this has been finished by #1417. Can we close this?

**Comment by natasha41575** [comment]
> I think this has been finished by #1417. Can we close this?

+ 1
