### ISSUE TITLE
Add e2e test for `kpt pipeline run` for nested package UX

### ISSUE THREAD

**Issue by droot** [GoogleContainerTools/kpt#1441]
We need to add e2e test case for nested package UX for `kpt pipeline run` where:

- top level package `app` that contains deployment.yaml and kptfile
- subpackage `db` under `app` package that contains some KRM resource say statefulset.yaml and kptfile
- `app`'s pipeline uses set-labels, set-namespace functions from function catalog
- `db`'s pipeline uses set-labels, set-namespace functions from function catalog 

test should ensure `kpt pipeline run` produces expected results i.e. recursive hydration where `db` package is hydrated first and `app` package is hydrated later and KRM resources in both packages should be transformed accordingly.

**Comment by natasha41575** [comment]
I believe this is covered by https://github.com/GoogleContainerTools/kpt/pull/1483
