### ISSUE TITLE
Doc story for kpt fn catalog

### ISSUE THREAD

**Issue by mengqiy** [GoogleContainerTools/kpt#1465]
Figure out a detailed plan about the site for kpt function catalog.
Kpt functions are versioned independently from the kpt version.
We should have a site that can allow users to choose what version of the document they want to see. An example is https://registry.terraform.io/modules/terraform-google-modules/kubernetes-engine/google/latest

**Comment by frankfarzan** [comment]
Other concerns:

- [ ] Function usage docs are consistent across 1st party functions
- [ ] Function examples are consistent
- [ ] Function categorization is rationalized
- [ ] Function versioning in docs

**Comment by mengqiy** [comment]
Let's update the list in https://github.com/GoogleContainerTools/kpt/issues/1489 if needed.

**Comment by frankfarzan** [comment]
What's the difference between these issues? Do you want dedup?
