### ISSUE TITLE
Curated functions should return error when the input is empty

### ISSUE THREAD

**Issue by Shell32-Natsu** [GoogleContainerTools/kpt#1488]
Functions should return an error when the input spec is considered empty.

For example, if the input key-value list is empty for set-label. In this case, we should assume there are some errors in the pipeline config. Now we will silently do nothing.

cc @droot @mengqiy

**Comment by frankfarzan** [comment]
What do you mean by input spec, `ResourceList.items`? If so, having no input is a valid scheario.

**Comment by Shell32-Natsu** [comment]
What I mean is the input function config, like the label name and label value for set-label functions. Not the input resources.
