### ISSUE TITLE
create an image for kpt with gcloud and git included

### ISSUE THREAD

**Issue by mikebz** [GoogleContainerTools/kpt#1506]
### Is your feature request related to a problem? Please describe.
some functionality of kpt requires `gcloud` and `git` client to be installed on the Docker image.  The customer request is to provide an image with those already installed instead of having to install those manually.

### Describe the solution you'd like
There should be a docker image for kpt that people can use in their CI/CD pipeline that includes gcloud and git.  It should be an officially supported image.

### Describe alternatives you've considered
#1457 PR originally attempted upgrading the base image for kpt to go from alpine to `gcr.io/google.com/cloudsdktool/cloud-sdk:alpine` but the image size has gone from ~50MB to almost 200MB. 

### Additional context
@martinmaly - original requestor

**Comment by martinmaly** [comment]
Thank you!

Would it work to have 2 images, one being the original, smaller kpt image and add the larger image which contains gcloud and git? that way customers using the kpt-only image won't be affected by addition of the other components?

**Comment by mikebz** [comment]
that makes sense to me.  @mortent @frankfarzan feel free to chime in on this.

**Comment by runewake2** [comment]
Right now I would recommend using some of the general purpose [`gcr.io/google.com/cloudsdktool/cloud-sdk`](https://github.com/GoogleCloudPlatform/cloud-sdk-docker) images (either the `latest` or `debian_component_based` versions). Right now `latest` does not include kpt but I'll see if we can get it added. The `debian_component_based` version does already include kpt and you can use that image right now.

These general purpose images do contain a number of features so are larger images (multiple GB). Would these images satisfy the use case you are trying to address here @martinmaly?

***

With the `debian_component_based` image kpt version `0.37.1` is currently available:

```sh
➜  docker run gcr.io/google.com/cloudsdktool/cloud-sdk:debian_component_based kpt version   
0.37.1
```

**Comment by martinmaly** [comment]
Looking at the image, it may be initially sufficient. it seems that majority of the size is coming from gcloud (possibly some also from the base images). It may be good place to start and we can optimize if and as needed.

It appears that the image contains git so that should satisfy our requirements for now. 

Thank you!

**Comment by runewake2** [comment]
To provide some context here outside our other conversations:

Version 0.39.0 of kpt introduces a new `kpt-gcloud` image that you can find here: [`gcr.io/kpt-dev/kpt-gcloud`](gcr.io/kpt-dev/kpt-gcloud)

Sizewise this image is in between the `kpt` image and the `cloud-sdk` images w/ kpt.

There are currently 4 images available with kpt. They will fit different needs:

- `gcr.io/kpt-dev/kpt` - This includes git and kpt and is the smallest image available
- `gcr.io/kpt-dev/kpt-gcloud` - This image is based on the `cloud-sdk:alpine` image and includes `gcloud` in addition to what is included in the `kpt` image.
- `gcr.io/google.com/cloudsdktool/cloud-sdk:latest` and `gcr.io/google.com/cloudsdktool/cloud-sdk:debian_component_based` are `cloud-sdk` images defined at [GoogleCloudPlatform/cloud-sdk-docker](https://github.com/GoogleCloudPlatform/cloud-sdk-docker) that are much larger images and provide a lot of different tools including kpt.

**Comment by runewake2** [comment]
I'm going to close this issue. We have a new image available and documentation for that image is available at https://kpt.dev/installation/docker/

I think we can handle additional changes or feedback in other issues.
