### ISSUE TITLE
Bug: kpt fn source includes non-KRM resources

### ISSUE THREAD

**Issue by karlkfi** [GoogleContainerTools/kpt#1508]
### Expected behavior

`kpt fn source "${SRC_DIR}"` to exclude non-KRM resources (like `.prettierrc.json` files)

### Actual behavior

`kpt fn source "${SRC_DIR}"` includes non-KRM resources (like `.prettierrc.json` files), which can cause subsequent kpt functions to error because they expect all resources to be KRM resources.

### Workaround

Filter for KRM resources manually:

```
kpt fn source "${SRC_DIR}" \
| kpt cfg grep "kind=" \
| kpt fn run --image "${IMAGE}" -- "key=value" \
| kpt fn sink "${DEST_DIR}"
```

### Information

Kpt Version: 0.37.1

**Comment by Shell32-Natsu** [comment]
This issue needs to update the `cmd/config`, will do it after #1698 merged.

**Comment by Shell32-Natsu** [comment]
@droot @frankfarzan Should we filter out non-KRM resources in `fn render` and `fn eval`?

**Comment by droot** [comment]
Here is my mental model: `kpt` should process files with `yaml, yml, json` extensions by default. If user wants to exclude certain files from processing,  they can add such files to`.krmignore`. So in this case, adding `.prettierrc.json` to `.krmignore` should work unless there is a bug. @Shell32-Natsu can you pl. verify that ?

There's been a discussion of tracking these ignore files in the `Kptfile` instead extra files such `.kptignore` (I do think that can make discovering it easier).

/cc @frankfarzan @mortent

**Comment by Shell32-Natsu** [comment]
@droot The `.krmignore` works fine.

**Comment by frankfarzan** [comment]
Different discussions here:

- Mechanism for kpt to ignore files and directories:
  - For `next` branch, we need to finalize the mechanism for ignoring files and directories. https://github.com/GoogleContainerTools/kpt/issues/1664
  - On `master` branch, we should document the current behavior of using `.krmignore`.
- kpt should enforce a precondition that all items in `ResourceList` (`.items` and `.functionConfig` fields) should have the minimum KRM type meta. It's debatable which of GVKNN needs to be required. I think GVK is a must. @droot This ties into enforcing preconditions for hydration.

**Comment by Shell32-Natsu** [comment]
@karlkfi So for this particular issue, the solution is adding the non-KRM resources you don't want to include to `.krmginore` file. We may improve the ignore list functionality in the kpt v1.

**Comment by Shell32-Natsu** [comment]
#1733
