### ISSUE TITLE
Support/document how to handle raw YAML URLs

### ISSUE THREAD

**Issue by howardjohn** [GoogleContainerTools/kpt#1509]
### Is your feature request related to a problem? Please describe.

Some applications, like https://cert-manager.io/docs/installation/kubernetes/, just stick a YAML file at some URL. This is easy to apply with `kubectl apply -f url.yaml`. Its a bit harder to do with kpt packages.

### Describe the solution you'd like

I am quite new to kpt, so maybe I am "doing it wrong", but I would expect to be able to do standard `pkg` operations like on a git repo, but with a raw URL.

### Describe alternatives you've considered

If this doesn't actually makes sense, which is plausible, then it would be great to have a snippet in the docs recommending what I do in these cases. Should I just curl it and do `kpt pkg init` in the folder, or is there something better?

### Additional context

**Comment by mikebz** [comment]
Hi @howardjohn no issue with asking questions, we are revamping our documentation and understand that the current docs are not sufficient.

First you correct that the on the fly pull of remote resources is a harder with kpt, but we would argue that kpt opinionated approach enforces some good practices.  We would argue that it's creates a more stable environment if you save whatever YAML you are applying before just applying it. 

Of course when you are dealing with prototypes it seems like an unnecessary overhead, but in my opinion the overhead is minimal and it's a good practice to adopt early in your development.

Here is an alternative flow:
1) you create a git repo which will mirror whatever it is that you have applied last to your cluster.
2) you pull in your remote resources and commit whatever you pulled to git, possibly having a branch that maps to the environment you are working with.
3) at this point in time you have whatever you intended to apply saved in version control, so if anything happens to the cluster or if you just want to roll back you have that power.
4) you can then apply the resources.

Let me know if this makes sense or if you'd like to see exact kpt commands there.

**Comment by mikebz** [comment]
Closing for now.  Please let us know if you have any more questions and don't hesitate to re-open the ticket.
