### ISSUE TITLE
Plan for reorganize code organization for `kpt fn run`

### ISSUE THREAD

**Issue by droot** [GoogleContainerTools/kpt#1519]
We want to refactor code driving `kpt fn run` with following desired goals:

- Lower level code such as `kio`, YAML manipulation, lower level function runtimes should live in kyaml
- Code that is impact the `kpt CLI UX` should live in kpt code repo

So the task here is to come up with plan keeping the licensing and ownership in mind.

**Comment by frankfarzan** [comment]
Is there a separate issue for limiting `kpt fn eval` to imperative functions?

**Comment by Shell32-Natsu** [comment]
@frankfarzan I created #1547

**Comment by frankfarzan** [comment]
Thanks!
