### ISSUE TITLE
Sample hello world images don't seem to be accessible

### ISSUE THREAD

**Issue by davidebbo** [GoogleContainerTools/kpt#153]
Trying to deploy the sample to a test GKE cluster failed with:

```Failed to pull image "gcr.io/kpt-dev/helloworld-gke:0.1.0": rpc error: code = Unknown desc = Error response from daemon: pull access denied for gcr.io/kpt-dev/helloworld-gke, repository does not exist or may require 'docker login'```

Do the images need to be made public?

**Comment by pwittrock** [comment]
Just checked that these are public.  re-open if this is still an issue
