### ISSUE TITLE
go.mod replace directive breaks go 1.16 module aware install

### ISSUE THREAD

**Issue by yhrn** [GoogleContainerTools/kpt#1535]
### Expected behavior
`go install github.com/GoogleContainerTools/kpt@v0.38.1` to succeed (assuming go 1.16 is used), `go install github.com/GoogleContainerTools/kpt@v0.38.0` works.

### Actual behavior
```
> go install github.com/GoogleContainerTools/kpt@v0.38.1
go: downloading github.com/GoogleContainerTools/kpt v0.38.1
go install github.com/GoogleContainerTools/kpt@v0.38.1: github.com/GoogleContainerTools/kpt@v0.38.1
        The go.mod file for the module providing named packages contains one or
        more replace directives. It must not contain directives that would cause
        it to be interpreted differently than if it were the main module.
```

**Comment by mikebz** [comment]
@yhrn is this blocking your workflow?

**Comment by yhrn** [comment]
@mikebz blocking sounds so dramatic but yes, we have switched to something like `GOBIN=$(pwd)/project-specific-bin-dir go install package@version` to install specific versions of various tools for some of our projects.

I also thought it was relevant to report this as I think this new go install feature is really convenient in general and hope that it will become the de facto standard way of installing Go based dev tools.

**Comment by mikebz** [comment]
@etefera can you please take a look?

**Comment by etefera** [comment]
Thanks for reporting! Taking a look at this now.

**Comment by mortent** [comment]
I had to add the replace directive before the latest release to work around the issue described at https://github.com/ory/dockertest/issues/208#issuecomment-686820414. But it would be great if we could fix the root cause of this and remove the directive.

**Comment by etefera** [comment]
Updating the `apimachinery` library https://github.com/GoogleContainerTools/kpt/blob/master/go.mod#L19 allows for the removal of that replace directive and results in a successful build on both macOS and Linux. However, doing so seems to break a `live` test https://github.com/GoogleContainerTools/kpt/blob/master/pkg/live/dual-delegating-loader_test.go#L27 

Investigating with @Liujingfang1 if it's feasible to resolve that breakage with the latest version of the dependency, in which case the replace directive may be safely removed.
