### ISSUE TITLE
kpt doesn't work with symlinks

### ISSUE THREAD

**Issue by morgante** [GoogleContainerTools/kpt#1544]
### Expected behavior
When working in a symlinked directory, kpt should behave normally and have commands process properly.

### Actual behavior
kpt commands fail unpredictably when working in symlinked directories.

### Information
v0.38.1

### Steps to reproduce the behavior
1. Get a package: `kpt pkg get https://github.com/GoogleContainerTools/kpt/package-examples/helloworld-set hello2`
2. Create a symlink to the package: `ln -s hello2/ hello3`
3. Try various kpt commands and see they return no output. (Ex. `kpt cfg tree hello3/`)

**Comment by mikebz** [comment]
We will see what it takes to get this to work but setting the priority to p2 for now since I have not seen this widely reported and I don't know if customers have mentioned this.

**Comment by stephenjlevy** [comment]
I am seeing this issue as well, and it has become a blocker for us when trying to use kpt with an existing monorepo.

```
kpt pkg get /Users/me/src/myproj.git/test/abc@v0.1
Package "v0.1":
Fetching /Users/me/src/myproj@master
From /Users/me/src/myproj
 * branch            master     -> FETCH_HEAD
 + e2c7f6c...23411f2 master     -> origin/master  (forced update)
Error: error copying package: read /Users/me/.kpt/repos/f5axgwlsomxxg4dfoz2s693smmxw64dt2qryzwcpacbbj3mabgmozbncpy======/bbb/xyz: is a directory
```

Addressing this TODO would fix the issue in our particular case, as the directory containing the symlink is external to where the kpt package is located.
https://github.com/GoogleContainerTools/kpt/blob/cbd342d350b88677e522bf0d9faa0675edb8bbc1/internal/util/fetch/fetch.go#L195-L196

**Comment by morgante** [comment]
@mikebz Can we increase priority on this. Another customer has run into it.

**Comment by phanimarupaka** [comment]
> So I think this feature requires more than just making sure kpt follows symlinks. Some questions we should answer:
> 
> * Are there any constraints on following symlinks and what are the security implications? Symlinks can point to anywhere on the users filesystem, so it is not clear to me if we should blindly follow all symlinks. In particular since users might fetch a package with symlinks from someone else and might not be aware that there are symlinks pointing outside the package.
> * How should we handle broken symlinks?
> * What does this mean for support on Windows and other filesystems that doesn't support symlinks?
> * Git treatment of symlinks is actually dependent on a configuration option: https://git-scm.com/docs/git-config#Documentation/git-config.txt-coresymlinks. Is this something kpt should check if encountering symlinks?

I am writing up a doc to discuss the scope and possible solutions for this problem.

**Comment by droot** [comment]
@phanimarupaka as @mortent has already mentioned the reasons that makes this problem lot harder.
Resolving the arg for the top level pkg dir (if its a symlink) in `kpt` commands is the best we can do at this point.

something related: in future, we want to support other location targets for packages such as OCI artifacts, GCS storage buckets and use of symlinks in the package makes it less portable.

**Comment by phanimarupaka** [comment]
This feature will be supported in beta.5 release of kpt.

**Comment by chasecaleb** [comment]
@phanimarupaka Are you sure this is supported now? I'm on kpt `1.0.0-beta.14` and symlinks still appear to be ignored. Here's an example:

```
caleb@work-vmware> kpt pkg tree
Package "test1"
└── [Kptfile]  Kptfile kptfile
caleb@work-vmware> ln -s ../../base/ ./base
caleb@work-vmware> kpt pkg tree            
Package "test1"
└── [Kptfile]  Kptfile kptfile
caleb@work-vmware> rm base
caleb@work-vmware> cp -r ../../base/ base
caleb@work-vmware> kpt pkg tree          
Package "test1"
├── [Kptfile]  Kptfile kptfile
└── Package "base"
    ├── [Kptfile]  Kptfile kptfile
    ├── [cluster-autoscaler.yaml]  ClusterRole cluster-autoscaler
    ├── [cluster-autoscaler.yaml]  ClusterRoleBinding cluster-autoscaler
    ├── [cluster-autoscaler.yaml]  Deployment kube-system/cluster-autoscaler
    ├── [cluster-autoscaler.yaml]  Role kube-system/cluster-autoscaler
    ├── [cluster-autoscaler.yaml]  RoleBinding kube-system/cluster-autoscaler
    ├── [kpt-annotations.yaml]  ConfigMap kpt-annotations
    └── [kpt-labels.yaml]  ConfigMap kpt-labels
caleb@work-vmware> kpt version
1.0.0-beta.14
```

**Comment by phanimarupaka** [comment]
cc @droot

**Comment by rahuldhir** [comment]
@phanimarupaka @droot any update on support for this? The lack of symlink support makes it difficult to have different Kptfiles that rely on a common base.

If you do not plan to support symlinks, how do you advise setting up environment-specific Kptfiles (e.g. separate Kptfiles for dev/stg/prd) that each rely on a common base configuration?
