### ISSUE TITLE
Drop declarative function and starlark support

### ISSUE THREAD

**Issue by Shell32-Natsu** [GoogleContainerTools/kpt#1547]
#1494

We should
 - Refactor copied codes about `kpt fn run`
 - Rename `kpt fn run` to `kpt fn eval`
 - Drop declarative function support
 - Drop starlark support.

**Comment by frankfarzan** [comment]
Related: https://github.com/GoogleContainerTools/kpt/issues/1548

**Comment by Shell32-Natsu** [comment]
Closed in #1561
