### ISSUE TITLE
Migrate functions catalog docs/tests to use kpt 1.0 CLI

### ISSUE THREAD

**Issue by frankfarzan** [GoogleContainerTools/kpt#1548]
Once kpt 1.0 CLI is close to final release, we should convert function catalog example to use the new CLI. This will also provide additional test coverage for the orchestrator.

**Comment by frankfarzan** [comment]
Should think about tagging/branching the catalog repo before this migration so it is possible to see examples of functions using old CLI.

**Comment by mengqiy** [comment]
We will need to update output in function examples after the kpt output change lands (https://github.com/GoogleContainerTools/kpt/issues/1783)
