### ISSUE TITLE
Add e2e tests for fn eval

### ISSUE THREAD

**Issue by Shell32-Natsu** [GoogleContainerTools/kpt#1552]
`kpt fn run` has been renamed to `kpt fn eval`. We should add e2e tests for it.

**Comment by Shell32-Natsu** [comment]
cc @droot

**Comment by droot** [comment]
We should prioritize testing for newly added functionality.

**Comment by droot** [comment]
@Shell32-Natsu This seems to be a subtasks of #1631

**Comment by Shell32-Natsu** [comment]
Duplicate of #1631
