### ISSUE TITLE
Improve `kpt fn render` end to end test converage

### ISSUE THREAD

**Issue by droot** [GoogleContainerTools/kpt#1558]
`kpt fn render` has basic end to end test coverage today, but we are nearing code complete, having a better sense of where we are wrt end to end tests will be helpful. As part of this task, identify all the end to end test scenarios (happy paths, negative testing) and implement tests to ensure we have decent coverage.

**Comment by frankfarzan** [comment]
Test case tracker: https://docs.google.com/spreadsheets/d/1V5f1UpL0_WqJPyeFTaR0bR4acCGtoUENYHVvV_HOlrc/edit#gid=0
