### ISSUE TITLE
Enforce invariants during `kpt fn` 

### ISSUE THREAD

**Issue by droot** [GoogleContainerTools/kpt#1559]
There are two parts of this task:

- Define the invariants that needs to be held as functions are applied during `kpt fn render`.
- Implement checks for invariants

# Duplicate resource invariant
A resource is identified by the following properties:

- GVKNN (group, version, kind, namespace (if namespaced resource), name)
- filepath of the resource

`kpt fn render` should fail with error whenever it detects duplicate resource in the `input` or `output` of the function in the pipeline. Alternative behavior such as merging the two resources if part of a same file or overwriting the resource with the copy that appears later in the resourceList.items can also be supported with some additional configuration. But being conservative here and enforcing this invariant seems like a good starting point

# Validators should not mutate resources
`validators` functions should not mutate resources. One way to ensure this will be to discard the resourceList.items from the output of `validators`.

# Meta resources should not be mutated

`Kptfile` and function config files should not be mutated.

Any other ?
 
/cc @frankfarzan @Shell32-Natsu @mortent @phanimarupaka

**Comment by frankfarzan** [comment]
Re "filepath of the resource": Orchestrator must handle multi-object files, so filepath is not a primary key.

**Comment by frankfarzan** [comment]
Are all resources required to have `metadata.name`? How about function configs?

**Comment by frankfarzan** [comment]
Generalizing this to both `fn render` and `fn eval`. For example, with `eval`, if you have two function configs with same GKNN, you get such an error today:

`"failed to run function: may not add resource with an already registered id: ~G_v1_ConfigMap|~X|setterValues"`

**Comment by droot** [comment]
> if you have two function configs with same GKNN, you get such an error today:
> 
> `"failed to run function: may not add resource with an already registered id: ~G_v1_ConfigMap|~X|setterValues"`

Can you share more about the scenario here ? (especially how were you invoking these)
Are these functionConfigs referred in the pipeline ? If yes, then `kpt fn eval` should exclude those by default.  @Shell32-Natsu

**Comment by frankfarzan** [comment]
```
pipeline:
  mutators:
    - image: gcr.io/kpt-fn/apply-setters:v0.1
      configPath: setters.yaml
    - image: gcr.io/kpt-fn/apply-setters:v0.1
      configPath: setters2.yaml
```

Where both setters.yaml and setter2.yaml are identical (Same GVKNN):

This succeeds:
 
```
$ kpt fn render
```

This fails: 
```
$ kpt fn source \                                                                             
  | kpt fn eval --image gcr.io/kpt-fn/set-namespace:v0.1 - -- namespace=mywordpress \
  | kpt fn sink
failed to run function: may not add resource with an already registered id: ~G_v1_ConfigMap|~X|setterValues
 ```

**Comment by droot** [comment]
@frankfarzan @Shell32-Natsu The use-case above reveals another issue. `fn eval` and `fn render` excludes `meta resources` from the input unless specified. So in this case `fn source` whose primary job is to generate input for the function execution should be consistent with `fn eval` and `fn render` and should exclude `meta resources` by default.

**Comment by droot** [comment]
Filed https://github.com/GoogleContainerTools/kpt/issues/2033 for the `fn source` consistency.

**Comment by droot** [comment]
created a task bug for enforcing `metadata.name` for `functionConfig`: https://github.com/GoogleContainerTools/kpt/issues/2105

**Comment by droot** [comment]
We have settled on new behavior in `kpt` where `kpt fn` commands include meta resources to be included in the function input and their modification is allowed. 
`kpt fn render` ignores the mutations done by validators.

Since we have settled on new behavior, closing this issue. We can reopen this issue if we have any requirements missing.
