### ISSUE TITLE
Starlark demo -> examples

### ISSUE THREAD

**Issue by mengqiy** [GoogleContainerTools/kpt#1563]
Depending on how long we want the demo to be,  we can choose to cover some of the following scenarios.
- Generator: create a or more new resources
- Mutate some fields in the existing resources
- Remove one more resources from the resource list
- Validate resources: return structured errors

**Comment by mengqiy** [comment]
@frankfarzan @droot @Shell32-Natsu Thoughts?

**Comment by frankfarzan** [comment]
SGTM. My recommendation is to show examples that do something useful (no foobar).

**Comment by mengqiy** [comment]
We need to move the 3 examples in https://github.com/mengqiy/starlark-demo to the catalog repo.

**Comment by mengqiy** [comment]
Closed by https://github.com/GoogleContainerTools/kpt-functions-catalog/pull/342
