### ISSUE TITLE
Use ENTRYPOINT in apply-setter and search-replace functions

### ISSUE THREAD

**Issue by mengqiy** [GoogleContainerTools/kpt#1564]
We should follow what we do in https://github.com/GoogleContainerTools/kpt-functions-catalog/pull/189/files#diff-22be26d2b9ade84e3aa6f7e8dfe4992f0fbb6a8da7bbf6c2cd6c109d7097e4a5R15
We need to ensure they work with `kpt fn doc`

**Comment by mikebz** [comment]
@mengqiy @phanimarupaka this wasn't added to the project.  Not sure if this is actively being worked on or not.  Please update when you get a chance.

**Comment by phanimarupaka** [comment]
@mikebz Yes. This is being worked on.

**Comment by mikebz** [comment]
thank you!  Adding to the `In Progress`
