### ISSUE TITLE
reference docs: fn

### ISSUE THREAD

**Issue by frankfarzan** [GoogleContainerTools/kpt#1571]
Overhaul and audit of all reference docs for fn commands.

See #1577 for guidance on command references.

**Comment by mikebz** [comment]
@droot reminder - can you please resolve the potential dupe here.

**Comment by droot** [comment]
> @droot reminder - can you please resolve the potential dupe here.

Done.

**Comment by droot** [comment]
Docs for `fn eval`, `fn render`, `fn source` and `fn sink` are done. 

Docs for `fn doc` is remaining. That isn't super critical, so moving this issue to `m3`.

**Comment by droot** [comment]
@mengqiy Can you pl. update the reference docs for `fn doc` subcommand ?

**Comment by droot** [comment]
Reference docs are remaining for `fn doc` command and that is being tracked by https://github.com/GoogleContainerTools/kpt/issues/2009 so closing this one.
