### ISSUE TITLE
Make DIR optional for live commands

### ISSUE THREAD

**Issue by phanimarupaka** [GoogleContainerTools/kpt#1592]
As part of making cli experience consistent across all the commands in kpt, we should make DIR argument optional for live commands and default to current directory. STDIN should be accepted by commands if '-' is specified similar to kubectl.

`kpt live apply` should default to current working directory

`kpt live apply -` should accept STDIN input.

**Comment by mikebz** [comment]
How does STDIN reconcile with ResourceGroup being recorded on disk?  Wouldn't the customer always have the resources on disk?  If we are getting a STDIN input from another tool, where does the resourcegroup come from?

**Comment by phanimarupaka** [comment]
The resource group also must be part of STDIN. That is true in the current version of kpt as well.

cc @seans3

**Comment by mikebz** [comment]
@phanimarupaka or @seans3 can you please add the rough sizing to this problem?
