### ISSUE TITLE
The kpt pkg diff command should handle nested packages

### ISSUE THREAD

**Issue by mortent** [GoogleContainerTools/kpt#1606]
The diff command currently doesn't handle remote subpackages and will try to diff everything in local with upstream. We should at least make sure diffing a single package excludes remote subpackages, and potentially allow diffing a full hierarchy of packages at the same time.

**Comment by mikebz** [comment]
@etefera between the doc site issues can you please connect with @mortent and take on this task?

**Comment by etefera** [comment]
Can do.

**Comment by mengqiy** [comment]
@etefera Are you working on this?

@mikebz This task is much bigger than I expected. XL means ~2 weeks of work which is pretty big commitment. If Eyob is not working on this or doesn't plan to  work on this, I can try to help with it.

**Comment by etefera** [comment]
@mortent Do we have some repro steps with our packages for this?
