### ISSUE TITLE
Race when install RG with kpt live apply

### ISSUE THREAD

**Issue by mortent** [GoogleContainerTools/kpt#1612]
### Expected behavior
Running kpt live apply should install the RG and complete successfully

### Actual behavior
I get an error `error: no matches for kind "ResourceGroup" in group "kpt.dev"` on the first attempt. Trying again works as expected.

### Information
CRDs are not immediately ready after being installed, so kpt should wait for the `Established` condition to become true before continuing.

### Steps to reproduce the behavior
It doesn't happen every time since this is a race.

**Comment by seans3** [comment]
Closed by: https://github.com/GoogleContainerTools/kpt/pull/1817
