### ISSUE TITLE
kubeval example docs doesn't work

### ISSUE THREAD

**Issue by frankfarzan** [GoogleContainerTools/kpt#1619]
https://github.com/GoogleContainerTools/kpt-functions-catalog/tree/master/examples/validators/kubeval

Package has been moved.

AI(s):
- Audit all example package documentation
- Consider how to test documentation is correct

**Comment by frankfarzan** [comment]
Per our offline discussion, don't use categories for subdirectory organization

**Comment by frankfarzan** [comment]
Also, what's the status for using semver in docs instead of `unstable`?

**Comment by frankfarzan** [comment]
Also, why does kubeval require network? We should make it work hermatically so it can be used declaratively. Eventually, this function should use the OpenAPI document provided by orchestrator to validate schemas.

**Comment by mengqiy** [comment]
> Also, what's the status for using semver in docs instead of unstable?

semver is being used in the release branch which is where the doc will be generated from.
e.g. https://github.com/GoogleContainerTools/kpt-functions-catalog/blob/set-namespace/v0.1/examples/mutators/set-namespace/v0.1.1/advanced/fn-config.yaml#L8

We plan to use `unstable` in the master branch.
