### ISSUE TITLE
`kpt pkg tree` visualization of package hierarchy

### ISSUE THREAD

**Issue by frankfarzan** [GoogleContainerTools/kpt#1622]
```
$ kpt pkg tree cassandra
.
├── [Kptfile]  Kptfile cassandra
├── [service.yaml]  Service cassandra
├── [statefulset.yaml]  StatefulSet cassandra
└── [statefulset.yaml]  StorageClass fas
```

Kptfile is rendered like a regular file which makes the output less readable.

**Comment by phanimarupaka** [comment]
@frankfarzan Here is the PR. https://github.com/kubernetes-sigs/kustomize/pull/3759

**Comment by mortent** [comment]
So the reason why the Kptfile is included in the output, it that it provides a way for users to see the package hierarchy with the `tree` command. I agree we should look at whether including the Kptfile in the output is the right way to achieve this, but I'm not sure we should just remove it without any replacement. Visualizing the package hierarchy seems pretty useful, so I think we should keep that as an option.

I'm also not certain if we need to address this in the `cmd/config` package. It seems like the `pkg tree`, `fn sink` and `fn source` are the only remaining dependencies from `cmd/config`, so maybe we should consider pulling the `tree` command into thirdparty.

**Comment by phanimarupaka** [comment]
@mortent There is Pkg: prefix for folders which are packages. Please refer to tests in the PR. This helps users to know the package hierarchy.

**Comment by mortent** [comment]
Ack. I had forgotten that we also use the Pkg prefix.

**Comment by frankfarzan** [comment]
Couple of issue with current formatting:

```
$ kpt pkg tree wordpress/
wordpress
├── [service.yaml]  Service wordpress
├── deployment
│   ├── [service.yaml]  Deployment wordpress
│   └── [volume.yaml]  PersistentVolumeClaim wp-pv-claim
└── Pkg: mysql
    ├── [deployment.yaml]  PersistentVolumeClaim mysql-pv-claim
    ├── [deployment.yaml]  Deployment wordpress-mysql
    └── [deployment.yaml]  Service wordpress-mysq
```

1. Inconsistent treatment of top-level package (`wordress`) and subpackages (`mysql`). There's `Pkg: ` prefix for subpackages, but not top-level package.
2. Using `Pkg: ` doesn't really highlight the fact it's a package.
3. Inconsistent treatment of meta resources. We define meta resources as any resource specific to kpt functioning. Besides, Kptfile, there are also function configs. Omitting just the Kptfile will be confusing.

Here's is what I think is a reasonable UX for now:

- **PKG: wordpress**
  - [Kptfile]  Kptfile wordpress
  - [service.yaml]  Service wordpress
  - deployment
    - [service.yaml]  Deployment wordpress
    - [volume.yaml]  PersistentVolumeClaim wp-pv-claim
  - **PKG: mysql**
     - [Kptfile]  Kptfile mysql
     - [deployment.yaml]  PersistentVolumeClaim mysql-pv-claim
     - [deployment.yaml]  Deployment wordpress-mysql
     - [deployment.yaml]  Service wordpress-mysql

Changes:

- [ ] Top-level package is marked as a package
- [ ] All packages are marked in **bold** using `PKG: my-package-name`.
- [ ] Show Kptfile and Function configs like regular resources for now. Given the previous point, this is no longer an issue.
