### ISSUE TITLE
Add e2e tests for `kpt fn {eval, source, sink}`

### ISSUE THREAD

**Issue by Shell32-Natsu** [GoogleContainerTools/kpt#1631]
We need to add e2e tests for `kpt fn eval`.

- [x] Update test driver to support new command #1646 
- [x] Implement the [tests cases](https://docs.google.com/spreadsheets/d/1V5f1UpL0_WqJPyeFTaR0bR4acCGtoUENYHVvV_HOlrc/edit#gid=0)
- [ ] Automate the tests

**Comment by frankfarzan** [comment]
Not all test cases are covered: https://docs.google.com/spreadsheets/d/1V5f1UpL0_WqJPyeFTaR0bR4acCGtoUENYHVvV_HOlrc/edit#gid=1609746542
