### ISSUE TITLE
Better handling of changes to GVKNN for resource-merge strategy

### ISSUE THREAD

**Issue by mortent** [GoogleContainerTools/kpt#1635]
The resource-merge strategy doesn't currently work well if there are changes to the values we use to pair resources for merge, i.e. G(V)KNN. This essentially means that using the `set-namespace` function, or any of the `set-name-prefix/suffix` would cause unexpected behavior when updating the package.

- [x] Design and test-cases
- [ ] Implementation

**Comment by phanimarupaka** [comment]
@mortent I can pick this up as I have worked on this issue in current version of kpt.

**Comment by mortent** [comment]
An interesting case here is how we can determine during update whether we should run the pipeline or not. A package might have a pipeline, but it isn't clear whether the user is leveraging the pipeline for in-place or out-place hydration.

**Comment by phanimarupaka** [comment]
@frankfarzan This is almost done. Just need a final approval from @mortent on the PR. So moving it back to m2.
