### ISSUE TITLE
Prev/Next buttons reload the entire page

### ISSUE THREAD

**Issue by frankfarzan** [GoogleContainerTools/kpt#1651]
Compare the following:
- Clicking on a book page in navbar
- Click on 'next' or 'previous'

The latter reloads the entire page including the navbar taking significantly longer.

**Comment by etefera** [comment]
This is a bug reproducible when the text of next/previous is selected. For some reason, clicking a non-character pixel in the link doesn't cause this behavior. Investigating now.

**Comment by frankfarzan** [comment]
This still happens on kpt.dev

**Comment by etefera** [comment]
Addressed in https://github.com/GoogleContainerTools/kpt/pull/1728
