### ISSUE TITLE
Single installation page

### ISSUE THREAD

**Issue by frankfarzan** [GoogleContainerTools/kpt#1653]
We should combine all installation instructions into a single page. Within that page, order sections based on most common:

1. Download binary
2. gcloud
3. brew (mac specific)
4. docker

**Comment by mikebz** [comment]
I have a PR but I slightly disagree with the ordering of the most common.  Not a huge issue and we can always change it around.  I think GCP customers probably get kpt through gcloud first.  At least the sample of 1 (myself) is that I rarely download binaries onto my local machine directly.

**Comment by frankfarzan** [comment]
I think that assumes the following:

1. All users of `kpt` have `glcoud`
2. `gcloud` is using the latest version of `kpt

This may not be true. If someone wants to kick the tire around with kpt (maybe go through the 5m Quickstart), asking them to download gcloud presents friction. 

I suggest the following:

1. Download binary
2. gcloud
3. brew (mac specific)
4. docker
5. source
