### ISSUE TITLE
Clean up and aggregate demo videos 

### ISSUE THREAD

**Issue by frankfarzan** [GoogleContainerTools/kpt#1654]
Currently each reference doc has an asciicinema video which will be stale given the v1 changes. Probably the most maintainable option is to have one or two demo videos max giving a very high level view of kpt and delete all these videos. We can have a demo of the quick start to ensure the video doesn't go stale in the future given the quick start will need to be e2e tested.

**Comment by frankfarzan** [comment]
@phanimarupaka is putting together a demo of the Quickstart, so let's produce a video we can embed somewhere in the site and delete all the other demo scripts/videos.

**Comment by mikebz** [comment]
+1 on removing most of the videos.  I would suggest just one video on the overview page that basically walks through the wordpress Quickstart: https://kpt.dev/book/01-getting-started/02-quickstart

**Comment by phanimarupaka** [comment]
Do we need demo video at all ? They go stale soon and relatively difficult to update them.

**Comment by frankfarzan** [comment]
We may want a single video at some point. Post v1, they won't go stale given backwards compatibility.

**Comment by frankfarzan** [comment]
Agree with @phanimarupaka, we can skip this all together, as demo videos go stale and need proper testing, etc.
