### ISSUE TITLE
Set up release pipeline for the `next` branch

### ISSUE THREAD

**Issue by mortent** [GoogleContainerTools/kpt#1659]
We want to be able to make early access releases from the `next` branch. We still need to be able to make normal releases from the master branch, so it should not impact our current pipeline. If some of the setup in the existing pipeline can be reused, that would be great.

We also want to be able to make these pre-releases, to make it clear to users that these would not be stable releases. Eventually we obviously want to change that.

**Comment by frankfarzan** [comment]
Related to this, installation docs need to be updated.

**Comment by mortent** [comment]
I think we should just keep releases from `next` only on github until we have something that can replace the existing releases from master.

**Comment by runewake2** [comment]
When should a `next` release be triggered?

Is the intention to use a tagged release or would some derivative of the existing [Cloud Build job](https://github.com/GoogleContainerTools/kpt/blob/master/release/branch/cloudbuild.yaml) we have that publishes the most recent `master` version work?

What artifacts should a `next` release include? Binaries for the different architectures? Containers?

**Comment by mortent** [comment]
I think we want releases to be triggered by tags, so the same strategy as we do now. No need to build artifacts on every push to the next branch, at least for now.
This is not fully decided yet, but if we end up setting a separate job, we can assume tags originating from the `next` branch start with `v1.` and tags originating from master starts with `v0.`. This should allow us to set up non-overlapping triggers.

We want to move away from binaries published through gcs (just use Github for this), so lets not do that for the `next` branch releases.

We want mostly the same artifacts as we create now. So binaries and tar files published as part of github releases, and build images for kpt that we publish to gcr.
