### ISSUE TITLE
Visually distinguish new and old sites

### ISSUE THREAD

**Issue by frankfarzan** [GoogleContainerTools/kpt#1662]
There will be two kpt sites co-existing for a while:

1. https://googlecontainertools.github.io/kpt  for master (0.39)
2. https://kpt.dev for next (1.0+)

Both sites should make it very obvious what kpt version they're targeting. If a user does a Google search and lands in one of these, there should be a prominent way to quickly figure this out what version the doc is talking about.

Related: Figure out a docs deprecation plan, considering SEO.

**Comment by mikebz** [comment]
in backlog grooming, moving to M3 to focus on functionality

**Comment by frankfarzan** [comment]
Should consider having kpt.dev use a different theme as well, currently it uses the same color palette as existing site. I'm personally a fan of dark themes (you can use an extension to see how it would look), but don't have a strong opinion.

**Comment by mikebz** [comment]
I think a different theme is a good idea.  Dark is good but also since this is a "Google Cloud Tools" production we might want to have something that aligns more with https://cloud.google.com/docs

Either way this is probably something we can save for M4.

**Comment by frankfarzan** [comment]
Yes, there are multiple aspects to this issue which can be separated:

- [ ] New site should show the CLI version (1.0+) as docs are versioned (Visible on every page)
- [ ] Old site should show it's targeting pre 1.0 version. Do not need to make major surgery to the old site, probably a banner  on every page suffices.
- [ ] In addition, using a different theme to as an additional differentiator.
- [ ] After the release, new site should be indexed instead of the old one and need to optimize SEO

**Comment by etefera** [comment]
Sent a request to temporarily remove site from index and merged a change that should indicate the docs are for an in-development version of kpt.
