### ISSUE TITLE
Finalize mechanism for ignoring files/directories

### ISSUE THREAD

**Issue by frankfarzan** [GoogleContainerTools/kpt#1664]
Decide between ignore list in Kptfile versus `krmignore`. I prefer the former given Kptfile is conceptually about defining what's in (or not in) a package. Having a separate mechanism seems extraneous.

**Comment by mortent** [comment]
We have the design mostly done. Also, this is a duplicate of https://github.com/GoogleContainerTools/kpt/issues/517, so closing this.
