### ISSUE TITLE
`kpt fn eval` should ignore the function config files used in pipeline by default

### ISSUE THREAD

**Issue by Shell32-Natsu** [GoogleContainerTools/kpt#1670]
They will be included if `--include-meta-resources` is given.

**Comment by Shell32-Natsu** [comment]
@mikebz @droot Which milestone do you think this should belong to?

**Comment by Shell32-Natsu** [comment]
1. We need to upgrade kyaml version after next kyaml release.
2. We have a work around (`.krmignore`). Not ideal but works.

I will put this to m2 milestone.

**Comment by droot** [comment]
So had a discussion with @Shell32-Natsu about it. Here is the summary:

- He has already done the hard work of adding a function to filter files in `kio` pkg in `kyaml`. So bring that change in kpt next will require bumping up `kyaml` [This has some minor risks associated].
- Users can use `.krmignore` files to ignore function config files if they run in to this issue.

So, no pressing need to do in `m1` milestone, can be tackled in `m2`.
