### ISSUE TITLE
Docs preview does not work properly

### ISSUE THREAD

**Issue by frankfarzan** [GoogleContainerTools/kpt#1680]
Steps to repo:
1. Run `make site-run-server`
2. Make an edit to a markdown file

The page doesn't reflect the changes. Reloading the page leads to a 404:

[2021-04-02T21:33:41.642Z]  "GET /book/02-concepts/00" Error (404): "Not found"
[2021-04-02T21:33:41.799Z]  "GET /book/02-concepts/00" "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36"

**Comment by etefera** [comment]
In this case, the browser likely cached the previous README file. The above PR addresses cache-busting for the dev experience. In the interim, a hard refresh should remove the stale file from the cache. The above PR also updates `make site-run-server` to allow for the same routing behavior as the URL checking script, which should prevent 404ing on paths that exist on the local filesystem while an instance of the server is running.

**Comment by frankfarzan** [comment]
Preview still doesn't work correctly, it seems to cache the content once at the start up. Subsequent changes are not rendered.

To repro:

1. make site-run-server
2. Edit a page, e.g. http://127.0.0.1:3000/book/03-packages/
3. Reload the page -> changes not shown
4. Rerun step 1 -> changes shown
