### ISSUE TITLE
Convert wordpress example to v1alpha2 and setter function

### ISSUE THREAD

**Issue by frankfarzan** [GoogleContainerTools/kpt#1688]
wordpress is the primary example of using subpackages. It also contains setters which need to be moved to use the function.

**Comment by phanimarupaka** [comment]
Ack.

**Comment by frankfarzan** [comment]
PR is still in progress.

**Comment by phanimarupaka** [comment]
My bad. Closed by mistake. Thanks.

**Comment by phanimarupaka** [comment]
Closing this issue as the PR is approved but can't be merged till Frank's approval. The PR will still be open.
