### ISSUE TITLE
kpt fn render doesn't handle subpackage files correctly

### ISSUE THREAD

**Issue by phanimarupaka** [GoogleContainerTools/kpt#1691]
When we invoke `kpt fn render` on a package with subpackages in it, the rendered resources in the subpackages are written to parent parent package as opposed to writing them to subpackages itself.

e.g. for a package with following tree structure
```
wordpress
├── Kptfile
├── README.md
├── mysql
│   ├── Kptfile
│   └── mysql-deployment.yaml
└── wordpress-deployment.yaml
```

`kpt fn render` on the package results in the following

```
wordpress
├── Kptfile
├── README.md
├── mysql-deployment.yaml
├── mysql
│   ├── Kptfile
│   └── mysql-deployment.yaml
└── wordpress-deployment.yaml
```

**Comment by droot** [comment]
This is addressed as part of #1694
