### ISSUE TITLE
Documentation usability feedback for run.md

### ISSUE THREAD

**Issue by frankfarzan** [GoogleContainerTools/kpt#170]
https://github.com/GoogleContainerTools/kpt/blob/master/docs/fn/run.md

* `Caveats` section is very long since it's explaining multiple concepts. It's probably worth creating subsection for each
* Need to use verbatim code style in many instances. e.g. `metadata.annotations.[config.kubernetes.io/function]`. Otherwise, it's hard to read.
* `Config Functions` -> `KPT Functions` ?
* We should simplify number of ways to invoke functions declarativey. Or at least, emphasize one approach in docs so user doesn't get overwhelmed.
* It's ambiguous whether functions directory is required or just a convention used (`functions` dir is in fact a special dir recognized by kpt).
* Also note that the implicit pattern is currently broken: #188

**Comment by droot** [comment]
This will be addressed with the docs revamp (and pipeline implementation) targeted for v1.0
