### ISSUE TITLE
Consistent YAML formatting

### ISSUE THREAD

**Issue by frankfarzan** [GoogleContainerTools/kpt#1722]
kpt needs to consistently format resources. Previously, there was `kpt cfg fmt` which is now removed in favor of having a global flag that controls styling/formatting as a cross-cutting feature.

As part of this, all examples in `/package-examples` (highest priority) and test data should be pre-formatted (Unless testing formatting logic itself). For example, `eval` comand on the nginx package in the Quickstart produces formatting changes which creates unnecessary noise:

https://kpt.dev/book/01-getting-started/02-quickstart

What's worse, there's no way to automatically preformat the example. We should also reconsider removing `fmt` command.

**Comment by droot** [comment]
I think having a dedicated command to format resources sounds useful to me. Which subcommand group we should bring it in ?

**Comment by frankfarzan** [comment]
`kpt pkg fmt` is consistent with `kpt pkg tree`, etc. In english: "I want to format my package".

**Comment by phanimarupaka** [comment]
How about having it as a format function instead ? By default any such functionality should be a function unless there is a great need to include it as part of cli.

**Comment by phanimarupaka** [comment]
https://github.com/GoogleContainerTools/kpt-functions-catalog/pull/242

**Comment by mengqiy** [comment]
It seems we start to format the resources in `kpt fn render` (#1813).
@phanimarupaka Is there a reason not doing it for `kpt fn eval`?

**Comment by phanimarupaka** [comment]
Yes. `eval` can be invoked on validator functions as well. Mutating resources in such scenarios looks awkward. If users want to format resources, they can invoke explicit `format` image.

**Comment by mengqiy** [comment]
Thanks for clarification!
