### ISSUE TITLE
`live init` on `next` branch should not use `inventory-template.yaml`

### ISSUE THREAD

**Issue by frankfarzan** [GoogleContainerTools/kpt#1723]
Default behavior in 1.0 release is to use `inventory` field in Kptfile and `ResourceGroup`.

**Comment by seans3** [comment]
The default behavior in 1.0 is that new packages which call `kpt live init` will store the `Inventory` fields in the `kptfile` (which creates a `ResourceGroup` custom resource when applied).

Just to be clear, any existing `ConfigMap` inventory objects in clusters previously created with `inventory-template.yaml` will continue to work (we're not going to force all users to recreate their cluster deployments). We will provide a `kpt live migrate` command to upgrade existing packages from `ConfigMap` to the `ResourceGroup` inventory object.

**Comment by seans3** [comment]
https://github.com/GoogleContainerTools/kpt/pull/1734

**Comment by mikebz** [comment]
gentle reminder: let's put the triaged label on for things that are already understood by the team 🙇

**Comment by seans3** [comment]
Completed
