### ISSUE TITLE
kpt functions writing using Go SDK should use latest release of go-yaml pkg

### ISSUE THREAD

**Issue by droot** [GoogleContainerTools/kpt#1726]
We have been experiencing several issues related to roundtripping of comments in YAML. One such example is license header is deleted when starlark function is invoked. Pl. refer to discussion in the PR https://github.com/GoogleContainerTools/kpt/pull/1696.

Issue filed on `go-yaml` pkg repo: https://github.com/go-yaml/yaml/issues/613

I have tested two functions `starlark` and `set-annotation` by building them using latest `go-yaml` and have seen improvements (manual testing) in the roundtripping related to comments. We need to bump the `go-yaml` version in all functions.

Steps to do so:
```sh

# cd to the project directory
go get gopkg.in/yaml.v3@496545a6307b2a7d7a710fd516e5e16e8ab62dbc

# you should see `go.mod` to be updated with the latest version point to Jan, 2021 date
```

This change will have ripple effect because it will likely impact the `e2e` tests. Also, note `kpt` repo will also be bumped to use latest `go-yaml`.

/cc @Shell32-Natsu @natasha41575 @mengqiy @frankfarzan @phanimarupaka

**Comment by mikebz** [comment]
gentle reminder - let's put that triage flag on the things that are already understood by the team 🙇

**Comment by mengqiy** [comment]
Fixed in https://github.com/GoogleContainerTools/kpt-functions-catalog/pull/213
