### ISSUE TITLE
`kpt fn render` e2e test cases should check content for stdout/stderr output messages

### ISSUE THREAD

**Issue by droot** [GoogleContainerTools/kpt#1755]
We introduced many negative e2e test cases for `kpt fn render` but we do not check content output on stdout/stderr for these test cases. Test harness is going to support assertions for content emitted on stdout/stderr and we should use that to ensure expected content is emitted in all the negative test cases.

/cc @Shell32-Natsu @natasha41575

**Comment by Shell32-Natsu** [comment]
Dup with #1666 ?
