### ISSUE TITLE
Do not use `unstable` function images in kpt repo

### ISSUE THREAD

**Issue by frankfarzan** [GoogleContainerTools/kpt#1782]
All code and documentation should use a specific version of a function.

**Comment by mikebz** [comment]
agreed.  I have tagged all of them to unstable because it was available and enabled the automatic checking which was the goal of migration of existing samples.  We def should fix this before going live.

**Comment by frankfarzan** [comment]
@mengqiy to confirm, but I think the best practice for ene-users is to either use `vMAJOR` or `vMAJOR.MINOR`. We should pick one of these and consistency use them in docs.

**Comment by mengqiy** [comment]
Yes, using `v<MAJOR>` or `v<MAJOR>.<MINOR>` is recommended.
For functions that are pre-v1, I'd recommend to use `v<MAJOR>.<MINOR>`, since `v0` may look a little strange to users.
For functions that are post-v1, I'd recommend to use `v<MAJOR>`.

**Comment by phanimarupaka** [comment]
This is fixed.
