### ISSUE TITLE
`kpt fn` error formatting

### ISSUE THREAD

**Issue by frankfarzan** [GoogleContainerTools/kpt#1783]
Example error message after running `kpt fn render` in Quickstart:
https://kpt.dev/book/01-getting-started/02-quickstart

```
package ".": running function "gcr.io/kpt-fn/kubeval:0.0.1": FAILED
fn.render: pkg .:
        pkg.render:
        pipeline.run: Unable to find image 'gcr.io/kpt-fn/kubeval:0.0.1' locally
docker: Error response from daemon: manifest for gcr.io/kpt-fn/kubeval:0.0.1 not found: manifest unknown: Failed to fetch "0.0.1" from request "/v2/kpt-fn/kubeval/manifests/0.0.1".
See 'docker run --help'.
```

Issues:

- [x] Inconsistency referring to the package. `package ".".` vs "pkg .`"
- [x] Need to follow style guide (K5): go/kpt-errors-style-guide
- [x] Line breaks.
- [x] There's bunch of internal identifiers that wouldn't make sense to the user such as `fn.render` `pkg.render` `pipeline.run`. This is specially irrelevant for validation issues which are WIP. In general, there seems to be a conflation between kpt-developer debugging traces and end-user error messages.
- [x] End user is told to run `docker run --help` which leaks the implementation details

As part of this, I like to review the error reporting UX for functions. Related issue: #1557

**Comment by frankfarzan** [comment]
cc @phanimarupaka for CLI-wide consistency

**Comment by frankfarzan** [comment]
When you change `0.0.1` to `unstable`, render doesn't return the error from kubeval function:

```
kpt1 fn render
package ".": running function "gcr.io/kpt-fn/kubeval:unstable": FAILED
fn.render: pkg .:
        pkg.render:
        pipeline.run:
```

Compare to running imperatively:

```
nginx » kpt1 fn eval --image gcr.io/kpt-fn/kubeval:unstable
[ERROR] Failed to parse raw kubeval output:
Unexpected token E in JSON at position 0

ERR  - stdin: Failed initializing schema https://kubernetesjsonschema.dev/master-standalone/deployment-apps-v1.json: Get "https://kubernetesjsonschema.dev/master-standalone/deployment-apps-v1.json": dial tcp: lookup kubernetesjsonschema.dev on 192.168.65.5:53: dial udp 192.168.65.5:53: connect: network is unreachable
 in object 'apps/v1/Deployment//my-nginx' in file deployment.yaml
[ERROR] Failed to parse raw kubeval output:
Unexpected token E in JSON at position 0

ERR  - stdin: Failed initializing schema https://kubernetesjsonschema.dev/master-standalone/service-v1.json: Get "https://kubernetesjsonschema.dev/master-standalone/service-v1.json": dial tcp: lookup kubernetesjsonschema.dev on 192.168.65.5:53: dial udp 192.168.65.5:53: connect: network is unreachable
 in object 'v1/Service//my-nginx-svc' in file svc.yaml
error: exit status 1
```

**Comment by frankfarzan** [comment]
Also, a question on what's send to stdout vs stderr:
https://github.com/GoogleContainerTools/kpt/pull/1762/files#r617836270

cc @natasha41575

**Comment by Shell32-Natsu** [comment]
> When you change `0.0.1` to `unstable`, render doesn't return the error from kubeval function:
> 
> ```
> kpt1 fn render
> package ".": running function "gcr.io/kpt-fn/kubeval:unstable": FAILED
> fn.render: pkg .:
>         pkg.render:
>         pipeline.run:
> ```
> 
> Compare to running imperatively:
> 
> ```
> nginx » kpt1 fn eval --image gcr.io/kpt-fn/kubeval:unstable
> [ERROR] Failed to parse raw kubeval output:
> Unexpected token E in JSON at position 0
> 
> ERR  - stdin: Failed initializing schema https://kubernetesjsonschema.dev/master-standalone/deployment-apps-v1.json: Get "https://kubernetesjsonschema.dev/master-standalone/deployment-apps-v1.json": dial tcp: lookup kubernetesjsonschema.dev on 192.168.65.5:53: dial udp 192.168.65.5:53: connect: network is unreachable
>  in object 'apps/v1/Deployment//my-nginx' in file deployment.yaml
> [ERROR] Failed to parse raw kubeval output:
> Unexpected token E in JSON at position 0
> 
> ERR  - stdin: Failed initializing schema https://kubernetesjsonschema.dev/master-standalone/service-v1.json: Get "https://kubernetesjsonschema.dev/master-standalone/service-v1.json": dial tcp: lookup kubernetesjsonschema.dev on 192.168.65.5:53: dial udp 192.168.65.5:53: connect: network is unreachable
>  in object 'v1/Service//my-nginx-svc' in file svc.yaml
> error: exit status 1
> ```

This is because of the implementation in `kubeval` function, more accurate, TS-SDK. By default it will only generate the structured results to stdout. The errors will be printed to `stderr` only when env `STRUCTURED_RESULTS` is set.

**Comment by frankfarzan** [comment]
> > When you change `0.0.1` to `unstable`, render doesn't return the error from kubeval function:
> > ```
> > kpt1 fn render
> > package ".": running function "gcr.io/kpt-fn/kubeval:unstable": FAILED
> > fn.render: pkg .:
> >         pkg.render:
> >         pipeline.run:
> > ```
> > 
> > 
> > Compare to running imperatively:
> > ```
> > nginx » kpt1 fn eval --image gcr.io/kpt-fn/kubeval:unstable
> > [ERROR] Failed to parse raw kubeval output:
> > Unexpected token E in JSON at position 0
> > 
> > ERR  - stdin: Failed initializing schema https://kubernetesjsonschema.dev/master-standalone/deployment-apps-v1.json: Get "https://kubernetesjsonschema.dev/master-standalone/deployment-apps-v1.json": dial tcp: lookup kubernetesjsonschema.dev on 192.168.65.5:53: dial udp 192.168.65.5:53: connect: network is unreachable
> >  in object 'apps/v1/Deployment//my-nginx' in file deployment.yaml
> > [ERROR] Failed to parse raw kubeval output:
> > Unexpected token E in JSON at position 0
> > 
> > ERR  - stdin: Failed initializing schema https://kubernetesjsonschema.dev/master-standalone/service-v1.json: Get "https://kubernetesjsonschema.dev/master-standalone/service-v1.json": dial tcp: lookup kubernetesjsonschema.dev on 192.168.65.5:53: dial udp 192.168.65.5:53: connect: network is unreachable
> >  in object 'v1/Service//my-nginx-svc' in file svc.yaml
> > error: exit status 1
> > ```
> 
> This is because of the implementation in `kubeval` function, more accurate, TS-SDK. By default it will only generate the structured results to stdout. The errors will be printed to `stderr` only when env `STRUCTURED_RESULTS` is set.

There's a discrepancy between output of `render` and `eval` for the same function.

Also, regardless of whether a function uses structured results, stderr, or both, we need to provide reasonable UX. See https://github.com/GoogleContainerTools/kpt/issues/1557#issuecomment-824348955

**Comment by natasha41575** [comment]
Listing some other output issues here (based on https://github.com/GoogleContainerTools/kpt/pull/1774 and https://github.com/GoogleContainerTools/kpt/pull/1762):

fn-render/invalid-inline-config error message should include what Resource is missing metadata; the error currently only says `missing Resource metadata`, leaving the user to hunt for which Resource threw the error.

fn-render/no-fnconfig error: `"failed to configure function: function config must be a ConfigMap or SetLabelConfig"` - per go/kpt-errors-style-guide, fields should be in back quotes

fn-eval/invalid-fn-config-file set-namespace should improve upon errors reported by low-level yaml libraries, see https://github.com/GoogleContainerTools/kpt/issues/1793

**Comment by Shell32-Natsu** [comment]
https://github.com/GoogleContainerTools/kpt/pull/1999 has addressed the last problem here. So close this one.
