### ISSUE TITLE
ResourceGroup CRD not installed automatically

### ISSUE THREAD

**Issue by frankfarzan** [GoogleContainerTools/kpt#1787]
```
$ kpt live init .
$ kpt live preview .
error: no matches for kind "ResourceGroup" in version "kpt.dev/v1alpha1"
```

**Comment by frankfarzan** [comment]
In the case that kpt fails to install CRD for whatever reason, the error message should instruct the user to install it using `install-resource-group`.

**Comment by mortent** [comment]
It is installed, but it seems like we don't wait to the CRD to become `Established` before we continue. There is another issue for this: https://github.com/GoogleContainerTools/kpt/issues/1612

**Comment by seans3** [comment]
Closed by: https://github.com/GoogleContainerTools/kpt/pull/1817
