### ISSUE TITLE
TS-SDK will not write errors to stderr by default

### ISSUE THREAD

**Issue by Shell32-Natsu** [GoogleContainerTools/kpt#1804]
TS-SDK uses env `LOG_TO_STDERR` and CLI flag `log_to_stderr` to control the behavior of writing errors to `stderr`. By default it will not write the errors to `stderr`.

https://github.com/GoogleContainerTools/kpt-functions-sdk/blob/b7e346f0c18f972edf7ca02272734fbc68fca905/ts/kpt-functions/src/run.ts#L143
https://github.com/GoogleContainerTools/kpt-functions-sdk/blob/b7e346f0c18f972edf7ca02272734fbc68fca905/ts/kpt-functions/src/types.ts#L226

In `fn render` we don't provide this env so the command cannot read error messages (https://github.com/GoogleContainerTools/kpt/issues/1783#issuecomment-824315178). We can either
1. Add env `LOG_TO_STDERR` to render container runtime
2. Update SDK to write the errors to `stderr` by default.

**Comment by Shell32-Natsu** [comment]
@frankfarzan

**Comment by frankfarzan** [comment]
In case of `kubeval`, even if function doesn't write to `stderr`, it's populating `results` right? So given the output UI, you should be able to see the results:
https://docs.google.com/document/d/1mWZyYcCWmFUZuNNG3O0r-Y-FOk256JS-1mVpNRxeuMg/edit?hl=en#

**Comment by Shell32-Natsu** [comment]
Yes. But the structured result support in the CLI output should be done after #1390

**Comment by Shell32-Natsu** [comment]
We will add the env to `render` runtime to keep consistent and avoid breaking existing functions.

**Comment by frankfarzan** [comment]
The way LOG_TO_STDERR works today in TS SDK: if enabled, it prints the results to stderr. Its semantic is really `ALSO_LOG_RESULTS_TO_STDERR`. This means with the UI proposal [1] where the orchestrator prints the `results`, you will see the same information duplicated.

So, once there new UI is ready:
- Neither `render` or `eval` should set this env variable

[1] https://docs.google.com/document/d/1mWZyYcCWmFUZuNNG3O0r-Y-FOk256JS-1mVpNRxeuMg/edit?hl=en#

**Comment by Shell32-Natsu** [comment]
The behavior of `render` has been updated in #1805. We should remove the env after supporting structured result but it's not a big deal (the env is only used in TS SDK to control stderr output). So close this.
