### ISSUE TITLE
Catalog site styling issues

### ISSUE THREAD

**Issue by frankfarzan** [GoogleContainerTools/kpt#1825]
- [x] Match styling with kpt.dev (font, navlink states, etc.)
- [x] Consistent use of headers between usage and example docs (Use `###` instead of `##` in examples). Compare:
    - https://kpt-dev-catalog.web.app/set-annotation/v0.1/
    - https://kpt-dev-catalog.web.app/set-annotation/v0.1/advanced/
- [x] From catalog site, clicking on kpt.dev links in navbar does a full reload (maybe WIP)

**Comment by etefera** [comment]
> * [ ]  From catalog site, clicking on kpt.dev links in navbar does a full reload (maybe WIP)
Unlikely to be addressed since the catalog is hosted on a different site, but marking done as it should consistently load in the same frame https://github.com/GoogleContainerTools/kpt-functions-catalog/pull/272
