### ISSUE TITLE
Render Notes box in docs

### ISSUE THREAD

**Issue by frankfarzan** [GoogleContainerTools/kpt#1843]
Currently we hack it using:

`> Refer to the [command reference][get-doc] for more details.`

For an example of a Notes box, see:

https://cloud.google.com/anthos/multicluster-management/connect/registering-a-cluster

Alternate solution to introducing html or non-markdown: we can change how quotes `> ` are rendered to make them look like notes boxes (more portable docs). Otherwise please update the docs.

**Comment by frankfarzan** [comment]
Alternate solution to introducing html or non-markdown: we can change how quotes `> ` are rendered to make them look like notes boxes.

**Comment by etefera** [comment]
@frankfarzan We can use Docsify's built-in helpers for this as well https://docsify.js.org/#/helpers?id=general-tips and https://docsify.js.org/#/helpers?id=important-content
Do those look good to you?
