### ISSUE TITLE
Go  Function SDK docs are very out of date

### ISSUE THREAD

**Issue by aw185176** [GoogleContainerTools/kpt#1844]
### Expected behavior
Doc examples work with dependencies used by Kpt itself (in this case, kyaml@v0.10.17)

### Actual behavior
`framework.Command` doesn't  exist in kyaml@v0.10.17

**Comment by mikebz** [comment]
@mengqiy heads up

**Comment by mengqiy** [comment]
There was a big refactor in kyaml@v0.10.14.
Our golang guide (https://googlecontainertools.github.io/kpt/guides/producer/functions/golang/) only works with kyaml <= v0.10.13.

cc: @frankfarzan who is overhauling our user guides.

**Comment by frankfarzan** [comment]
Dup of https://github.com/GoogleContainerTools/kpt/issues/2054
