### ISSUE TITLE
`fn eval` should use the same runtime with `render`

### ISSUE THREAD

**Issue by Shell32-Natsu** [GoogleContainerTools/kpt#1849]
Currently `fn eval` is using the runtime borrowed from kyaml instead of the `render` runtime because the `render` runtime hasn't supported some features required by `eval`, like network, mount, etc. Eventually we should get rid of the runtime from kyaml and make `eval` to use the same runtime with `render`.

This requires:
- [ ] Extract `internal/cmdrender/runtime` to a separate package.
- [ ] Implement functionalities required by `eval` in the runtime.
- [ ] Modify `eval` command to use new runtime.

**Comment by droot** [comment]
The innermost function runner is shared between `fn eval` and `fn render`, so closing this issue.
