### ISSUE TITLE
Cli Usability: Ensure consistent pkg reference across commands

### ISSUE THREAD

**Issue by Shell32-Natsu** [GoogleContainerTools/kpt#1850]
The `DisplayPath` used in `fn render` [PR](https://github.com/GoogleContainerTools/kpt/pull/1822) is a simple relative path to CWD. This is very ugly when users run the command with absolute path to the package.

We should have a solution for package reference and ensure consistent across all commands.

Also discussed in this thread https://docs.google.com/document/d/1mWZyYcCWmFUZuNNG3O0r-Y-FOk256JS-1mVpNRxeuMg/edit?disco=AAAAIVle320.

**Comment by Shell32-Natsu** [comment]
cc @droot @frankfarzan @phanimarupaka

**Comment by Shell32-Natsu** [comment]
Example of current display path used in `render`. https://github.com/GoogleContainerTools/kpt/pull/1822#discussion_r624015876

**Comment by frankfarzan** [comment]
This is part of CLI consistency effort. We need the following to be standardized:

- Definition of package name and identifier (and provide common code for them). See https://kpt.dev/book/03-packages/01-getting-a-package?id=package-name-and-identifier
- How the package name and identifier are presented.

For example, compare how `tree` command present the package:

`PKG: nginx`

vs how `render` and `eval` present the package:

`Package "nginx/configs":`

Differences:
- `PKG` vs `Package`
- Quoted vs not quoted
- OK: package name vs package identifier (tree needs only the name, not the identifier)

**Comment by phanimarupaka** [comment]
@frankfarzan The output for functions look good. So should we change the output of `tree`? 

```
Package "nginx":
├── [Kptfile]  Kptfile nginx
├── [deployment.yaml]  Deployment my-nginx
└── [svc.yaml]  Service my-nginx-svc
```
