### ISSUE TITLE
Remove unfriendly stack trace in error messages

### ISSUE THREAD

**Issue by frankfarzan** [GoogleContainerTools/kpt#1852]
```
$ pkg get https://github.com/GoogleContainerTools/kpt/package-examples/nginx@v0.2
cmdget.preRunE: destination directory nginx already exists
```

`cmdget.preRunE` doesn't make sense to end-users and is polluting the output.

**Comment by mortent** [comment]
Same for the error message if running `kpt pkg update` with a dirty working tree:

```
updating package <path>
cmdupdate.runE: pkg .:
	update.Run: package must be committed to git before attempting to update 
```

**Comment by mortent** [comment]
Trying to update a package and provide the incorrect path gives an unhelpful error message:
```
updating package /<path>/wordpress/wordpress to v0.2

Error: Failed to execute git command "git status -s"
```

**Comment by frankfarzan** [comment]
Guideline for error messages:

go/kpt-errors-style-guide

Feel free to add more rules or clarify with examples
