### ISSUE TITLE
Docs: 3.2 Exploring a Package

### ISSUE THREAD

**Issue by mikebz** [GoogleContainerTools/kpt#1856]
Following: https://kpt.dev/book/03-packages/02-exploring-a-package results in empty output. Not sure if things are working or not working.  We should have an example that gives user feedback that something positive happened.

**Comment by phanimarupaka** [comment]
Function output is being addressed as part of this issue 

https://github.com/GoogleContainerTools/kpt/issues/1557

**Comment by Shell32-Natsu** [comment]
Covered by #1861

**Comment by phanimarupaka** [comment]
@mikebz Should we close this ? Make it a duplicate ? Or keep it open ?

**Comment by mikebz** [comment]
Closing is fine. Thanks!
