### ISSUE TITLE
Installation doc doesn't work

### ISSUE THREAD

**Issue by frankfarzan** [GoogleContainerTools/kpt#1864]
Currently, Installation docs point to `latest` builds of binaries which wouldn't work (There are other releases besides CLI such as example packages).

**Comment by mikebz** [comment]
I would consider just pointing to next for now and doing a PR when we switch to latest.  I suspicion is that adding versioning to docs is a bigger task.

**Comment by mortent** [comment]
So there are a few things related to this:
 * We should consider moving the examples into a separate repo to avoid having non-kpt releases in the same repo. It will break the automatic generating of release notes with goreleaser and also means the time needed to fetch the example packages are dependent on the size of the kpt repo. Alternatively, we need to look into tuning the generation of release notes to ignore the non-kpt releases.
 * Can we set up an example of versioned docs? Once that is in place, we can look into automatically updating the references to the binaries and images using a separate commit after a successful release. But this logic needs to take into account that we almost certainly will not have separate doc versions for bug releases.

**Comment by frankfarzan** [comment]
Versioning of docs is tracked by https://github.com/GoogleContainerTools/kpt/issues/1925

This issue is scoped to making installation doc valid in m2 using stop gap solutions.

**Comment by frankfarzan** [comment]
> So there are a few things related to this:
> 
> * We should consider moving the examples into a separate repo to avoid having non-kpt releases in the same repo. It will break the automatic generating of release notes with goreleaser and also means the time needed to fetch the example packages are dependent on the size of the kpt repo. Alternatively, we need to look into tuning the generation of release notes to ignore the non-kpt releases.

The proper solution here is versioning the docs instead of pointing to the latest release artifact. This is tracked by #1925. Limiting releases to just CLI is brittle is a brittle solution.

> * Can we set up an example of versioned docs? Once that is in place, we can look into automatically updating the references to the binaries and images using a separate commit after a successful release. But this logic needs to take into account that we almost certainly will not have separate doc versions for bug releases.

**Comment by mikebz** [comment]
@etefera assigning this to you for right now to make sure we unblock people who use kpt.dev

**Comment by etefera** [comment]
> Versioning of docs is tracked by #1925
> 
> This issue is scoped to making installation doc valid in m2 using stop gap solutions.

Closing since installation docs currently point to working binaries.
