### ISSUE TITLE
Add copy button to shell blocks on kpt.dev

### ISSUE THREAD

**Issue by runewake2** [GoogleContainerTools/kpt#1867]
kpt doc packages that includes CLI examples include `$` characters to signify user input. These characters are included when copying from the documentation (you need to manually remove them). Preventing this character from being copied would make interacting with docs easier.

For example:

```sh
$ kpt live apply
```

currently copies `$ kpt live apply` but ideally would only include `kpt live apply`. This would help streamline consuming our docs and examples.

**Comment by mikebz** [comment]
I would argue that this is an M4 task.  This doesn't preclude us from going out to customers with fairly good doc as long as the documents are accurate.

**Comment by runewake2** [comment]
Agreed, I do not think this issue should block any of our release milestones but would provide a helpful UX improvement to the sites current behavior whenever we are able to prioritize that.

**Comment by frankfarzan** [comment]
The real solution here is to add copy buttons to code blocks.

Examples:
1. https://cloud.google.com/anthos-config-management/docs/how-to/installing-policy-controller
2. https://stripe.com/docs/api (This has the $ sign which is not copied)
