### ISSUE TITLE
More user-friendly errors for kpt pkg update

### ISSUE THREAD

**Issue by etefera** [GoogleContainerTools/kpt#1869]
### Expected behavior
On a bad invocation of `kpt pkg update`, expect to see actionable or user-oriented feedback.
For example, `kpt pkg update mypackage` in a non-initialized or non-package directory:
`Error: Unable to update package "/mydir/mypackage". Are you referencing an initialized package directory?`
### Actual behavior
`Error: Failed to execute git command "git status -s" `

### Information
Running on the `next` version of `kpt` as of https://github.com/GoogleContainerTools/kpt/tree/c3132208b9d760c6c1b22fe90f7166a6ecc165ce

Encountered with the https://github.com/GoogleContainerTools/kpt.git/package-examples/wordpress@v0.1 package.

### Steps to reproduce the behavior
1. `kpt pkg get https://github.com/GoogleContainerTools/kpt.git/package-examples/wordpress@v0.1`
2. `cd wordpress`
3. `kpt pkg update wordpress@v0.2`

**Comment by mortent** [comment]
This is also covered in https://github.com/GoogleContainerTools/kpt/issues/1852. Closing this as a duplicate and we'll track it there.
