### ISSUE TITLE
kpt live apply reading from stdin doesn't work

### ISSUE THREAD

**Issue by mortent** [GoogleContainerTools/kpt#1894]
### Expected behavior
I should be able to use `cat * | kpt live apply -` to apply resources into a cluster. This currently just returns the error `error: argument '-' is not but must be a directory`.

### Actual behavior
This should lead to the resources in `*` being applied.

### Information
As part of this, we should also look into how users can provide inventory information to kpt when reading from Stdin. It is not clear if requiring the information to be within the Kptfile is useful in this situation.

### Steps to reproduce the behavior

**Comment by mortent** [comment]
We should align this with https://github.com/GoogleContainerTools/kpt/issues/1952. I think they both will require a change in how we manage ManifestReader in kpt.

**Comment by mikebz** [comment]
I just tried it and it worked for me while I was working on the kustomize sample:

```
 ~/src/kpt/package-examples » kpt live init kustomize-pkg/overlays/dev
initializing Kptfile inventory info (namespace: default)...success
 ~/src/kpt/package-examples » kustomize build kustomize-pkg/overlays/dev | kpt live apply - 
service/dev-my-nginx-svc created
deployment.apps/dev-my-nginx created
2 resource(s) applied. 2 created, 0 unchanged, 0 configured, 0 failed
0 resource(s) pruned, 0 skipped, 0 failed
 ~/src/kpt/package-examples » kustomize build kustomize-pkg/overlays/dev | kpt live destroy - 
deployment.apps/dev-my-nginx deleted
service/dev-my-nginx-svc deleted
2 resource(s) deleted, 0 skipped

```
should we close this bug?
