### ISSUE TITLE
Check stdout in fn render and eval tests with non-zero exit code

### ISSUE THREAD

**Issue by phanimarupaka** [GoogleContainerTools/kpt#1910]
Currently fn eval and render tests only check the stdout if exit code is non-zero. Output to stdout of non-zero cases also must be verified.

**Comment by phanimarupaka** [comment]
> Currently fn eval and render tests only check of the stdout if exit code is non-zero. Output to stdout of non-zero cases also must be verified.

**Comment by Shell32-Natsu** [comment]
This has been done in #2062
