### ISSUE TITLE
Hash out details for CLI input/output, resource input/output and result output in `fn` commands

### ISSUE THREAD

**Issue by droot** [GoogleContainerTools/kpt#1915]
`kpt fn` commands involve the following:

- Resources: How are resources read and written out
- StructuredResult: How are structured results written out (No reading here)
- CLI output: How is the CLI output written

Some of `kpt fn` commands can be composed together, for ex. `kpt fn source| kpt fn eval| kpt fn sink.....` or `kpt fn render| kpt live apply`. All the above are controlled by the CLI flags, so we need to ensure they are consistent across the commands and also offers enough flexibility to meet user's need.

**Comment by Shell32-Natsu** [comment]
#2010 

The usage of commands in pipe should also be considered as a part of this design.

**Comment by droot** [comment]
@phanimarupaka since we are addressing all of these as part of `out-of-place`, I am assigning it to you.

**Comment by phanimarupaka** [comment]
This has been addressed and released as part of out-of-place hydration story.
