### ISSUE TITLE
Functions using kustomize library should not drop resource with local-config annotation

### ISSUE THREAD

**Issue by mengqiy** [GoogleContainerTools/kpt#1933]
For example, https://github.com/GoogleContainerTools/kpt/tree/87191859fdef443395741d85e134e5aa1cd0f877/package-examples/pipeline-validate this package has 4 input resources (2 normal resources + 2 local-config resources for gatekeeper)
After running fn set-labels, it drops the 2 local-config resources that are for gatekeeper.
Fn gatekeeper doesn't find any constraints specified, and always return success.

The functions that use [`NewResMapFromRNodeSlice`](https://pkg.go.dev/sigs.k8s.io/kustomize/api/resmap#Factory.NewResMapFromRNodeSlice) from kustomize repo to convert `[]*yaml.RNode` to `ResMap`, will drop resources with `local-config` annotation and there is no way to control this behavior currently: https://github.com/kubernetes-sigs/kustomize/blob/api/v0.8.9/api/resource/factory.go#L205-L236

One potential downstream fix is https://github.com/GoogleContainerTools/kpt-functions-catalog/pull/285.
We can also try to change the behavior in upstream kustmoze repo by allowing an option to control this behavior. @Shell32-Natsu said he will take a look at this upstream.

**Comment by frankfarzan** [comment]
Why and how does that function drop `local-config`?

**Comment by mengqiy** [comment]
set-annotations, set-labels, set-namespace and ensure-name-substring use kustomize library to update resources.
All of them is doing something like the following (e.g. https://github.com/GoogleContainerTools/kpt-functions-catalog/blob/d4dd831f1657660cdfd4fec51a6882c43d9ddf97/functions/go/set-labels/main.go#L75-L83):
```
resMap, err := resmapFactory.NewResMapFromRNodeSlice(items)
Transform(resMap)
return resMap.ToRNodeSlice()
```

`NewResMapFromRNodeSlice`drops every resource with a `local-config` annotation. 
This behavior probably makes sense for kustomize, but it's a bug for the functions.

**Comment by Shell32-Natsu** [comment]
@mengqiy https://github.com/kubernetes-sigs/kustomize/pull/3940 has updated the kustomize resource factory to have an option to include local-config file. You can update the functions.

**Comment by mengqiy** [comment]
fixed in https://github.com/GoogleContainerTools/kpt-functions-catalog/pull/382
