### ISSUE TITLE
reference doc: top-level

### ISSUE THREAD

**Issue by frankfarzan** [GoogleContainerTools/kpt#1937]
https://kpt.dev/reference/

Just a high-level description of the command groups will suffice. Examples and demo are stale and should be deleted.

**Comment by frankfarzan** [comment]
cc @mortent since you're changing the global flags.

**Comment by mikebz** [comment]
I see that the page is there.  Do we have other loose ends that we want to wrap up before we close this out?

**Comment by phanimarupaka** [comment]
https://github.com/GoogleContainerTools/kpt/pull/1978

@frankfarzan Any other items should be covered by this issue ?
