### ISSUE TITLE
Discrepancy between `--help` and `kpt.dev/reference/`

### ISSUE THREAD

**Issue by frankfarzan** [GoogleContainerTools/kpt#1939]
For example:

- [x] `pkg tree` command is missing in kpt.dev
- [x] `live migrate` command is missing in kpt.dev
- [x] `live fetch-k8s-schema` is stale on kpt.dev (should be removed)

General fix is to ensure the two cannot diverge.

**Comment by frankfarzan** [comment]
cc @mortent

**Comment by etefera** [comment]
`live fetch-k8s-schema` is already removed on site.
