### ISSUE TITLE
Partial setter matching  doesn't work with kebab case

### ISSUE THREAD

**Issue by stefanhenseler** [GoogleContainerTools/kpt#1940]
### Expected behavior

running:

`kpt fn run . --image gcr.io/kpt-fn/apply-setters:v0.1 -- 'registry=gcr.io' `

against a resource with the following setter comment:

` image: docker.io/my-app/my-app-backend:1.0.0 # kpt-set: ${registry}/${app-image-repo}/${app-image-name}:${app-image-tag}`

should result in the following output:

` image: gcr.io/my-app/my-app-backend:1.0.0 # kpt-set: ${registry}/${app-image-repo}/${app-image-name}:${app-image-tag}`

partial pattern matching should work with kebab case.

### Actual behavior

The following error is the result:

`values for setters [${app-image-repo} ${app-image-name} ${app-image-tag}] must be provided`

### Information

I'm currently using kebab case setter names with the apply-setters function v1.0. It seems like pattern matching fails due to the `-` being invalid for regex group matching names. The code block here specifies the group matcher https://github.com/GoogleContainerTools/kpt-functions-catalog/blob/master/functions/go/apply-setters/applysetters/apply_setters.go#L211.  As a workaround I'm currently using Camel Case, which works. I've also tried snake case, which also seems to work.

### Steps to reproduce the behavior

Here the test case I'm using to reproduce the issue :

```
        {
	name: "set setter pattern partial kebab case",
	config: `
data:
    registry: gcr.io
`,
			input: `apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: my-app
          image: docker.io/my-app/my-app-backend:1.0.0 # kpt-set: ${registry}/${app-image-repo}/${app-image-name}:${app-image-tag}
`,
			expectedResources: `apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: my-app
          image: gcr.io/my-app/my-app-backend:1.0.0 # kpt-set: ${registry}/${app-image-repo}/${app-image-name}:${app-image-tag}
`,
		},
```

this test will fail with:

```
--- FAIL: TestApplySettersFilter (167.62s)
    --- FAIL: TestApplySettersFilter/set_setter_pattern_partial_kebab_case (167.62s)
        apply_setters_test.go:398: 
            	Error Trace:	apply_setters_test.go:398
            	Error:      	Received unexpected error:
            	         	
            	Test:       	TestApplySettersFilter/set_setter_pattern_partial_kebab_case
```

The actual exception seems to be this:

`error parsing regexp: invalid named capture: (?P<app-image-repo> `

This is a snippet that reproduces the issue as well:

https://play.golang.org/p/5Ttn7N4QVyq

This one would work:

https://play.golang.org/p/e-jYgaU7p19

**Comment by phanimarupaka** [comment]
@stefanhenseler Thanks for trying out the new apply-setters function and filing the issue. I raised a PR for the fix. 

As a user survey, can you please provide feedback on the new version of setters when compared to the existing version of setters. Do you see any friction points ?

**Comment by stefanhenseler** [comment]
@phanimarupaka Thanks for creating a PR for this.

I really like the new way how setters work. Also, our customers really like how simple it is to write setters now. It used to be very tedious to just write up a simple setter using the openapi spec in the kpt file. The new way is so much simpler and also kind of elegant. I especially like how quickly you can now just write up a whole kpt package without switching between files all the time. I think the new approach is also more flexible in regards to sub-packages and how "inheritance" works. It's just straightforward. Here a couple of things we thought could be improved:

**Comment by stefanhenseler** [comment]
@phanimarupaka Thanks for creating a PR for this.

In a nutshell, we really like the new way how setters work. Our customers really appreciate how simple it is to write setters now. It used to be very tedious to just write up a simple setter using the openapi spec in the kpt file. The new way is so much simpler and also kind of elegant. I especially like how quickly you can now just write up a whole kpt package without switching between files all the time. I think the new approach is also more flexible in regards to sub-packages and how "inheritance" works. It's just straightforward. 

Here a couple of things we thought could be improved:

1. Setter discoverability is not convenient for new users. It would be nice to have some tooling for vscode or other IDE's to discover setters when typing, including default values and a description, which we usually just append to the kpt-set marker as an additional comment.
2. Being able to use setters in setter values would be nice as well. for example, imagine the following setters:

    ```yaml
    stage: dev
    domain: example.com
    auth-url: https://auth.dev.example.com
    realm-name: dev-auth
    ```
    I would want to set the `auth-url` using the two other setters so I don't have to repeat the stage name all over my setter values. So ideally I could just do this:
    
    ```yaml
    stage: dev
    domain: example.com
    auth-url: https://auth.${stage}.${domain}
    realm-name: ${stage}-auth
    ```
    
    We experimented with a first iteration over the setter values and just replacing all the substitutions in the setter values using the setter values available. This seems to work quite well.

But besides these things, I think we are really happy with how the apply-setters function works. We started migrating all our packages to the function-based approach.

**Comment by phanimarupaka** [comment]
> @phanimarupaka Thanks for creating a PR for this.
> 
> In a nutshell, we really like the new way how setters work. Our customers really appreciate how simple it is to write setters now. It used to be very tedious to just write up a simple setter using the openapi spec in the kpt file. The new way is so much simpler and also kind of elegant. I especially like how quickly you can now just write up a whole kpt package without switching between files all the time. I think the new approach is also more flexible in regards to sub-packages and how "inheritance" works. It's just straightforward.
>
@stefanhenseler Thanks for the feedback. Good to hear that. 
> Here a couple of things we thought could be improved:
> 
> 1. Setter discoverability is not convenient for new users. It would be nice to have some tooling for vscode or other IDE's to discover setters when typing, including default values and a description, which we usually just append to the kpt-set marker as an additional comment.

That issue is already under consideration. 
Current solution: Assuming you are a package publisher, you can help your consumers by including ConfigMap with descriptions as comments so that your package consumers can discover and edit the values in file([example](https://github.com/GoogleContainerTools/kpt-functions-catalog/blob/master/examples/apply-setters/simple/fn-config.yaml)).

Long term, we want to provide an easy way(retaining the current simplicity which you pointed out) for package publishers to provide validation schema for setter values so that IDE extensions like Cloud Code can leverage them and provide authoring assistance.

![image](https://user-images.githubusercontent.com/58999035/117581603-83fd1280-b0b2-11eb-9019-1730402d6658.png)

> 2. Being able to use setters in setter values would be nice as well. for example, imagine the following setters:
>    ```yaml
>    stage: dev
>    domain: example.com
>    auth-url: https://auth.dev.example.com
>    realm-name: dev-auth
>    ```
>    
>    
>    I would want to set the `auth-url` using the two other setters so I don't have to repeat the stage name all over my setter values. So ideally I could just do this:
>    ```yaml
>    stage: dev
>    domain: example.com
>    auth-url: https://auth.${stage}.${domain}
>    realm-name: ${stage}-auth
>    ```
>    

We have considered this option but wanted to know more real world use-cases. Why do you need it ? Why cant the `kpt-set` comment itself point to `stage`, `domain` setters and get rid of `auth-url` setter? Is it because `auth-url` setter can have a totally different value like `https://foo.bar.com`? Can you please provide the resource example as well with setter comments to know more about the use-case ? 

>    
>    We experimented with a first iteration over the setter values and just replacing all the substitutions in the setter values using the setter values available. This seems to work quite well.
> 
> But besides these things, I think we are really happy with how the apply-setters function works. We started migrating all our packages to the function-based approach.

**Comment by stefanhenseler** [comment]
> Current solution: Assuming you are a package publisher, you can help your consumers by including ConfigMap with descriptions as comments so that your package consumers can discover and edit the values in file([example](https://github.com/GoogleContainerTools/kpt-functions-catalog/blob/master/examples/apply-setters/simple/fn-config.yaml)).

Yes, this is what we are doing at the moment. We just comment out all the available setters and add comments as descriptions. This allows a user to understand the setters right away. But especially if there are many sub-packages which one does dynamically add, it would be better if this could be part of the tooling. I think adding the possibility to use a schema for validation using comments as well, would be really great (That was one thing I liked about the openapi spec approach :)). But as you say, it should retain the current simplicity and lightweight notation.

> We have considered this option but wanted to know more real world use-cases. Why do you need it ? Why cant the `kpt-set` comment itself point to `stage`, `domain` setters and get rid of `auth-url` setter? Is it because `auth-url` setter can have a totally different value like `https://foo.bar.com`? Can you please provide the resource example as well with setter comments to know more about the use-case ?

exactly. So one particular example would be a VirtualService resource (or Ingress / Route). Where in the package, almost all instances use the default pattern, but there is always one customer where this is not possible and then you need to change the pattern. Is the search-replace function the tool to be used for this case? Here an example:

```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: my-app
spec:
  hosts:
  - "my-app.helix.dev.example.com" # kpt-set: my-app.${stage}.${domain} <--- So here we might have to change the pattern to  something like this: accounts.apis.${domain}
  gateways:
  - helix-istio-ingress-external/helix-gateway
  http:
  - route:
    - destination:
        host: my-app
        port:
          number: 8443
```

**Comment by phanimarupaka** [comment]
> > Current solution: Assuming you are a package publisher, you can help your consumers by including ConfigMap with descriptions as comments so that your package consumers can discover and edit the values in file([example](https://github.com/GoogleContainerTools/kpt-functions-catalog/blob/master/examples/apply-setters/simple/fn-config.yaml)).
> 
> Yes, this is what we are doing at the moment. We just comment out all the available setters and add comments as descriptions. This allows a user to understand the setters right away. But especially if there are many sub-packages which one does dynamically add, it would be better if this could be part of the tooling. I think adding the possibility to use a schema for validation using comments as well, would be really great (That was one thing I liked about the openapi spec approach :)). But as you say, it should retain the current simplicity and lightweight notation.
> 

Yes. We want to leave the most common cases UX simple. So we will not be adding more data to setter comments as it will affect the readability of resource files. We might ask package publishers to provide schema in a meta file separate from resources itself. But it is too early to discuss about that. Stay tuned for updates.

> > We have considered this option but wanted to know more real world use-cases. Why do you need it ? Why cant the `kpt-set` comment itself point to `stage`, `domain` setters and get rid of `auth-url` setter? Is it because `auth-url` setter can have a totally different value like `https://foo.bar.com`? Can you please provide the resource example as well with setter comments to know more about the use-case ?
> 
> exactly. So one particular example would be a VirtualService resource (or Ingress / Route). Where in the package, almost all instances use the default pattern, but there is always one customer where this is not possible and then you need to change the pattern. Is the search-replace function the tool to be used for this case? Here an example:
> 
> ```yaml
> apiVersion: networking.istio.io/v1beta1
> kind: VirtualService
> metadata:
>   name: my-app
> spec:
>   hosts:
>   - "my-app.helix.dev.example.com" # kpt-set: my-app.${stage}.${domain} <--- So here we might have to change the pattern to  something like this: accounts.apis.${domain}
>   gateways:
>   - helix-istio-ingress-external/helix-gateway
>   http:
>   - route:
>     - destination:
>         host: my-app
>         port:
>           number: 8443
> ```
> 
> @ryane do you have another example?

If most of your customers are using default pattern, I would recommend using the default pattern as `kpt-set` comment. Yes, if there are customers who want to change the value completely, they can use [search-replace](https://catalog.kpt.dev/search-replace/v0.1/) function.

**Comment by stefanhenseler** [comment]
> Yes. We want to leave the most common cases UX simple. So we will not be adding more data to setter comments as it will affect the readability of resource files. We might ask package publishers to provide schema in a meta file separate from resources and function config. But it is too early to discuss about that. Stay tuned for updates.

Sounds great! Looking forward to seeing where this goes.

> Let me know if combination of apply-setters and search-replace solves your use-case.

I didn't use it yet in that way, but I guess this should be sufficient. I actually think although there might be some edge cases where the setter substitution would help, It's better to keep it out for simplicity's sake. Also, search-replace seems very flexible. I will look into it.

**Comment by Pitta** [comment]
I'm curious @stefanhenseler - have you settled in to a pattern without the classic pattern substitutions used to provide? I leveraged that pattern a lot, especially with regards to heavily verbose internal DNS urls. 

It was nice to be able to expose simple setters that took a single value, then have those be concatenated but a substitution downstream. When using setters imperatively, it seems like it would be impossible to discover what used to be a substitution, instead requiring the consumer to know the entire value that needs to be replace.

I'm not sure how search-replace helps with discoverability in this case. The substitutions helped allow package maintainers to simplify consumption - and it seems like we are losing that.

**Comment by stefanhenseler** [comment]
@Pitta yes, we chose to simplify our setup and basically use single setter values where possible. If we use two setters in one key, we always make sure to explicitly set both setters. It's not ideal, but this works for us at the moment.
