### ISSUE TITLE
Design and implement `upsert-resource` function

### ISSUE THREAD

**Issue by phanimarupaka** [GoogleContainerTools/kpt#1942]
Users need a way to easily upsert a resource to the package. Upsert is an operation that adds a Resource(uniquely identified by Group, Kind, Name and Namespace(GKNN)) to a package if it does not already exist, or replaces it if it already exists in the package.

- [x] Design `upsert-resource` function
- [ ] Implement `upsert-resource` function

**Comment by mikebz** [comment]
this is in review.  Do we hav e PR associated with it?
