### ISSUE TITLE
'kpt tutorial' requires installing asciicinema

### ISSUE THREAD

**Issue by cslink** [GoogleContainerTools/kpt#195]
From here: https://googlecontainertools.github.io/kpt/pkg/

cslink@mercutio:~/Downloads$ ./kpt tutorial pkg
must install asciinema to run tutorials: https://asciinema.orgcslink@mercutio:~/Downloads$ 

It also messes up my ability to click this link.

**Comment by phanimarupaka** [comment]
There are no more kpt tutorials in kpt.dev.
