### ISSUE TITLE
`live apply` should not apply function configs by default

### ISSUE THREAD

**Issue by mengqiy** [GoogleContainerTools/kpt#1952]
We should have this behavior to ensure the package after hydration is ready to be consumed by `kpt live`.
`kpt live` ignore resources what have the local-config annotation.

For example, we have the following Kptfile and fn config file:
```shell
$ cat Kptfile
apiVersion: kpt.dev/v1alpha2
kind: Kptfile
metadata:
  name: app
pipeline:
  mutators:
  - image: gcr.io/kpt-fn/set-label:unstable
    configPath: labelconfig.yaml
```

```
$ cat labelconfig.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: label-config
data:
  tier: db
```

After the hydration, the fn config file should become:
```
$ cat labelconfig.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: label-config
  annotations:
    config.kubernetes.io/local-config: 'true'
data:
  tier: db
```

**Comment by frankfarzan** [comment]
Probably the more seamless UI is that `live` should not apply `functionConfig` without requiring this annotation. The only corner case is when there's a `functionConfig` that happens to also be a resource you want to apply.
