### ISSUE TITLE
formatting changes introduced by `eval`

### ISSUE THREAD

**Issue by frankfarzan** [GoogleContainerTools/kpt#1973]
```
kpt pkg get https://github.com/GoogleContainerTools/kpt.git/package-examples/wordpress@next
cd wordpress
kpt fn render
kpt fn eval --image gcr.io/kpt-fn/set-namespace:v0.1 -- namespace=wordpress
git diff
```

Two issues:
1) Why is `set-namespace` changing the formatting?
2) More importantly: This is a general issue that can happen with arbitrary functions. The current answer is that you should run `render` after `eval`. But then, why not just have `eval` perform formatting as well as a convenience?

**Comment by frankfarzan** [comment]
But you can have a pipeline with just a validator and `render` would format?

**Comment by phanimarupaka** [comment]
> But you can have a pipeline with just a validator and `render` would format?
> 
> Not all functions are or will be using Go or kyaml, so the general question about formatting by eval is orthogonal.

So you say we should format resources as part of eval as well ?

**Comment by phanimarupaka** [comment]
> But you can have a pipeline with just a validator and `render` would format?
> 
> Not all functions are or will be using Go or kyaml, so the general question about formatting by eval is orthogonal.

Agree. So how about formatting resources as part of eval command as with clear messaging. In the following example, search(without replace) is formatting resources with clear messaging.

```
$ kpt fn eval --image gcr.io/kpt-fn/search-replace:v0.1 -- by-value=4

[RUNNING] "gcr.io/kpt-fn/search-replace:v0.1"
[PASS] "gcr.io/kpt-fn/search-replace:v0.1"
  Results:
    [INFO] Matched field value to "4" in file "resources.yaml" in field "spec.replicas"
    [INFO] Formatted resources.
```
