### ISSUE TITLE
kpt cfg count has printing issue for kustomization directories

### ISSUE THREAD

**Issue by seans3** [GoogleContainerTools/kpt#199]
**Steps to reproduce**

1. Download the `helloworld-kustomize` repo:
 `kpt pkg get git@github.com:GoogleContainerTools/kpt.git/package-examples/helloworld-kustomize helloworld-kustomize`
 
2. Run the `kpt cfg count` command on this local dir:
`kpt cfg count helloworld-kustomize`

Output has a missing identifier:

: 1
Deployment: 2
Service: 1

Notice the missing identifier for the first entry. This seems to be because the `kustomization.yaml` file does not have a `kind: Kustomization` field.

**Comment by pwittrock** [comment]
WDYT the behavior should be?  not print the kustomization?

**Comment by phanimarupaka** [comment]
This feature is no longer supported in kpt v1.
