### ISSUE TITLE
Move inflate-helm-chart function from contrib to the catalog

### ISSUE THREAD

**Issue by yuwenma** [GoogleContainerTools/kpt#1993]
Can we keep the helm-inflator image in repo kpt-functions-catalog? 

We used to have that function with helpful docs and examples in  
https://github.com/GoogleContainerTools/kpt-functions-catalog/tree/master/examples/contrib/helm-inflator. Some how it is removed

**Comment by yuwenma** [comment]
@mengqiy @mikebz

**Comment by Shell32-Natsu** [comment]
This is new example location: https://github.com/GoogleContainerTools/kpt-functions-catalog/tree/master/examples/contrib/inflate-helm-chart

**Comment by mengqiy** [comment]
We should solve https://github.com/GoogleContainerTools/kpt/issues/1181 before releasing the function in the curated catalog.

**Comment by yuwenma** [comment]
This is resolved with the new gcr.io/kpt-fn/render-helm-charts. @natasha41575 @mengqiy @mikebz closed

**Comment by mengqiy** [comment]
@natasha41575 Can you please remove the old inflate-helm-chart directory and examples, but leave a simple README.md in `functions/contrib/go/inflate-helm-chart` telling the new location of the function?

**Comment by natasha41575** [comment]
/assign

will do
