### ISSUE TITLE
kpt fn eval gives an error: args must have keys and values separated by =

### ISSUE THREAD

**Issue by mikebz** [GoogleContainerTools/kpt#2004]
### Expected behavior
The example works on zsh on MacOS
https://kpt.dev/book/04-using-functions/02-imperative-function-execution

### Actual behavior
error: args must have keys and values separated by =

### Steps to reproduce the behavior

```
 ~/src/sandbox/fishfood4 » kpt fn eval --image gcr.io/kpt-fn/set-namespace:v0.1 -- namespace=mywordpress wordpress
error: args must have keys and values separated by =
 ~/src/sandbox/fishfood4 » kpt fn eval --image gcr.io/kpt-fn/set-namespace:v0.1 -- "namespace=mywordpress" wordpress
error: args must have keys and values separated by =
```

**Comment by etefera** [comment]
Reproducible on bash on Linux as well. The invocation looks incorrect to me in the documentation; the package path should appear before the arguments passed to the function:
`kpt fn eval --image gcr.io/kpt-fn/set-namespace:v0.1 wordpress -- namespace=mywordpress`

**Comment by Shell32-Natsu** [comment]
The package name must go before `--`. This is expected bahavior.
