### ISSUE TITLE
kpt fn should time out instead of hanging when Docker is not available

### ISSUE THREAD

**Issue by natasha41575** [GoogleContainerTools/kpt#2005]
When `docker ps` hangs, `kpt fn render` also hangs. Kpt fn should never hang, and should time out and throw an error.

The same should be true generally, e.g. if git is unresponsive, etc.

cc @droot 

Somewhat related: kpt should show docker progress https://github.com/GoogleContainerTools/kpt/issues/1948

**Comment by Shell32-Natsu** [comment]
https://github.com/GoogleContainerTools/kpt/blob/fdecff4640e105408230c830eabcf7c979c66a49/internal/fnruntime/container.go#L38

The timeout now is 5 min.

**Comment by natasha41575** [comment]
5 minutes is a bit long; if there is no response from docker daemon maybe we should time out earlier?

**Comment by droot** [comment]
@Shell32-Natsu if remember correctly, `docker ps` was also hanging on your machine. What that means, the command is hanging in the `docker prerequisite check` that we before even running the pipeline. If that's the case, the timeout for that prerequisite check can be made just 5 seconds or something to inform the user.

**Comment by Shell32-Natsu** [comment]
We have 3 docker commands to run when running pipeline

1. `docker image ls`
2. `docker image pull`
3. `docker run`

So the problem here is finding proper timeout value for these commands.

**Comment by Shell32-Natsu** [comment]
Docker command timeout:

1. `docker image inspect`: 5s
2. `docker image pull`: 5min
3. `docker run`: 5min

WDYT?

**Comment by natasha41575** [comment]
> Docker command timeout:
docker image inspect: 5s
docker image pull: 5min
docker run: 5min
WDYT?

SGTM

There is also `docker version` run by `DockerCmdAvailable` in `internal/util/cmdutil/cmdutil.go`. Does this need a timeout too?

**Comment by Shell32-Natsu** [comment]
> > Docker command timeout:
> > docker image inspect: 5s
> > docker image pull: 5min
> > docker run: 5min
> > WDYT?
> 
> This makes sense to me. There is also `docker version` run by `DockerCmdAvailable` in `internal/util/cmdutil/cmdutil.go`. Does this need a timeout too?

Probably yes.
