### ISSUE TITLE
output of `eval` with Unix pipe

### ISSUE THREAD

**Issue by frankfarzan** [GoogleContainerTools/kpt#2010]
```
kpt fn source wordpress \
  | kpt fn eval --image gcr.io/kpt-fn/set-namespace:v0.1 - \
  | kpt fn eval --image gcr.io/kpt-fn/set-label:v0.1 -
error:   Stderr:
    "failed to configure function: input namespace cannot be empty"
  Exit Code: 1
error:   Stderr:
    "failed to configure function: input label list cannot be empty"
  Exit Code: 1
```

Related comment: https://github.com/GoogleContainerTools/kpt/pull/1981#discussion_r632026952

**Comment by Shell32-Natsu** [comment]
Some discussions in another issue.

https://github.com/GoogleContainerTools/kpt/issues/2006#issuecomment-841393567

https://github.com/GoogleContainerTools/kpt/issues/2006#issuecomment-841397475

**Comment by Shell32-Natsu** [comment]
#2090 adds test cases for this behavior and slightly improves the output. Detail design should be done in #1915. Close this one and use #1915 to track.
