### ISSUE TITLE
Support image digest in pipelines

### ISSUE THREAD

**Issue by bzub** [GoogleContainerTools/kpt#2020]
### Expected behavior

This should work:
```yaml
apiVersion: kpt.dev/v1alpha2
kind: Kptfile
metadata:
  name: my-pkg
pipeline:
  validators:
    # - image: gcr.io/kpt-fn/kubeval:v0.1.0
    # - image: gcr.io/kpt-fn/kubeval:unstable
    - image: gcr.io/kpt-fn/kubeval@sha256:a2672547b418a57a2b2b41940f96ab4fe78f19851f15c74017ff074bba70c9d9
      configMap:
        ignore_missing_schemas: "true"
```
For example `gcr.io/kpt-fn/kubeval@sha256:a2672547b418a57a2b2b41940f96ab4fe78f19851f15c74017ff074bba70c9d9`

### Actual behavior

```
kpt fn render

Error: invalid pipeline: function "gcr.io/kpt-fn/kubeval@sha256:a2672547b418a57a2b2b41940f96ab4fe78f19851f15c74017ff074bba70c9d9": 'image' is invalid: function name "gcr.io/kpt-fn/kubeval@sha256:a2672547b418a
57a2b2b41940f96ab4fe78f19851f15c74017ff074bba70c9d9" is invalid
```

### Information

kpt version from next branch: https://github.com/GoogleContainerTools/kpt/commit/810971b0520a07c1398c8f631388677f0ee34890

**Comment by mikebz** [comment]
thank you for reporting this and trying it out!

I am going to put this into the "fit and finish" milestone unless you are blocked from further testing.  Please advise.

**Comment by mikebz** [comment]
@droot heads up

**Comment by natasha41575** [comment]
should be fixed by https://github.com/GoogleContainerTools/kpt/pull/2334
