### ISSUE TITLE
fn render invariant: throw error if duplicate resources are detected

### ISSUE THREAD

**Issue by natasha41575** [GoogleContainerTools/kpt#2028]
Parent issue: https://github.com/GoogleContainerTools/kpt/issues/1559

`kpt fn render` should fail with error whenever it detects duplicate resource in the input or output of the function in the pipeline

There are two parts to this task:

- [ ] Define when resources should be considered "duplicates" (e.g. are resources allowed to have the same GVKNN if they are in separate subpackages?)
- [ ] Enforce the definition above and throw errors when duplicates are found

cc @droot

**Comment by phanimarupaka** [comment]
Resource identity should be based on GKNN and not GVKNN. 
Input should not be checked for duplicates as there could be functions in the pipeline which can change the name of the resource.

**Comment by droot** [comment]
> Resource identity should be based on GKNN and not GVKNN.
> Input should not be checked for duplicates as there could be functions in the pipeline which can change the name of the resource.

+1 for both the points.

**Comment by natasha41575** [comment]
@droot I added both points to the doc I shared with you that should address the first part of the task.

Thank you @phanimarupaka!

**Comment by droot** [comment]
This invariant is very tricky and several implications if we simply apply `GVNN` based primary key on resources. The packages will only be useful for single cluster, but in practice, we have seen to be packages being used for multi cluster deployments. This isn't something that blocks `m2`, but the behavior is under specified, so we would like to get to a well defined behavior in `m3`.

**Comment by droot** [comment]
The behavior seems to have been settled so closing this. We should open new issue if current behavior isn't sufficient.
