### ISSUE TITLE
Support symlinks in hydration package traversal

### ISSUE THREAD

**Issue by natasha41575** [GoogleContainerTools/kpt#2040]
Currently, `kpt fn render` subpackage traversal doesn't follow symlinks. 

See lines 7-9 for fn-render in go/kpt-test-cases

cc @droot

**Comment by mikebz** [comment]
is this different than #1544

**Comment by natasha41575** [comment]
No sorry. Didn't realize that issue was filed; closing this as a dup and linking the other one in the sheet
