### ISSUE TITLE
Pattern matching doesn't work with urls and multiple setters

### ISSUE THREAD

**Issue by stefanhenseler** [GoogleContainerTools/kpt#2044]
### Expected behavior

It should be possible to pattern match the following setter:
```yaml
host: my-app-layer-dev-id.tc.demo-example.com # kpt-set: my-app-layer-${stage}-${id}.${domain}
```
${stage} = dev
${id} = id
${domain} = tc.demo-example.com

### Actual behavior

The pattern gets matched like this:

${stage} = dev-id.tc.demo
${id} = example
${domain} = com

this causes the apply-setter function to fail, in a case when only `domain` is set.  

```bash
kpt fn run imp --log-steps
Running gcr.io/kpt-fn/apply-setters:unstable
failed to apply setters: values for setters [${stage} ${id}] must be providederror: exit status 
```

### Information

This could be related to how regexp does group matching, but I'm not sure if this behavior can be changed. Right now it does cause problems. If this can't be fixed, what would be the recommended approach to set the host field using multiple setters?

### Steps to reproduce the behavior

Run this code: https://play.golang.org/p/zAMGPDC924Z

this is an implementation of the `currentSetterValues` function https://github.com/GoogleContainerTools/kpt-functions-catalog/blob/38008b450af02be99c6ebfdb6c3010fb198878b7/functions/go/apply-setters/applysetters/apply_setters.go#L261. This is the actual code doing the pattern matching.

You can also use this test case to reproduce it:

```go
		{
			name: "scalar partial setter using dots and dash",
			config: `
data:
  domain: customer.com
`,
			input: `apiVersion: v1
kind: ConfigMap
metadata:
  name: my-app-layer
spec:
  host: my-app-layer-stage-id.tc.demo-example.com # kpt-set: my-app-layer-${stage}-${id}.${domain}
`,
			expectedResources: `apiVersion: v1
kind: ConfigMap
metadata:
  name: my-app-layer
spec:
  host: my-app-layer-stage-id.customer.com # kpt-set: my-app-layer-${stage}-${id}.${domain}
`,
		},
```

**Comment by mikebz** [comment]
@etefera can you please take a look at this?

**Comment by phanimarupaka** [comment]
@stefanhenseler This is an ambiguous case which can't be solved. Work around is simple, users should pass all the values. What else do you think can be done ?

**Comment by phanimarupaka** [comment]
Closing this issue due to no response. Please reopen it if you still have questions.
