### ISSUE TITLE
Generate resources doesn't work with subpackages

### ISSUE THREAD

**Issue by phanimarupaka** [GoogleContainerTools/kpt#2050]
### Expected behavior

Function which generates resources should generate resource if the function is declared in subpackage Kptfile and invoked through `kpt fn render`

### Actual behavior

Works for root package but fails for subpackage

```
➜  upsertruntest git:(main) ✗ kpt fn render       
Package "upsertruntest/foo": 
[RUNNING] "gcr.io/kpt-fn/upsert-resource:unstable"
[PASS] "gcr.io/kpt-fn/upsert-resource:unstable"

Package "upsertruntest": 
[RUNNING] "gcr.io/kpt-fn/upsert-resource:unstable"
[PASS] "gcr.io/kpt-fn/upsert-resource:unstable"

error: failed to save resources: resources must be annotated with config.kubernetes.io/index to be written to files
```
### Steps to reproduce the behavior

Add a function which generates resource to Kptfile of subpackage and trigger `kpt fn render` on root package.

**Comment by frankfarzan** [comment]
Please add an e2e test for this and include it in go/kpt-test-cases

**Comment by frankfarzan** [comment]
@phanimarupaka please add a minimum reproducible test case to https://github.com/GoogleContainerTools/kpt/tree/next/e2e/testdata

**Comment by phanimarupaka** [comment]
sure

**Comment by phanimarupaka** [comment]
@frankfarzan Yes. The root cause is that, I was trying to add same resource in root package and subpackage but the duplicates are not allowed. The error message was misleading. This should be addressed as part if invariant story @natasha41575 is working on.

**Comment by droot** [comment]
@phanimarupaka Note that a generator function in a sub package can not add resource in the parent (or ancestor) package, however an ancestor package can add resource to a `sub package`. [We have e2e tests for both].
Yes, ancestor package adding duplicate resource in any descendent package is yet to be addressed as part of `invariant` story.

**Comment by frankfarzan** [comment]
I expect the test case that was added to fail if this is a bug, not be passing. The test should also make sure there is reasonable failure message. Otherwise, there are other test cases for generation that currently passing.

**Comment by phanimarupaka** [comment]
The issue is related to better error messaging which is already being worked on https://github.com/GoogleContainerTools/kpt/issues/2028
