### ISSUE TITLE
Kptfile should be formatted based on openapi schema, not lexicographically

### ISSUE THREAD

**Issue by mortent** [GoogleContainerTools/kpt#2052]
Kptfile should be formatted based on openapi schema, and not lexicographically. This will give us better control of formatting and make sure we can add new fields easier.

**Comment by mikebz** [comment]
relevant to #1381

**Comment by phanimarupaka** [comment]
@etefera Are you working on Kptfile schema ?

**Comment by etefera** [comment]
> @etefera Are you working on Kptfile schema ?

I'm working on presenting it in the documentation, yes, but not the schema itself.

**Comment by droot** [comment]
We have done significant work to preserve ordering/formatting of resources during `fn eval|render`, so not sure if this is still valid. I will close this issue for now and let's reopen it in context of new requirements related to formatting (if any)
