### ISSUE TITLE
Feature request: A function that lists setters

### ISSUE THREAD

**Issue by grmoon** [GoogleContainerTools/kpt#2097]
### Is your feature request related to a problem? Please describe.

Inability to list setters in kpt v1.0

### Describe the solution you'd like

With kpt 1.0 changing the nature of setters, the ability to [list setters](https://googlecontainertools.github.io/kpt/reference/cfg/list-setters/) is going away. It would be great to add a function catalog function that lists setters and has the ability to output the setters in json format, something like

`$ kpt fn eval --image gcr.io/kpt-fn/list-setters:v0.1 -- 'format=json'` which outputs something like:

#### Success
```json
{ 
  "success": true,
  "setters": [
    { 
        "name": "image",
        "type": "string"
    },
    {
       "name": "labels",
       "type": "list"
    }
  ]
}
```

#### Failure
```json
{ 
  "success": false,
  "error": "some error message"
}
```

**Comment by mikebz** [comment]
@grmoon a couple of questions:
are you looking to see what setters are already in the kpt pipeline?
are you looking to see what parameters are missing?

Trying to get the end to end scenario here.

**Comment by grmoon** [comment]
> @grmoon a couple of questions:
> are you looking to see what setters are already in the kpt pipeline?
> are you looking to see what parameters are missing?
> 
> Trying to get the end to end scenario here.

we are looking to see setters that are already in a kpt file or config map. The end to end flow here is for users editing their kpt package to be able to open a dialog and say "i want to set the `image` setter value to `ubuntu`/`nginx`/whatever"

This is not one of our near-term goals, so not urgent. but it is something we will eventually need

**Comment by morgante** [comment]
This is also essential for users to be able to easily interact with new packages and for autogenerating documentation. I've had to strip exploratory commands from documentation.

**Comment by phanimarupaka** [comment]
@grmoon You can try out this function using unstable tag(`kpt fn eval list-setters:unstable`). This will be released soon with a version tag.
