### ISSUE TITLE
fn render should not format Kptfile and the fn config files used in a Kptfile

### ISSUE THREAD

**Issue by mengqiy** [GoogleContainerTools/kpt#2101]
We need to verify if eval has this issue too.

**Comment by mengqiy** [comment]
cc: @phanimarupaka

**Comment by droot** [comment]
This is by design. @phanimarupaka added the behavior recently.

@mengqiy why `kpt render` shouldn't format meta resources ?

**Comment by mengqiy** [comment]
There are 2 resources in this context:
- Kptfile
- fn-config.yaml files that are referenced by Kptfile.

I don't have a strong opinion about formatting `Kptfile`.
But IMO `fn-config.yaml` files should be invariants. Formatting them generates noise when looking at the diff of a package.
