### ISSUE TITLE
Feature request: Use `validator` and `mutator` repositories

### ISSUE THREAD

**Issue by grmoon** [GoogleContainerTools/kpt#2102]
### Is your feature request related to a problem? Please describe.

There is no easy way to distinguish between function catalog validators and mutators based on function names or tags. Autocompletion for Kptfile pipelines needs to be able to tell the difference between the two in order to display valid options for validator images and mutator images.

### Describe the solution you'd like

Instead of deploying everything to `gcr.io/kpt-fn`, deploy validators to `gcr.io/kpt-fn/validators/...` and mutators to `gcr.io/kpt-fn/mutators/...`. This makes it easy to retrieve only the desired type of functions using (for example) `gcloud container images list --repository gcr.io/kpt-fn/validators`

**Comment by droot** [comment]
Thanks for sharing the feedback @grmoon .

**Comment by mengqiy** [comment]
> Autocompletion for Kptfile pipelines needs to be able to tell the difference between the two in order to display valid options for validator images and mutator images.

What Autocompletion tool are you using? Is it OpenAPI-based?

**Comment by grmoon** [comment]
> > Autocompletion for Kptfile pipelines needs to be able to tell the difference between the two in order to display valid options for validator images and mutator images.
> 
> What Autocompletion tool are you using? Is it OpenAPI-based?

The autocompletion is a planned feature for the kpt integration with Cloud Code. It will be implemented using the [language server protocol](https://microsoft.github.io/language-server-protocol/) and will be based on JSON schemas. Since the list of functions in the catalog will change over time, it would be nice for us to be able to generate json schemas that specify the most up-to-date list of validators/mutators.

**Comment by mikebz** [comment]
I think another way to think about this is to provide some sort of a metadata that allows people to figure out if it's a validator or a mutator.  I am not sure if different repos is necessarily the way but to give people authoring assistance more metadata probably helps.

**Comment by grmoon** [comment]
> I think another way to think about this is to provide some sort of a metadata that allows people to figure out if it's a validator or a mutator. I am not sure if different repos is necessarily the way but to give people authoring assistance more metadata probably helps.

If there's an easy way to set and retrieve this metadata then this sounds good to me! I suggested the different repository because there didn't seem to be an easy way to add such metadata using gcr and the information returned by `gcloud container images list gcr.io/kpt-fn` is pretty sparse -- just the image name

**Comment by mikebz** [comment]
One of the things you can potentially do is grab the metadata from the git repo (which is the source of those functions.

If you take a look here: https://github.com/GoogleContainerTools/kpt-functions-catalog/blob/master/functions/go/search-replace/metadata.yaml

You will see the data that you need.  You can also get additional metadata like description.  That comes handy in the IDE context as well.
The GCR image is in that same metadata file.

So instead of interrogating the GCR you can start with examining the repo

**Comment by grmoon** [comment]
excellent, adding a field to that metadata works for me!

**Comment by grmoon** [comment]
closing this issue -- it looks like the resolution is to use tags in the metadata
