### ISSUE TITLE
UX of formatting performed by `fn render|eval`

### ISSUE THREAD

**Issue by mengqiy** [GoogleContainerTools/kpt#2104]
Formatting changes and real migration changes are mixed together. It's not easy for users to locate the real migration changes given the diff is pretty big.

We can try to split the formatting changes from the real migration changes. For example, we can do it in the following steps:
1. Format the resources
2. git commit the formatting changes
3. Run the `fix` function and inspect the real changes.

**Comment by frankfarzan** [comment]
I like to see a brief doc or discussion on the style of formatting being performed by kpt. See this thread: https://github.com/GoogleContainerTools/kpt-functions-sdk/pull/307#discussion_r638385436
