### ISSUE TITLE
`kpt fn render|eval` should enforce that `functionConfigs` be valid KRM with `metadata.name` field.

### ISSUE THREAD

**Issue by droot** [GoogleContainerTools/kpt#2105]
The task here is to enforce that `functionConfigs` referred in the `pipeline` or provided using `-fn-config` flag in `eval` needs to be valid KRM with `metadata.name`. We enforce that it should be a KRM, but we don't enforce `metadata.name`, we need to add that.

**Comment by natasha41575** [comment]
why do functionConfigs need `metadata.name`?

**Comment by Shell32-Natsu** [comment]
> why do functionConfigs need `metadata.name`?

I believe the field `metadata.name` is required for a valid k8s resource.
