### ISSUE TITLE
Fix update resource-merge with kustomize patches

### ISSUE THREAD

**Issue by pwittrock** [GoogleContainerTools/kpt#217]
- the 3-way merge updates Resources based on the GVKNNS
- kustomize packages may have patches and Resources with the same GVKNNS
- this will cause the following error: `Error: dest source already specified`

Possible Solution: disambiguate multiple resources with the same GVKNNS based on filename

**Comment by iuriaranda** [comment]
Is the kubernetes-sigs/kustomize#2175 PR integrated in kpt already?

Asking because I'm getting the `Error: dest source already specified` error as well. Not sure if it's caused by the same issue though.

**Comment by phanimarupaka** [comment]
@iuriaranda Can you provide the steps to reproduce with the resource files/repo you used to see this issue.

**Comment by bzub** [comment]
@phanimarupaka 

This reproduces the issue for me:
```sh
(
REPRO=$(mktemp -d)
cd $REPRO
git init
kpt pkg get https://github.com/bzub/manifests.git/consul@v0.0.1_1 consul
git add .
git commit -m "initial commit"
kpt pkg update consul@v0.0.1_2 --strategy resource-merge
)
```

**Comment by pwittrock** [comment]
Which version of kpt are you using `kpt version`.  There is a bug where teh `latest` link hasn't been updated.

**Comment by pwittrock** [comment]
I am able to reproduce on head.  Running with `--stack-trace` will show where the error is coming from.

**Comment by pwittrock** [comment]
path-based merging wasn't enabled for update.  See #508 for the fix.

**Comment by phanimarupaka** [comment]
@iuriaranda Merged phil's PR. It should be fixed at head. I tested it with your steps and it's working.

**Comment by iuriaranda** [comment]
yep, it now works. Thanks for the quick response!
