### ISSUE TITLE
`kpt fn` should print diagnostic output on `stderr` instead of `stdout`.

### ISSUE THREAD

**Issue by droot** [GoogleContainerTools/kpt#2178]
`kpt fn` commands can be composed together using Unix `pipe`. `kpt` suppresses the `fn` output when used in `pipe` to avoid rendering invalid content on `stdout` . This introduces inconsistency in `kpt fn` output in pipe/non-pipe mode and also introduces some complexity in the code in disabling/enabling the CLI output. Instead, simpler solution is to always write the `fn` output on `stderr`.

/cc @frankfarzan

**Comment by mortent** [comment]
Do we have any reference to prior art here? I'm not convinced printing everything to stderr is the right solution here. This issue seems very focused on `kpt fn` commands, but we need a solution here that makes sense for packaging and live as well.
