### ISSUE TITLE
Remove `nonIdempotent` option in test harness

### ISSUE THREAD

**Issue by frankfarzan** [GoogleContainerTools/kpt#2193]
All functions should be idempotent, providing this enables anti-patterns.

**Comment by Shell32-Natsu** [comment]
There are 2 test cases using `nonIdempotent` now:
1. `e2e/testdata/fn-render/fnresult-fn-success`
2. `e2e/testdata/fn-eval/structured-results-in-stdout`

They both use function `gcr.io/kpt-fn/search-replace` and the structured result of this function is not idempotent. We don't have other functions that can be used to test structured result in successful scenario now according to @mengqiy.

**Comment by mengqiy** [comment]
Tring to get https://github.com/GoogleContainerTools/kpt-functions-catalog/pull/309 merged, then we will have a function for that, though we may need to use `unstable` tag for a while.

**Comment by Shell32-Natsu** [comment]
@frankfarzan Are you ok with using `unstable` tag? Or we can wait for next release of that function?

**Comment by mengqiy** [comment]
@Shell32-Natsu Just found  that `apply-setters` can generate structured result while exit code is 0.
 I guess we can use it

**Comment by mengqiy** [comment]
Same for `create-setter`

**Comment by Shell32-Natsu** [comment]
> @Shell32-Natsu Just found that `apply-setters` can generate structured result while exit code is 0.
> I guess we can use it

Cool.

**Comment by frankfarzan** [comment]
Idempotency only applies to changes made to the filesystem. search-replace should be idempotent in that regard. You may want to relax what the test harness asserts.
