### ISSUE TITLE
SDK should provide a way to sort the structured results

### ISSUE THREAD

**Issue by mengqiy** [GoogleContainerTools/kpt#2195]
Both Golang and TS SDK should provide the same way to sort the structured results

Ref: https://github.com/GoogleContainerTools/kpt-functions-catalog/pull/309#discussion_r635427563

**Comment by morgante** [comment]
This code is now being continuously copied into multiple functions.

This SDK needs to be improved.

**Comment by mengqiy** [comment]
> This code is now being continuously copied into multiple functions.

If this is happening, we should prioritize it.
@sdowell Can you please help with this? We can do it in kyaml first and then TS SDK.

**Comment by mengqiy** [comment]
We have done something in the gatekeeper function: https://github.com/GoogleContainerTools/kpt-functions-catalog/pull/309/files#diff-1f6a622bc453fb37a0ae3331ea0243ef52cbea2d9bd4e2614b62fad97b87092bR188
We should upstream it to kyaml and then do something similar in https://github.com/GoogleContainerTools/kpt-functions-sdk

**Comment by morgante** [comment]
Agreed with prioritizing it in kyaml first, since Go is where it's currently being copied ([two examples](https://github.com/GoogleContainerTools/kpt-functions-catalog/search?q=sortResultItems) so far).

**Comment by sdowell** [comment]
This PR added support for sorting results via the Go SDK:
https://github.com/kubernetes-sigs/kustomize/pull/4325

**Comment by mengqiy** [comment]
TS SDK should provide similar sorting capability as kubernetes-sigs/kustomize#4325
