### ISSUE TITLE
Kpt fn render swallows stderr output when exit code is 0

### ISSUE THREAD

**Issue by mengqiy** [GoogleContainerTools/kpt#2200]
Current UX when exit code is 0:
Run `kpt fn render --results-dir=results`. There are no stderr in the console and no stderr in the structured results.

Proposed UX when exit code is 0:
Run `kpt fn render --results-dir=results`, there are no stderr in the console, but we should have stderr in the structured results.

Motivation:
Using stderr is a common way for debugging. (e.g. starlark).

Related code: https://github.com/GoogleContainerTools/kpt/blob/24e8929b1332b8185e6f439a6b4787c444305b76/internal/fnruntime/runner.go#L142-L147

**Comment by Shell32-Natsu** [comment]
cc @frankfarzan

**Comment by frankfarzan** [comment]
Structured results should be comprehensive (include stderr). This seems like a bug. Please add e2e tests for it.

**Comment by droot** [comment]
@Shell32-Natsu Can you pl. take it up.
