### ISSUE TITLE
Rev CRDs for v1 {Kptfile, FunctionResultList, ResourceGroup}

### ISSUE THREAD

**Issue by mikebz** [GoogleContainerTools/kpt#2203]
### Is your feature request related to a problem? Please describe.
Currently the next branch CRDs are alpha2, they need to be v1

**Comment by droot** [comment]
This change involves the following:

- [ ] Updating the schema in the types.go & all references in tests (unit and end to end)/code
- [ ] Updating examples in the `kpt` repo
- [ ] Updating reference docs and book
- [ ] Updating the code that handles unrecognized versions of `Kptfile`, for example, if one uses `kpt 1.0` and finds a package with `alpha2` or previous versions
- [ ] Updating examples/tests/docs in function catalog

@frankfarzan @mortent @phanimarupaka , am I missing anything on the list ?

**Comment by frankfarzan** [comment]
CRDs in scope here: Kptfile, FunctionResultList

**Comment by droot** [comment]
> CRDs in scope here: Kptfile, FunctionResultList

Good point, both are in scope. updated the list.

**Comment by frankfarzan** [comment]
Also note that ResourceList is also going v1, but that can be tracked differently as it lives in Kustomize repo.

**Comment by phanimarupaka** [comment]
I think 4 is already done.

**Comment by mortent** [comment]
We have added code to handle unrecognized versions of the `Kptfile` resource, but we should probably do the same thing for `FunctionResultList`? Or is it a type that is just used when running the Pipeline so it won't be affected by updating kpt?

**Comment by droot** [comment]
> We have added code to handle unrecognized versions of the `Kptfile` resource, but we should probably do the same thing for `FunctionResultList`? Or is it a type that is just used when running the Pipeline so it won't be affected by updating kpt?

It's a type that is produced as output during `render`. We never read it back, so I don't think we need to anything for `FunctionResultList` when it comes to handling unrecognized version.

**Comment by frankfarzan** [comment]
`ResourceGroup` should be added to the list.

**Comment by Shell32-Natsu** [comment]
> `ResourceGroup` should be added to the list.

Can you please remind me where do we use `ResourceGroup`?

**Comment by mortent** [comment]
I don't think we should update the ResourceGroup CRD now. It is used outside of kpt, so updating it has other implications we need to consider.

**Comment by Shell32-Natsu** [comment]
@frankfarzan How do you think about this?

> I don't think we should update the ResourceGroup CRD now. It is used outside of kpt, so updating it has other implications we need to consider.

**Comment by Shell32-Natsu** [comment]
This issue has been resolved by https://github.com/GoogleContainerTools/kpt-functions-catalog/pull/397 and #2248. For `ResourceGroup` we can open new issue for it if we want.

**Comment by frankfarzan** [comment]
Those PRs were reverted. Need to:
- Consider the migration doc and fix command
- Consider supporting v1alpha2
- Consider updating critical packages to v1
- Uprevving ResourceGroup by M4: https://github.com/GoogleContainerTools/kpt/issues/2277
