### ISSUE TITLE
nested package with the same name as namespace renders duplicate files

### ISSUE THREAD

**Issue by bzub** [GoogleContainerTools/kpt#2218]
### Expected behavior

Running `kpt fn render` with no pipelines should result in the same number of files with the same paths/names as before if a nested package has the same name as some of the resource's namespace.

For example: `parentpkg/nestedpkg/nestedpkg/deployment_nestedpkg.yaml` should be the only copy after running `kpt fn render parentpkg`.

### Actual behavior

It creates a copy of all resources in the `nestedpkg` namespacce in `parentpkg/nestedpkg`. For example it adds `parentpkg/nestedpkg/deployment_nestedpkg.yaml`.

### Information

kpt version: https://github.com/GoogleContainerTools/kpt/commit/081973bad400cf1cf40a5862676dd882e34ba941

### Steps to reproduce the behavior

```sh
(
set -e

tmpdir="$(mktemp -d)"
parentpkg="${tmpdir}/parentpkg"
nestedpkg="${parentpkg}/cert-manager"

mkdir -p "${nestedpkg}"
curl -sL "https://github.com/jetstack/cert-manager/releases/download/v1.4.0-beta.1/cert-manager.yaml" \
  | kpt fn sink "${nestedpkg}"

kpt pkg init "${parentpkg}"
kpt pkg init "${nestedpkg}"

pushd "${parentpkg}"
files_before_render="$(find .)"
kpt fn render "${parentpkg}"
files_after_render="$(find .)"
popd

diff <(echo "${files_before_render}") <(echo "${files_after_render}")
)
```

Output:
```
writing /var/folders/w4/c24yvdzn7qb7lfbn03mwnx8nhjh8lv/T/tmp.hmO8MQ6B/parentpkg/Kptfile
writing /var/folders/w4/c24yvdzn7qb7lfbn03mwnx8nhjh8lv/T/tmp.hmO8MQ6B/parentpkg/README.md
writing /var/folders/w4/c24yvdzn7qb7lfbn03mwnx8nhjh8lv/T/tmp.hmO8MQ6B/parentpkg/cert-manager/Kptfile
writing /var/folders/w4/c24yvdzn7qb7lfbn03mwnx8nhjh8lv/T/tmp.hmO8MQ6B/parentpkg/cert-manager/README.md
/var/folders/w4/c24yvdzn7qb7lfbn03mwnx8nhjh8lv/T/tmp.hmO8MQ6B/parentpkg ~/git/github/pkgs
Package "parentpkg/cert-manager":
Package "parentpkg":
Successfully executed 0 function(s) in 2 package(s).
7a8
> ./cert-manager/service_cert-manager-webhook.yaml
12a14,15
> ./cert-manager/deployment_cert-manager-webhook.yaml
> ./cert-manager/deployment_cert-manager.yaml
26a30,31
> ./cert-manager/role_cert-manager-webhook:dynamic-serving.yaml
> ./cert-manager/serviceaccount_cert-manager.yaml
30a36
> ./cert-manager/service_cert-manager.yaml
39a46
> ./cert-manager/deployment_cert-manager-cainjector.yaml
47a55
> ./cert-manager/serviceaccount_cert-manager-webhook.yaml
49a58,59
> ./cert-manager/serviceaccount_cert-manager-cainjector.yaml
> ./cert-manager/rolebinding_cert-manager-webhook:dynamic-serving.yaml
```

NOTE: If you change `nestedpkg="${parentpkg}/cert-manager"` to end in anything other than `cert-manager`, everything works as expected.

**Comment by droot** [comment]
Thanks @bzub for the detailed report. Appreciate the repro steps.

**Comment by droot** [comment]
I think I know what's happening here. While rendering resources from a sub package, we [adjust the relative path ](https://github.com/GoogleContainerTools/kpt/blob/main/internal/cmdrender/executor.go#L445) of the resource to be relative to the root package. The adjust-path function can be triggered multiple times on the same resource as we render from inward package to outward packages, so it has to be idempotent.
The check for making it idempotent is based on path prefix works for most cases but breaks in cases like this where path to the resource `cert-manager/deployment_cert-manager-cainjector.yaml` and subpackage's path relative to root `cert-manager` share prefix.

```
 if !strings.HasPrefix("cert-manager/deployment_cert-manager-cainjector.yaml", "cert-manager" +"/") {
     // we don't adjust the path of the resource here
 }
```

So renaming the subpackage `cert-manager` avoids this edge case.

I am investigating the right fix for this. One way to fix this would be to add a `control` notation that tracks the sub-package path, that will remove the need for adjustment of relative path.

/cc @frankfarzan @phanimarupaka I suspect we will have to introduce control notations sooner than later.

**Comment by droot** [comment]
@bzub The PR #2295 addresses this issue, will be available in next release. If you want it before that, you can try building kpt on latest HEAD on `main`. Thanks once again for reporting it!
