### ISSUE TITLE
CheckSite doesn't catch broken books link

### ISSUE THREAD

**Issue by frankfarzan** [GoogleContainerTools/kpt#2234]
Example: https://github.com/GoogleContainerTools/kpt/commit/e46f4dc2c32a657bd599eed06272556784aae278

**Comment by etefera** [comment]
Caused by autogenerated book titles on pages counting as content.
![image](https://user-images.githubusercontent.com/31711490/121936398-6dc02300-ccfe-11eb-90a1-84f7200dc164.png)
