### ISSUE TITLE
kpt fn eval --save

### ISSUE THREAD

**Issue by morgante** [GoogleContainerTools/kpt#2249]
We should add a `--save` flag to `kpt fn eval` which executes the function and saves it back to the Kptfile.

This would be helpful for two scenarios:
1. It provides an easy mechanism for preserving the semantic intent of running the function. By saving the function into the Kptfile, I can ensure it will continue to be applied on new resources which are added to the package later (either manually or via a package update).
2. It provides a simple way for higher level systems (ex. Blueprints Controller) to integrate with Kpt by injecting functions and potentially overriding default values.

In terms of implementation:
1. If the function is not already present in the Kptfile, it should be appended to the mutators.
2. If the function *is* already present in the Kptfile, the new invocation should have its config *merged* with the existing config.

The second point is particularly important for accommodating the ability to "overlay" setter values which were already set.

**Comment by mikebz** [comment]
@frankfarzan @droot @phanimarupaka

**Comment by bgrant0607** [comment]
This sounds useful.

**Comment by phanimarupaka** [comment]
Eval and render serve 2 different purposes.

Eval is meant to be used for non-repeatable one-time transformations in an imperative fashion.
Render is meant to be used for repetitive transformations and the functions are declared in the pipeline.

By design, eval is not the porcelain for render, but it serves a different purpose. If we introduce this flag, we are essentially making eval a porcelain for render which means

`kpt fn eval --image apply-setters:v0.1 --save -- foo=bar` = declare `apply-setters` in the pipeline + declare param `foo=bar` + `kpt fn render`

This can be done but it is beyond adding just a flag. We will be having only the declarative model.

If we compare with other tools, terraform also has 2 models similar to eval and render. 

Eval equivalent: If you want to apply a tf module with adhoc values once, you can use `terraform apply -var="image_id=ami-abc123"`. This value is not saved to tfvars making it a one time non-repetitive imperative transaction.
Render equivalent: Declare vars in tfvars file and run `terraform apply`

**Comment by morgante** [comment]
Hi @phanimarupaka, thanks for chiming in.

I don't agree that a hard distinction between "eval" and "render" serves our users well. We should focus on CUJs.

1. One CUJ is applying all functions which have previously been defined (often by the original package author). This is done via `kpt fn render`.
2. Another CUJ is adding an additional customization to a package which has not been predefined. `kpt fn eval` accommodates this CUJ.

A natural extension of CUJ2 is *saving* this customization so it can be automatically applied again in the future.

> If we compare with other tools, terraform also has 2 models similar to eval and render.
I don't think comparison is meaningful here. Terraform has no concept of sequential transforms.

**Comment by bgrant0607** [comment]
Right. We could create a separate Kptfile editing command for this, as discussed in https://github.com/GoogleContainerTools/kpt/issues/2284#issuecomment-867263570. However, I could easily imagine the user wanting to actually test the operation before adding it to the Kptfile, and having to manually translate the eval command to another syntax seems unnecessary.

**Comment by phanimarupaka** [comment]
Sounds good. I am fine with it. Should we make `--save` functionality a default behavior then ? This makes the model consistent with `kpt pkg update`

`kpt pkg update @v0.8` = Declare v0.8 in Kptfile + `kpt pkg update`
`kpt fn eval --image apply-setters:v0.1` -- foo=bar = declare apply-setters in the pipeline(if not present) + declare param foo=bar + `kpt fn render`

cc @frankfarzan @droot

**Comment by morgante** [comment]
I'm supportive of `--save` being the default (if a Kptfile is present).

**Comment by phanimarupaka** [comment]
> Sounds good. I am fine with it. Should we make `--save` functionality a default behavior then ? This makes the model consistent with `kpt pkg update`
> 
> `kpt pkg update @v0.8` = Declare v0.8 in Kptfile + `kpt pkg update`
> `kpt fn eval --image apply-setters:v0.1` -- foo=bar = declare apply-setters in the pipeline(if not present) + declare param foo=bar + `kpt fn render`
> 
> cc @frankfarzan @droot

And it was just my opinion. We need to come up with a design doc, weigh the pros and cons and discuss the feasibility. Then we can move forward if we get consensus.

**Comment by frankfarzan** [comment]
General note: we should start with focusing on the CUJs, and not go into the weeds with a specific solution, flag names, whether they're default, etc. This is reflected in [FR template].

One use case captured here is starting with imperative post-processors, and then once satisfied with the outcome, declaring it in the pipeline of the top-level package:

a) Run post-processor function imperatively:

```
$ kpt fn render
$ kpt fn eval -i post-processor
$ git diff # I like the results
```

b) Run post-processor function declarativel:

```
# Append function to the pipeline
$ kpt fn render
```

Currently b) can be done by manually editing the Kptfile or creating a [meta function]. We can provide porcelain in the kpt CLI.

Some caveats in this flow:
1. Imperative functions can be more privileged than declarative functions. Need to validate and show an appropriate error message if adding a [privileged functions] 
2. Need to specify whether it's a `mutator` or a `validator`


[FR Template]: https://github.com/GoogleContainerTools/kpt/issues/new?assignees=&labels=enhancement&template=feature_request.md&title=
[meta function]: https://kpt.dev/book/04-using-functions/02-imperative-function-execution?id=mutate-meta-resources
[privileged functions]: https://kpt.dev/book/04-using-functions/02-imperative-function-execution?id=privileged-execution

**Comment by bgrant0607** [comment]
+1 for CUJs. In this case, I think the CUJ is adding a function to the pipeline when or after testing it.

I don't think making it the default makes sense, and that would be a breaking change. There are other CUJs for imperative functions.

**Comment by morgante** [comment]
> Need to specify whether it's a mutator or a validator

Is this something we could track in the function metadata so it can be automatically placed correctly?

**Comment by frankfarzan** [comment]
> > Need to specify whether it's a mutator or a validator
> 
> Is this something we could track in the function metadata so it can be automatically placed correctly?

In general, no since it depends on a how a function is used. For example `starlark` can be used to validate or mutate. `search-and-replace` can only query or optionally replace. In specific cases, it is a static property of the function. For example, `kubeval` cannot mutate.

**Comment by morgante** [comment]
I can see how some general purpose functions might be ambiguous, but the vast majority of functions have a specific purpose in my experience.

I think it would be reasonable to default to mutators and put in validators only if the function is tagged as such.

**Comment by bgrant0607** [comment]
Has a separate issue been filed for function metadata? We should be using OCI annotations to record function metadata, to identify containers as krm functions, and so on.

Other attributes that would be useful to represent include:
* whether the function is expected to be idempotent / invariant-maintaining or not
* resource types the function operates on as input (need to support API groups and wildcards)
* new resource types generated, if any (need to support API groups and wildcards)

**Comment by droot** [comment]
> Has a separate issue been filed for function metadata? We should be using OCI annotations to record function metadata, to identify containers as krm functions, and so on.
> 
> Other attributes that would be useful to represent include:
> 
> * whether the function is expected to be idempotent / invariant-maintaining or not
> * resource types the function operates on as input (need to support API groups and wildcards)
> * new resource types generated, if any (need to support API groups and wildcards)

Filed #2334 to capture all function catalog related requirements.

**Comment by natasha41575** [comment]
@droot I think you meant to link to https://github.com/GoogleContainerTools/kpt/issues/2344

**Comment by droot** [comment]
> @droot I think you meant to link to #2344

Thanks, updated it :)

**Comment by yuwenma** [comment]
should be there in next release
