### ISSUE TITLE
Support auto-generating function pipelines for different workflow orchestrators

### ISSUE THREAD

**Issue by frankfarzan** [GoogleContainerTools/kpt#226]
e.g.:

`kpt fn export [cloud-build,jenkins-pipeline,github-actions]`

This would generate e.g. Cloud Build configuration for running a pipeline of kpt functions.

There are various design options we should explore:

1. Each workflow step runs the function wrapped with a utility that wires functions input/output in a shared volume
2. Each workflow step runs the function directly using unique input/output files in a shared volume. As an example see:
https://github.com/GoogleCloudPlatform/csp-config-management/blob/1.0.0/ci-pipeline-unstructured/cloudbuild.yaml
3. A single workflow step that runs the entire kpt functions pipeline. This would lose some UX benefit of separate reporting/notifications in the workflow UI, but maybe acceptable if the workflow orchestrator is an implementation detail. For example, if everything is bubbled up into the GitHub UI instead of user going to Jenkins or Cloud Build. A technical challenge: Running docker-in-docker is not supported by all orchestrators.

A general issue is that workflow orchestrators do not typically support stdin/stdout, and the configuration function spec doesn't enforce a consistent flag name for input/output.

**Comment by frankfarzan** [comment]
4. Mandate flags and/or env vars to [functions spec](https://github.com/kubernetes-sigs/kustomize/blob/master/cmd/config/docs/api-conventions/functions-spec.md):

-i, --input
-o, --output

Downside is that existing tools (e.g. kubectl, helm, kustomize) need to be wrapped.

**Comment by prachirp** [comment]
@Liujingfang1 is this done?

**Comment by Liujingfang1** [comment]
@prachirp Yes, this is done. The document is available https://googlecontainertools.github.io/kpt/guides/consumer/function/export/
