### ISSUE TITLE
HomeBrew installs old version

### ISSUE THREAD

**Issue by eikemeier** [GoogleContainerTools/kpt#2262]
### Expected behavior

[Homebrew installation](https://googlecontainertools.github.io/kpt/installation/homebrew/) should install v0.39.3 (#2213)

### Actual behavior

HomeBrew installs version v0.36.1

### Information

The `master` brach has been renamed to `v0`: [`v0` Formula](https://github.com/GoogleContainerTools/kpt/blob/v0/Formula/kpt.rb)

The current `main` branch has an old version: [`main` Formula](https://github.com/GoogleContainerTools/kpt/blob/main/Formula/kpt.rb)

### Steps to reproduce the behavior

Follow the steps in [the documentation](https://googlecontainertools.github.io/kpt/installation/homebrew/).

**Comment by mikebz** [comment]
Hi @eikemeier we are working on updating homebrew #1842 , but we are updating it to the v1 branch.  We'd love to get your feedback on the next version.  There is a migration involved so keep that in mind.  If you want to get an intro it might be worth while do go through the "Book"
https://kpt.dev/book/

**Comment by eikemeier** [comment]
> Hi @eikemeier we are working on updating homebrew #1842 , but we are updating it to the v1 branch. We'd love to get your feedback on the next version. There is a migration involved so keep that in mind.

I'm excited to see the new version and am aware of the migration requirements.

In the meantime, while 1.0 is not ready - how about simply keeping the status quo with v0.39.3 instead of downgrading to  v0.36.1?

**Comment by eikemeier** [comment]
@mikebz I think the `p1` label is a mistake. You're breaking the **current** installed base. Otherwise you should fix the documentation at https://googlecontainertools.github.io/kpt/installation/homebrew/ and tell people that installation with HomeBrew is no longer working and they should wait for 1.0.

**Comment by mikebz** [comment]
The fix is absolutely in order.  I just use any touch points with our customers as a way to see if folks will check out the new version.  PR is waiting approval.

**Comment by eikemeier** [comment]
@mikebz ♥

**Comment by mikebz** [comment]
The PR will get merged in the next little bit, but I want to give you a heads up that the update to kpt is imminent and it does require you to migrate your current config.  If it poses any problems to your solution we'd love to know early.
