### ISSUE TITLE
[Question] kpt fmt for v1

### ISSUE THREAD

**Issue by bharathkkb** [GoogleContainerTools/kpt#2274]
Is there a replacement for `kpt cfg fmt` in v1? I could not find any looking through the docs. This would be useful for maintaining a standard formatting for configs rather than making our own. 

https://googlecontainertools.github.io/kpt/reference/cfg/fmt/

**Comment by phanimarupaka** [comment]
Hey. Did you go through this section in the doc.

https://kpt.dev/installation/migration?id=cli-changes

**Comment by bharathkkb** [comment]
Thanks I did not see the guide linked anywhere in https://kpt.dev/reference/cli/
