### ISSUE TITLE
Publish metadata about all functions in single doc in kpt functions catalog

### ISSUE THREAD

**Issue by phanimarupaka** [GoogleContainerTools/kpt#2276]
Here is the desired format 

For each minor-version
1. Fn name
2. Short description
3. mutator/validator tag
4. Explicit link to documentation

**Comment by phanimarupaka** [comment]
cc @mengqiy

**Comment by bgrant0607** [comment]
It seems like the source of this information should be container image metadata.

**Comment by bgrant0607** [comment]
https://github.com/opencontainers/image-spec/blob/master/annotations.md

**Comment by marshall007** [comment]
@phanimarupaka for convenience can we also get a link to the source code for where each function is implemented? It was not immediately obvious to me that all the new kpt functions were implemented in the "old" repo:

https://github.com/GoogleContainerTools/kpt-functions-catalog/tree/apply-setters/v0.1/functions/go/apply-setters

I was only able to find one reference to the `kpt-functions-catalog` repo in the v1 docs, buried at the bottom of this page:

https://kpt.dev/book/05-developing-functions/02-developing-in-Go

**Comment by phanimarupaka** [comment]
Here is the metadata of all functions which is maintained up to date https://catalog.kpt.dev/catalog.json
