### ISSUE TITLE
Allow `kpt fn source` to take multiple dirs

### ISSUE THREAD

**Issue by viglesiasce** [GoogleContainerTools/kpt#228]
ATM `kpt fn source` cannot be used to concatenate and format resources into a list. The use case for this is when you have something like OPA constraints in one repo/folder and the actual manifests in the other. 

Currently you need to do copy the files into a single folder but it would be simpler to run:
`kpt source fn constraints/ manifests`

That would generate  single resources list that could be used in functions like  gatekeeper-validate.

**Comment by frankfarzan** [comment]
I think this is a reasonable FR, but what do you see as downsides of doing this (I think what you mean by 'copy into a single folder'?)

```
kpt pkg get source1 dir1
kpt pkg get source2 dir2
kpt fn source .
```

**Comment by pwittrock** [comment]
Done
