### ISSUE TITLE
The "Customize the package" section talks about "different approaches" but doesnt separate them clearly

### ISSUE THREAD

**Issue by viglesiasce** [GoogleContainerTools/kpt#2287]
### Expected behavior

When reading this page:
https://kpt.dev/book/01-getting-started/02-quickstart?id=customize-the-package

I read that "you can use different approaches depending on your use case." It seems the first is to edit the files directly which doesnt seem different than cloning a repo of YAML and doing the same thing. Maybe we could say more here about the value Kpt provides in addition to that. Also separating this "approach" under another sub-heading could help users differentiate the approaches.

**Comment by karlkfi** [comment]
Part of the issue is how it's being explained, but part of it is also that the new kpt v1 way of modifying config files is more verbose and less intuitive than the old `kpt cfg set key value` method.

**Comment by viglesiasce** [comment]
Also the use of "automatically mutate" here seems like its doing a lot of work. What does that even mean?

**Comment by viglesiasce** [comment]
I think we need a quick blurb on what functions do... Namely yaml->function (does things to yaml) -> yaml. That would help ratify the idea of "automatically mutate"
