### ISSUE TITLE
set user-agent to kpt + http headers

### ISSUE THREAD

**Issue by pwittrock** [GoogleContainerTools/kpt#229]
set the user agent for requests to `kpt`

**Comment by monopole** [comment]
strictly only the string "kpt" plus the version.
No full path to the kpt binary (could include PII).

**Comment by seans3** [comment]
Also, as extra "X-Header"s, we can add the `kpt` subcommand WITHOUT parameters/args (e.g. `kpt live apply`, `kpt pkg`) to get information on which subcommands are being used.
