### ISSUE TITLE
Docs: 1.2 Quickstart : live apply dry-run should acknowledge CRD warning

### ISSUE THREAD

**Issue by linde** [GoogleContainerTools/kpt#2290]
when i ran the `kpt live apply --dry-run` command on a pristine kind cluster, it warned me with the following:

```bash
stevenlinde@stevenlinde:~/.../kpt-book/nginx$ kpt live apply --dry-run
Error: The ResourceGroup CRD was not found in the cluster. Please install it either by using the '--install-resource-group' flag or the 'kpt live install-resource-group' command. 
```

this is reasonable, but it is worthwhile to explain to the reader that this is expected on an empty cluster and share why.

**Comment by frankfarzan** [comment]
This was fixed in https://github.com/GoogleContainerTools/kpt/pull/2289
