### ISSUE TITLE
`render` deletes comments from Kptfile

### ISSUE THREAD

**Issue by droot** [GoogleContainerTools/kpt#2301]
### Expected behavior

When I run `kpt fn render` on a package, comments in the `Kptfile` should not be dropped.

### Actual behavior

`render` drops comments from `Kptfile`

Refer to https://github.com/GoogleContainerTools/kpt/pull/2295#discussion_r655395904 for an example.

**Comment by phanimarupaka** [comment]
This is no longer true as we don't format Kptfile anymore. This is fixed.
