### ISSUE TITLE
keep comments from `kpt fn run`, even if they are dropped by the function

### ISSUE THREAD

**Issue by pwittrock** [GoogleContainerTools/kpt#231]
Most functions will drop comments when performing serialization.  We should keep the comments when possible by re-applying them

Use `kyaml/comments` lib in `kyaml/kio/filters/container.go`  to restore comments.  Similar to what is done by `kyaml/starlark` to restore comments.

- Add a temporary id to each input resource before feeding them to the container
- After running the container, match input and output resources by their ID
- Use the comments lib to copy input resource comments to output resource comments
- Support disabling with a boolean field

**Comment by pwittrock** [comment]
Use `kyaml/comments` lib in `kyaml/kio/filters/container.go`  to restore comments.  Similar to what is done by `kyaml/starlark` to restore comments.

- Add a temporary id to each input resource before feeding them to the container
- After running the container, match input and output resources by their ID
- Use the comments lib to copy input resource comments to output resource comments
- Support disabling with a boolean field

**Comment by frankfarzan** [comment]
Not that this is a must have now that setter mechanism use annotations.

**Comment by seh** [comment]
This may be related to #629.

**Comment by pwittrock** [comment]
Fixed on HEAD.

I think this is unrelated to #629
