### ISSUE TITLE
Functions Catalog rendering issues

### ISSUE THREAD

**Issue by frankfarzan** [GoogleContainerTools/kpt#2320]
Some rendering issues:

- [x] Version drop down. `0.1` -> `v0.1`. They're not equivalent.
- [x] Do you actually want to show the other container tags. e.g. `v0` or `v0.1.1`? Specially for the latter, the only way to get that is by pulling the image, and not through the docs.
- [x] We don't show the full function image name anywhere (`gcr.io/kpt-fn`)

**Comment by mengqiy** [comment]
Ref: #2609

**Comment by mengqiy** [comment]
@sdowell there is one last thing in the list.
