### ISSUE TITLE
kpt can't reference images by sha

### ISSUE THREAD

**Issue by martinmaly** [GoogleContainerTools/kpt#2322]
### Expected behavior

It would be wonderful if kpt could understand image references via SHA

gcr.io/yakima-eap/generate-folders@sha256:3434a5299f8fcb2c2ade9975e56ca5a622427b9d5a9a971640765e830fb90a0e

### Actual behavior

```
kpt1 fn render .
Kptfile is invalid:
Field: `pipeline.mutators[0].image`
Value: "gcr.io/yakima-eap/generate-folders@sha256:3434a5299f8fcb2c2ade9975e56ca5a622427b9d5a9a971640765e830fb90a0e"
Reason: function name "gcr.io/yakima-eap/generate-folders@sha256:3434a5299f8fcb2c2ade9975e56ca5a622427b9d5a9a971640765e830fb90a0e" is invalid
```

Kptfile:
```
apiVersion: kpt.dev/v1alpha2
kind: Kptfile
metadata:
  name: simple-hierarchy
info:
  description: Resource hierarchy blueprint for GCP
pipeline:
  mutators:
    - image: gcr.io/yakima-eap/generate-folders@sha256:3434a5299f8fcb2c2ade9975e56ca5a622427b9d5a9a971640765e830fb90a0e
```

Strangely, with kpt fn eval --image XYZ it seems possible to reference image via sha:

```
docker run gcr.io/yakima-eap/generate-folders@sha256:3434a5299f8fcb2c2ade9975e56ca5a622427b9d5a9a971640765e830fb90a0e
apiVersion: v1
kind: ResourceList
metadata:
  name: output
items: []
```

### Information

 % kpt version
1.0.0-alpha.10

### Steps to reproduce the behavior

**Comment by droot** [comment]
Thanks for submitting this. 

@natasha41575 

1. We should relax the validation function for the function image to support this use-case. I think we have taken the validation too far :)
2. Also, it will be good to make the validation consistent across `fn eval` and `fn render`.

**Comment by bzub** [comment]
https://github.com/GoogleContainerTools/kpt/issues/2020
