### ISSUE TITLE
Add a simpler example for gatekeeper

### ISSUE THREAD

**Issue by mengqiy** [GoogleContainerTools/kpt#2328]
We heard feedback from @viglesiasce:
The existing example for gatekeeper function is a little complex for newcomers of gatekeeper function.
We should add a simpler example. Vic has provided an candidate: https://github.com/viglesiasce/sample-app/commit/c8599eaaf904c862aaa0d942b718364ea4465160#diff-0cfd4dce36abb7416498d14a8fd48d5b3b750aab4473496aa62d095ecb3748f0

**Comment by mengqiy** [comment]
Fixed in https://github.com/GoogleContainerTools/kpt-functions-catalog/pull/445

**Comment by viglesiasce** [comment]
Thanks Mengqi! This example is perfect.
