### ISSUE TITLE
kpt returns an error if downloaded package is not a subfolder in git repo

### ISSUE THREAD

**Issue by mortent** [GoogleContainerTools/kpt#234]
I have a kpt package at https://github.com/mortent/kpt-test. I can fetch this package with
```
kpt pkg get git@github.com:mortent/kpt-test.git/nginx@v0.1.0 nginx
```
I then make the nginx directory into a git repo:
```
cd nginx
git init
git add . && git commit -m "nginx package"
```
If I try to update the package to v0.2.0, which only adds additional files to the package, I get an error `Error: RemoveAll .: invalid argument`

If I make the nginx folder a subdirectory of the git repo, everything works well. We might want to make this clear.

**Comment by pwittrock** [comment]
this is the intended behavior.  should improve the docs to make this more clear.
