### ISSUE TITLE
Kpt migration guide friction

### ISSUE THREAD

**Issue by selfmanagingresource** [GoogleContainerTools/kpt#2340]
1) Which version of kpt is v1 is confusing  as I'm going through the guide - as a user I have to alias kpt-old/kptv1 in my own way. It'd be great if the guide required clear aliasing or allowed the user to specify their alias for kpt so they copy/paste shell commands work.

2) PKG_PATH should be $PKG_PATH (should also have an export step)

**Comment by frankfarzan** [comment]
Related to this: the migration guide should also show `kpt version` explicitly to have the user check the version. Otherwise, it can be confusing.
