### ISSUE TITLE
Document multi-function execution ordering

### ISSUE THREAD

**Issue by frankfarzan** [GoogleContainerTools/kpt#235]
Currently, the behavior of declaring multiple functions is underspecified:

https://github.com/GoogleContainerTools/kpt/blob/master/docs/fn/run.md

What happens if there are multiple function config files? What's the ordering? Or are they run in parallel instead of serialY/

**Comment by bgrant0607** [comment]
I like the idea of distinguishing generators, transformers, and validators. Admission webhooks distinguish between mutating and validating webhooks, and kustomize distinguishes generators and transformers: https://github.com/kubernetes-sigs/kustomize/tree/master/docs/plugins

That would enable some ordering to be inferred (and/or to sanity-check explicit ordering), and also would make it easier to run just the validations in some situations.

Ordering also seems necessary for pipeline generation: #226

**Comment by droot** [comment]
This will be addressed with kpt pipeline implementation.
