### ISSUE TITLE
Add annotations to subset of resources or specific resources using kpt v1

### ISSUE THREAD

**Issue by halvards** [GoogleContainerTools/kpt#2364]
### Describe your problem

I'd like to use kpt v1 to add an annotation to a specific resource, or a subset of resources. This was possible in kpt v0.

The motivating example is the [GKE Workload Identity](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity) annotation  [`iam.gke.io/gcp-service-account=[GSA_NAME]@[PROJECT_ID].iam.gserviceaccount.com`](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity#authenticating_to) on Kubernetes service accounts. This annotation informs GKE that the Kubernetes service account should impersonate the Google service account to access Google APIs.

Typically, I want to bind different Kubernetes service accounts to different Google service accounts, so I can't add the same annotation to all ServiceAccount resources. And the annotation isn't relevant for non-ServiceAccount resources. The [set-annotations](https://catalog.kpt.dev/set-annotations/v0.1/) function adds annotations to all resources, so it doesn't match what I need.

In kpt v0, this could be accomplished imperatively in two ways:

1. Using `kpt cfg annotate` with filters on kind, name, namespace, and/or apiVersion. `cfg annotate` isn't available in kpt v1.

2. Using `kpt fn source` with a file name or pattern, such as `manifests/service-account.yaml` or `manifests/service-account-*.yaml`. With kpt v1, `fn source` can only take a directory name.

With kpt v1, the only workaround I can find is to place the one resource I want to annotate in its own kpt sub-package, and use `kpt fn source manifests/directory-containing-only-the-service-account-to-annotate`. However, this complicates the package layout unnecessarily.

For now, I'm using kustomize to do achieve this:

```sh
kustomize cfg annotate [directory or file pattern] \
    --kind ServiceAccount \
    --name [resource name] \
    --namespace [resource namespace] \
    --kv "iam.gke.io/gcp-service-account=$GSA"
```

Using a setter or the `search-replace` function could be another approach. However:

1. There is no sensible default value of the workload identity annotation.

2. This annotation is only relevant to GKE users, so someone who develops for general K8s use would likely not want to 'hardcode' the GKE workload identity annotation (with a dummy default value) in their resources.

**Suggestion:** Add support for filtering resources by kind, name, namespace, and apiVersion to the set-annotations function, allowing for both imperative and declarative usage.

This type of filtering may also be relevant to other functions, but I haven't come across clear use cases yet.

**Comment by morgante** [comment]
https://github.com/GoogleContainerTools/kpt/issues/2315 is related.

**Comment by halvards** [comment]
#2015 also.

**Comment by phanimarupaka** [comment]
@halvards As an immediate workaround, you can use `search-replace` function with `by-file-path` filter. This is not as granular as GVKNN filter but you can filter particular files. You can organize the resources in files accordingly. So the query becomes

```
kpt fn eval -i gcr.io/kpt-fn/search-replace:v0.1 -- by-file-path a/b.yaml --by-path metadata.annotations.anno-key=anno-value
```

--by-file-path filter is WIP and will be released in a couple of days. https://github.com/GoogleContainerTools/kpt-functions-catalog/pull/459

@mengqiy Can help you with adding filters to `set-annotations` function. This is the right way to do it.

**Comment by halvards** [comment]
Thanks for your reply @phanimarupaka!

`search-replace` isn't ideal here, because the annotation doesn't exist on the base (dry) resource, so I need to add the annotation, not just replace the value.

A GVKNN (what an acronym!) filter for `set-annotations` would be great!

**Comment by phanimarupaka** [comment]
@halvards That query adds new annotation if it doesn't exist.

**Comment by halvards** [comment]
@phani TIL. Thanks!

**Comment by droot** [comment]
I think applying a function selectively on resources seems to be generally useful across functions, so we will explore making filtering part of the `kpt fn eval` CLI.

**Comment by bgrant0607** [comment]
I would like to see filtering be part of the orchestrator rather than having to be implemented in individual functions.

**Comment by droot** [comment]
> I would like to see filtering be part of the orchestrator rather than having to be implemented in individual functions.

Agreed. We have seen quite a few requests related to filtering (not a surprise), so will be prioritizing this.

**Comment by droot** [comment]
@halvards we are prioritizing support for filtering and will begin work on it soon. I will be closing this issue, since we are tracking the work under the feature issue https://github.com/GoogleContainerTools/kpt/issues/2015.

**Comment by phanimarupaka** [comment]
@halvards You can use search-replace with `by-file-path` matcher as a workaround for now. https://catalog.kpt.dev/search-replace/v0.2/?id=file-path-patterns
