### ISSUE TITLE
kpt tutorial encounters error

### ISSUE THREAD

**Issue by trodge** [GoogleContainerTools/kpt#238]
Currently the tutorial errors out at the following step:
```
$ # kpt works just as well with kustomize as raw config
$ kpt pkg get git@github.com:GoogleContainerTools/kpt.git/package-examples/helloworld-kustomize helloworld-kustomize
fetching package /package-examples/helloworld-kustomize from git@github.com:GoogleContainerTools/kpt to helloworld-kustomize
/Users/pwittroc/Projects/kpt/docs/gifs/kpt.sh: line 69: unexpected EOF while looking for matching `"'
/Users/pwittroc/Projects/kpt/docs/gifs/kpt.sh: line 70: syntax error: unexpected end of file
```
This may be related to [this issue](https://github.com/GoogleContainerTools/kpt/issues/237).

**Comment by pwittrock** [comment]
hm, I'm not able to reproduce:

```sh
$ kpt pkg get git@github.com:GoogleContainerTools/kpt.git/package-examples/helloworld-kustomize k
fetching package /package-examples/helloworld-kustomize from git@github.com:GoogleContainerTools/kpt to k
$ tree k
k
├── Kptfile
├── kustomization.yaml
├── patches
│   └── patch.yaml
└── resources
    ├── deploy.yaml
    └── service.yaml

2 directories, 5 files
```

**Comment by pwittrock** [comment]
@trodge what do you get when you run `kpt version` ?

**Comment by trodge** [comment]
```
thomasrodgers@thomasrodgers2:~$ kpt version
Error: unknown command "version" for "kpt"
Run 'kpt --help' for usage.

```

**Comment by selmanj** [comment]
Just ran into the same issue. I'm running 0.5.0.

```
$ # kpt works just as well with kustomize as raw config
$ kpt pkg get git@github.com:GoogleContainerTools/kpt.git/package-examples/helloworld-kustomize helloworld-kustomize
fetching package /package-examples/helloworld-kustomize from git@github.com:GoogleContainerTools/kpt to helloworld-kustomize
/Users/pwittroc/Projects/kpt/docs/gifs/kpt.sh: line 69: unexpected EOF while looking for matching `"'
/Users/pwittroc/Projects/kpt/docs/gifs/kpt.sh: line 70: syntax error: unexpected end of file
jsselman-imacpro:~ $ kpt version
0.5.0
jsselman-imacpro:~ $ 
```

I installed kpt via homebrew.

**Comment by selmanj** [comment]
Note that the command and output listed above are displayed in the tutorial and not commands that I actually ran.

**Comment by trodge** [comment]
New kpt version, new issue:

```
$ # kpt works just as well with kustomize as raw config
$ kpt pkg get git@github.com:GoogleContainerTools/kpt.git/package-examples/helloworld-kustomize helloworld-kustomize
fetching package /package-examples/helloworld-kustomize from git@github.com:GoogleContainerTools/kpt to helloworld-kustomize
/Users/pwittroc/Projects/kpt/docs/gifs/kpt.sh: line 69: unexpected EOF while looking for matching `"'
/Users/pwittroc/Projects/kpt/docs/gifs/kpt.sh: line 70: syntax error: unexpected end of file
thomasrodgers@thomasrodgers2:~$ kpt version
v0.8.0
thomasrodgers@thomasrodgers2:~$ 
```

**Comment by pwittrock** [comment]
Would you try:

```
kpt pkg get https://github.com/GoogleContainerTools/kpt.git/package-examples/helloworld-kustomize helloworld-kustomize
```

**Comment by pwittrock** [comment]
@phanimarupaka would you take a look and see if you can reproduce?  Seems like we need to provide a better error message once we discover the root cause.

Also would you update the tutorial with the correct address.

**Comment by phanimarupaka** [comment]
@pwittrock Works fine for me.

pmarupaka-macbookpro:~ pmarupaka$ kpt version
0.8.0
pmarupaka-macbookpro:~ pmarupaka$ kpt pkg get https://github.com/GoogleContainerTools/kpt.git/package-examples/helloworld-kustomize helloworld-kustomize
fetching package /package-examples/helloworld-kustomize from https://github.com/GoogleContainerTools/kpt to helloworld-kustomize
pmarupaka-macbookpro:~ pmarupaka$ ls helloworld-kustomize/
Kptfile			README.md		kustomization.yaml	patches			resources

**Comment by phanimarupaka** [comment]
@pwittrock I am also not able to reproduce either. 

@trodge Are you on linux?

![image](https://user-images.githubusercontent.com/58999035/75933233-4bb6d000-5e2e-11ea-859c-d1d89bf6c041.png)

**Comment by trodge** [comment]
Yes, I am on gLinux.
```
thomasrodgers@thomasrodgers2:~$ kpt pkg get https://github.com/GoogleContainerTools/kpt.git/package-examples/helloworld-kustomize helloworld-kustomize
fetching package /package-examples/helloworld-kustomize from https://github.com/GoogleContainerTools/kpt to helloworld-kustomize
thomasrodgers@thomasrodgers2:~$ uname -r
5.2.17-1rodete3-amd64
thomasrodgers@thomasrodgers2:~$ 
```

**Comment by pwittrock** [comment]
the https seems to look.  i am guessing this is an issue with the git auth, and the error just isn't shown.  what happens when you do 

```
git clone git@github.com:GoogleContainerTools/kpt.git/ && cd kpt/package-examples/helloworld-kustomize
```

I am guessing you will get some error

@phanimarupaka I think we should probably catch any error in the `kpt get` command and tell the user to run `git clone REPO && cd DIR` so they can debug the issue.

**Comment by phanimarupaka** [comment]
@pwittrock @trodge I am sure this issue is related to linux and can't be reproduced on mac. I will try to reproduce on linux to find the root cause.

**Comment by phanimarupaka** [comment]
@trodge Never mind. I was not able to reproduce it on Linux either. I think it is git auth issue as pwittrock mentioned.
