### ISSUE TITLE
search-replace: allow specifying a resource to modify

### ISSUE THREAD

**Issue by karlkfi** [GoogleContainerTools/kpt#2384]
I want to be able to modify a field in a specific resource or set of similar resources.

One way to do this would be to modify the search-replace function to support additional fields:

Example 1
```
$ kpt fn eval --image gcr.io/kpt-fn/search-replace:v0.1 -- \
    by-kind=IAMPolicyMember \
    by-name=kcc-project-id-owners-permissions \
    by-namespace projects \
    by-path=spec.resourceRef.external \
    put-value=project-id
```

Example 2
```
$ kpt fn eval --image gcr.io/kpt-fn/search-replace:v0.1 -- \
    field-selector=kind=IAMPolicyMember \
    field-selector=metadata.name=kcc-project-id-owners-permissions \
    field-selector=metadata.namespace=projects \
    by-path=spec.resourceRef.external \
    put-value=project-id
```

In these examples, I would be wanting to replace a name/namespace resourceRef with an external resourceRef, which would require running the single-field update function 3x: once to add and twice to remove (set to null).

Another option would be to accept json fragments to allow doing it all in one command:
```
$ kpt fn eval --image gcr.io/kpt-fn/search-replace:v0.1 -- \
    field-selector=kind=IAMPolicyMember \
    field-selector=metadata.name=kcc-project-id-owners-permissions \
    field-selector=metadata.namespace=projects \
    by-path=spec.resourceRef \
    put-value-json={ "resourceRef": { "apiVersion": "resourcemanager.cnrm.cloud.google.com/v1beta1", "kind": "Project", "external": "project-id" }
```

One limitation with taking json is that it doesn't support inline comments tho, so you couldn't use that to add an inline setter comment. For that, you'd probably need to accept yaml fragments on STDIN:
```
$ kpt fn eval --image gcr.io/kpt-fn/search-replace:v0.1 -- \
    field-selector=kind=IAMPolicyMember \
    field-selector=metadata.name=kcc-project-id-owners-permissions \
    field-selector=metadata.namespace=projects \
    by-path=spec.resourceRef \
    put-value-yaml=- << 'EOF'
apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
kind: Project
external: project-id # kpt-set: ${project-id}
EOF
```

**Comment by morgante** [comment]
Opened #2387 to track this as a general request.

**Comment by mikebz** [comment]
@mengqiy heads up

**Comment by droot** [comment]
@karlkfi we are starting work on this one and will be tracking the filtering work in this issue https://github.com/GoogleContainerTools/kpt/issues/2015.

**Comment by droot** [comment]
so closing issue since it will be addressed as part https://github.com/GoogleContainerTools/kpt/issues/2015
