### ISSUE TITLE
Function filtering

### ISSUE THREAD

**Issue by morgante** [GoogleContainerTools/kpt#2387]
In many cases, it is desirable to apply a function to only a subset of resources in a package. Instead of trying to do this on a per-function basis, `kpt` should provide a generic method to filter which resources a function applies to.

Some examples of concrete requests for this:
1. #2356 - file-path matching
2. #2384 - filter by specific resource name+namespace
3. #2364 - filter by GVK
4. [v0.39 example](https://github.com/GoogleCloudPlatform/blueprints/blob/main/utils/add-attribution.sh#L21) of applying an annotation to resources by apiVersion
5. #2315 - filter by annotation

**Comment by frankfarzan** [comment]
There's a tracking issue for this feature: https://github.com/GoogleContainerTools/kpt/issues/2015
