### ISSUE TITLE
Evaluating starlark function leads to deleting function configuration

### ISSUE THREAD

**Issue by morgante** [GoogleContainerTools/kpt#2389]
### Expected behavior
When I `eval` a function, it should only run that function. It should not *delete* my function configuration.

### Actual behavior
When I eval a Starlark function, it *deletes* any function config objects within the package.

### Information
kpt 1.0

### Steps to reproduce the behavior
1. Create a `StarlarkRun` config file. For example, `filter-local.yaml`:
```
apiVersion: fn.kpt.dev/v1alpha1
kind: StarlarkRun
metadata:
  name: filter-local
source: |
  def conditionallySetAnnotation(resources):
    for resource in resources:
      if "config.kubernetes.io/local-config" in resource["metadata"]["annotations"] and (resource["metadata"]["annotations"]["config.kubernetes.io/local-config"] == True or resource["metadata"]["annotations"]["config.kubernetes.io/local-config"] == "true"):
        resource["metadata"]["annotations"]["configmanagement.gke.io/managed"] = "disabled"
  conditionallySetAnnotation(ctx.resource_list["items"])
```
2. Evaluate the starlark function:
```
kpt fn eval --image gcr.io/kpt-fn/starlark:v0.1 --fn-config filter-local.yaml
```
3. Observe that `filter-local.yaml` has been deleted from disk for some reason.

**Comment by droot** [comment]
Taking a look at it now.

**Comment by droot** [comment]
@morgante We found out that starlark function is dropping the functionConfig (`filter-local.yaml` in this case) from the function `output.items` and that is causing it to be deleted from the filesystem.

@mengqiy would be addressing this behavior in the newer release of starlark function. If you are blocked, you can add `filter-local.yaml` to `.krmignore` file to avoid it from being deletion.

Some more background info (somewhat related to this):
If this config was referenced as functionConfig in the pipeline, kpt would automatically exclude it from the input list (treating it as a meta resource), but in this case, it seems that it is not referenced as functionConfig in the pipeline and causing this behavior.

**Comment by mengqiy** [comment]
@droot An interesting behavior I found is that if we rename `filter-local.yaml` to `fn-config.yaml` and then run
```
kpt fn eval --image gcr.io/kpt-fn/starlark:v0.1 --fn-config fn-config.yaml
```
You will not see this issue.

It seems `kpt fn eval` does something special when the file name is `fn-config.yaml`.
