### ISSUE TITLE
kpt prematurely creates directory when running `kpt pkg get`

### ISSUE THREAD

**Issue by morgante** [GoogleContainerTools/kpt#2391]
### Expected behavior
If I run `kpt pkg get` with incorrect arguments leading to an error, it has no side effects.

### Actual behavior
If I run `kpt pkg get` with an incorrect package URL, it creates the destination directory anyways before failing. Then future gets are blocked.

This causes friction when making typos.

### Information
kpt v1

### Steps to reproduce the behavior
1. Get package with incorrect URL
```
kpt pkg get https://github.com/GoogleCloudPlatform/blueprints.get/catalog/bucket@kpt-v1
```
Error:
Package "bucket":
Fetching https://github.com/GoogleCloudPlatform/blueprints.get@kpt-v1
Error: Repository "https://github.com/GoogleCloudPlatform/blueprints.get" not found.

Details:
remote: Repository not found.
fatal: repository 'https://github.com/GoogleCloudPlatform/blueprints.get/' not found 
```
2. See that `bucket` directory was created anyways.
3. If I try to `get` again with the corrected URL, I get an error:
```
$ kpt pkg get https://github.com/GoogleCloudPlatform/blueprints.git/catalog/bucket@kpt-v1
Error: destination directory "bucket" already exists 
```
4. I need to manually `rm -rf bucket` to undo the error state and get the package.

**Comment by droot** [comment]
PR https://github.com/GoogleContainerTools/kpt/pull/2410 should address this.
