### ISSUE TITLE
Prepend `gcr.io/kpt-fn/` prefix by default to image and short hand for include-meta-resources flag

### ISSUE THREAD

**Issue by phanimarupaka** [GoogleContainerTools/kpt#2401]
Users can specify just the image name and not the full path for kpt functions catalog images. Have a short hand for `include-meta-resources`

Example function run

```
Long form
kpt fn eval --image gcr.io/kpt-fn/fix:v0.2 --include-meta-resources
```

```
Short form
kpt fn eval -i fix:v0.2 -m
```

**Comment by mikebz** [comment]
if possible also have a shorthand for the latest tag (this is probably going to be used mostly development of the CICD solution) and then folks will probably button things down once they graduate to full automation.

**Comment by phanimarupaka** [comment]
@mikebz You mean a short-hand for word `unstable` ?

We don't want to have the notion of `latest`.

**Comment by mikebz** [comment]
I actually mean the english "latest" and as long as we pick one thing and stick with it - I think we are good.  The point is that the best UX for someone who is playing around with kpt is to type this:

```
kpt fn eval -i kubeval
```

Preferably it works like pip or npm where i get the latest released version of the dependency.  We want to minimize the friction to people exploring kpt, knowing the tag currently requires leaving your terminal and going to a website where you need to pick a version.
