### ISSUE TITLE
kpt pkg get fails when repo contains links

### ISSUE THREAD

**Issue by aodinokov** [GoogleContainerTools/kpt#2408]
### Expected behavior
The repo that contains links (to files or dirs) should be cloned without errors

### Actual behavior
It fails, see steps to reproduce below

### Information

kpt version:
```
$ kpt version
1.0.0-beta.2
```

### Steps to reproduce the behavior

`config` dir is in fact a link to another directory:
```
$ kpt pkg get https://github.com/airshipit/images/image-builder
Package "image-builder":
Fetching https://github.com/airshipit/images@master
From https://github.com/airshipit/images
 * branch            master     -> FETCH_HEAD
Error: error copying package: read /home/ubuntu/.kpt/repos/nb2hi4dthixs6z3joruhkyromnxw2l3bnfzhg2djobuxil3jnvqwozlt2qoyzwmpaczaj2mabgmoz6ccpy======/image-builder/config: is a directory
```

Apparently [CopyDir](https://github.com/kubernetes-sigs/kustomize/blob/master/kyaml/copyutil/copyutil.go#L20) can't handle links in its current implementation.

**Comment by droot** [comment]
@aodinokov Yes, this is a known issue. kpt doesn't handle links well in various workflow not just packaging.

**Comment by zijianjoy** [comment]
+1 on getting this error.

**Comment by zijianjoy** [comment]
My use case is a bit different:

I ran the following command:

```
kpt pkg get "https://github.com/argoproj/argo-workflows.git/manifests@v3.1.6" upstream
```

When in kpt 0.39, this command ran successfully. But when in kpt 1.0.0+, the command fails with:

```

Package "manifests":
Fetching https://github.com/argoproj/argo-workflows@v3.1.6
From https://github.com/argoproj/argo-workflows
 * tag               v3.1.6     -> FETCH_HEAD
Error: error copying package: read /Users/jamxl/.kpt/repos/nb2hi4dthixs6z3joruhkyromnxw2l3bojtw64dsn5vc6ylsm5xs253pojvwm3dpo5z5ihmm3ghqbmqe5gaatghm7bbh4===/docs/examples: is a directory 
```

Note that I only need the files in `manifests/` folder, but the error is about symlink `examples` in a separate folder `docs`. I think this error is avoidable as long as kpt 1.0.0+ doesn't copy the whole repo.
