### ISSUE TITLE
kpt live status with stdin not working

### ISSUE THREAD

**Issue by sbellan** [GoogleContainerTools/kpt#2412]
```
$ kpt version
1.0.0-beta.1
$ kustomize build instance | kpt live status -
error: argument '-' is not but must be a directory
```
live apply works with stdin, but live status does not

**Comment by droot** [comment]
@seans3 @mortent any idea what could be going here ?

**Comment by seans3** [comment]
Looking into this now.

**Comment by mortent** [comment]
@seans3  The issue here is for the `kpt live status` command, not `kpt live apply`.
