### ISSUE TITLE
Warning users when legacy functions are used

### ISSUE THREAD

**Issue by karlkfi** [GoogleContainerTools/kpt#2423]
### Expected behavior

I expect `kpt fn eval` to preserve local-config files so it can be run multiple times with idempotent behavior.

### Actual behavior

`kpt fn eval` deletes files with the local-config=true annotation.

### Information

```
$ kpt version
1.0.0-beta.3
```

### Steps to reproduce the behavior

```
$ git clone https://github.com/GoogleCloudPlatform/blueprints

$ cd blueprints

$ kpt fn eval catalog/empty --image gcr.io/kpt-fn/set-annotation:v0.1 -- "example=true"
[RUNNING] "gcr.io/kpt-fn/set-annotation:v0.1"
[PASS] "gcr.io/kpt-fn/set-annotation:v0.1"

$ git status
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	deleted:    catalog/empty/noop.yaml

no changes added to commit (use "git add" and/or "git commit -a")
```

**Comment by bharathkkb** [comment]
It also occurs when invoked declaratively via `kpt fn render` so maybe a bug with set-annotation?

```
apiVersion: kpt.dev/v1
kind: Kptfile
metadata:
  name: empty
  annotations:
    blueprints.cloud.google.com/title: Empty blueprint
info:
  description: An example of an empty blueprint.
pipeline:
  mutators:
    - image: gcr.io/kpt-fn/set-annotation:v0.1
      configMap:
            foo: bar
```

**Comment by bharathkkb** [comment]
seems related to https://github.com/GoogleContainerTools/kpt/issues/1933

**Comment by bharathkkb** [comment]
Looks like the fn was `set-annotations` and not `set-annotation`. `set-annotation` doesnt seem to have the above fix and doesnt seem to be updated. Using `set-annotations` it is WAI.

**Comment by phanimarupaka** [comment]
@mengqiy What is the deprecation plan for set-annotation and set-label legacy functions ?

**Comment by bharathkkb** [comment]
@phanimarupaka if possible surfacing a warning in `set-annotation` to use `set-annotations` would be useful.

**Comment by mengqiy** [comment]
@karlkfi I'm trying to understand why the legacy functions are being used. Is that because we don't currently provide a warning for the legacy functions?

**Comment by karlkfi** [comment]
> @karlkfi I'm trying to understand why the legacy functions are being used. Is that because we don't currently provide a warning for the legacy functions?

Just ignorance that the name had changed.

The problem is solved by using the new image, but it was not obvious that that was the problem.

**Comment by mengqiy** [comment]
We should figure out a way to surface a warning when a deprecated image is used.

**Comment by droot** [comment]
This was a temporary problem when were changing name of the functions. Closing this. We can reopen if we encounter this problem again.
