### ISSUE TITLE
Package Update Umbrella Issue

### ISSUE THREAD

**Issue by pwittrock** [GoogleContainerTools/kpt#243]
- [ ] keep field ordering when updating #240
- [ ] sophisticated resource merging during updates
  - raise error on conflicts between updated, common ancestor, and local
  - allow users to specify per-field merge strategies -- always updated, always local

**Comment by phanimarupaka** [comment]
1 was due to the format step after update which was fixed a while ago.
resource-merge already takes care of 3-way merge and other requests are not relevant in the current context.
