### ISSUE TITLE
Include changed files in function output

### ISSUE THREAD

**Issue by grmoon** [GoogleContainerTools/kpt#2448]
### Describe your problem

When users run a mutator (e.g. `set-annotations`), the output doesn't tell them which files changed. The only way a user can figure out which files were affected is by looking through them manually or doing `git status` or however they might normally be notified of changes to files.

It would be nice if we were able to notify the user which files changed as a result of their running a function in the output of that function.

**Comment by phanimarupaka** [comment]
@grmoon Output similar to `apply-setters` is what you are looking for ?

**Comment by grmoon** [comment]
> @grmoon Output similar to `apply-setters` is what you are looking for ?

that would be great!

**Comment by phanimarupaka** [comment]
@etefera This would be a good issue if you want to pick up.

**Comment by sdowell** [comment]
This has now been implemented for set-annotations by adding the following functionality to the kustomize api:
https://github.com/kubernetes-sigs/kustomize/pull/4307

And subsequently consuming the new functionality in the set-annotations function:
https://github.com/GoogleContainerTools/kpt-functions-catalog/pull/662

**Comment by sdowell** [comment]
We plan on providing this functionality to the `set-labels` function as well
