### ISSUE TITLE
Simplify the user config for kpt curated functions

### ISSUE THREAD

**Issue by yuwenma** [GoogleContainerTools/kpt#2458]
### Describe your problem

It would be more handy (and easier to spead) if users can provide less config to use a kpt function.

For example, use a short name rather than the full gcr.io url, use `kubeval` in  `.pipeline.validators.image` (rather than  ​`gcr.io/kpt-fn/kubeval:v0.1`). This is of similar idea as docker image.

**Comment by phanimarupaka** [comment]
@yuwenma kpt already supports it. Please make sure you are on beta3+ version of kpt. https://kpt.dev/book/04-using-functions/02-imperative-function-execution. Please re-open the issue if this din't answer your question.
