### ISSUE TITLE
Function: set-enforcement-action

### ISSUE THREAD

**Issue by morgante** [GoogleContainerTools/kpt#2460]
We should have a function which sets the [enforcement action](https://github.com/GoogleCloudPlatform/acm-policy-controller-library/blob/master/bundles/cis-k8s-1.5.1/5.1.3_prohibit-role-wildcard-access.yaml#L9) on Gatekeeper constraints. Right now this is being done via repetitive setters and is an ideal case for a reusable function.

**Comment by morgante** [comment]
I can take this.

**Comment by phanimarupaka** [comment]
@morgante Sure. Thanks for taking this up.

**Comment by mengqiy** [comment]
Done by GoogleContainerTools/kpt-functions-catalog#625
