### ISSUE TITLE
Kpt does not preserve order of fields when field value is null

### ISSUE THREAD

**Issue by natasha41575** [GoogleContainerTools/kpt#2462]
See https://github.com/GoogleContainerTools/kpt-functions-catalog/pull/544/files, and the example `render-helm-chart-crds`.

The function fails the idempotency check, because upon the first run, the contents of `customresourcedefinition_workspaces.app.terraform.io.yaml`
contains the following:

```
creationTimestamp: null
name: workspaces.app.terraform.io
```

On the second run, this gets reversed:

```
name: workspaces.app.terraform.io
creationTimestamp: null
```

If in between the first and second run, I change the value of `creationTimestamp` to anything except null, e.g. `999`, this reordering does not occur - the field ordering is preserved correctly. My guess is kpt is somehow ignoring `creationTimestamp: null` because of the null value, resulting in a bug in the order preservation code. 

cc @droot @phanimarupaka

**Comment by phanimarupaka** [comment]
@natasha41575 Thanks for filing the issue. I will debug and update the progress.

**Comment by phanimarupaka** [comment]
@natasha41575 I added the test and it works fine. https://github.com/kubernetes-sigs/kustomize/pull/4134/files

Which version of kpt are you using ? kpt version on your local should have version beta2 or above.

Where can I find render-helm-chart function ? I don't see it here https://pantheon.corp.google.com/gcr/images/kpt-fn/GLOBAL
