### ISSUE TITLE
Docs: Kptfile (https://kpt.dev/reference/schema/kptfile/)

### ISSUE THREAD

**Issue by nairb774** [GoogleContainerTools/kpt#2464]
This page attempts to link to the schema, but that link 404s: https://kpt.dev/reference/schema/kptfile/kptfile.yaml

It is possible there is an underlying infra issue given: https://github.com/GoogleContainerTools/kpt/issues/2454

**Comment by phanimarupaka** [comment]
@nairb774 This works for me. Can you please try again.

**Comment by nairb774** [comment]
If you go direct to the url it works. If you tap the link to follow from the Kptfile doc page it 404s.

I doubt it matters, but I'm using Chrome on Android.

**Comment by phanimarupaka** [comment]
@nairb774 Got it. I see the same. @etefera can you please take a look at this issue.
