### ISSUE TITLE
`filters.MergeFilters` leads to different results depending on if merge occured

### ISSUE THREAD

**Issue by howardjohn** [GoogleContainerTools/kpt#2467]
### Expected behavior

`filters.MergeFilter([a,a]) == [a]`

### Actual behavior

`filters.MergeFilter([a,a]) == [not-a]`

### Information

I am writing a generator that uses `filters.MergeFilter`. The generator creates a configmap, then renders it to yaml. This means the yaml output has `creationTimestamp: "null"`, as sigs.k8s.io/yaml library always renders that (why, I don't know...).

The first time this function is run, we see  `creationTimestamp: "null"` in the output file. The second time, it disappears. I think this is because when it merges, it does some additional processing that ends up removing `creationTimestamp` - just a guess though.

I don't really care if `creationTimestamp` ends up in the output or not (either is fine), but running a function once vs twice should return the same output, without requiring function writers to jump through hoops. As a workaround, I have added:
```
	b = bytes.ReplaceAll(b, []byte(`  creationTimestamp: null
	`), nil)
```

But this is not ideal 

Somewhat related to https://github.com/GoogleContainerTools/kpt/issues/2466

**Comment by droot** [comment]
@phanimarupaka it seems related to https://github.com/GoogleContainerTools/kpt/issues/2462

**Comment by phanimarupaka** [comment]
This issue has been addressed on beta.5 version of kpt and will be released today.
