### ISSUE TITLE
apply-setter kpt function may provide wrong results when using subpackages

### ISSUE THREAD

**Issue by RolandOtta** [GoogleContainerTools/kpt#2474]
we have 2 kpt packages

package A (main package)
package B (subpackage in package A)

package b defines a pattern for kpt-set `# kpt-set: prefix-${var1}-${var2}

if both vars are containing a substring of the kpt pattern, for example `-` in the given case, the apply-setter function cuts off the var2 in the result.

to reproduce the issue:

* clone git@github.com:RolandOtta/kpt-issue-2.git
* cd to directory A
* `kpt fn render . --output="/tmp/output" --truncate-output=false`

the output already shows the invalid result

for package A/B it is still fine

`[INFO] set field value to "prefix-foo-bar-foo2-bar2" in file "demo.yaml" in field "metadata.name"`

package A then provides the wrong result

`[INFO] set field value to "prefix-foo-bar-bar2" in file "demo.yaml" in field "metadata.name"`

the problem seems to be caused by the regex pattern in the https://github.com/GoogleContainerTools/kpt-functions-catalog/blob/master/functions/go/apply-setters/applysetters/apply_setters.go#L271 function.

the following patch fixed my issue. as i am not really familiar with go i am not sure whether this patch could cause other issues.

```
@@ -207,7 +207,7 @@ func (as *ApplySetters) visitScalar(object *yaml.RNode, path string) error {
                return nil
        }

-       curPattern := setterPattern
+       //curPattern := setterPattern
        if !shouldSet(setterPattern, as.Setters) {
                // this means there is no intent from user to modify this setter tagged resources
                return nil
@@ -224,7 +224,7 @@ func (as *ApplySetters) visitScalar(object *yaml.RNode, path string) error {

        // replace the remaining setter names in comment pattern with values derived from current
        // field value, these values are not provided by user
-       currentSetterValues := currentSetterValues(curPattern, object.YNode().Value)
+       currentSetterValues := currentSetterValues(setterPattern, object.YNode().Value)
        for setterName, setterValue := range currentSetterValues {
                setterPattern = strings.ReplaceAll(
                        setterPattern,
```

**Comment by phanimarupaka** [comment]
@RolandOtta This is because the regex is ambiguous and the function in `A/Kptfile` is assuming that the current value of `var1` is `foo-bar-foo2` and is replacing it with new value `foo-bar`. Why don't you also declare the value of `var2` in `A/Kptfile` ?

**Comment by unlimitedbits** [comment]
@phanimarupaka 
we also experienced that issue in our use cases.
we often have the same kpt blueprint (e.g. a secretmanager secret) as a subpackage within one folder, which have overlapping setters with the root package.
in such situations it's not possible to copy `var2` to `A/Kptfile` because then you'll overwrite the value in multiple subpackages.

**Comment by phanimarupaka** [comment]
The task here is
For value `prefix-foo-bar-foo2-bar2`
For setter pattern `prefix-${var1}-${var2}`
We should derive the values of `var1` and `var2`
This is ambiguous pattern and has multiple possibilities, and can't have deterministic answer without additional data.

@unlimitedbits Can I know more about your actual use-case with an example ? 
There are couple of ways to solve this 
Avoid having `var1` in `A/Kptfile` and push them to all sub-packages.
Use different setter name for `var2`(var2B) 

But this can be solved in general using [target selectors](https://github.com/GoogleContainerTools/kpt/issues/2015) feature which will be released soon(by early october). Using this, you can select specific packages on which the setters should be applied.

**Comment by phanimarupaka** [comment]
Closing this issue as the alternatives are proposed and no response. Please reopen if you still have questions.
