### ISSUE TITLE
Unknown command "cfg" for "kpt"

### ISSUE THREAD

**Issue by Cypherman1** [GoogleContainerTools/kpt#2475]
I ran this command:

`kpt cfg set -R . name "${MGMT_NAME}"`

but received  error:

```
error: unknown command "cfg" for "kpt"

Did you mean this?
	fn
	pkg
```
Please help!

**Comment by HP-Nunes** [comment]
@Cypherman1 did you find a solution to this issue? I have the same problem, and I suspect you were also going through the G-Cloud's Kubeflow [deployment steps](https://www.kubeflow.org/docs/distributions/gke/deploy/management-setup/).
