### ISSUE TITLE
Kpt should use internal.config.kubernetes.io/* annotations

### ISSUE THREAD

**Issue by mengqiy** [GoogleContainerTools/kpt#2478]
Kpt should use the annotations as specified in https://github.com/kubernetes-sigs/kustomize/blob/master/cmd/config/docs/api-conventions/functions-spec.md#internal-annotations.

For example, kpt currently use `config.kubernetes.io/path` but it should use `internal.config.kubernetes.io/path`.

**Comment by natasha41575** [comment]
Issue on kustomize side: https://github.com/kubernetes-sigs/kustomize/issues/4024

LMK if you plan to take care of it on both sides or if you need me to work on it

**Comment by mengqiy** [comment]
I will take a closer look 

> I'm guessing the fix will be in kyaml for both kpt and kustomize.

That's very likely to be the case.

**Comment by droot** [comment]
The fix needs to be done in kyaml (common orchestrator layer) as part of kubernetes-sigs/kustomize#4024. @natasha41575 No plans to address this in the short term on kpt side yet.

**Comment by mengqiy** [comment]
This has been confusing for contributors. We should fix it soon.
@natasha41575 Do you have cycle to fix this?
If we want to fix this in kyaml v0.11.*, it should add both `config.kubernetes.io/*` and `internal.config.kubernetes.io/*` annotations.
When we are ready to move to kyaml v0.12.0, we can remove the `config.kubernetes.io/*` annotation support.

**Comment by natasha41575** [comment]
> Do you have cycle to fix this?

Yes, I can take a look this sprint. 

> If we want to fix this in kyaml v0.11.*, it should add both config.kubernetes.io/* and internal.config.kubernetes.io/* annotations.

We should do this first, and after some time we can drop support for config.kubernetes.io/* and release 0.12.

**Comment by natasha41575** [comment]
As an update, I am currently working on this but the reconciliation algorithm (e.g. if a function changes the legacy path annotation, then the orchestrator must detect the change and update the new path) will take a little bit more thought and care than I'd expected.

**Comment by natasha41575** [comment]
See https://github.com/kubernetes-sigs/kustomize/pull/4190

**Comment by natasha41575** [comment]
This is updated in kyaml v0.12.0. I will work on a PR to update kpt.

**Comment by droot** [comment]
Closing since the PR has been merged.
