### ISSUE TITLE
Setter support for adding fields, list items and map entries

### ISSUE THREAD

**Issue by pwittrock** [GoogleContainerTools/kpt#248]
Currently setters only support modifying existing fields.  This is a feature request for adding fields or list items from setters.

- [ ] Add scalar fields which aren't present
- [ ] Add list items which aren't present
- [ ] Add scalar map entries which aren't present
- [ ] Add complex fields

Maybe use kustomize for this instead.

**Comment by pwittrock** [comment]
Probably want to do this a different way

**Comment by phanimarupaka** [comment]
Will be implemented as part of https://github.com/GoogleContainerTools/kpt/issues/961
