### ISSUE TITLE
error: unknown command "cfg" for "kpt"

### ISSUE THREAD

**Issue by HP-Nunes** [GoogleContainerTools/kpt#2481]
### Expected behavior
I want to configure kpt setter values for the name, project, and location of a management cluster in Google Cloud.

```
kpt cfg set -R . name "${MGMT_NAME}"
kpt cfg set -R . gcloud.core.project "${MGMT_PROJECT}"
kpt cfg set -R . location "${LOCATION}"

```

### Actual behavior

I tried running the first line in bash, and got this in return:

```
error: unknown command "cfg" for "kpt"

Did you mean this?
	fn
	pkg
```

### Information

I followed the installation instructions from ktp's [website](https://kpt.dev/installation/), using docker to install both ktp and ktp-gcloud.

I'm running ktp version **1.0.0-beta.1** with kubectl version GitVersion:"v1.22.1" and kustomize/v4.3.0.

I am following the Kubeflow's [tutorial](https://www.kubeflow.org/docs/distributions/gke/deploy/management-setup/) on deploying a management cluster on Google Cloud. 

I understand that someone has posted about this exact issue 4 days ago, but the issue was closed without a resolution. I am a beginner with ktp/Kubeflow, so apologies if the resolution is obvious.

**Comment by droot** [comment]
Kubeflow's tutorial has a note saying:

>Note: kpt v1.0.0-beta.1 or above doesn’t work due to a known issue: https://github.com/kubeflow/pipelines/issues/6100. Please downgrade gcloud or install kpt separately https://github.com/GoogleContainerTools/kpt/releases/tag/v0.39.2 for now.

So looks like kubeflow hasn't migrated to kpt 1.0+ yet, so you will have to use https://github.com/GoogleContainerTools/kpt/releases/tag/v0.39.2 release.

**Comment by HP-Nunes** [comment]
@droot that resolved my issue; many thanks! Just goes to show that you can get so absorbed into solving an issue that one fails to see the obvious....

I'm adding some additional details below for any n00b like myself in a similar predicament:

1. I had the ktp v1.0+ binary installed, so I removed it running:
`sudo apt-get remove google-cloud-sdk-kpt`
Make sure to later run `gcloud components update`
2. I reinstalled the v0.39 binary using the instructions from: https://cloud.google.com/service-mesh/docs/environment-setup
**Important**: make sure to install ktp within the directory where you want it to execute. Within the context of the context of the Kubeflow's management setup tutorial, that would be within the gcp-blueprints folder: https://www.kubeflow.org/docs/distributions/gke/deploy/management-setup/
3. Verify that the install worked properly with `ktp version`
4. The `kpt cfg set` command should now be working. As I understand it, this command is deprecated in the latest beta binary: https://kpt.dev/installation/migration?id=changes-to-setters
