### ISSUE TITLE
Regressions in kpt.dev site

### ISSUE THREAD

**Issue by frankfarzan** [GoogleContainerTools/kpt#2490]
There have been couple of regressions in kpt.dev:

1. Navbar rendering regression, items have inconsistent bullet points and inconsistent coloring (Note that catalog doesn't have one)

<img width="316" alt="Screen Shot 2021-09-09 at 1 08 46 PM" src="https://user-images.githubusercontent.com/4031551/132755704-e94c7ca0-5bbf-40eb-a770-845701d2e3a5.png">

2. Githhub link on top right of pages leads to https://kpt.dev/reference/undefined

**Comment by droot** [comment]
@mengqiy As we discussed this morning:

- kpt.dev and catalog.kpt.dev should have same navigation (they should feel like they are part of the same website)
- Make the `Function Catalog` hierarchical so it will appear with collapse(non-collapse) icon with `Curated` and `Contrib` as children nodes.

I just checked `github` link  seems to be working for me.

**Comment by mengqiy** [comment]
Fixed by #2522 and https://github.com/GoogleContainerTools/kpt-functions-catalog/pull/604
