### ISSUE TITLE
Github action `Deploy to Firebase Hosting on merge` is failing

### ISSUE THREAD

**Issue by droot** [GoogleContainerTools/kpt#2507]
Quick look suggest there seems to an auth issue. Logs at https://github.com/GoogleContainerTools/kpt/runs/3602208625?check_suite_focus=true

**Comment by mengqiy** [comment]
Failing due to an expired SA key.
It has been fixed now.

Same problem as https://github.com/GoogleContainerTools/kpt/issues/2443.
