### ISSUE TITLE
kpt shouldn't require an initial Git commit when using `resource-merge` strategy

### ISSUE THREAD

**Issue by morgante** [GoogleContainerTools/kpt#2512]
### Describe your problem

Currently, if I want to use `kpt pkg update` to update a bare Kptfile (which only has upstram info), `kpt` refuses to run update unless the `Kptfile` has been committed.

When using `resource-merge` strategy, I don't think this is necessary and it adds additional friction.

**Comment by droot** [comment]
> Currently, if I want to use kpt pkg update to update a bare Kptfile (which only has upstram info), kpt refuses to run update unless the Kptfile has been committed.

@phanimarupaka @mortent Do you remember rationale behind this. Was this to prevent users from losing their local change in-case `update` behaves unexpectedly ?

**Comment by droot** [comment]
This has been addressed so closing the issue.
