### ISSUE TITLE
Improve performance for kpt live e2e tests

### ISSUE THREAD

**Issue by mortent** [GoogleContainerTools/kpt#2554]
We have a small number of e2e tests for kpt live (outside of the bash-based approach). They currently run in serial and requires that a new cluster is created for several of the tests. This causes them to be very slow.

We should improve this by:
 * Reduce the number of times we need to create a new kind cluster, as this takes ~1 minute. Tests should clean up after themselves and we can handle some of the clean-up in the framework.
 * Look at ways we can run multiple tests in parallel against a single cluster. This applies mostly for test-cases that doesn't involve cluster-scoped resources.

**Comment by sdowell** [comment]
@mortent is this resolved by https://github.com/GoogleContainerTools/kpt/pull/2613?

**Comment by yuwenma** [comment]
Yeah, I think @sdowell is right. This issue seems to be fixed already.
