### ISSUE TITLE
Improve `upsert-resource` to handle multiple resources

### ISSUE THREAD

**Issue by morgante** [GoogleContainerTools/kpt#2570]
In order to make `upsert-resource` more useful for editing complex blueprints (go/oc-customize-bp), we need two main enhancements:

# 1. Ability to pass multiple resources to upsert at once.

This is purely a performance optimization, because invoking a separate container+function call for each resource is slow.
 
The easiest way to do this would probably be to accept a `ResourceList` as the functionConfig and upsert each resource in the list.

# 2. Specify resource path

In some cases, it is needed to upsert specific resources within a package (particularly when multiple "instances" of the same upstream package) are contained in a parent package even when they have the same name. Therefore, we need the ability to (optionally) upsert the resource at a specific path.

I suggest this could be done by setting the `internal.config.kubernetes.io/path` annotation but am open to alternatives.

**Comment by phanimarupaka** [comment]
@morgante As pinged you internally 2 days ago.

Your requested changes have been implemented and merged with `upsert-resource:unstable` tag
Please try it out and let me know if it works for you.
You will have to compile kpt from [source](https://kpt.dev/installation/?id=source) and invoke this function.
Please let me know if this works fine. We can release `kpt` and `upsert-resource` function once we get a go ahead from you.

**Comment by phanimarupaka** [comment]
Both the function and kpt have been released.

Please refer to https://kpt.dev/installation/ to install kpt
Please use upsert-resource:v0.2 tag for new functionality
