### ISSUE TITLE
Allow Starlark source to be defined in Kptfile

### ISSUE THREAD

**Issue by FrenchBen** [GoogleContainerTools/kpt#2575]
### Describe your problem

functionConfig currently supports 2 approaches:
* Run via Kptfile
* Run via CLI arguments

While these 2 approaches provide some flexibility in testing, it also creates inequality for certain functions, more specifically Starlark.

### Example

Taking the core example of [Starlark Configmap](https://github.com/GoogleContainerTools/kpt-functions-catalog/tree/starlark/v0.3/functions/go/starlark#functionconfig)

```
# fn-set-replicas.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: set-replicas
data:
  replicas: "5"
  source: |
    def setReplicas(resources, replicas):
      for r in resources:
        if r["apiVersion"] == "apps/v1" and r["kind"] == "Deployment":
          r["spec"]["replicas"] = replicas
    replicas = ctx.resource_list["functionConfig"]["data"]["replicas"]
    setReplicas(ctx.resource_list["items"], replicas)
```

When running this, a few options are available:

1. Call it via config map: `kpt fn eval --image gcr.io/kpt-fn/starlark:v0.3 --fn-config fn-set-replicas.yaml`
2. Add it to your Kptfile, and call `kpt fn render`
```
apiVersion: kpt.dev/v1
kind: Kptfile
metadata:
  name: sample-pkg
info:
  description: sample description
pipeline:
  mutators:
    - image: gcr.io/kpt-fn/starlark:v0.3
      configPath: fn-set-replicas.yaml
```

But a 3rd option exists, which is to extract the Starlark code into a much more user-friendly (and editor parsable) file:
```
#set-replicas.star
    def setReplicas(resources, replicas):
      for r in resources:
        if r["apiVersion"] == "apps/v1" and r["kind"] == "Deployment":
          r["spec"]["replicas"] = replicas
    replicas = ctx.resource_list["functionConfig"]["data"]["replicas"]
    setReplicas(ctx.resource_list["items"], replicas)
```
Then run it via:
`kpt fn eval --image gcr.io/kpt-fn/starlark:v0.3 -- source="$(cat set-replicas.star)" replicas=5`

The problem is that you cannot then bring this back into your `Kptfile`, forcing you to copy this back into your awkward yaml file.

### Solution

Add support for Starlark file parsing, from a Kptfile. Similar to the `configPath` or `configMap` option, add a `sourcePath`  option where a `.star` file path could be declared.
```
apiVersion: kpt.dev/v1
kind: Kptfile
metadata:
  name: sample-pkg
info:
  description: sample description
pipeline:
  mutators:
    - image: gcr.io/kpt-fn/starlark:v0.3
      sourcePath: set-replicas.star
      configMap:
          replicas: 5
```

Which would result in something like:
```
# set-replicas.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: set-replicas
data:
  replicas: "5"
  source: | <insert-content-from-sourcePath>
```

**Comment by droot** [comment]
Another solution that has been discussed: [include-file support ](https://github.com/GoogleContainerTools/kpt/issues/2350)

**Comment by FrenchBen** [comment]
Closing as duplicate of https://github.com/GoogleContainerTools/kpt/issues/2350
