### ISSUE TITLE
Function to change / update / pin container images

### ISSUE THREAD

**Issue by bgrant0607** [GoogleContainerTools/kpt#2577]
A common deployment pattern is to update images to the latest tags or, ideally, digests. Sometimes people want to change the image repo, also, such as for dev builds.

Pinning images is one of the oldest issues in Kubernetes:
https://github.com/kubernetes/kubernetes/issues/1697

Kustomize supports a feature in this area:
https://github.com/kubernetes-sigs/kustomize/blob/master/examples/image.md

Skaffold has features in this area:
https://skaffold.dev/docs/environment/image-registries/

kbld does pinning, operating kind of like a function would:
https://carvel.dev/kbld

It should use duck typing to operate on anything with an image field. 

Users also want images replaced in custom resources:
https://github.com/GoogleContainerTools/skaffold/issues/4081

**Comment by droot** [comment]
Yes, `set-image` function is needed.

**Comment by bgrant0607** [comment]
Another KRM function:
https://github.com/google/k8s-digester

Clearly it needs to be easier to find these.
