### ISSUE TITLE
Quick start walkthough is producing an error

### ISSUE THREAD

**Issue by y0psolo** [GoogleContainerTools/kpt#2591]
### Expected behavior

kpt pkg update @v0.8
Package "nginx":
Fetching upstream from https://github.com/GoogleContainerTools/kpt@v0.8
From https://github.com/GoogleContainerTools/kpt
 * tag               package-examples/nginx/v0.8 -> FETCH_HEAD
Fetching origin from https://github.com/GoogleContainerTools/kpt@v0.8
From https://github.com/GoogleContainerTools/kpt
 * branch            88796824e8eb3a3c5c880ed7dcd303d244579b51 -> FETCH_HEAD
Updating package "nginx" with strategy "resource-merge".

### Actual behavior

kpt pkg update @v0.8
error: lstat : no such file or directory

### Workaround for expected behavior

kpt pkg update .@v0.8
Package "nginx":
Fetching upstream from https://github.com/GoogleContainerTools/kpt@v0.8
From https://github.com/GoogleContainerTools/kpt
 * tag               package-examples/nginx/v0.8 -> FETCH_HEAD
Fetching origin from https://github.com/GoogleContainerTools/kpt@v0.8
From https://github.com/GoogleContainerTools/kpt
 * branch            88796824e8eb3a3c5c880ed7dcd303d244579b51 -> FETCH_HEAD
Updating package "nginx" with strategy "resource-merge".

### Information

Kpt version : 1.0.0-beta.7

### Steps to reproduce the behavior

Do the Quick start (https://kpt.dev/book/01-getting-started/02-quickstart)  with a fresh kpt pkg get https://github.com/GoogleContainerTools/kpt/package-examples/nginx@v0.7

**Comment by droot** [comment]
This has been fixed in beta.8 `pre-release` https://github.com/GoogleContainerTools/kpt/releases/tag/v1.0.0-beta.8 . The release is not yet announced the `kpt.dev` site, which we will do soon, we are verifying a fixes. If you are blocked, use the beta.8 directly.

**Comment by mengqiy** [comment]
beta.9 has the fix and was released several days ago.

**Comment by nicolaiskogheim** [comment]
I just hit this same issue.
https://kpt.dev/book/01-getting-started/02-quickstart

![2021-12-06-152625_911x150_scrot](https://user-images.githubusercontent.com/2117636/144863346-a6b2e9a4-33d4-4d29-9e3f-568515b2f251.png)

Still no dot in `@v0.8`.
