### ISSUE TITLE
kpt fn render|eval should always printing truncated stderr output from functions

### ISSUE THREAD

**Issue by mengqiy** [GoogleContainerTools/kpt#2599]
Currently `kpt fn render|eval` prints stderr from the functions in the following 2 scenarios:
- functions result a failure.
- flag `--results-dirs` is specified, stderr will be captured in the structured results.

`kpt fn render|eval should` always printing truncated stderr output from functions.
Alternatively, we can add a flag (e.g. `--always-print-stderr`) to allow users to see stderr from functions. I will be helpful for debugging functions.

**Comment by mengqiy** [comment]
@sdowell Maybe this is something you can work on.

**Comment by sdowell** [comment]
@mengqiy Sounds good, I'll take a look
