### ISSUE TITLE
function catalog should make full version (vX.Y.Z) of all functions available

### ISSUE THREAD

**Issue by droot** [GoogleContainerTools/kpt#2609]
We want to recommend users to use fully qualified version (vX.Y.Z) of functions in their packages to ensure that the render config is immutable but catalog seems to use floating version (vX.Y) today. So two asks:
 - Make it easy to discover all the patch versions of functions
 - All examples should use latest stable full versions.

Note: This is even more critical because very soon, we will make `image-pull-policy` to `ifNotPresent`.

**Comment by droot** [comment]
We should also ensure that `kpt fn eval` auto complete should display the latest patch version the function.

Note: our installation guide should document `kpt completion` to enable auto completion.

**Comment by mengqiy** [comment]
This is done
