### ISSUE TITLE
Update section on kpt book to author function using new Go library

### ISSUE THREAD

**Issue by droot** [GoogleContainerTools/kpt#2610]
We should have a draft doc PR ready when kubernetes-sigs/kustomize#4319 is in flight.
We can merge kubernetes-sigs/kustomize#4319 and the doc PR at the same time.

We can port the examples from kubernetes-sigs/kustomize#4319

**Comment by yuwenma** [comment]
Done in https://github.com/GoogleContainerTools/kpt/pull/3148
