### ISSUE TITLE
kpt-functions-catalog e2e tests failing after newest kpt PR

### ISSUE THREAD

**Issue by rquitales** [GoogleContainerTools/kpt#2611]
### Expected behavior
All [GoogleContainerTools/kpt-functions-catalog](https://github.com/GoogleContainerTools/kpt-functions-catalog/) e2e tests should pass.

### Actual behavior
Some e2e test cases are failing as PR #2603 introduces changes to error messages.

### Information
In PR #2603, the output of error messages differ slightly which I believe is due to changes in upstream `kyaml`. While the test cases in [GoogleContainerTools/kpt](https://github.com/GoogleContainerTools/kpt) have been updated to reflect this, we also need to update the exepcted error messages in GoogleContainerTools/kpt-functions-catalog.

As an aside, is there a way we could have better testing? These tests seem very much like change detector tests to me, [which provides negative value ultimately](https://testing.googleblog.com/2015/01/testing-on-toilet-change-detector-tests.html).

### Steps to reproduce the behavior
```
go install -v github.com/GoogleContainerTools/kpt@main
git clone https://github.com/GoogleContainerTools/kpt-functions-catalog.git
cd kpt-functions-catalog
make build
make e2e-test
```

Using an older version of kpt will have all tests passing: `go install -v github.com/GoogleContainerTools/kpt@cbd93fa25dda7c556f03cadcbba5b8b8444218c4`.

**Comment by droot** [comment]
This is fixed by https://github.com/GoogleContainerTools/kpt-functions-catalog/pull/667 so closing it.

> These tests seem very much like change detector tests to me

@mengqiy we may consider using structured result for most functions and leave one or two for CLI output comparison.

**Comment by mikebz** [comment]
I like the structured results idea 👍
