### ISSUE TITLE
Keep remote file permissions

### ISSUE THREAD

**Issue by pwittrock** [GoogleContainerTools/kpt#266]
kpt changes the file permissions to be 0600 when getting / updating

it should keep the original permissions

**Comment by jijiew** [comment]
It looks to me that kpt does keep the permission. Please correct me if I'm wrong below:

test with kpt get
kpt pkg get https://github.com/jijiew/testing.git

in the folder file permission-test.yaml have permission 755, and local fetched file have the same permission

test with kpt update
modify the file with permission locally and udpate the pkg, the permission changes keeps.

**Comment by mortent** [comment]
@jijiew I think we can close this issue as it seems like it is working. We can reopen if we find a concrete example where this doesn't work as expected.
