### ISSUE TITLE
Tab completion behavior is now unuseable

### ISSUE THREAD

**Issue by Pitta** [GoogleContainerTools/kpt#2661]
### Expected behavior

When typing `kpt` in shell, and hitting tab, get a list of the verbs and flags available

### Actual behavior

```shell
pitta@hostname% kpt Usage:
  kpt [flags]
  kpt [command]

Available Commands:
  completion  generate the autocompletion script for the specified shell
  fn          Transform and validate packages using containerized functions.
  help        Help about any command
  live        Deploy local packages to a cluster.
  pkg         Get, update, and describe packages with resources
  version     Print the version number of kpt

Flags:
      --add_dir_header                   If true, adds the file directory to the header of the log messages
      --alsologtostderr                  log to standard error as well as files (default true)
  -h, --help                             help for kpt
      --log-flush-frequency duration     Maximum number of seconds between log flushes (default 5s)
      --log_backtrace_at traceLocation   when logging hits line file:N, emit a stack trace (default :0)
      --log_dir string                   If non-empty, write log files in this directory
      --log_file string                  If non-empty, use this log file
      --log_file_max_size uint           Defines the maximum size a log file can grow to. Unit is megabytes. If the value is 0, the maximum file size is unlimited. (default 1800)
      --logtostderr                      log to standard error instead of files
      --one_output                       If true, only write logs to their native severity level (vs also writing to each lower severity level)
      --skip_headers                     If true, avoid header prefixes in the log messages
      --skip_log_headers                 If true, avoid headers when opening log files
      --stack-trace                      Print a stack-trace on failure
      --stderrthreshold severity         logs at or above this threshold go to stderr (default 2)
      --truncate-output                  Enable the truncation for output (default true)
  -v, --v Level                          number for the log level verbosity
      --vmodule moduleSpec               comma-separated list of pattern=N settings for file-filtered logging

Use "kpt [command] --help" for more information about a command.

```
With my cursor at the bottom of this output. This output seems to be the same no matter what verb follows `kpt`

### Information

Version: `1.0.0-beta11`

### Steps to reproduce the behavior

* type `kpt` in your shell
* hit `tab`

**Comment by sdowell** [comment]
Can you describe how you have configured completion for your environment?

Try following the setup steps here and see if the issue persists:
https://kpt.dev/installation/?id=optional-enable-shell-auto-completion

**Comment by Pitta** [comment]
```

**Comment by Pitta** [comment]
```shell
source <(kpt completion zsh)
```

Just tried this and has the same behavior, even on `1.0.0-beta12`

I tend to do this:
```shell
kpt completion zsh > ~/.zsh/completion/_kpt
```

But looking at my setups, I haven't even typically been doing this with KPT. Just have all the `zsh` compinit turned on and its been fine as of `1.0.0-beta7`, which was the last version I was on before I updated.

**Comment by Pitta** [comment]
Just reverted to `beta7` and it is behaving in a far more useable state.

**Comment by sdowell** [comment]
Hi @Pitta

I did some more investigation into this today, and I can confirm that `source <(kpt completion zsh)` doesn't appear to work without the addition of `compdef _kpt kpt`.

However, completion did work for me after following cobra's built-in instructions (`kpt completion zsh -h`) for enabling zsh completion (which is in line with your usual approach that you mentioned):
```shell
kpt completion zsh > ~/.zsh/completion/_kpt
```
Can you confirm that the above command does not work for your environment?
If this does not work, can you provide a bit more information about your environment? e.g. relevant portion of your `.zshrc` file, operating system, etc

**Comment by Pitta** [comment]
Can confirm that:
```shell
kpt completion zsh > ~/.zsh/completion/_kpt
```
indeed does not work on my machine.

I am on a fully updated MacBook. I admittedly have a small section for completion in my zsh, and it is probably in need of cleaning since its a mishmash of things I was doing to get diff tools working.

```shell

**Comment by Pitta** [comment]
Can confirm the same busted behavior on Ubuntu via WSL2:

`neofetch` system info:
```shell
OS: Ubuntu 20.04.3 LTS on Windows 10 x86_64
Kernel: 5.10.60.1-microsoft-standard-WSL2
Uptime: 8 hours, 18 mins
Shell: zsh 5.8
CPU: AMD Ryzen 7 5800X (16) @ 3.800GHz
Memory: 386MiB / 32078MiB
```

**Comment by sdowell** [comment]
What is the output when you run
```
echo "${fpath[@]}"
```
If `~/.zsh/completion` is not included in the output, you may need to add a line to your `zshrc` to make sure your directory is included in the zsh function search path. This is of course assuming you placed the script at `~/.zsh/completion/_kpt` and not one of the default locations of `fpath`

The relevant section of my `zshrc` is nearly identical to the latter (flattened) version you shared, with the addition of adding `~/.zsh/completion` to my `fpath`.
```
fpath=(~/.zsh/completion $fpath)
autoload -Uz compinit ; compinit
```

**Comment by Pitta** [comment]
I do seem to have this further up my config, and clearly need to do a gardeningpass on my stuff:

```shell
fpath=(${HOME}/.zsh/completion $fpath)
```

and the output of  echo "${fpath[@]}" shows the path is indeed there, and first. On both machines.

**Comment by sdowell** [comment]
From the information you've provided I believe I've figured out how to reproduce the issue you're seeing in your environment. I may of course be mistaken as I'm trying to recreate the configuration of your environment from limited information.

It appears the issue is arising due to the presence of the following artifact of a previous completion installation:
```
complete -C $(which kpt) kpt
```

This line needs to be removed from `zshrc` for the updated version of `kpt completion` to function properly, otherwise I observed the same behavior as you saw. You already removed this in your flattened `zshrc`, so you should be fine here already.

However, it seems it is not sufficient to merely `source ~/.zshrc` after applying this change. From my testing the error continued until creating a new `zsh`. I may be mistaken, but I expect in your testing you may have ran `source ~/.zshrc` and not started a new `zsh`.

If you don't mind, could you try invoking completion in a fresh zsh (with the configuration changes we discussed above)?

**Comment by Pitta** [comment]
TIL things about `zsh`

```shell
% kpt                                                                                                                                                                                                                                          completion  -- generate the autocompletion script for the specified shell
fn          -- Transform and validate packages using containerized functions.
help        -- Help about any command
live        -- Deploy local packages to a cluster.
pkg         -- Get, update, and describe packages with resources
version     -- Print the version number of kpt
```

This works now! This must have been self inflicted based on a poor understanding of the compinit feature. Thank you for your help!
