### ISSUE TITLE
kpt version incorrect for v1.0.0-beta.12 (displays v1.0.0-beta.9)

### ISSUE THREAD

**Issue by aaron-prindle** [GoogleContainerTools/kpt#2691]
### Expected behavior
```
# install kpt v1.0.0-beta.12
$ kpt version
1.0.0-beta.9
```

### Actual behavior
```
# install kpt v1.0.0-beta.12
$ kpt version
1.0.0-beta.12
```

### Steps to reproduce the behavior
```
$ curl -lO https://github.com/GoogleContainerTools/kpt/releases/download/v1.0.0-beta.12/kpt_linux_amd64
$ sudo mv kpt_linux_amd64 /usr/local/bin/kpt
$ kpt version
1.0.0-beta.9
```

**Comment by droot** [comment]
@aaron-prindle I am not able to reproduce this in my setup. Can you check `/usr/local/bin/kpt` is being invoked ?  I have run into situations where I had `kpt` binaries with different versions installed in different paths and older one was taking precedence because of dir ordering in $PATH.

**Comment by aaron-prindle** [comment]
Sorry for the noise, I had a different installation of kpt installed that was being used in the invocation.  The version is correct in kpt, sorry again!
