### ISSUE TITLE
create-subst should throw and error if using v0.4.0 setters or lower

### ISSUE THREAD

**Issue by pwittrock** [GoogleContainerTools/kpt#280]
create-subst only works with v0.5.0 setters or higher, but creates the substitution anyway which won't work

check for v0.4.0 setters and throw and error

**Comment by phanimarupaka** [comment]
This is addressed. In fact, the v1 setters are being deprecated soon and users must use [fix](https://googlecontainertools.github.io/kpt/reference/pkg/fix/) command to migrate setters.
