### ISSUE TITLE
should have a way to migrate setters from v0.4.0 to v0.5.0

### ISSUE THREAD

**Issue by pwittrock** [GoogleContainerTools/kpt#281]
v0.4.0 setters look like this:

     # {"description":"The project ID","type":"","x-kustomize":{"setter":{"name":"project-id","value":"something"}}}

v0.5.0 setters look like this:

    # {"$ref":"#/definitions/io.k8s.cli.setters.project-id"}

with a definition in the Kptfile

write a command to go through and find each old-style setter and convert it to a new style setter

**Comment by mortent** [comment]
@phanimarupaka I know you had some ideas about how we should do this. Can you write up a proposal for this? As we continue to make improvements to setters/substitutions we need to provide tooling so users can migrate and allow us to eventually remove support for old formats (like the v1 setters).

**Comment by phanimarupaka** [comment]
@mortent Sure. Will do.

**Comment by phanimarupaka** [comment]
This has been addressed with the fix feature https://github.com/GoogleContainerTools/kpt/issues/848
