### ISSUE TITLE
correctly merge updates when resource names have changed

### ISSUE THREAD

**Issue by pwittrock** [GoogleContainerTools/kpt#284]
If resource names are changed with substitutions or setters, then the update will not work when merging resources.

We should apply the current setter values to all the inputs before merging them.

**Comment by phanimarupaka** [comment]
@pwittrock what do you mean by resource names. Can you please provide more details or point to an example.

**Comment by pwittrock** [comment]
- Create a package containing a resource with a name substitution
- Get the package and change the name in the local copy via the substitution
- Modify the upstream package
- Update the local copy with --resource-merge, expect the updates to be applied
