### ISSUE TITLE
`kpt` functions do not work on M1 Mac

### ISSUE THREAD

**Issue by Pitta** [GoogleContainerTools/kpt#2874]
### Expected behavior

`kpt fn eval -i list-setters:v0.1.0` to list all setters in directory tree

### Actual behavior

```bash
[RUNNING] "gcr.io/kpt-fn/apply-setters:v0.2.0"
[PASS] "gcr.io/kpt-fn/apply-setters:v0.2.0" in 1.2s
  Results:
    [info] spec.template.spec.containers[1].env[3].value: set field value to "cluster-name-test"
  Stderr:
    "WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested"
```

### Information

kpt version `v1.0.0-beta.13`

### Steps to reproduce the behavior

Try to run any kpt function on an M1 Mac

**Comment by droot** [comment]
@mengqiy @yuwenma we are seeing an increase of issues reported for supporting Mac M1. I think we should be able to compile our Go based functions easily for linux/arm target, but I wonder what is idiomatic way to support the container images across different platforms.

**Comment by Pitta** [comment]
https://docs.docker.com/desktop/mac/apple-silicon/

Detailed here. And i tested this flag manually for running containers on amd64 machine with the flag `--platform linux/amd64` and it ran fine.

I suspect if this is added to the call for docker run, it would solve this until native images are baked in the CI.

**Comment by Pitta** [comment]
I also want to note - this will only get worse if not addressed. Apple doesnt sell intel macs anymore. Multi architecture is the new normal.

**Comment by mikebz** [comment]
Proposal and tradeoffs:
https://github.com/GoogleContainerTools/kpt/pull/2938

**Comment by PatrickChenSe** [comment]
Hi I'm still having the same error when running the kubeval example. 
```
kpt fn eval kubeval-imperative --image gcr.io/kpt-fn/kubeval:v0.3.0 --results-dir /tmp -- strict=true skip_kinds=MyCustom,MyOtherCustom

[RUNNING] "gcr.io/kpt-fn/kubeval:v0.3.0"
[FAIL] "gcr.io/kpt-fn/kubeval:v0.3.0" in 16s
  Results:
    [error] v1/ReplicationController/bob templates: Additional property templates is not allowed
    [error] v1/ReplicationController/bob spec.replicas: Invalid type. Expected: [integer,null], given: string
  Stderr:
    "WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested"
```
Do I need to set anything to make this work?
