### ISSUE TITLE
Setter Types Issues

### ISSUE THREAD

**Issue by trodge** [GoogleContainerTools/kpt#288]
Having trouble using kpt setters to set a string which happens to be a number.

In project-factory I have a setter for "org-id" which should be a string. However, when I try to set it it appears as though kpt now infers type of setters from their values. I have tried creating the setter for org-id both as an integer and as a string and in both cases I get the following error:

```
thomasrodgers@thomasrodgers2:~/Code/kpt-samples$ kpt cfg list-setters project-factory/
Error: json: cannot unmarshal number into Go struct field setter.setter.value of type string
```

This occurs after I run

```
kpt cfg set project-factory org-id "111111111111"
```

**Comment by pwittrock** [comment]
@trodge thanks, I am able to reproduce
