### ISSUE TITLE
kpt fn render exits 0 when apply-replacements function returns error

### ISSUE THREAD

**Issue by natasha41575** [GoogleContainerTools/kpt#2901]
When apply-replacements function returns an error, kpt fn render prints:

```
Package "apply-replacements-error": 
[RUNNING] "gcr.io/kpt-fn/apply-replacements:unstable"
[PASS] "gcr.io/kpt-fn/apply-replacements:unstable" in 1.1s
  Results:
    [error]: nothing selected by Pod.[noVer].[noGrp]/my-po.[noNs]:spec
```

and exits 0. It should say [FAIL] and exit 1.

**Comment by droot** [comment]
Looks like a regression in the latest `kpt fn render` refactoring. I am surprised we don't have a test covering this.

**Comment by natasha41575** [comment]
I don't think this is a regression, running an error case with `kubeval` behaves as expected: 

```
[FAIL] "gcr.io/kpt-fn/kubeval:v0.1.1" in 16.3s
  Results:
    [error] apps/v1/Deployment/nginx-deployment selector: selector is required
    [error] apps/v1/Deployment/nginx-deployment template: template is required
    [error] apps/v1/Deployment/nginx-deployment spec.replicas: Invalid type. Expected: [integer,null], given: string
```

It seems like something about the apply-replacements function itself. I'll have a fix in the next day or so.
