### ISSUE TITLE
make <func-name>-BUILD doesn't work

### ISSUE THREAD

**Issue by mengqiy** [GoogleContainerTools/kpt#2902]
It seems there is an issue with our scripts/docker.sh.

```
$ cd functions/go

$ make apply-setters-BUILD
...
Building image for apply-setters...
../../scripts/go-function-release.sh build curated
../../scripts/docker.sh: line 54: build_args[@]: unbound variable
make[1]: *** [func-build] Error 1
make: *** [apply-setters-BUILD] Error 2
```

This issue exists when running `make <func-name>-BUILD` for any go functions.

**Comment by mengqiy** [comment]
@sdowell This is not urgent. But please fix when you find a chance.

**Comment by sdowell** [comment]
I was not able to reproduce this locally on the tip of master. Could you provide some more information for the environment in which you encountered this error? I expect perhaps this was encountered using an older version of bash

**Comment by mengqiy** [comment]
```
$ bash --version
GNU bash, version 5.1.16(1)-release (x86_64-apple-darwin21.1.0)
```
What version do you have?

**Comment by sdowell** [comment]
I normally run on linux, where I have the following bash version:
```
$ bash --version
GNU bash, version 5.1.8(1)-release (x86_64-pc-linux-gnu)
```

I was however able to reproduce this on my mac, so I'll take a deeper look
