### ISSUE TITLE
`set-namespace` function should read input from package context unless specific args specified

### ISSUE THREAD

**Issue by droot** [GoogleContainerTools/kpt#2973]
### Expected behavior

Running `set-namespace` on a kpt package that has `package context` should succeed and use the input from `data.name` field in the package context.

### Actual behavior

```
$ kpt fn eval -i gcr.io/kpt-fn/set-namespace:unstable --image-pull-policy never
[RUNNING] "gcr.io/kpt-fn/set-namespace:unstable"
[PASS] "gcr.io/kpt-fn/set-namespace:unstable" in 700ms
  Results:
    [error] v1/ConfigMap/function-input: `data.namespace` should not be empty
```

Two things to note here:

- Function actually failed but `kpt fn render` is reporting that it has passed
- function input: it should use the `data.name` for function input

**Comment by yuwenma** [comment]
The latest `unstable` image should work.
https://console.cloud.google.com/gcr/images/kpt-fn/global/set-namespace@sha256:a457b9266764ae42c94b2ecd6690e4fc858295b2c58a7043d9e486697ef8b201/details

**Comment by droot** [comment]
`package-context.yaml` need to be specified as `functionConfig`. Once I did that, it worked, so closing this issue.
