### ISSUE TITLE
"kpt pkg update" with large number of subpackages can trigger Github throttling for clone operations

### ISSUE THREAD

**Issue by bcongdon** [GoogleContainerTools/kpt#2988]
### Information

If you try to run `kpt pkg update` on a package with many (~20+) subpackages that each have upstreams, kpt attempts to clone each of those subpackages in quick succession, resulting in Github throttling the clone operations and the update failing.

Unfortunately, if this happens in the middle of an update, there is no way to resume the operation -- so the next time `kpt pkg update` is run, `kpt` starts from the beginning, and fails partway through.

### Expected behavior
Running `kpt pkg update` on a package with many subpackages throttles the underlying `git clone`, performs exponential backoff/retry in case `git clone` fails, or allows resuming a partly failed update.

### Actual behavior
After ~20 or so clones, Github throttles subsequent requests and the `kpt pkg update` fails.

```
Fetching upstream from https://github.com/GoogleCloudPlatform/blueprints
Error: Failed to execute git command "git ls-remote --heads --tags --refs origin" against repo "https://github.com/GoogleCloudPlatform/blueprints" 

Details:
fatal: unable to access 'https://github.com/GoogleCloudPlatform/blueprints/': Failed to connect to github.com port 443 after 15428 ms: Connection timed out 
```

### Steps to reproduce the behavior
Clone https://github.com/bcongdon/many-subpackages-blueprint-example and attempt to run `kpt pkg update`

This was tested using `1.0.0-beta.13`

**Comment by bcongdon** [comment]
Another alternative would be if kpt cached instances of the same upstream during the whole update. The linked blueprint uses many instances of the same upsteam. It's unlikely that the upstream will change _during_ the update, so perhaps kpt could cache (e.g. using the [existing env variable](https://kpt.dev/reference/cli/pkg/update/?id=env-vars)) upstreams for the lifetime of the update operation

**Comment by mengqiy** [comment]
@bcongdon Thanks for providing steps to reproduce it!
I want to hear more about your use case. Do you have a real world use case that a package has many (~20+) subpackages? Or it's just a experiment?

**Comment by bcongdon** [comment]
Yes, when deploying a resource hierarchy (e.g. 
akin to [the resource hierarchy example](https://github.com/GoogleCloudPlatform/blueprints/tree/main/catalog/hierarchy)), the package we're trying to deploy has several subpackages of the project blueprint in it ([project blueprint](https://github.com/GoogleCloudPlatform/blueprints/tree/main/catalog/project))

We're nearing an upper limit of the number of projects that can be deployed due to this bug.

Perhaps there's a better way of structuring the blueprints that would not result in so many subpackages, I'd appreciate any input

**Comment by mengqiy** [comment]
Thanks for letting us know the use case.
I agree we should optimize it before our customers hit the upper limit.

@droot will look at this when he is back next Monday.

**Comment by charleshansen** [comment]
To add some context, the real world use case we are trying to build right now will have the following minimum subpackages:
- 1 resource hierarchy
- 8 projects
- 3-6 VPCs
- 6-12 subnets
- 3-12 firewalls
- 1-2 log-exports

That full blueprint will hit the github limit every time. We can't run this as an authenticated github user either, which would be the obvious workaround. Our current workaround will be to manually vendorize the subpackages ourselves so that `kpt` no longer manages them. This has some drawbacks (extra work for us, plus `kpt pkg update` no longer gets updates), but should at least deploy what we need.

**Comment by droot** [comment]
@bharathkkb will be taking a look at it next week.

Thanks Bharath.
