### ISSUE TITLE
User friendly `--type` flag behavior

### ISSUE THREAD

**Issue by yuwenma** [GoogleContainerTools/kpt#3014]
### Current behavior 
`--type` flag is defined in `kpt fn eval`, default to "mutator". It has autocompletion to suggest "mutator" and "validator". It has two functionalities
1. Used with `--save` flag to store the function to the corresponding Kptfile `pipeline.mutators` or `pipeline.validators` list
2. Used with `--keywords` or `--image` autocompletion to filter suggested functions by type.
  

### Problems
- Problem 1. 
`kpt fn eval` already has too many flags that sort of correlate to each other. `--keywords`, `--type`, `--exec`, `--image`. The usage of `--type` is determined and determines other behavior. I don't want to give users too much burden to understand all of these.  it may be even not a good idea to use --type flag.

- Problem 2. 
`--type` only really matters when used with "--save". At which point "mutator" is a valid default. But when used as a filter to functions, I'm not quite confident this default value is the right filter. 

### Proposal
-  `--type` is default to "" (rather than "mutator") with autocompletion enabled to suggest "validator" and "mutator".
- Matching functions by type accepts the "--type" to be empty string "", in such case suggest all functions. 
- Only when "--save" is true, will kpt validate "--type". It accepts value `["", "mutator", "validator"]`, and reassign `""` to `"mutator"`.

Pros:
The advantage is that users are guided to only care the `--type` when they want to write function to Kptfile `pipeline.validators`. All other cases the `--type` is a nice to have thing.  
Cons:
these assumptions might confuse users.

**Comment by yuwenma** [comment]
This is from the previous PR discussion https://github.com/GoogleContainerTools/kpt/pull/2956#discussion_r851551772
CC @mengqiy @droot

**Comment by mengqiy** [comment]
>--type is default to "" (rather than "mutator") with autocompletion enabled to suggest "validator" and "mutator".
Matching functions by type accepts the "--type" to be empty string "", in such case suggest all functions.

These 2 make sense.

>Only when "--save" is true, will kpt validate "--type". It accepts value ["", "mutator", "validator"], and reassign "" to "mutator".

IMO when `--save` is specified, we should require users to set `--type` explicitly. Defaulting it to `mutator` when it's empty might be a problematic defaulting.

**Comment by yuwenma** [comment]
> > --type is default to "" (rather than "mutator") with autocompletion enabled to suggest "validator" and "mutator".
> > Matching functions by type accepts the "--type" to be empty string "", in such case suggest all functions.
> 
> These 2 make sense.
> 
> > Only when "--save" is true, will kpt validate "--type". It accepts value ["", "mutator", "validator"], and reassign "" to "mutator".
> 
> IMO when `--save` is specified, we should require users to set `--type` explicitly. Defaulting it to `mutator` when it's empty might be a problematic defaulting.

You are right! I'll force user providing `--type` if `--save` is given. Thanks.

**Comment by yuwenma** [comment]
Fixed.
