### ISSUE TITLE
Kpt live shouldn't report resources are created when package has 0 resources

### ISSUE THREAD

**Issue by nan-yu** [GoogleContainerTools/kpt#310]
When running `kpt live preview <package-dir>` on a package that has no resources, the output is
```
configmap/test-inventory created
all resources have been applied
prune completed
```

It would be better to count the resources, and improve the output message something like "no resources found".

**Comment by mortent** [comment]
I think this points to a slightly bigger issue that preview doesn't make it clear enough that it isn't actually performing these operations. I have a PR that partly addresses this by printing the actual count of resources that have been applied/pruned (https://github.com/kubernetes-sigs/cli-utils/pull/77), but I think we still need to make it clearer in the output that it is just a preview.

@phanimarupaka can you take a look at this one?

**Comment by phanimarupaka** [comment]
@mortent Agree. Working on it

**Comment by phanimarupaka** [comment]
This issue has been resolved by https://github.com/kubernetes-sigs/cli-utils/pull/79
