### ISSUE TITLE
Package version needs to be udpated

### ISSUE THREAD

**Issue by mengqiy** [GoogleContainerTools/kpt#311]
> kpt pkg get $SRC_REPO/package-examples/helloworld-set@v0.1.0 helloworld

Version needs to be updated to v0.3.0 in 
https://googlecontainertools.github.io/kpt/quick-start-guides/consumer-quick-start-guide.html

**Comment by mortent** [comment]
@phanimarupaka Since you are already looking at the quick start guides and examples, could you make a fix for this?

**Comment by phanimarupaka** [comment]
@mortent sure

**Comment by phanimarupaka** [comment]
This has been fixed as part of this PR https://github.com/GoogleContainerTools/kpt/pull/317
