### ISSUE TITLE
Support Starlark in kpt fn

### ISSUE THREAD

**Issue by mengqiy** [GoogleContainerTools/kpt#315]
We can probably natively support `Starlark` as a **scripting** language in `kpt fn`.
We can embed the Starlark runtime in kpt so that it doesn't need images and docker engine in this way.

This idea comes from @pwittrock

**Comment by pwittrock** [comment]
Thanks for the issue!  Effectively this would add a second function runtime:

- containers (used today)
- starlark scripts (proposed)

Using Starlark as an embedded scripting language in go programs seems to be a common trend -- e.g. Isopod, QRI, ytt are some examples of golang programs that do this.

We could probably enable more powerful setters by allowing the triggering starlark post-processing scripts in response to set.

The key point here is that Starlark would not be a configuration language, but rather as a function runtime for programmatically applying a transformation to some configuration.

**Comment by pwittrock** [comment]
https://github.com/kubernetes-sigs/kustomize/pull/2267
