### ISSUE TITLE
Update kpt roadmaps

### ISSUE THREAD

**Issue by bgrant0607** [GoogleContainerTools/kpt#3156]
I gutted the kpt roadmap: https://github.com/GoogleContainerTools/kpt/blob/main/docs/ROADMAP.md

We'll need to rebuild it once we get user feedback on package orchestration.

The porch roadmap needs to be prioritized:
https://github.com/GoogleContainerTools/kpt/blob/main/porch/docs/porch-roadmap.md

We will need to create a UI roadmap. For starters, there are quite a few features from the prototype UI that we don't have yet: https://www.youtube.com/watch?v=d_iV22_6nAM

The roadmap should be driven by UX, for specific scenarios/CUJs: CUJ UX drives UI drives porch drives kpt.

**Comment by bgrant0607** [comment]
For backstage+porch, the next features I'd like to see, if they don't already exist, are:
1. Edits
2. Updates/upgrades (for individual downstream packages)
3. Restore

If/when the features do exist, we need to document them, such as by extending the guides or creating new guides.

**Comment by bgrant0607** [comment]
Actually, let's move the roadmap from markdown to a project. I don't want to send PRs to change it, and I'd like it to be easy to link to issues and update with the current status.

**Comment by droot** [comment]
Sounds good. We can re-purpose existing project https://github.com/GoogleContainerTools/kpt/projects/14 for this because this project hasn't been used in a while (I can clean this up). Or we can create a new project. Let me know.

**Comment by droot** [comment]
I cleaned up the existing project  https://github.com/GoogleContainerTools/kpt/projects/14. Feel free to use it or create new project, but I like the idea of tracking roadmap items using project.

**Comment by mortent** [comment]
I will create issues in the project for the items in the porch roadmap.

We should leverage the project to provide status on what is being worked on and it allows us to keep a roughly stack-ranked backlog. Not sure if we should put everything in one project or try to use multiple for different areas. Seems simplest to start with one and rely on the labels to focus on specific areas.
