### ISSUE TITLE
Fix site landing page for mobile

### ISSUE THREAD

**Issue by bgrant0607** [GoogleContainerTools/kpt#3178]
#3165 put the "Why kpt" and "Get started" buttons next to the embedded video. It looks better on my laptop.

However, on my Android phone, the buttons are squeezed off the page, with just "Why" and "Get" appearing at the edge.

We probably need to play with the layout more. For example:

K          text
buttons video

or

K  buttons
text
video

cc @yuwenma

**Comment by yuwenma** [comment]
Approved on https://responsivedesignchecker.com/checker.php?url=https%3A%2F%2Fkpt.dev&width=375&height=667

The "Why kpt" and "Get Started" should fit into all listed computer, tablet and phones. 
This is the Android pixel look

 
<img width="261" alt="Screen Shot 2022-05-14 at 17 18 21" src="https://user-images.githubusercontent.com/5606098/168452268-82864c00-653d-4ef0-9b55-e3545d02ef7d.png">
