### ISSUE TITLE
Support for composite setters when composing packages

### ISSUE THREAD

**Issue by pwittrock** [GoogleContainerTools/kpt#325]
When composing packages, it will be necessary to compose the setters of the included packages as higher level setters in the composite.

Following are scenarios that need to be supported:

- Directly expose a single setter in an included package
  - e.g. if Package A includes package B (setter project-id), then package A has setter project-id which invokes package B's project-id setter
  - Allow the setter to be rename -- e.g. expose project-id from B as projectID in A
- Directly expose multiple setters from the included packages under a new name
  - e.g. if package A includes packages C (setter project-id) and D (setter projectID), then A should expose setter project-id which maps to project-id in package C and projectID in package D -- setting each
- Map the setters of included packages to new names
  - e.g. if Package A includes package B (setter image) multiples times (B1, B2, B3), in A create a setter for each instance of B with a different name (image-1, image-2, image-3)
- Perform substitutions in composite packages from renamed setters
  - e.g. if Package A includes package B (setter image, substitution img), create setter imgA in package A which sets image in B, and performs the substitution img in B

**Comment by phanimarupaka** [comment]
We will not be implementing composite setters. Instead we will be supporting this functionality by setter aliases.
