### ISSUE TITLE
WASM as a KRM function runtime

### ISSUE THREAD

**Issue by mengqiy** [GoogleContainerTools/kpt#3299]
WASM can be potentially used as a KRM function runtime and KRM function packaging method.
Exploration in the area is in progress. More details will be updated in this thread.

**Comment by mengqiy** [comment]
wasm function runtime is implemented in https://github.com/GoogleContainerTools/kpt/pull/3450.

**Comment by droot** [comment]
We can close this issue since WASM support was added in https://github.com/GoogleContainerTools/kpt/pull/3450. 

I opened another `good first issue` for publishing end user docs for this feature. https://github.com/GoogleContainerTools/kpt/issues/3755
