### ISSUE TITLE
Rancher Desktop support

### ISSUE THREAD

**Issue by vfarcic** [GoogleContainerTools/kpt#3317]
### Describe your problem

I'd love to use kpt, but it currently supports only Docker and Postman while I'm using Rancher Desktop (nerdctl, containerd). Would it be possible to add the support for nerdctl?

**Comment by vfarcic** [comment]
I already tried that (docker alias to nerdctl).

**Comment by mengqiy** [comment]
Sorry for the late response, I was OOO for a couple of days.

I will try to add the support for nerdctl.

> I already tried that (docker alias to nerdctl).

@vfarcic Is there any difference that worth mentioning here?

**Comment by vfarcic** [comment]
My best guess is that kpt is going directly for Docker socket or something like that. I didn't go through the code (yet) so I'm likely wrong. In any case, making it work with `nerdctl` or with `docker` alias set to `nerdctl` would be awesome.

**Comment by mengqiy** [comment]
@vfarcic We have added supporting for nerdctl in https://github.com/GoogleContainerTools/kpt/pull/3362. It has not been released yet but is available from HEAD of main.

**Comment by droot** [comment]
As per @mengqiy comment above, support for `nerdctl` has been added, so closing this.
