### ISSUE TITLE
Support for auto setter for gcloud in the substitution format

### ISSUE THREAD

**Issue by elfinhe** [GoogleContainerTools/kpt#333]
Context - I am working on converting the KRMs below to use the substitution format. 
https://github.com/GoogleCloudPlatform/anthos-service-mesh-packages/blob/new-variables/asm/cluster/istio-operator.yaml

Some of our logics depend on auto setters such as `gcloud.project.projectNumber` and `gcloud.core.project`. So when running `kpt pkg get ...`, those setters will replace them with the values in their gcloud environment.

Issue - we are not able to use auto setters such as gcloud.core.project in the new substitution format. We need to consider adding support for the auto setters.

**Comment by elfinhe** [comment]
@pwittrock

**Comment by elfinhe** [comment]
I want we will need those auto setters:

- `gcloud.core.project` to be project ID
- `gcloud.project.projectNumber` to be project Number, similar to [this one](https://github.com/GoogleContainerTools/kpt/pull/260)
- `gcloud.compute.zone` to be the current default zone, optional

**Comment by phanimarupaka** [comment]
@elfinhe Thanks. Working on it.

**Comment by pwittrock** [comment]
@elfinhe I believe this is fixed on head, can you confirm?

**Comment by elfinhe** [comment]
Thanks so much @phanimarupaka and @pwittrock, will verify.

**Comment by elfinhe** [comment]
yes, it works!
thanks. ; )
