### ISSUE TITLE
Deleting and recreating packagerevisions with same revision can lead to incorrect task list

### ISSUE THREAD

**Issue by mortent** [GoogleContainerTools/kpt#3331]
Currently the task list of a packagerevision is encoded as part of the commit messages in git. Porch reconstructs the list when reading a package from git by looking back at the commit history and identifying relevant commits by using the package name and the package revision. This is not sufficient if a packagerevision is approved (and therefore merged into the main branch) and then part of the commit history if a new packagerevision reuses the revision.

Once we address https://github.com/GoogleContainerTools/kpt/issues/3329, we will know that every packagerevision must start with either a CloneTask or an InitTask, and no packagerevision can have more than one of either. Thus, we can address this issue by only walking backwards through the commit log until we find the CloneTask or InitTask for the packagerevision.

**Comment by natasha41575** [comment]
> Porch reconstructs the list when reading a package from git by looking back at the commit history and identifying relevant commits by using the package name and the package revision. This is not sufficient if a packagerevision is approved (and therefore merged into the main branch) and then part of the commit history if a new packagerevision reuses the revision.

Do you mind providing some more details about what specifically goes wrong in the case described in the last sentence?

**Comment by mortent** [comment]
@natasha41575 The steps for reproducing the problem is to:
* Create a packagerevision with a specific name and revision (name `foo` and revision `v1`)
* Approve the packagerevision.
* Delete the packagerevision.
* Create a new packagerevision and reuse the same name and revision as the previous one (name `foo` and revision `v1`).

Fetching the new packagerevision will now have a task list that includes the tasks from both the new version of the packagerevision as well as the old deleted one (since the commits exists in the main branch).
