### ISSUE TITLE
Come up with a short, descriptive tag line for the site

### ISSUE THREAD

**Issue by bgrant0607** [GoogleContainerTools/kpt#3356]
The current description is considered [by some](https://www.youtube.com/watch?v=Wavigyq7NdQ) to be long and academic.

A shorter, pithier but somewhat descriptive tag line for the landing page and repo description would be useful. We can put the longer, more accurate description deeper in the docs.

Kustomize's tag line was "template-free customization".

What should kpt's be?
* Configuration as Data
* WYSIWYG config
* Automate your configuration
* API-driven configuration
* KRM-native configuration
* KRM Platform Toolkit
Other ideas???

cc @justinsb @selfmanagingresource @droot @mortent

**Comment by selfmanagingresource** [comment]
Well, he's not wrong - it is a bit long! Another question is whether we should mentioned GitOps in the short-tag line or will it be too much? 

A few thoughts:
- Of the ones listed above I think something akin to "automate your configuration for scale" is closest. WYSIWYG describes more the result you get with the toolkit. We've leaned in a lot into WYSIWYG for discussing what we enable that is challenging today, but other projects don't really focus on that in their tag lines.
- KRM Platform Toolkit has the benefit of actually explaining what KPT stands for.
- We can go all in on GitOps. Kubernetes GitOps Automation Toolkit

**Comment by justinsb** [comment]
How about: "Kubernetes-first packages".  To me, the core idea is that we're embracing kubernetes ideas and kubernetes objects and kubernetes schemas.  We're different from the tooling that tries to build an abstraction layer that hides kubernetes - because we've found that these abstraction layers can be counterproductive.

**Comment by bgrant0607** [comment]
Along with the tag line, we should explain the value prop. We tried to explain what CaD is and what the motivation was, but that's not the same as the user value, by role: platform team, app ops, app dev.

**Comment by bgrant0607** [comment]
More ideas:
* Full-lifecycle configuration automation
* Day 0 to N configuration automation
* Operate on your configuration
* Generate, transform, validate
* The API for configuration
* Control and data plane for configuration
* Accelerate configuration management

I don't think we want users to think about kpt as just another package tool.

**Comment by bgrant0607** [comment]
Another:
* The Configuration Automation Platform

Thinking about the GitOps angle:
* The frontend for GitOps
* The GitOps Platform

**Comment by bgrant0607** [comment]
More:
* Simplify, accelerate, and scale configuration management and governance
* Low-code configuration management
* Transform configuration management

**Comment by selfmanagingresource** [comment]
I really like the GitOps platform. It's simple and those interested in our automation should understand GitOps and its challenges at least to some extent. 

Otherwise:

Simplify, accelerate, and scale configuration management and governance
Low-code configuration management

Do resonate with me too!

**Comment by bgrant0607** [comment]
After thinking about it more, with "GitOps" in the tag line, I think it's important to express that it's a layer above GitOps. We do have Config Sync, but I don't want to preclude Flux or ArgoCD. "The GitOps Platform" also sounds similar to Flux's GitOps Toolkit. Probably it would need to be "The GitOps <something> Platform". Or, another UI-centric one would be ClickOps for GitOps. 

We could also do this by first brainstorming what words we think are important to include, in different categories, such as who, what, how, when, where, why, superlatives.

**Comment by bgrant0607** [comment]
Thinking about this more, a pithy phrase is only going to be able to answer one question. If I were a prospective user, I'd want it to concretely answer "what" (or maybe "for what") rather than a more marketing-like slogan that answers some level of the 5 "whys", or "how", or a broader "what". Probably we should answer all the questions on the FAQ, and link to that.

In terms of a concrete "what", the kpt toolchain does quite a few things, most of which can be done by other tools. The thing that seems most unique is the editing, as @selfmanagingresource suggested. The adjective / adverb / verb we choose depends on whether we want to convey power or simplicity. To me, "automate" suggests both, potentially.

So how about:
Automate Kubernetes Configuration Editing

A follow-on mission-sentence-style sentence, which would be longer, could address multiple questions. 

The current statement is:

> kpt is a package-centric toolchain that enables a WYSIWYG configuration authoring, 
automation, and delivery experience, which simplifies managing Kubernetes platforms and KRM-driven infrastructure at scale by manipulating declarative Configuration as Data, separated from the code that transforms it.

What: package-centric toolchain that enables a WYSIWYG configuration authoring, automation, and delivery experience
Why: simplifies managing Kubernetes platforms and KRM-driven infrastructure at scale
How: by manipulating declarative Configuration as Data, separated from the code that transforms it

That's not terrible for the FAQ, but there are lots of terms that may not be universally understood (e.g., authoring, delivery) or are vague (e.g., automation, managing, platforms), two jargon acronyms (WYSIWYG, KRM), and one jargon phrase (Configuration as Data). So we'd want to break this down to explain what it means. A little is covered in the FAQ (https://kpt.dev/faq/?id=how-is-kpt-different-from-other-solutions), but not as explicitly as it could.

**Comment by selfmanagingresource** [comment]
This gets my vote. Not sure about others.

**Comment by bgrant0607** [comment]
Went with "Automate Kubernetes Configuration Editing".
