### ISSUE TITLE
kpt fn sink doesn't support prune

### ISSUE THREAD

**Issue by morgante** [GoogleContainerTools/kpt#337]
I am attempting to run a function which selects a subset of resources and prunes the rest:

Function code:https://github.com/forseti-security/policy-library/blob/experimental/policy-bundling/bundling/func/src/select_policies.ts#L34

Command used to test:
```
kpt fn source ../sample |
node dist/select_policies_run.js -d bundle=dev |
kpt fn sink ../sample
```

Note that if I sink to a *different* directory then the resources are correctly deleted. How can I have `kpt fn sink` prune existing resources from the target directory that are not selected?

**Comment by frankfarzan** [comment]
Can you confirm, that the resources are missing from the output of select_policies function?

```
kpt fn source ../sample |
node dist/select_policies_run.js -d bundle=dev |
less
```

**Comment by morgante** [comment]
```$ kpt fn source ../sample |
node dist/select_policies_run.js -d bundle=prod |
more
apiVersion: v1
kind: List
items:
- apiVersion: anthos.cft.dev/v1alpha1
  kind: Team
  metadata:
    name: payments
    labels:
      remove: 'yes'
    annotations:
      config.kubernetes.io/index: '0'
      config.kubernetes.io/path: team.yaml
  spec:
    roles:
    - role: sre
      users:
      - jane@clearify.co
    - groups:
      - payments-developers@clearify.co
      role: developer
      users:
      - basic@clearify.co
- apiVersion: v1
  kind: Namespace
  metadata:
    name: payments-prod
    annotations:
      env: prod
      config.kubernetes.io/index: '0'
      config.kubernetes.io/path: namespace_payments-prod.yaml
    labels:
      color: orange
      hello: prod
      found_env: prod
      key: v1/Namespace//payments-prod
      remove: 'yes'
```

**Comment by frankfarzan** [comment]
@pwittrock This seems to be a bug in `kpt sink`.

**Comment by pwittrock** [comment]
This is a known limitation.

In order to prune resources kpt needs to know which resources it read, and these aren't propagated as part of function spec.  `kpt fn run` is able to prune because it knows which resources were read, and is able to prune those files when writing output.

The kpt function spec would need to be updated with a field containing a list of files, and kpt sink would need to prune based on this.  The kpt functions themselves would need to propagate this list from their input to their output.

@frankfarzan

**Comment by morgante** [comment]
Thanks for the explanation, I got this working with `kpt fn`.

**Comment by seh** [comment]
> I got this working with `kpt fn`.

@morgante, can you elaborate on how you got it working? @pwittrock says that _kpt fn run_ can prune, because it can see the full pipeline. Did you wind up using _kpt fn run_ instead of _kpt source_ and _kpt sink_?

**Comment by morgante** [comment]
@seh Indeed, I switched to `run`.

**Comment by seh** [comment]
Just because I'm so new to this tool, are you willing to share a little more of your configuration to explain how you integrated use of _kpt fn run_? Do you run it manually on the command line? Are you using declarative invocation?

**Comment by morgante** [comment]
Yeah I just executed `kpt fn run` on the command line.
