### ISSUE TITLE
Shouldn't have to kill porch to get it to reload secrets

### ISSUE THREAD

**Issue by bgrant0607** [GoogleContainerTools/kpt#3406]
My github access token expired, so I updated my repo secrets. Porch didn't seem to notice until I killed its pod, but I only waited for about a minute.

**Comment by mortent** [comment]
Yeah, porch doesn't currently refetch the auth credentials even if the connection to the repository fails. I have a PR that fixes a similar problem with WI (https://github.com/GoogleContainerTools/kpt/pull/3410). I will do a follow-up to address this issue as well.
