### ISSUE TITLE
kpt repo package-examples directory can't be registered with porch

### ISSUE THREAD

**Issue by bgrant0607** [GoogleContainerTools/kpt#3407]
```
kpt alpha rpkg list
Error: failed to load packages from tag "refs/tags/v0.33.0": object not found
```

Probably because the release version tags have a similar form to the kpt package version tags. I guess this would be for a package named the empty string?

Porch should probably ignore these. It should also gracefully recover. 

We may want to uniquify the kpt version tag format as well.

cc @droot

**Comment by bgrant0607** [comment]
I'm fine with moving these packages to kpt-samples as a temporary workaround

**Comment by droot** [comment]
> I'm fine with moving these packages to kpt-samples as a temporary workaround

Yes, I will move the packages under `kpt-samples` till we solve the edges cases in porch.

**Comment by droot** [comment]
So copied over the three packages `ingress-nginx`, `cert-manager-basic`, `ghost` from kpt repo to [kpt-samples repo](https://github.com/GoogleContainerTools/kpt-samples).

I have also tagged them with the same versions that we had the kpt repo. We will be using `kpt-samples` repo the development of packages.

**Comment by natasha41575** [comment]
Fixed by https://github.com/GoogleContainerTools/kpt/issues/3407
