### ISSUE TITLE
kpt-samples don't work with porch

### ISSUE THREAD

**Issue by natasha41575** [GoogleContainerTools/kpt#3419]
Cloning https://github.com/GoogleContainerTools/kpt-samples/tree/cert-manager-basic/v1/cert-manager-basic fails with an error about an illegal file name

Cloning https://github.com/GoogleContainerTools/kpt-samples/tree/main/ghost fails with an issue with running fn-render

**Comment by natasha41575** [comment]
cc @ChristopherFry

**Comment by natasha41575** [comment]
https://github.com/kubernetes-sigs/kustomize/pull/4729 should fix the issue with cert-manager-basic.

**Comment by natasha41575** [comment]
An update with the ghost package example - the problem seems to go away if you change set-namespace to v0.4.1 (the version that's built into porch).

**Comment by natasha41575** [comment]
Per https://github.com/GoogleContainerTools/kpt/pull/3421#issuecomment-1199844216, the last thing we need to do to make the ghost package work is build v0.3.4 of the set-namespace function into porch.

**Comment by natasha41575** [comment]
Copying @ChristopherFry's comment from https://github.com/GoogleContainerTools/kpt/pull/3421#issuecomment-1200076493:

> @natasha41575 re: set-namespace function, we should include v0.3.4 as builtin as well since we will be consuming ghost package with porch pretty heavily in coming days. @mengqiy can help you with the instructions or make a PR.
> 
> Quick thought. Instead of adding v0.3.4 as a buildiin function, should we update the set-namespace function so we can use the latest with the ghost package?

@yuwenma @droot Do you know how difficult that would be?

**Comment by yuwenma** [comment]
Should be easy to do because the workflow is already there so it's just a configuration thing (and adding the dependencies) :  Porch maps functions by versions. As long as the version is built into porch, it can be found and used. 

See https://github.com/GoogleContainerTools/kpt/blob/main/porch/pkg/kpt/internal/functions.go#L21

**Comment by ChristopherFry** [comment]
I am able to clone the `ghost` package now, however I am still seeing the same error as before while cloning the `cert-manager-basic` package.

```
> kpt alpha rpkg get | grep cert-manager
kpt-samples-1db3883c5d61deef6b5ebcd99a8f6dba45a75d56               cert-manager-basic           main       false    Published   kpt-samples
kpt-samples-3eb5e2c814673b9d21a3d5a18b903e8212a4a679               cert-manager-basic           v0         false    Published   kpt-samples
kpt-samples-97ce90db33dd48783f3712dcc88feb1eccdab249               cert-manager-basic           v1         true     Published   kpt-samples

> kpt alpha rpkg clone kpt-samples-97ce90db33dd48783f3712dcc88feb1eccdab249 kpt-samples-blueprint1 -n default --repository application-blueprints
Error: Internal error occurred: illegal name 'role-cert-manager-cainjector:leaderelection.yaml' in file creation 
```

**Comment by natasha41575** [comment]
Ah I closed this too soon, we need to update the kyaml dependency in porch to pick up the fix. I will do that shortly.

**Comment by natasha41575** [comment]
Please feel free to try out the cert-manager-basic package with the change in https://github.com/GoogleContainerTools/kpt/pull/3437.

**Comment by ChristopherFry** [comment]
> Please feel free to try out the cert-manager-basic package with the change in https://github.com/GoogleContainerTools/kpt/pull/3437.

Confirming I can successfully clone the `cert-manager-basic` package with the changes in this pull request. Thanks!
