### ISSUE TITLE
Newer podman is needed to stabilize the CI

### ISSUE THREAD

**Issue by mengqiy** [GoogleContainerTools/kpt#3435]
Podman CI sometimes fails with the following error:

```
Error: error attaching to container 4a88c6c75919307675b210c45a5c1a61cda84cfc23d31047f238bedf885cc02a: read unixpacket @->/proc/self/fd/14/attach: read: connection reset by peer\"\n  Exit code: 126
```

The issue has been fixed in pod v4.2.0+: https://github.com/containers/podman/pull/14109

The podman version we are using now is 3.4.2 and it is installed on the base image in the GitHub Action: https://github.com/actions/virtual-environments/blob/ubuntu20/20220724.1/images/linux/Ubuntu2004-Readme.md#tools

We can try to upgrade it podman to v4.2.0+ if this test becomes very flaky. Otherwise, we can wait for GitHub Action to upgrade it for us.

cc: @mortent

**Comment by mortent** [comment]
We only see very occasional flakes, so I think we can just wait for GitHub Action to do the upgrade.

**Comment by mortent** [comment]
I haven't seen this happen in a while, so closing this issue.
