### ISSUE TITLE
Porch: ssh auth support

### ISSUE THREAD

**Issue by johnbelamaric** [GoogleContainerTools/kpt#3440]
### Describe your problem

When using Porch, I can register a repository with basic auth or workload identity. The basic auth can be used with GitHub personal access tokens. However, those tokens are highly priviliged - so much so that for my testing I created a new, separate GitHub user.

Instead, if we can support ssh auth, then I should be able to use a [deploy key](https://docs.github.com/en/developers/overview/managing-deploy-keys#deploy-keys), which is scoped to an individual repository.

Not a blocker at this time but will be needed as we move towards something that folks could use in prod.

**Comment by mortent** [comment]
We do have a broader issue about supporting additional auth schemes for working with git providers: https://github.com/GoogleContainerTools/kpt/issues/3232

**Comment by johnbelamaric** [comment]
Duplicate
