### ISSUE TITLE
`pkg get` doesn't work with Azure DevOps

### ISSUE THREAD

**Issue by nadworny** [GoogleContainerTools/kpt#3479]
### Expected behavior

Getting package from Azure DevOps is working.

### Actual behavior

When invoking:
`kpt pkg get https://dev.azure.com/your_private_organization/your_project/_git/repo_name/kpt_dir@main`

I'm getting the following error:
```
Package "kpt":
Fetching https://dev.azure.com/your_private_organization/your_project/@main
Error: Repository "https://dev.azure.com/your_private_organization/your_project/" not found.

Details:
fatal: repository 'https://dev.azure.com/your_private_organization/your_project/' not found 
``` 

### Information

kpt version: 1.0.0-beta.19

### Steps to reproduce the behavior

Create a sample repository in Azure Devops, push a kpt package with default values, i.e. `kpt pkg init awesomeapp` and try to get it.

**Comment by nadworny** [comment]
I guess not so many devs using Azure DevOps here? 😉 

Maybe at least some guidance if that's even possible to implement and if yes, where to start? 😄 This is the only blocker for us to start using kpt. The rest works wonderfully.

**Comment by stoetti** [comment]
+1 for us.

We had the same issue when introducing fluxcd as gitops-controller. There we had the option to use a different git-library (libgit2) that supports Azure DevOps.
