### ISSUE TITLE
cryptic error messages for auto project number setters when using expired gcloud creds.

### ISSUE THREAD

**Issue by elfinhe** [GoogleContainerTools/kpt#350]
When gcloud credentials are expired and i’m trying to follow the setup guide, i get this:

```
$ kpt pkg get https://github.com/GoogleCloudPlatform/anthos-service-mesh-packages.git/asm .

fetching package /asm from https://github.com/GoogleCloudPlatform/anthos-service-mesh-packages to asm
Error: failed to get project number for facilities-cloud-api-demo: exit status 1
```

which means when creds are expired, the[ auto setters for project number](https://github.com/GoogleContainerTools/kpt/pull/260) won't work. Also it does not give helpful message to understand why it fails.

**Comment by pwittrock** [comment]
Opened: #419
