### ISSUE TITLE
`kpt live apply` hangs

### ISSUE THREAD

**Issue by BrianPi** [GoogleContainerTools/kpt#351]
When entering the `kpt live apply` command, the terminal hangs, instead of informing you that the command requires a directory to execute.

**Comment by seans3** [comment]
@BrianPi Please put the version: `kpt version`. I am unable to reproduce this with version `v0.11.0`, which is the latest built version. To retrieve the latest version:

`gsutil ls gs://kpt-dev/latest/...`

**Comment by BrianPi** [comment]
Yes, sorry, I was still on kpt v0.8.0
