### ISSUE TITLE
Don't write unmodified files from setters

### ISSUE THREAD

**Issue by pwittrock** [GoogleContainerTools/kpt#352]
Currently setters write back all the resources they read

**Don't write files which have no modified resources**

- Use ByteReader instead of ByteReadWriter from setters
- When applying a setter to a resource, add the filename to a set
- After applying all setters, remove all resources from the list that were not read from a file in the set
- Write back using ByteWriter

**Comment by phanimarupaka** [comment]
@pwittrock Working on it.
