### ISSUE TITLE
porch-server regression in v0.0.9

### ISSUE THREAD

**Issue by yuwenma** [GoogleContainerTools/kpt#3523]
I installed the latest Porch released v0.0.9 to install Porch in my cluster. After using `kpt alpha live apply` to deploy all resources, I can no longer see the `repositories` in the api-resources, Porch UI also gives 404 error about not finding repositories.

See logs
```bash
yuwenma@yuwenma-macbookpro4 ~/config/catalyst/porch-installation2 % kubectl api-resources | grep porch
I0830 22:05:35.878838   64752 request.go:665] Waited for 1.038812103s due to client-side throttling, not priority and fairness, request: GET:https://35.202.13.102/apis/recaptchaenterprise.cnrm.cloud.google.com/v1beta1?timeout=32s
remoterootsyncsets                                   config.porch.kpt.dev/v1alpha1                        true         RemoteRootSyncSet
rootsyncsets                                         config.porch.kpt.dev/v1alpha1                        true         RootSyncSet
workloadidentitybindings                             config.porch.kpt.dev/v1alpha1                        true         WorkloadIdentityBinding
functions                                            porch.kpt.dev/v1alpha1                               true         Function
packagerevisionresources                             porch.kpt.dev/v1alpha1                               true         PackageRevisionResources
packagerevisions                                     porch.kpt.dev/v1alpha1                               true         PackageRevision
```

Porch UI 
<img width="1427" alt="Screen Shot 2022-08-30 at 22 08 21" src="https://user-images.githubusercontent.com/5606098/187597036-10820f6b-e8af-40df-96d1-e177a560e8e5.png">

cc @mortent @justinsb

**Comment by yuwenma** [comment]
Root cause: I missed the repositories CRD in the porch package.

Some more findings about the v0.0.9 package:

- The package still refers to the old porch image v0.0.8 in `2-function-runner.yaml` `3-porch-server.yaml` `9-controllers.yaml`
- The package does not contain CRD added in the [porch/controllers/config/crd/bases/config.porch.kpt.dev_workloadidentitybindings.yaml](https://github.com/GoogleContainerTools/kpt/blob/main/porch/controllers/config/crd/bases/config.porch.kpt.dev_workloadidentitybindings.yaml)

**Comment by mortent** [comment]
@yuwenma How did you fetch and install the v0.0.9 package? The configuration package that we publish as part of the release (https://github.com/GoogleContainerTools/kpt/releases/tag/porch%2Fv0.0.9) seems to be correct as far as I can tell. It contains all the CRDs and refers to the v0.0.9 images.

**Comment by yuwenma** [comment]
@mortent Yes, I downloaded the [deploy-blueprint.tar.gz from porch/v0.0.9](https://github.com/GoogleContainerTools/kpt/releases/download/porch%2Fv0.0.9/deployment-blueprint.tar.gz) , untar the file. And the 3 files are using v0.0.8 tag as their image.
- gcr.io/kpt-dev/porch-server:v0.0.8
- gcr.io/kpt-dev/porch-function-runner:v0.0.8
- gcr.io/kpt-dev/porch-controllers:v0.0.8

**Comment by yuwenma** [comment]
@mortent you are right. My local setup seems to be polluted. The release is good. 

What's your insights about the other two issues?

**Comment by mortent** [comment]
Which issues are you referring to? As far as I can tell, the WorkloadIdentityBinding CRD is in the package and the versions are correct. The repository CRD is defined in a different place than the CRD for the controllers, but this is by design since the repository CRD is part of the core porch API, while the controllers are (currently at least) more similar to add-ons.

**Comment by yuwenma** [comment]
Gotcha, and thanks for the confirmation. Close this issue.
