### ISSUE TITLE
statically link kpt releases

### ISSUE THREAD

**Issue by jsravn** [GoogleContainerTools/kpt#3524]
### Describe your problem

Pre 1.x kpt binaries used to be statically linked, similar to other k8s CLI tools (helm, kubectl, etc.). Now it seems to be dynamically linked, so breaks on certain systems (NixOS being a notable one).

I think it makes sense for pre-built binaries to be static. WDYT?

```sh
$ curl -LO https://github.com/GoogleContainerTools/kpt/releases/download/v1.0.0-beta.20/kpt_linux_amd64
$ file kpt_linux_amd64             
kpt_linux_amd64: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=0bf72bd5373d686750b3c84c47f8d51035397d8a, for GNU/Linux 3.2.0, stripped
```

```sh
$ curl -LO https://github.com/GoogleContainerTools/kpt/releases/download/v0.39.3/kpt_linux_amd64
$ file kpt_linux_amd64             
kpt_linux_amd64: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=uDFyZUedRMzQAkxIjEbD/8WZ-E2xLU5MJCiBHdd9V/3-fqk_CLQl_i1s8pix-m/gYsd1NjiXOPKWFVXhYm_, stripped
```

**Comment by mortent** [comment]
Yeah, we are aware of this issue and we do plan to fix it. This is also related to https://github.com/GoogleContainerTools/kpt/issues/3511.

**Comment by mortent** [comment]
Just some quick research seems to suggest that the golang toolchain normally creates a statically linked binary, but switches to dynamically linked binary if cgo is used. And we did introduce cgo in the latest release.
