### ISSUE TITLE
Kpt beta 20 docker image fails to run

### ISSUE THREAD

**Issue by physcat** [GoogleContainerTools/kpt#3528]
### Expected behavior

Testing with kpt beta.19 works as expected:
```bash
docker run -it --rm gcr.io/kpt-dev/kpt:v1.0.0-beta.19 version

1.0.0-beta.19
```

### Actual behavior

`kpt:v1.0.0-beta.20` fails:
```bash
docker run -it --rm gcr.io/kpt-dev/kpt:v1.0.0-beta.20 version

standard_init_linux.go:228: exec user process caused: no such file or directory
```

### Steps to reproduce the behavior

Step 0: Docker run kpt images:
```bash
docker run -it --rm gcr.io/kpt-dev/kpt:v1.0.0-beta.20 version
```
```

**Comment by natasha41575** [comment]
I can reproduce the reported issue on Mac. On linux, I get:

```
docker run -it --rm gcr.io/kpt-dev/kpt:v1.0.0-beta.20 version
exec /usr/local/bin/kpt: no such file or directory
```

Evidently, something went wrong with [this line](COPY kpt /usr/local/bin/kpt) of the Dockerfile. As @mortent, might have something to do with the CGO changes. Will dig deeper.

**Comment by physcat** [comment]
If it is CGO then I wonder if this [change](https://github.com/GoogleContainerTools/kpt/commit/14562bede8cba237cac7824f408481278bf641b1) is related to the issue... 
That's where they change:
```diff
+ env:
+  - CGO_ENABLED=1
+  - GO111MODULE=on
builds:
-  - env:
-      - CGO_ENABLED=0
-      - GO111MODULE=on
```

**Comment by natasha41575** [comment]
We believe https://github.com/GoogleContainerTools/kpt/pull/3530 will fix the issue for future releases.

@mortent @droot Do we want to repush the v1.0.0-beta.20 image too?
