### ISSUE TITLE
porch v0.0.9: porch-controllers in crash loop due to RemoteRootSyncSets

### ISSUE THREAD

**Issue by philippart** [GoogleContainerTools/kpt#3529]
Since upgrading porch to v0.0.9 (from v0.0.6) which now includes 2 new controllers (RemoteRootSyncSet + WorkloadIdentityBinding), the porch-controllers keeps crashing due to this error.

It's not clear what the "RemoteRootSyncSet" controller does (nothing found in the documentation) and how to configure/deploy it properly with the deployment manifests provided in v0.0.9. I confirmed the CRDs and API services are there. Note: I'm running this on a local cluster together with config-sync (v1.12.2).

```
E0901 16:14:24.510333 1 logr.go:279] controller-runtime/source "msg"="if kind is a CRD, it should be installed before calling Start" "error"="no matches for kind "RemoteRootSyncSet" in version "config.porch.kpt.dev/v1alpha1"" "kind"={"Group":"config.porch.kpt.dev","Kind":"RemoteRootSyncSet"}
E0901 16:14:29.894775 1 controller.go:203] controller/remoterootsyncset "msg"="Could not wait for Cache to sync" "error"="failed to wait for remoterootsyncset caches to sync: timed out waiting for cache to be synced" "reconciler group"="config.porch.kpt.dev" "reconciler kind"="RemoteRootSyncSet"
I0901 16:14:29.894843 1 logr.go:261] "msg"="Stopping and waiting for non leader election runnables"
I0901 16:14:29.894857 1 logr.go:261] "msg"="Stopping and waiting for leader election runnables"
I0901 16:14:29.894970 1 controller.go:240] controller/workloadidentitybinding "msg"="Shutdown signal received, waiting for all workers to finish" "reconciler group"="config.porch.kpt.dev" "reconciler kind"="WorkloadIdentityBinding"
I0901 16:14:29.894986 1 controller.go:240] controller/rootsyncset "msg"="Shutdown signal received, waiting for all workers to finish" "reconciler group"="config.porch.kpt.dev" "reconciler kind"="RootSyncSet"
I0901 16:14:29.895104 1 controller.go:242] controller/workloadidentitybinding "msg"="All workers finished" "reconciler group"="config.porch.kpt.dev" "reconciler kind"="WorkloadIdentityBinding"
I0901 16:14:29.895132 1 controller.go:242] controller/rootsyncset "msg"="All workers finished" "reconciler group"="config.porch.kpt.dev" "reconciler kind"="RootSyncSet"
I0901 16:14:29.895145 1 logr.go:261] "msg"="Stopping and waiting for caches"
I0901 16:14:29.895340 1 logr.go:261] "msg"="Stopping and waiting for webhooks"
I0901 16:14:29.895358 1 logr.go:261] "msg"="Wait completed, proceeding to shutdown the manager"
error running manager: failed to wait for remoterootsyncset caches to sync: timed out waiting for cache to be synced
```

**Comment by mortent** [comment]
Thanks for reporting this. I will take a look at it.

**Comment by mortent** [comment]
@philippart I'm not able to reproduce this issue. I have tried to install the latest version of Porch on a new GKE cluster, and the controllers are running without any crashing. Could you provide some more details on your environment and maybe steps for reproducing it?

**Comment by philippart** [comment]
@mortent here is what I did on a local dev cluster (microk8s):

1. installed kpt and porcch v0.0.6 using the deployment blueprint and customized the blueprint to include our corporate proxy:
```
mkdir porch-install
wget https://github.com/GoogleContainerTools/kpt/releases/download/porch%2Fv0.0.6/deployment-blueprint.tar.gz
tar xzf deployment-blueprint.tar.gz -C porch-install
kubectl apply -f porch-install
```
2. reproduced the porch quickstart example with the basens and istions packages (everything worked fine)
3. configured config-sync with a couple of RootSync and RepoSync (worked fine except an issue with helm proxy)
4. upgraded porch to v0.0.9 using the same method as above (merge changes I made with the proxy)
And since then I am getting this error with the porch-controllers in crash loop.
Note: when upgrading porch config-sync was also upgraded (config-management-operator v1.12.2)

What would help if you could point me to some documentation about the RemoteRootSyncSet which seems to be what is causing problems. I havent created any CR of that Kind (only RootSync and RepoSync as explained above).

My configs are available in this [public repo](https://github.com/philippart/kpt-demo).

**Comment by philippart** [comment]
Actually in [remoterootsyncset_types.go ](https://github.com/GoogleContainerTools/kpt/blob/c9b7522f63326599436cae40a059e5976084c9ec/porch/controllers/remoterootsync/api/v1alpha1/remoterootsyncset_types.go) I see these comments which seem to suggest that RemoteRootSyncSet and RootSync are closely related (except that config-sync uses cluster selectors) but it's unclear if both are incompatible with each other (the last sentence makes be doubt).

```
// RemoteRootSyncSet represents applying a package to multiple target clusters.
// In future, this should use ConfigSync, but while we're iterating on OCI/porch support,
// and making a few similar iterations (e.g. what feedback do we need for rollout),
// we're just applying directly to the target cluster(s).
//
// We follow the "managed remote objects" pattern; we don't want to create a mirror
// object, so we start with the "ReplicaSet" of Pod/ReplicaSet/Deployment.
//
// spec.clusterRefs specifies the target clusters
//
// spec.template maps to the spec of our "Pod", in this case a ConfigSync RootSync/RepoSync.
// Because we're not actually using ConfigSync in this prototype, we are only defining a
// small subset of fields.
```

**Comment by philippart** [comment]
Sorry I haven't tried the fix you proposed since I've been able to fix the issue as explained above. Thanks anyway.
