### ISSUE TITLE
kpt live apply doc claims --poll-period is supported, but it's not

### ISSUE THREAD

**Issue by tgjonestx** [GoogleContainerTools/kpt#3548]
### Expected behavior
`kpt live apply --help` does not include descriptions of unsupported arguments

### Actual behavior
```
/ # kpt live apply --poll-period=10s
error: unknown flag: --poll-period
/ # kpt live apply --help | grep poll-period
  --poll-period:
  $ kpt live apply --reconcile-timeout=15m --poll-period=5s my-dir
```

### Information
The `--poll-period` command line option was supported in kpt `v1.0.0-beta.15`; it's not supported in `v1.0.0-beta.19`,  but I'm not sure when support was dropped.

Suggestion - I know that beta means that there will be breaking changes, but it would be a little bit easier for users to adopt new versions if the release notes called out breaking changes.

### Steps to reproduce the behavior
Run `kpt live apply --poll-period=10s`

**Comment by mortent** [comment]
Yeah, this is a leftover from when kpt used polling for checking status for resources during apply. We recently switched to using watches for this, so the poll-period is no longer necessary. Thanks for reporting this and I'll make sure the documentation is updated.
