### ISSUE TITLE
Support mounting volumes when using `kpt fn run --image`

### ISSUE THREAD

**Issue by prachirp** [GoogleContainerTools/kpt#359]
Add a command line flag called --volume to kpt fn run which takes the host source path and container destination path as a string
Usage:
--volume string The host source and container destination paths, as for docker run --volume [host-src:]container-dest[:<options>]

kpt fn run . --volume /Users/prachirp/workspace/helm/charts/bitnami:/source --image gcr.io/kpt-functions/helm-template -- chart_path=/source/redis name=test1

**Comment by pwittrock** [comment]
@prachirp Is this something you can pick up?
