### ISSUE TITLE
We should not use yaml: annotations

### ISSUE THREAD

**Issue by justinsb** [GoogleContainerTools/kpt#3618]
The `yaml` field tags are not used by sigs.k8s.io/yaml, and using anything other than that library gives unexpected results when working with apimachinery types.  We should get rid of the yaml field tags, and ensure that we are not using any other yaml libraries (at least not with kube objects)

**Comment by mortent** [comment]
This was fixed in https://github.com/GoogleContainerTools/kpt/pull/3643
