### ISSUE TITLE
Add levelled logging to kpt.

### ISSUE THREAD

**Issue by seans3** [GoogleContainerTools/kpt#372]
Add levelled logging to `kpt` command. This will allow users to get debugging information (by level) while running these commands. This would be similar to `-v=<NUMBER>` in kubectl. We have initially agreed to use `klog` package.

**Comment by mortent** [comment]
We should also make sure this will allow us to output all logging to StdErr. For UIs that rely on in-place updates, it is important to be able to direct logs to a different place than the normal output.

**Comment by seans3** [comment]
Implemented with: https://github.com/kubernetes-sigs/cli-utils/pull/161
