### ISSUE TITLE
Rollout API should support deletion of objects created by it

### ISSUE THREAD

**Issue by droot** [GoogleContainerTools/kpt#3797]
Here is the scenario:

I created a Rollout that resulted in creating KRM objects in the target clusters. When I delete the Rollout, the KRM objects created in the target clusters are not deleted even though the `rootsync` object is deleted from the target cluster.

In some scenario, we would like to configure the rollout to delete the underlying KRM objects. Think of it as `DeletionPolicy`. `Config-Sync` added an experimental support for this feature in the recent release so it will be nice to plumb that through the Rollout API.

This will mainly assist in testing and demos for now and also help complete the API specification.

**Comment by droot** [comment]
I realized this can be addressed if we improve the configurability of `RootSync` and `RepoSync` template in the `Rollout` API. One can specify the appropriate labels required to specify the deletion policy in the template. 

Had a discussion with @natasha41575 so she will improve the configurability of `RootSync` and `RepoSync` and as part of that it will be addressed. 

/cc @mortent

**Comment by natasha41575** [comment]
Adding a note that the deletion propagation feature in Config Sync is not yet released, so to test out that feature, you will have to use an unreleased version of CS. I created a package to install CS built from current HEAD here: https://github.com/natasha41575/packages/tree/main/config-sync
