### ISSUE TITLE
porch: package names must include the repo directory if not using the root directory

### ISSUE THREAD

**Issue by johnbelamaric** [GoogleContainerTools/kpt#3870]
### Expected behavior
The downstream PackageRevision is created in the directory associated with the registered Porch repository.

### Actual behavior
```

E0309 23:11:37.327209       1 controller.go:326]  "msg"="Reconciler error" "error"="Internal error occurred: cannot create cachingdns-edge outside of repository directory \"us-central1-edge-01\"" "PackageVariant"={"name":"cachingdns-edge-6b3bac48e67223051e4e47b5c52095eda9c1ee35","namespace":"default"} "controller"="packagevariant" "controllerGroup"="config.porch.kpt.dev" "controllerKind"="PackageVariant" "name"="cachingdns-edge-6b3bac48e67223051e4e47b5c52095eda9c1ee35" "namespace"="default" "reconcileID"="f6c2dda9-24dd-4aff-8721-14f4b4530b58"

```
### Information

```
apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariant
metadata:
  creationTimestamp: "2023-03-09T23:11:01Z"
  finalizers:
  - config.porch.kpt.dev/packagevariants
  generation: 1
  labels:
    config.porch.kpt.dev/packagevariantset: 721c0f5a-ac8b-4ef6-9d2c-101ce07ce850
  name: cachingdns-edge-6b3bac48e67223051e4e47b5c52095eda9c1ee35
  namespace: default
  ownerReferences:
  - apiVersion: config.porch.kpt.dev/v1alpha1
    controller: true
    kind: PackageVariantSet
    name: cachingdns-edge
    uid: 721c0f5a-ac8b-4ef6-9d2c-101ce07ce850
  resourceVersion: "1913366"
  uid: 66ca7e6f-6b32-4d43-8b20-70777d4a708b
spec:
  adoptionPolicy: adoptNone
  deletionPolicy: delete
  downstream:
    package: cachingdns-edge
    repo: us-east1-edge-01
  upstream:
    package: cachingdns-edge
    repo: nephio-testorg-packages
    revision: v2
```

See the repo https://github.com/johnbelamaric/nephio-testorg-deploy which contains a bunch of directories as well as the manifests for the repository objects themselves.

Version: Porch v0.0.15

### Steps to reproduce the behavior

**Comment by johnbelamaric** [comment]
Also:
```
apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariantSet
metadata: # kpt-merge: /cachingdns-edge
  name: cachingdns-edge
  annotations:
    internal.kpt.dev/upstream-identifier: 'config.porch.kpt.dev|PackageVariantSet|default|cachingdns-edge'
spec:
  upstream:
    package:
      repo: nephio-testorg-packages
      name: cachingdns-edge
    revision: v2
  targets:
  - repositories:
      nephio.org/site-type: edge
```

**Comment by johnbelamaric** [comment]
Looks like this could be fixed by prepending the directory name to the package name here: https://github.com/GoogleContainerTools/kpt/blob/18e6af152ec500075c01639aaf5626047c021c6a/porch/controllers/packagevariants/pkg/controllers/packagevariant/packagevariant_controller.go#L235

However, that seems strange, because we also include the repo in spec, so it would seem Porch could figure this out instead of all clients having to do it.

**Comment by natasha41575** [comment]
Yeah, I agree that this is odd. I would expect porch to automatically try to create the directory already specified by the registered repository. I will investigate further.

**Comment by natasha41575** [comment]
So it seems that this is not unique to the PackageVariant object but is a property of porch in general.

Steps to repro:
```
$ kpt alpha repo reg https://github.com/natasha41575/blueprints.git -ndefault --repo-basic-username=natasha41575 --repo-basic-password=<token> --directory=foo

$ kpt alpha rpkg init pkg --repository=blueprints --workspace=test1 -ndefault
Error: Internal error occurred: cannot create pkg outside of repository directory "foo" 
```

This can be fixed by prepending the directory name to the package name:
```
$ kpt alpha rpkg init foo/pkg --repository=blueprints --workspace=test1 -ndefault
blueprints-f3a0b1bd887b23171644594d41a001dde732d2d6 created
```

@mortent Do you know if this is intentional, and if so, the justification for it? It seems strange to require the directory name to be prepended on each package, when the directory was already specified during the repo registration step.

**Comment by mortent** [comment]
I agree this seems like odd behavior. I think we should consider this a bug in Porch and fix it there.
