### ISSUE TITLE
`kpt pkg update` overwrites set Kptfile values

### ISSUE THREAD

**Issue by tylerreidwaze** [GoogleContainerTools/kpt#3914]
### Expected behavior

I expect KPT to keep upstream values that I set.

### Actual behavior

kpt loads some old values from somewhere and overrides my repo and tag values

### Information

```
> kpt version
1.0.0-beta.19
```

### Steps to reproduce the behavior

Set KPT File to the values I intend

```
> ocat Kptfile
apiVersion: kpt.dev/v1
kind: Kptfile
metadata:
  name: Permissions
  annotations:
    config.kubernetes.io/local-config: "true"
upstream:
  type: git
  git:
    repo: sso://waze-sandbox/sre/kpt-packages
    directory: /infra/gcp/IAM/Permissions
    ref: v0.7.2
  updateStrategy: resource-merge
upstreamLock:
  type: git
  git:
    repo: sso://waze-sandbox/sre/kpt-packages
    directory: /infra/gcp/IAM/Permissions
    ref: v0.7.2
    commit: 1df87f724cb19bd752c6b1b3cffa6200ebdfe58d
info:
  description: A package for configuring bindings to resources on the old TI platform
pipeline:
  mutators:
    - image: gcr.io/kpt-fn/apply-setters:v0.2.0
      configPath: setters.yaml
```

Run KPT pkg update to ensure references/upstream lock are correct and any changes are pulled down

```
> kpt pkg update
Package "dreViewer":
Fetching upstream from sso://waze-sandbox/sre/kpt-packages@v0.7.2
From sso://waze-sandbox/sre/kpt-packages
 * tag               v0.7.2     -> FETCH_HEAD
Fetching origin from sso://waze-sandbox/sre/kpt-packages@v0.7.2
From sso://waze-sandbox/sre/kpt-packages
 * branch            1df87f724cb19bd752c6b1b3cffa6200ebdfe58d -> FETCH_HEAD

Updated 1 package(s).

```

View the results of the kpt file and the branch and repo have been overridden with old values that are not referenced anywhere.  Perhaps something is cashed?

```
> ocat Kptfile
apiVersion: kpt.dev/v1
kind: Kptfile
metadata:
  name: Permissions
  annotations:
    config.kubernetes.io/local-config: "true"
upstream:
  type: git
  git:
    repo: /home/tylerreid/dev/waze/kpt-packages
    directory: /infra/gcp/IAM/Permissions
    ref: master
  updateStrategy: resource-merge
upstreamLock:
  type: git
  git:
    repo: sso://waze-sandbox/sre/kpt-packages
    directory: /infra/gcp/IAM/Permissions
    ref: v0.7.2
    commit: 1df87f724cb19bd752c6b1b3cffa6200ebdfe58d
info:
  description: A package for configuring bindings to resources on the old TI platform
pipeline:
  mutators:
    - image: gcr.io/kpt-fn/apply-setters:v0.2.0
      configPath: setters.yaml
```

**Comment by natasha41575** [comment]
The output of `kpt pkg update` itself that you provided looks correct, so I find it odd that it is overwriting your Kptfile with irrelevant information.

I tried doing a `kpt pkg get` followed by a `kpt pkg update` and that seems to work fine on my end with that basic setup, so it's possible that somewhere along the way your package reached an unusual state. Would you be able to provide more context about how you created the Kptfile, and any other potentially relevant changes you made in between the original creation of your package and running into this error?

I also see that you are using `1.0.0-beta.19`, could you confirm if you still get this error if you update to `1.0.0-beta.30`?

Reassigning to the area lead for triage.

**Comment by tylerreidwaze** [comment]
Thanks for the quick response.

> Would you be able to provide more context about how you created the Kptfile, and any other potentially relevant changes you made in between the original creation of your package and running into this error?

When I originally created the kpt package, the upstream was a local version of the package I was working on.  I am now trying to migrate the package to have the remote repo be its source.  The original kpt pkg get would have been something like the following

```
kpt pkg get ~/dev/waze/kpt-packages.git/infra/permissions/CrossPlatformPermissions@master UsagePubSubEditor
```

With respect to the error, perhaps something is in the `KPT_CACHE_DIR` that kpt pkg update is using?  However, I set it to `/tmp` and the issue persisted

```
> echo $KPT_CACHE_DIR

> vi Kptfile
> export KPT_CACHE_DIR=/tmp
> echo $KPT_CACHE_DIR
/tmp
> kpt pkg update
Package "dreViewer":
Fetching upstream from sso://waze-sandbox/sre/kpt-packages@v0.7.2
From sso://waze-sandbox/sre/kpt-packages
 * tag               v0.7.2     -> FETCH_HEAD
Fetching origin from sso://waze-sandbox/sre/kpt-packages@v0.7.2
From sso://waze-sandbox/sre/kpt-packages
 * branch            1df87f724cb19bd752c6b1b3cffa6200ebdfe58d -> FETCH_HEAD

Updated 1 package(s).

```

> I also see that you are using 1.0.0-beta.19, could you confirm if you still get this error if you update to 1.0.0-beta.30

Almost.  gcloud components update took me to `1.0.0-beta.29`. The issue still exists with this version

**Comment by mortent** [comment]
I will try to take a look at this tomorrow.

**Comment by mortent** [comment]
I've tried to follow the same setup as described, but I'm not able to reproduce the issue.

I used the following steps:
* Create a local kpt package, initialize git, and make a local commit with the package.
* Use `kpt pkg get` providing the path on the local filesystem to get a downstream package.
* Push the original package to GitHub and create a release by tagging it on the local filesystem and then push the tag to GitHub.
* Update the Kptfile in the downstream package to point the `repo` and `ref` fields to point to the release of the initial package in GitHub. I tried both with only updating the fields under upstream, and changing the fields both in upstream and upstreamLock.
* Run `kpt pkg update`

It seems to do the right thing, where the package content is updated and the `upstreamLock.git.commit` field is set to the correct value.

**Comment by tylerreidwaze** [comment]
Thanks for looking into this so quickly.   I will wipe the pkg and reinitialize it from scratch.

```
cp dreSpannerAdmin/setters.yaml /tmp
rm -rf dreSpannerAdmin
kpt pkg get sso://waze-sandbox/sre/kpt-packages.git/infra/gcp/IAM/Permissions@v0.7.2
mv Permissions/ dreSpannerAdmin
> ocat dreSpannerAdmin/Kptfile
apiVersion: kpt.dev/v1
kind: Kptfile
metadata:
  name: Permissions
  annotations:
    config.kubernetes.io/local-config: "true"
upstream:
  type: git
  git:
    repo: sso://waze-sandbox/sre/kpt-packages
    directory: /infra/gcp/IAM/Permissions
    ref: v0.7.2
  updateStrategy: resource-merge
upstreamLock:
  type: git
  git:
    repo: sso://waze-sandbox/sre/kpt-packages
    directory: /infra/gcp/IAM/Permissions
    ref: v0.7.2
    commit: 1df87f724cb19bd752c6b1b3cffa6200ebdfe58d
info:
  description: A package for configuring bindings to resources on the old TI platform
pipeline:
  mutators:
    - image: gcr.io/kpt-fn/apply-setters:v0.2.0
      configPath: setters.yaml
```

Now, run a kpt pkg update

```
cd dreSpannerAdmin/ 
kpt pkg update
> ocat Kptfile
apiVersion: kpt.dev/v1
kind: Kptfile
metadata:
  name: Permissions
  annotations:
    config.kubernetes.io/local-config: "true"
upstream:
  type: git
  git:
    repo: /home/tylerreid/dev/waze/kpt-packages
    directory: /infra/gcp/IAM/Permissions
    ref: master
  updateStrategy: resource-merge
upstreamLock:
  type: git
  git:
    repo: sso://waze-sandbox/sre/kpt-packages
    directory: /infra/gcp/IAM/Permissions
    ref: v0.7.2
    commit: 1df87f724cb19bd752c6b1b3cffa6200ebdfe58d
info:
  description: A package for configuring bindings to resources on the old TI platform
pipeline:
  mutators:
    - image: gcr.io/kpt-fn/apply-setters:v0.2.0
      configPath: setters.yaml
```

This is really weird.  I will ask one of my teammates to try and reproduce with the same steps.  I would guess there is something cached on my machine about that particular folderpackage that wants to reset it

**Comment by tylerreidwaze** [comment]
I worked with a teammate and they could not reproduce either with the exact same packages.

Weirdly, this still happens with me even after `rm -rf` the repo.  

@mortent is there any cache or something that I can wipe (uninstall kpt?) to stop this issue?

**Comment by tylerreidwaze** [comment]
Just confirming issue still exists on latest kpt version

```
> kpt version
1.0.0-beta.30
> ocat Kptfile
apiVersion: kpt.dev/v1
kind: Kptfile
metadata:
  OMITTED
upstream:
  type: git
  git:
    repo: sso://waze-sandbox/sre/kpt-packages
    directory: /infra/discrete/IAM/CrossPlatformPermissions
    ref: v0.7.7
  updateStrategy: resource-merge
upstreamLock:
  type: git
  git:
    repo: sso://waze-sandbox/sre/kpt-packages
    directory: /infra/discrete/IAM/CrossPlatformPermissions
    ref: v0.7.7
    commit: 30130405a87786a1d143fbe314f37ed102d646ad
info:
  description: OMITTED
pipeline:
  OMITTED
> kpt pkg update
Package "AdmanageInvPredStorageObjectViewer":
Fetching upstream from sso://waze-sandbox/sre/kpt-packages@v0.7.7
From sso://waze-sandbox/sre/kpt-packages
 * tag               v0.7.7     -> FETCH_HEAD
Fetching origin from sso://waze-sandbox/sre/kpt-packages@v0.7.7
From sso://waze-sandbox/sre/kpt-packages
 * branch            30130405a87786a1d143fbe314f37ed102d646ad -> FETCH_HEAD

Updated 1 package(s).
> ocat Kptfile
apiVersion: kpt.dev/v1
kind: Kptfile
metadata:
  OMITTED
upstream:
  type: git
  git:
    repo: /home/tylerreid/dev/waze/kpt-packages
    directory: /infra/gcp/IAM/CrossPlatformPermissions
    ref: master
  updateStrategy: resource-merge
upstreamLock:
  type: git
  git:
    repo: sso://waze-sandbox/sre/kpt-packages
    directory: /infra/discrete/IAM/CrossPlatformPermissions
    ref: v0.7.7
    commit: 30130405a87786a1d143fbe314f37ed102d646ad
info:
  description: OMITTED
pipeline:
  OMITTED
```

**Comment by mortent** [comment]
Yes, kpt does have a local cache. Try to remove the `~/.kpt` directory and see if that fixes the issue.

**Comment by tylerreidwaze** [comment]
Okay, this is interesting.  After wiping the cache

```
apiVersion: kpt.dev/v1
kind: Kptfile
metadata:
  name: UsagePubSubEditor
  annotations:
    config.kubernetes.io/local-config: "true"
upstream:
  type: git
  git:
    repo: sso:/REDACTED/kpt-packages
    directory: /infra/discrete/IAM/CrossPlatformPermissions
    ref: v0.7.7
  updateStrategy: resource-merge
upstreamLock:
  type: git
  git:
    repo: sso://REDACTED/kpt-packages
    directory: /infra/discrete/IAM/CrossPlatformPermissions
    ref: v0.7.7
    commit: 30130405a87786a1d143fbe314f37ed102d646ad
info:
  description: A package for configuring bindings to resources on the old TI platform
pipeline:
  mutators:
    - image: gcr.io/kpt-fn/apply-setters:v0.2.0
      configPath: setters.yaml
```

then `kpt pkg update`

```
apiVersion: kpt.dev/v1
kind: Kptfile
metadata:
  name: UsagePubSubEditor
  annotations:
    config.kubernetes.io/local-config: "true"
upstream:
  type: git
  git:
    repo: /home/tylerreid/REDACTED/kpt-packages
    directory: /infra/gcp/IAM/CrossPlatformPermissions
    ref: master
  updateStrategy: resource-merge
upstreamLock:
  type: git
  git:
    repo: sso://REDACTED/kpt-packages
    directory: /infra/discrete/IAM/CrossPlatformPermissions
    ref: v0.7.7
    commit: 30130405a87786a1d143fbe314f37ed102d646ad
info:
  description: A package for configuring bindings to resources on the old TI platform
pipeline:
  mutators:
    - image: gcr.io/kpt-fn/apply-setters:v0.2.0
      configPath: setters.yaml
```

After stashing all of those changes, wiping the cache again, removing the `upstreamLock` section, and running `kpt pkg update`

```
apiVersion: kpt.dev/v1
kind: Kptfile
metadata:
  name: UsagePubSubEditor
  annotations:
    config.kubernetes.io/local-config: "true"
upstream:
  type: git
  git:
    repo: /home/tylerreid/dev/REDACTED/kpt-packages
    directory: /infra/gcp/IAM/CrossPlatformPermissions
    ref: master
  updateStrategy: resource-merge
upstreamLock:
  type: git
  git:
    repo: sso://REDACTED/kpt-packages
    directory: /infra/discrete/IAM/CrossPlatformPermissions
    ref: v0.7.7
    commit: 30130405a87786a1d143fbe314f37ed102d646ad
info:
  description: A package for configuring bindings to resources on the old TI platform
pipeline:
  mutators:
    - image: gcr.io/kpt-fn/apply-setters:v0.2.0
      configPath: setters.yaml
```

The issue seams to persist.  Note, my teammates were not able to reproduce the issue either.  I also `rm -rf`'d the repo from my machine, delete the kpt cache, and the issue persisted

**Comment by tylerreidwaze** [comment]
Okay.  I think I may have finally resolved this and found the root cause.

The way I had (just fixed it), I had to run render with `sudo`.  So, while I had an updated version of kpt, sudo did not

```
> sudo kpt version
1.0.0-beta.2
```

After fixing my docker installation and running without sudo, the issue is gone.  Sorry for the Goose chase I sent you on, but glad we got it resolved :)
