### ISSUE TITLE
[Question] Should not one expect to see status and conditions in kpt schema definiton file

### ISSUE THREAD

**Issue by vjayaramrh** [GoogleContainerTools/kpt#3916]
I was expecting to see references to status/conditions in the scheme file at https://raw.githubusercontent.com/GoogleContainerTools/kpt/main/site/reference/schema/kptfile/kptfile.yaml. Does this need to be updated?

Please also check if your question is answered in the
[FAQ](https://kpt.dev/faq/).

**Comment by droot** [comment]
Thanks for reporting it. The schema is not updated. Current process for updating schema is manual so we probably missed it when we added `status` field.

**Comment by droot** [comment]
Created a PR to update the schema: https://github.com/GoogleContainerTools/kpt/pull/3922

**Comment by droot** [comment]
@vjayaramrh The schema is now updated.
