### ISSUE TITLE
Revision is missing from the clone

### ISSUE THREAD

**Issue by Cbkhare** [GoogleContainerTools/kpt#3932]
Followed the [example](https://kpt.dev/reference/cli/alpha/rpkg/clone/?id=examples) to clone a package. 

Cli throws error that `--revision` is invalid flag.

```
$ kpt alpha rpkg clone  test-catalogue-93b612f846d238c0ee3cae8441f2e924d07eeca1  foo --repository=test-catalogue --revision=v1
error: unknown flag: --revision
```

Expected behaviour
- Cli to clone a repository should support revision.

**Comment by natasha41575** [comment]
The documentation is outdated, sorry about that! Revisions now get assigned upon publishing, and draft package revisions are uniquely identified by their `workspaceName`. 

You should be able to run this successfully:

```
$ kpt alpha rpkg clone  test-catalogue-93b612f846d238c0ee3cae8441f2e924d07eeca1  foo --repository=test-catalogue --workspace=my-workspace
```

I will update the documentation.
