### ISSUE TITLE
Remove apimachinery and staging deps from kustomize

### ISSUE THREAD

**Issue by pwittrock** [GoogleContainerTools/kpt#394]

**Comment by monopole** [comment]
[Resource]: https://github.com/kubernetes-sigs/kustomize/blob/master/api/resource/resource.go
[Kunstructured]: https://github.com/kubernetes-sigs/kustomize/blob/master/api/ifc/ifc.go#L43

proposed safe (and thus quick) way to do this deep refactor:

1. To the [Resource] struct add an instance of `*yaml.RNode`, and always populate it at the same time as [Kunstructured] when loading resources.
1. at all key choke points where [Kunstructured] is actually modified (e.g. `filtersutil.ApplyToJSON` calls), perform a dual edit to the RNode.  I.e. do twice as much work (this is like a dark launch).
1. add a kustomize build flag `--useRNodes` that simply switches from
outputting the final value of Kunstructured to outputting the final output of RNode.  We do twice as much work in the previous step to avoid the complex branching and flag passing needed to pass this flag down everywhere (including to tests).
1. get all unit and e2e tests to pass with the flag on
1. release a binary with the flag on by default (user can turn it off).
1. For _n_ (2?) weeks, respond to bugs related to the change, if any.
1. Delete the flag == false code path, which will include deleting Kunstructured from [Resource], which will also mean all apimachinery deps can be removed.

**Comment by monopole** [comment]
tracking in https://github.com/kubernetes-sigs/kustomize/issues/2506
