### ISSUE TITLE
Documentation: List kubectl install in the pre-requisites sections in the porch running locally documentation

### ISSUE THREAD

**Issue by vjayaramrh** [GoogleContainerTools/kpt#3987]
When following the steps at https://github.com/GoogleContainerTools/kpt/blob/main/porch/docs/running-locally.md I noticed that the `make run-local` requires kubectl installed. 
It would be good to add this as well to the per-requisites section in the documentation.

**Comment by natasha41575** [comment]
Makes sense to me, I'll create a PR to add kubectl to the porch prerequisites.

**Comment by vjayaramrh** [comment]
> Makes sense to me, I'll create a PR to add kubectl to the porch prerequisites.

@natasha41575 I already have a PR open at https://github.com/GoogleContainerTools/kpt/pull/3988
