### ISSUE TITLE
[Question] kpt function sdk golang no deep copy

### ISSUE THREAD

**Issue by jdkuki** [GoogleContainerTools/kpt#4029]
I am looking at using the kpt sdk to generate some unique yamls from a base template using a krm function. My template is tracked as a KRM resource as I would like to combine a different set of config from configPath on the function call.

I have code like:
```
for _, o := range rl.Items {
  newObj := fn.NewEmptyKubeObject()
 // somehow copy o into newObj, then modify newObj
}
```

How can I make a deep copy of a KubeObject? I don't find anything in the godoc that seems to accomplish this. Apologies if this is a rather obvious task...

**Comment by natasha41575** [comment]
@yuwenma Can you take a look at this one?

**Comment by johnbelamaric** [comment]
This should work, but maybe @yuwenma has a better way:

```
for _, o := range rl.Items {
    newObj, err := fn.ParseKubeObject(o.String())
    if err != nil {
        ...
    }
}

```

**Comment by yuwenma** [comment]
Thanks @johnbelamaric . Yes, I think `ParseKubeObject` is the best approach right now.

**Comment by natasha41575** [comment]
Closing this as it appears to be resolved. Let us know if you have any further questions, and thanks so much for trying out the sdk.

**Comment by jdkuki** [comment]
Yes this a good solution for now, thank you!
