### ISSUE TITLE
Functions -- Runtimes and Environments

### ISSUE THREAD

**Issue by pwittrock** [GoogleContainerTools/kpt#408]
Composable functions can be used in many environments

# Functions in CICD / pipelines

  - Jenkins
  - CloudBuild
  - Tekton
  - GitLab
  - GitHub checks

#407  Functions as Operators
  - Function + CRD = Operator

# Functions in Kustomize

  - Support for functions as Kustomize plugins

# Additional function runtimes

- Http endpoints (cloud functions)
- Starlark

**Comment by droot** [comment]
Seems like this is already addressed. Pl. reopen if required.
