### ISSUE TITLE
Diff should show resources that are deleted from the local state

### ISSUE THREAD

**Issue by mortent** [GoogleContainerTools/kpt#412]
Diff doesn't show objects that will be deleted by apply.

Diff currently does not take into account resources that doesn't exist in the local state. Diff should leverage the grouping object to make sure we include these in the diff

**Comment by seans3** [comment]
De-prioritizing this for now. Removed sprint labels.

**Comment by seh** [comment]
This came up in the "kustomize" Slack channel [here](https://kubernetes.slack.com/archives/C9A5ALABG/p1587561522401700).

**Comment by art-3** [comment]
@seans3 why was this de-prioritized? This is actually a big blocker for pull/reconcile-based deployments since we can't rely on `ktp live diff` to **really** compare the k8s state with the current git config. Is it possible to re-prioritize it?

**Comment by seans3** [comment]
`kpt live diff` command has been removed--closing
