### ISSUE TITLE
kpt live commands should provide output in json/yaml format

### ISSUE THREAD

**Issue by mortent** [GoogleContainerTools/kpt#413]
When using kpt live as part of a CI/CD pipeline, it is useful to have an output format that can be easily parsed.

**Comment by fsommar** [comment]
This would be very interesting to us. We're using the output as part of CI/CD pipelines, and while --output=table gives a nice summary of the state after a kpt live apply, it assumes the output is a terminal.

**Comment by mortent** [comment]
@fsommar My first thought here is that printing in json format will be similar to the default `event` format of kpt live, but with each line of the output as a json object. So something like:
```json
{"namespace": "default", "name": "foo", "apiVersion": "apps/v1", "kind": "Deployment", "action": "created"}
{"namespace": "default", "name": "foo", "apiVersion": "apps/v1", "kind": "Deployment", "status": "InProgress", "message": ".."}
```
The output will still be streaming from kpt as it happens. I still need to spend some time deciding on the exact fields we should use, but does the direction match what you are looking for?

**Comment by mortent** [comment]
@fsommar I have a WIP on this at: https://github.com/kubernetes-sigs/cli-utils/pull/231
I have added a description of what the output would look like as godoc at https://github.com/kubernetes-sigs/cli-utils/pull/231/files#diff-f0e3e33ec6b4df91f7a7e1b0b65e2675R4. Take a look and let me know if there is anything you need that are missing or if something doesn't look right.

**Comment by fsommar** [comment]
@mortent Thank you, LGTM!
