### ISSUE TITLE
Launch Kpt

### ISSUE THREAD

**Issue by pwittrock** [GoogleContainerTools/kpt#420]
# Packaging

- get
- update

# Declarative UX

- Setters
- Substitutions
- Format

# Extensibility

- Functions

# Apply

- Apply
- Prune
- Status

**Comment by jpugliesi** [comment]
@pwittrock ks it possible to declaratively invoke setters?

**Comment by pwittrock** [comment]
@jpugliesi would you create a separate issue for that discussion, and expand upon the problem you are trying to solve?
