### ISSUE TITLE
Auto kustomize recursively from annotation

### ISSUE THREAD

**Issue by pwittrock** [GoogleContainerTools/kpt#425]
When fetching a package that is a kustomize based package and including it as a component of another package (e.g. fetch mysql and include in app composite package), it should be possible to apply the composite package (app) and have it expand the subpackage (app/mysql) automatically.

This can be done using and annotation on the kustomization.yaml that should be expanded.

`cli.k8s.io/kustomize-apply: true`

**Comment by mikebz** [comment]
closing a kustomize issue, from what I understand since kustomize is rolled into kubectl and packaging is explicitly not a part of core kubernetes offering this would be a "won't fix" in kustomize.  Potentially something to look into in kpt packaging and functions.  @frankfarzan @mortent
