### ISSUE TITLE
Unclear how to implement CRDs for use with kpt live apply

### ISSUE THREAD

**Issue by yhrn** [GoogleContainerTools/kpt#446]
In the [documentation](https://googlecontainertools.github.io/kpt/reference/live/apply/) for `kpt live apply` the following sentence can be found: 

> For CRDs, there is a set of recommendations that if followed, will allow kpt live apply to correctly compute status.

It would be great with a link to those recommendations.

**Comment by yhrn** [comment]
Could you link to the relevant information here in the meantime?

**Comment by pwittrock** [comment]
@mortent

**Comment by mortent** [comment]
I'll be updating the documentation today.

**Comment by mortent** [comment]
@yhrn I have updated the docs. Please just file another issue or reach out if anything is unclear or missing.

**Comment by pwittrock** [comment]
Link to docs: https://googlecontainertools.github.io/kpt/reference/live/apply/#recommendations-for-crds
