### ISSUE TITLE
Create-subst broken link to edit

### ISSUE THREAD

**Issue by trodge** [GoogleContainerTools/kpt#447]
The page [here](https://googlecontainertools.github.io/kpt/reference/cfg/create-subst/) contains a link to [here](https://github.com/GoogleContainerTools/kpt/edit/master/content/en/reference/cfg/create-subst/_index.md), which is a 404 page.

The documentation itself has several issues in the examples, some of which I've outlined [here](https://github.com/GoogleContainerTools/kpt/issues/417).

**Comment by pwittrock** [comment]
Links removed
