### ISSUE TITLE
KPT live apply does not recognize Config Connector CR conditions

### ISSUE THREAD

**Issue by yhrn** [GoogleContainerTools/kpt#452]
Hi @mortent,

Thanks for addressing #446. While I think that these recommendations makes sense i general I don't know if many existing operators for CRDs would adhere to them - not even the Config Connector CRDs does. They use a "Ready" condition (abnormal-false polarity) to signal if they have completed reconciliation. Would it make sense for `kpt live` to also support this? Or are you talking to the KCC team about it?

As a side note, I think Helm recognizes the ready condition - `helm install --wait` will correctly block until KCC CRs have a "Ready=true" condition.

**Comment by mortent** [comment]
Yeah, I am aware that KCC does not use follow the recommendations (We came up with them pretty recently). We have discussed adding support for the `Ready` condition in kpt, not only because of KCC, but it is pretty widely used even though it does not follow the Kubernetes design best practices.

I will take a look at this. I think adding support for the `Ready` condition should be a pretty minor change.

**Comment by mortent** [comment]
I have a PR to add support for the `Ready` condition when we compute status: https://github.com/kubernetes-sigs/cli-utils/pull/109. There are some limitations to what we can do with just one condition, but I've tried to explain that in the documentation in the PR. If you have any suggestions or feedback on how this would be most useful, just comment here or on the PR.

**Comment by yhrn** [comment]
I can see that the referenced PR (https://github.com/kubernetes-sigs/cli-utils/pull/109) was merged a while ago - what does that mean for this issue?

**Comment by mortent** [comment]
@yhrn this change is included in the latest release of kpt (v0.23.0). It will also be in the version of kpt that ships with the next version of gcloud. I think that will be coming in about 2 weeks.

As mentioned in the docs, there are still some corner cases here. If you run into any of them, please let us know. We are talking with the Config Connector team about how we can best support those resources with kpt.

**Comment by yhrn** [comment]
I have now confirmed that it works as expected on v.0.23.0. Thanks a lot!
