### ISSUE TITLE
[doc] helloworld should be specified to 'kpt pkg update' 

### ISSUE THREAD

**Issue by mkimuram** [GoogleContainerTools/kpt#465]
In [Guides/Package Consumers/Update](https://googlecontainertools.github.io/kpt/guides/consumer/update/), `kpt pkg update helloworld-set@v0.5.0 --strategy=resource-merge` is executed to update. However, loal directory should be `helloworld`, instead of `helloworld-set`, because `kpt pkg get $REPO/package-examples/helloworld-set@v0.3.0 helloworld` is executed in the prior step.

**Comment by pwittrock** [comment]
Thanks for filing this.

Looks like this has been fixed: https://github.com/GoogleContainerTools/kpt/blob/master/site/content/en/guides/consumer/update/_index.md#command-1
