### ISSUE TITLE
kpt pkg get not cloning complete yaml

### ISSUE THREAD

**Issue by xmclark** [GoogleContainerTools/kpt#468]
On Windows 10, using PowerShell 7, kpt installed with gcloud. 

I see unexpected behavior when using `kpt pkg get` while [following a tutorial](https://googlecontainertools.github.io/kpt/reference/pkg/). It seems that yaml files are getting parsed and then modified? I only see the top yaml object in the statefulset for cockroachdb. The cockroachdb statefulset yaml is quite larger in the [git repo.](https://github.com/kubernetes/examples/tree/master/staging/cockroachdb).

![image](https://user-images.githubusercontent.com/1364747/78206282-419ae800-7453-11ea-8e33-b42e1671937c.png)

**Comment by pwittrock** [comment]
@xmclark thanks!
