### ISSUE TITLE
[doc] Incorrect KPT command in the guide fetch a helm chart

### ISSUE THREAD

**Issue by michael-bowen-sc** [GoogleContainerTools/kpt#476]
The command to get the mysql package is missing the env variable `$REPO` and `pkg` flag.  Moreover, the `./templates` directory does not exist @v0.1.0.

https://googlecontainertools.github.io/kpt/guides/ecosystem/helm/#fetch-a-helm-chart

```bash
export REPO=https://github.com/GoogleContainerTools/kpt.git
kpt get/package-examples/mysql/mysql/templates@v0.1.0 mysql/
```

Should be this...

```bash
export REPO=https://github.com/GoogleContainerTools/kpt.git
kpt pkg get $REPO/package-examples/mysql/mysql/templates@v0.16.0 mysql/
```

**Comment by pwittrock** [comment]
Thanks!
