### ISSUE TITLE
Kpt adds a new `patch` command group

### ISSUE THREAD

**Issue by nan-yu** [GoogleContainerTools/kpt#484]
Sometimes, we want to apply multiple patches on a package. Those patches can come from a git repository and even have kpt config setters and a kustomization file.
A real scenario is to enable ASM and Cloud Run on existing clusters.
First, we can export the resource configurations of the existing cluster and initialize as a Kpt package.
The ASM and Cloud Run patches can be two separate git repositories. We can fetch the patches, update the patches and eventually apply the patches on the current configurations.

I was thinking a command group that includes the following subcommands:
1. kpt patch desc my-patch
2. kpt patch get https://github.com/my-repo/my-patch
3. kpt patch update my-patch
4. kpt patch diff my-patch
5. kpt patch apply my-pkg my-patch

**Comment by nan-yu** [comment]
@justinsb @janetkuo This feature request is aiming to solve the multiple patches issue we discussed today. The workflow will be:
#### initialize package for the existing cluster
1. git init a repo for the existing cluster
2. export current resource configurations and push to the repo
3. kpt pkg init the package

#### apply asm-patch
4. kpt patch get ASM patch
5. kpt cfg set asm-patch key value
6. kpt patch apply my-pkg asm-patch

#### apply cloud-run-patch
7. kpt patch get Cloud Run patch
8. kpt cfg set cloud-run-patch key value
9. kpt patch apply my-pkg cloud-run-patch

#### review and apply
10. kpt pkg diff my-pkg
11. anthoscli apply

Please let me know if you have better ideas in your minds.

**Comment by phanimarupaka** [comment]
@nan-yu Is this issue still relevant in the context is kpt-v1 ? https://kpt.dev/installation/

**Comment by nan-yu** [comment]
Not relevant anymore. Closing it.
