### ISSUE TITLE
Function gatekeeper-validate fails parsing opa constraint template

### ISSUE THREAD

**Issue by nniikkoollaaii** [GoogleContainerTools/kpt#493]
Hey, 

I'm trying out your project in specific the [gatekeeper-validate function](https://googlecontainertools.github.io/kpt-functions-catalog/#validators)

I generated the following constraint template:

```
apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: registry
spec:
  crd:
    spec:
      names:
        kind: registry
      validation:
        # Schema for the `parameters` field
        openAPIV3Schema:
          properties:
            registry:
              type: string
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package registry

        violation[{"msg": msg, "details": {}}] {
          some container
          input_containers[container]
          #(, "quay.io/")
          not startswith(container.image, input.parameters.registry)
          msg := sprintf("image '%v' comes from untrusted registry", [container.image])
        }

        # read containers from various inputs

        # kubernetes admission review for kind pod
        input_containers[container] {
            container := input.request.object.spec.containers[_]
        }

        # kubernetes admission review for kind ???
        input_containers[container] {
            container := input.request.object.spec.template.spec.containers[_]
        }


        # deployment manifest
        input_containers[container] {
            input.kind = "Deployment"
            container := input.spec.template.spec.containers[_]
        }
```

This rego works on Rego Playground [Example](https://play.openpolicyagent.org/p/e9y1Wuypqh)

Using this constraint template with your function via this

`docker run -i -u $(id -u) -v $(pwd):/source gcr.io/kpt-functions/read-yaml -i /dev/null -d source_dir=/yaml_manifest_including_constraints_and_templates | docker run -i gcr.io/kpt-functions/gatekeeper-validate`

I get the following error message:

```
Error: 1 error occurred: templates["admission.k8s.gatekeeper.sh"]["registry"]:3: rego_parse_error: no match found
        violation[{"msg": msg, "details": {}}] { var container; input_containers[container]; not startswith(container.image, input.parameters.registry); assign(msg, sprintf("image '%v' comes from untrusted", [container.image])) }
                                                     ^
```

As you can see the rego parser changed my code from
`some container`
to
`var container`
which seem's to be not valid.
Rego Playground shows the same error after switching from "some" to "var"

I came across this [Issue](https://github.com/open-policy-agent/gatekeeper/issues/320) in the OPA Gatekeeper project with an similar problem.
This issue referenced an [commit to open-policy-agent/opa](https://github.com/open-policy-agent/opa/commit/f6b645822b41178b9646ff5175ce3bb61f542d75) from 12 Sep 2019

The user, who filed the issue, confirmed it works when OPA Gatekeeper released a new version.
From a contributor's comment I assume they updated the opa version

Could you please check the version of opa and/or gatekeeper you're using?

I can't remove the problematic line. It's still functional in Rego Playground but your function show's 
`Error: 1 error occurred: templates["admission.k8s.gatekeeper.sh"]["registry"]:3: rego_unsafe_var_error: expression is unsafe`
Probably Rego Playground is more lax?

**Comment by maxsmythe** [comment]
This looks like it's caused by the kpt-function running an older version of OPA, once a container has been built from this PR, the template should work:

https://github.com/maxsmythe/kpt-functions-sdk/pull/1

**Comment by nniikkoollaaii** [comment]
The link to your PR is invalid @maxsmythe 
In addition I can't manually find your PR?

**Comment by maxsmythe** [comment]
Argh, looks like some wires got crossed submitting the PR. Fixed. Here is the new change:

https://github.com/GoogleContainerTools/kpt-functions-sdk/pull/132
