### ISSUE TITLE
`kpt cfg` commands don't work on top-level lists

### ISSUE THREAD

**Issue by pwittrock** [GoogleContainerTools/kpt#510]
If the yaml file is a list `kpt cfg fmt` and other commands won't work on it as they expect a map at the top level.

**Comment by jijiew** [comment]
It looks to me that from code, there is a rule for fmt work on a yaml file that is a sequence (correct me if I misunderstood it)
that is:
the sequence have to have
	".spec.template.spec.containers": "name",
	".webhooks.rules.operations":     "",
in path.

**Comment by frankfarzan** [comment]
To repro, you can use a List as return by a kubectl:

kubectl get namespaces -o yaml

**Comment by mortent** [comment]
@jijiew I think your test looks correct. Can we simplify it a bit (mostly just reduce the number of fields in each of the list elements) and add a test for it to kyaml? Or maybe there is a test already?
And then I think we can just close this issue.
