### ISSUE TITLE
'kpt pkg get' truncates files after the first resouce '---' on Windows 10 pro

### ISSUE THREAD

**Issue by patflynn** [GoogleContainerTools/kpt#533]
Hey there,

I'm running through this demo on [this page](https://googlecontainertools.github.io/kpt/guides/consumer/get/), but I'm a bit puzzled by a few things.

1.
The docs contain this statement

> The package contains 2 resource configuration files – deploy.yaml and service.yaml. These are the same files that would typically be applied with kubectl apply.

I do not observe these yaml files in the cockroachdb directory, nor is it in the listing provided on the same page. Perhaps I am misunderstanding this portion?

2. 
The docs mention that the expected output of running:
`kubectl apply -R -f cockroachdb`
should be:
```
service/cockroachdb-public created
service/cockroachdb created
poddisruptionbudget.policy/cockroachdb-budget unchanged
statefulset.apps/cockroachdb created
```

However when I run this command I see
```
PS C:\Users\Patrick\IdeaProjects> kubectl apply -R -f .\cockroachdb\
service/cockroachdb-public created
```

Which is inline with what I expect from the available yaml.

3.
Finally if I run 
`PS C:\Users\Patrick> kubectl get all`
the resulting output does not match the expected output from the documentation:

```
NAME                         TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)              AGE
service/cockroachdb-public   ClusterIP   10.109.2.71   <none>        26257/TCP,8080/TCP   72s
service/kubernetes           ClusterIP   10.96.0.1     <none>        443/TCP              76s
```

I may be holding this wrong, but the demo sample doesn't seem to be working according to the instructions I see either in the kpt doc or the README for the sample.

**Comment by patflynn** [comment]
NM. I think I'm running into a Git+Windows line-endings issue.

**Comment by patflynn** [comment]
Re-opening and re-labeling.  It appears that the issue is that kpt get truncates the resource at the first '---' on Windows, so I'm only seeing the 'service' resource.

**Comment by jijiew** [comment]
@patflynn can you try to set auto crlf to false by doing:

git config core.autocrlf false

and then try to see if it works.

**Comment by patflynn** [comment]
This is what I suspected at first, but playing with that setting had no effect.  I also am able to git clone the k8s examples repo and the cockroachdb-statefulset.yaml is not truncated.

**Comment by jijiew** [comment]
> This is what I suspected at first, but playing with that setting had no effect. I also am able to git clone the k8s examples repo and the cockroachdb-statefulset.yaml is not truncated.

then, can you do git clone and check the cockroachdb-statefulset.yaml file to see what character is around ---.

Kpt does git clone internally and then add back each section of the yaml file which is seperated by "/n---/n", I suspect that this might be
the problem.

for example, od -t c cockroachdb/cockroachdb-statefulset.yaml will show me the characters in linux

**Comment by jijiew** [comment]
@patflynn I tried myself with a windows server + powershell setting. I was able to reproduce your issue. :)
git config core.autocrlf false
and then do kpt pkg get actually fix my problem. Here is what you can probably do:

1. git config core.autocrlf false
2. to confirm that it actually works:
 do git clone https://github.com/kubernetes/examples.git
and check the file ending character by:
(Get-Content staging\cockroachdb\cockroachdb-statefulset.yaml -Raw) -replace '\r','\r' -replace '\n','\n' -replace '\t','\t'
it will shows you the ending character, after setting to autocrlf false, it shall show characters like \n---\n (or \n as ending character)
3. go to a new dir, and do kpt pkg get https://github.com/kubernetes/examples/staging/cockroachdb cockroachdb-new
4. verify that statefulset.yaml contains the full content as git clone shows

Let me know if that works for you. I will close the issue, but feel free to reopen it once you are unable to get it work.

**Comment by patflynn** [comment]
I'm not on my windows machine right now, so I haven't verified this, although I'm sure your analysis is probably right.  However shouldn't kpt handle this case rather than just fail the way it does? It seems like it's likely to trip up many Windows users.

**Comment by jijiew** [comment]
> I'm not on my windows machine right now, so I haven't verified this, although I'm sure your analysis is probably right. However shouldn't kpt handle this case rather than just fail the way it does? It seems like it's likely to trip up many Windows users.

I agree, sent out a pr for fixing this:
https://github.com/kubernetes-sigs/kustomize/pull/2700
