### ISSUE TITLE
Releases page should include binary artifacts

### ISSUE THREAD

**Issue by ggilmore** [GoogleContainerTools/kpt#538]
https://github.com/GoogleContainerTools/kpt/issues/299 was closed, but the releases page still only publishes the source code with no binaries attached.

**Comment by drzero42** [comment]
Marking releases correctly (so it is possible to identify "latest" release) would also help tools (like [vk](https://github.com/cellpointmobile/vk)) that use the Github API to download and update releases.

**Comment by mortent** [comment]
This is planned for the next sprint, and it includes:
- Reuse the release notes script from [controller-runtime](https://github.com/kubernetes-sigs/controller-runtime/tree/master/hack/release) to generate release notes from PRs.
- Leverage goreleaser to create github releases with release notes and binaries attached.
- Add issue/PR templates to make sure we have a format that can be included in release notes and that captures information about any breaking changes.

**Comment by mortent** [comment]
Release 0.31.0 was released with the new setup. Binary artifacts and release notes are available at https://github.com/GoogleContainerTools/kpt/releases/tag/v0.31.0
