### ISSUE TITLE
wrong Node Kind when fetching pkg 

### ISSUE THREAD

**Issue by jlewi** [GoogleContainerTools/kpt#539]
I ran the following kpt pkg get command and got the error indicated below.

```
kpt pkg get git@github.com:jlewi/manifests.git/@blueprints manifests
fetching package / from git@github.com:jlewi/manifests to manifests/manifests

Error: manifests/manifests/common/ambassador/base/deployment-ambassador-patch.yaml: wrong 
Node Kind for  expected: MappingNode was SequenceNode: value: {- op: replace
  path: /spec/replicas
  value: 1}

```

It looks like files were fetched anyway. 

What sort of validation or processing is kpt pkg doing?

**Comment by jlewi** [comment]
Duplicate of #510

**Comment by Bobgy** [comment]
/reopen
This is not a duplicate of #510, because this happens when fetching the package.
Also, this error message still shows with `kpt version 0.36.1`.

**Comment by Bobgy** [comment]
This should in fact be
Duplicate of https://github.com/GoogleContainerTools/kpt/issues/1218
