### ISSUE TITLE
support for bounded setters

### ISSUE THREAD

**Issue by marklester** [GoogleContainerTools/kpt#540]
It would be useful to be able to set a valid set of options for setters and substitutions
```
kpt cfg create-setter proj/ image lts,beta.stable
```

**Comment by jpugliesi** [comment]
[I believe this should be possible via Enumerations](https://googlecontainertools.github.io/kpt/guides/producer/setters/#enumerations)

**Comment by phanimarupaka** [comment]
This feature is implemented as part of this PR https://github.com/kubernetes-sigs/kustomize/pull/2496. Next release will have this change.
