### ISSUE TITLE
[User Request] Declaratively invoke setters (and possibly functions) simultaneously

### ISSUE THREAD

**Issue by jpugliesi** [GoogleContainerTools/kpt#544]
As a maintainer of a repository of kpt package, I'd like to ensure that all package setters have been invoked (ideally pre-commit) so that the underlying manifests are rendered with the desired configuration in version control. This would at least help prevent inconsistencies that may arise when people directly modify the values in a `Kptfile`, while forgetting to propagate those changes by making the corresponding calls to `kpt cfg set`

As far as I can tell, it is currently only possible to [invoke setters imperatively](https://googlecontainertools.github.io/kpt/guides/consumer/set/#setters-explained). It seems the use case I've outlined above would be easier if it were possible to invoke setters declaratively, similar to how we can invoke functions declaratively. Something akin to:
```
# effectively kpt cfg set . ${SETTER} for all of the package's setters
kpt cfg set . 
```

More broadly, it would be nice to have a command to "ensure" that a Kptfile and its settings and functions are reflected in the underlying manifests, effectively: `kpt cfg set . && kpt fn run .`. Then it'd be simple to run something like `find . -name Kptfile -exec kpt cfg ensure {}` from the root of the repository.

Thoughts? I'd appreciate any additional ideas/approaches to address this

**Comment by phanimarupaka** [comment]
`kpt cfg set .` is one of our short term goals and thanks for bringing this up. 

Ensure is an interesting idea but combining set and fn should be something which should be thought about in terms of feasibility. Question arises, why not include pkg and live? so that ensure gets/updates, sets, validates and applies package. Can you elaborate on your end to end use case to give us more insights?

**Comment by mikebz** [comment]
#1107 is related.

**Comment by phanimarupaka** [comment]
@mikebz This is more related to declarative setters which is being tracked here. https://github.com/GoogleContainerTools/kpt/issues/1051

Marking this as duplicate.
