### ISSUE TITLE
[User Confusion]  `create-subst` silently creates new setters for not existing pattern values

### ISSUE THREAD

**Issue by yuwenma** [GoogleContainerTools/kpt#548]
When running 'kpt cfg create-subst SUB_NAME SUB_PARSING_VALUE --pattern SUB_PATTERN --value PATTERN_VAL' to create substitution. The "value" flag is "required" to refer to a setter. If the setter doesn't exist, the create-subst will create a setter for users. 

This silently creating new setters could cause user confusions and be more error-prone.

### Expected behavior

if the setter doesn't exist, block users from creating the substitutions until they create the setter first. 

#### Reason

User may have a typo in the value field. Current create-subst behavior will pass the command and creates a typo setter quietly. Users have no clue that they actually make a mistake, and it could take them longer time to find out the typo and clean up the bad substitution

**Comment by phanimarupaka** [comment]
Blocking might not be a good user experience. Users want the tool to understand user intent and work in most of the cases rather than throwing errors. To avoid confusion, we should add a warning message that the setter is being created which is addressed in this PR. https://github.com/kubernetes-sigs/kustomize/pull/2419

**Comment by yuwenma** [comment]
@phanimarupaka Just a quick check, do we still accept setter and substitution using the same name? Guess a warning for dup names is what user's looking for.

**Comment by phanimarupaka** [comment]
@yuwenma We do not anymore. https://github.com/kubernetes-sigs/kustomize/pull/2437
