### ISSUE TITLE
[User Confusion] `create-subst` silently accept bad values, assuming nested subst is supported but not

### ISSUE THREAD

**Issue by yuwenma** [GoogleContainerTools/kpt#549]
When creating substitution, its pattern can only contain setters but not substitution (nested substitution). 
```bash
kpt cfg create-subst SUBST_NAME SUBST_PARSING_VAL --pattern PATTERN --value PATTERN_NAME=SETTER_NAME
``` 

This is confusing in two ways:
1. When users use the cmd create new substitution, if they refer to a substitution in the value field, the command actually passes and creates a setter using the same substitution name. No warning or clue is given. (See [issue#548](https://github.com/GoogleContainerTools/kpt/issues/548) for related issue.)  

Since both setters and substitutions are defined under the `definitions` field and referred in the form of "$ref":"#/definitions/io.k8s.cli.TYPE.VALUE"}, it's straightforward for users to believe setter and substitutions can refer in the same way.

2. When users manually add the substitution in KptFile, they can use substitutions in the Marker/refs field (the same as value flag). No warnings or clues are given to bad KptFile. It's hard for customers to diagnose and fix the issue (especially create-subst can also silently create new setters under the same name, making things harder to break at early stage)

**Comment by phanimarupaka** [comment]
kpt doesn't support nested substitutions. Substitutions are only plain combination of setters as mentioned [here](https://googlecontainertools.github.io/kpt/reference/cfg/create-subst/). A setter and substitution can have same name as they are different semantically. I think that the action items are same as https://github.com/GoogleContainerTools/kpt/issues/550.
