### ISSUE TITLE
Add `kpt live` commands to kpt functions catalog

### ISSUE THREAD

**Issue by prachirp** [GoogleContainerTools/kpt#574]
As per discussion on helm template design:

"apply" is conceptually a sink function. We should have something like:
Fn |
<..> kubectl apply

**Comment by frankfarzan** [comment]
Upleveling this:

`kpt live apply` should also implement the functions spec, where resources to be applied are provided on stdin. Conceptually, a pipeline of functions can be constructed as such:

Source/Hydrate -> Transform/Validate -> Apply

**Comment by seans3** [comment]
`kpt live apply` on `stdin` has been recently implemented. If there are no args, `kpt live apply` uses `stdin`. An example would be:

```
kustomize build | kpt live apply
```
https://github.com/kubernetes-sigs/cli-utils/pull/143

**Comment by seans3** [comment]
We considered using the dash (`-`) to signify stdin (like `kubectl`), but we settled on no args. Let us know what you think. Now is the time to settle on these conventions before they get a lot of use.

**Comment by frankfarzan** [comment]
As part of this issue, we should document this `apply` to the catalog and document this flow:

https://googlecontainertools.github.io/kpt-functions-catalog/

**Comment by seans3** [comment]
The following `kpt live` commands now work on `stdin`: `apply`, `preview`, `diff`, and `destroy`.

**Comment by prachirp** [comment]
@seans3 It seems that `kpt live` expects multi-object yaml in `stdin` instead of accepting the resource list format that functions use. I tried running `kpt fn source example-configs | kpt live diff` and got an error `no matches for kind "ResourceList" in version "config.kubernetes.io/v1alpha1"`.
Can we start accepting List or ResourceList of configs on stdin?

**Comment by mikebz** [comment]
I believe this is addressed in the v1 branch: https://kpt.dev/reference/live/apply/
