### ISSUE TITLE
kpt fn run should be able to run source functions

### ISSUE THREAD

**Issue by prachirp** [GoogleContainerTools/kpt#587]
kpt does not allow sourcing non-valid yaml files. For example after running the below commands I expect expanded helm configs in the example directory, but it remains empty.

```
> helm create helloworld-chart; mkdir example
> kpt fn run example --mount type=bind,src=$(pwd),dst=/source --image gcr.io/kpt-functions/helm-template -- name=my-example chart_path=/source/helloworld-chart
```
```
> helm create helloworld-chart; mkdir example
> kpt fn source example | kpt fn run --mount type=bind,src=$(pwd),dst=/source --image gcr.io/kpt-functions/helm-template -- name=my-example chart_path=/source/helloworld-chart | kpt fn sink example
```

I also cannot get a package if it contains non-valid yaml files
```
kpt pkg get https://github.com/prachirp/kpt-functions-catalog.git/examples/helm-template/local_resource@helm-template-example .
```

We can work around this using docker, but as a package manager kpt should handle this:
```
helm create helloworld-chart; mkdir example
kpt fn source example |
docker run -i --mount type=bind,src=$(pwd),dst=/source gcr.io/kpt-functions/helm-template -d name=my-example -d chart_path=/source/helloworld-chart |
kpt fn sink example
```

A few ideas to fix this issue:
- Add a kptignore field containing a list of files to skip validation. This is similar to https://github.com/GoogleContainerTools/kpt/issues/517 but not specific to kpt live.
- Skip validation altogether, this will allow users to source arbitrary packages which may not be valid yaml. But it will also avoid the friction of having to set kptignore manually.

High level work for a kptignore solution:
1. Add ignored files to kustomize pkgio_reader, set the default files list as empty, add a function to set ignored files
2. Add ignored files to kptfile struct pkgfile.go as done for openapi, new string glob field 
3. Wire parsing ignored files from kptfile into pkg reader/writer
4. Change persistent prerun, currently kptfile has openapi definitions which kustomize parses and uses

**Comment by davinkevin** [comment]
This is a blocker for our clients (I can name them directly, but they are on our [website)](https://stack-labs.com/). 

We are using a lot `kustomize` and would like an integrated solution/pipeline like the documentation describe for our yaml management. 

I really upvote this feature ❤️

**Comment by aodinokov** [comment]
@prachirp , 
can it be that https://github.com/kubernetes-sigs/kustomize/pull/2709 is the reason why you were not able to see the files in ($pwd) in your original message?
First - because kpt by default was trying to set readonly mount (that's different behavior from docker --mount argument )
Second - it didn't work right. I noticed that 'kustomize-build' image didn't work with kpt for me because of that.
more details can be found here https://github.com/kubernetes-sigs/kustomize/pull/2709 . It fixes the issue and introduces explicit flag rw=true that has to be set if you want to make a read-write mount.

**Comment by prachirp** [comment]
Thanks @aodinokov for the fix!

@davinkevin the fix is in today's kpt release. Check out the examples [here](https://github.com/GoogleContainerTools/kpt-functions-catalog/tree/master/examples).

**Comment by davinkevin** [comment]
I've just tested it with the helm example. It works but I had to change paths in the example, because we can't have both relatively `helm-template/local-configs` and `(pwd)/helloworld-chart` at the same time in the second command. 

On the kustomize side (which was my first issue in https://github.com/GoogleContainerTools/kpt/issues/791), I still have some problem (with the image but not with the kustomize official binary). I don't think this is related to this but I prefer to share it:

```sh
Λ\: ./kpt pkg get "https://gitlab.com/davinkevin/Podcast-Server.git/distribution/kpt/podcast-server" podcast-server
fetching package /distribution/kpt/podcast-server from https://gitlab.com/davinkevin/Podcast-Server to podcast-server

/tmp/tmp-123 took 8s
Λ\: cat fn.yaml
───────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: fn.yaml
───────┼─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ # call `kpt fn run` on a directory containing this file, mounting the helm chart at /source
   2   │ apiVersion: v1
   3   │ kind: ConfigMap
   4   │ metadata:
   5   │   name: build
   6   │   annotations:
   7   │     config.kubernetes.io/function: |
   8   │       container:
   9   │         image: gcr.io/kpt-functions/kustomize-build
  10   │ data:
  11   │   path: /source
───────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

/tmp/tmp-123
Λ\: ./kpt fn run . --mount type=bind,src=(pwd)/podcast-server,dst=/source
[ERROR] Kustomize build command results in error: Error: accumulating resources: accumulateFile "accumulating resources from 'git::https://gitlab.com/davinkevin/Podcast-Server.git//distribution/kubernetes/base/': evalsymlink failure on '/source/git::https:/gitlab.com/davinkevin/Podcast-Server.git/distribution/kubernetes/base' : lstat /source/git::https:: no such file or directory", loader.New "stat /var/folders/z2/0d2vn4tn3_j7spd4v_t9y0s80000gn/T/: no such file or directory"

Error: exit status 1

/tmp/tmp-123
Λ\: kustomize build podcast-server/
apiVersion: v1
data:
  concurrent-download: "4"
...
```

Do you think we should open a new issue (or maybe the previous one) ?

PS: The binary of `kpt` hasn't be published on `brew` for the version `0.32.0` sadly 😓.

**Comment by prachirp** [comment]
@davinkevin Thanks for testing, I haven't seen that specific error before. I repro'd your error and see the same example run successfully using docker run so I created a new issue for it #879. I'll look into it this Friday or early next week.

**Comment by aodinokov** [comment]
@davinkevin , @prachirp 

the thing is that https://gitlab.com/davinkevin/Podcast-Server.git/distribution/kpt/podcast-server
uses network to get this:

```
y$ grep -Rni 'gitlab.com' podcast-server/
podcast-server/kustomization.yaml:5:- git::https://gitlab.com/davinkevin/Podcast-Server.git//distribution/kubernetes/base/
```

by default kpt doesn't allow you to access network. you need to do 2 things:

1. change your  fn.yaml to this:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: build
  annotations:
    config.kubernetes.io/function: |
      container:
        image: gcr.io/kpt-functions/kustomize-build
        network:
          required: true
data:
  path: /source
```

2. when call kpt add `--network` and optionally `--network-name` string args
