### ISSUE TITLE
Tab completion for kpt CLI

### ISSUE THREAD

**Issue by frankfarzan** [GoogleContainerTools/kpt#590]
Consider adding tab completion. For reference, what kubectl does:

https://kubernetes.io/docs/tasks/tools/install-kubectl/#enabling-shell-autocompletion

**Comment by lauchokyip** [comment]
Hi @frankfarzan , I would like to try tackling this one. :)  It's a great way for me to dig into kubectl autocompletion PR which just got merged few months ago but it would take some time for me to figure out how to apply kubectl autocompletion in kpt , hope you don't mind!

**Comment by mikebz** [comment]
@lauchokyip thanks for your help.  I do not think auto complete has been implemented @phanimarupaka and @droot can also chime in.

**Comment by phanimarupaka** [comment]
@mikebz Auto-complete is implemented in kpt already. I have extended it to functions as well with [this PR](https://github.com/GoogleContainerTools/kpt/pull/2449
) which will be released tomorrow.

You should enable it though using this command `kpt --install-completion`.

**Comment by phanimarupaka** [comment]
This has been released https://github.com/GoogleContainerTools/kpt/releases/tag/v1.0.0-beta.4
