### ISSUE TITLE
`--value` flag for `kpt cfg create-subst` is a misnomer

### ISSUE THREAD

**Issue by frankfarzan** [GoogleContainerTools/kpt#618]
This flag is specifies `PATTERN_MARKER=SETTER_NAME`.

The examples in `--help` also seem to conflate the value of a setter and the name of the setter:

```
  kpt cfg create-subst DIR/ image-tag nginx:v1.7.9 \
    --pattern IMAGE_SETTER:TAG_SETTER \
    --value IMAGE_SETTER=nginx \
    --value TAG_SETTER=v1.7.9
```

**Comment by phanimarupaka** [comment]
Substitutions are significantly simplified in latest release. --value flag is removed. 

https://googlecontainertools.github.io/kpt/reference/cfg/create-subst/

**Comment by phanimarupaka** [comment]
https://github.com/kubernetes-sigs/kustomize/pull/2419
