### ISSUE TITLE
How do you pronounce kpt?

### ISSUE THREAD

**Issue by simongottschlag** [GoogleContainerTools/kpt#641]
Hi,

We're in a meetup and haven't figured out how to pronounce kpt.

Is it:
- kept
- key pe te
- something else?

Thanks!

**Comment by a-hat** [comment]
From [https://googlecontainertools.github.io/kpt/](https://googlecontainertools.github.io/kpt/)

`Kpt (pronounced “kept”) is an OSS tool`

**Comment by simongottschlag** [comment]
"kept"

**Comment by MPV** [comment]
@simongottschlag https://github.com/GoogleContainerTools/kpt/search?q=pronounced (note the final `d`) 😛
