### ISSUE TITLE
Don't allow team instance to update non-setter fields

### ISSUE THREAD

**Issue by KeisukeYamashita** [GoogleContainerTools/kpt#645]
## What

As explained in the official document [here](https://googlecontainertools.github.io/kpt/guides/consumer/update/#commit-local-changes), teams can update any field of the fetched package whether the setter is configured or not.

I think it is better to restrict the team's changes on the non-setter configured field.

Also, what is the main use case of Setters? Is it a kind of API between `kfg cfg set` and upstream packages?

If teams can modify the fields by editing the resources directly, why teams use Setters and package publisher needs to configure it? 

Thanks in advance.

**Comment by KeisukeYamashita** [comment]
Sorry, self-solved.

I read this article [Kpt: Packaging up your Kubernetes configuration with git and YAML since 2014](https://opensource.googleblog.com/2020/03/kpt-packaging-up-your-kubernetes.html, Google Open Source Blog). It saids

> Alternatively, the package may define setters, allowing fields to be set programmatically using kpt cfg set. Setters streamline workflows by providing user and automation friendly commands to perform common operations.

So my question

> Is it a kind of API between kfg cfg set and upstream packages?

was right. But anyway, should Kpt allow teams to modify non-setter fields?

**Comment by mortent** [comment]
Setters allow producers to expose the main "knobs" for configuring the package, and kpt provides commands for consumers to discover them. But consumers will still have the full fidelity of the APIs available to them, either by editing the manifests directly or by defining new setters for the package.

If you are looking for validation that users does not change fields that shouldn't be changed, it should be possible to write kpt functions to validate this. Those functions can then be run by users locally or as part of you CI/CD pipeline.

**Comment by mortent** [comment]
@KeisukeYamashita Closing this issue, but feel free to reopen if my answer is does not fully address your question.
