### ISSUE TITLE
kpt fn source for json files

### ISSUE THREAD

**Issue by morgante** [GoogleContainerTools/kpt#647]
I have a workflow around functions where I run `kpt fn source` then a function imperatively.

```
kpt fn source provisioning/ l node generator/dist/my_func
```

This works fine for yaml files, but I'd like to also pick up any JSON configs stored in `provisioning/`. From the documentation, it's not clear how to do this (or why it doesn't work out of the box).

**Comment by frankfarzan** [comment]
Is your case to support directories with mixed JSON and YAML or only JSON?

Assuming directory is mixed: Preserving JSON file is straightforward. But we need to consider the UX where the result is written back to filesystem with a `kpt fn sink`. Is it acceptable to write it as YAML or do you expect it be preserved as JSON?

**Comment by morgante** [comment]
> Is your case to support directories with mixed JSON and YAML or only JSON?

Ideally, yes. If needed/simpler, I could convert from mixed to only JSON though.

> Is it acceptable to write it as YAML or do you expect it be preserved as JSON?

Yes, that is fine. In my use case, we're dumping output to an unrelated location where yaml is fine/expected.
