### ISSUE TITLE
Stdin argument for "kpt diff" command does not work

### ISSUE THREAD

**Issue by seans3** [GoogleContainerTools/kpt#669]
cli-utils issue: https://github.com/kubernetes-sigs/cli-utils/issues/170

/assign

**Comment by seh** [comment]
Even though kubernetes-sigs/cli-utils#179 recently disallowed use of standard input, can we take this issue's existence to imply that at some point we _will_ make it work, and that we'll then revert kubernetes-sigs/cli-utils#179?

**Comment by seans3** [comment]
@seh Yes. You are correct. We will make it work. I ran into problems on the fix and I wanted to fix the bug in the short term.

**Comment by seans3** [comment]
https://github.com/kubernetes-sigs/cli-utils/pull/175

**Comment by seans3** [comment]
@seh: https://github.com/kubernetes-sigs/cli-utils/pull/175

**Comment by seans3** [comment]
Available in next `kpt` release--closing.
