### ISSUE TITLE
kpt pkg sync recursively resolve dependencies

### ISSUE THREAD

**Issue by seaneagan** [GoogleContainerTools/kpt#686]
I have a use case for dependencies, but would need them to be recursively resolved, which `kpt pkg sync` doesn't appear to handle currently. Is there any opposition to adding this or just hasn't been priotizied yet?

**Comment by phanimarupaka** [comment]
This is part of our composite packages initiative. We are working on it(added to our milestones). Can you be a bit more specific and explain your use-case with example so that it would be helpful.

@mortent @frankfarzan FYI. A use-case for nested packages.

**Comment by phanimarupaka** [comment]
Assuming the issue has been resolved by its duplicate https://github.com/GoogleContainerTools/kpt/issues/794. Closing this as there is no response.
