### ISSUE TITLE
kpt fn for the transforming of a kustomization.yaml

### ISSUE THREAD

**Issue by artbegolli** [GoogleContainerTools/kpt#694]
One of my use cases is the ability to update `newTag` for a number of different kustomization yamls. 

The issue I've run into is that kustomization yamls aren't kubernetes resources and therefore fail the validation steps when inputting them to a kpt function. 
Although apiVersion and kind fields can be set in `Kustomization` files, the `metadata` field is missing and therefore can't implement `KubernetesObject`.

Is there any way for me to get around this? I understand that metadata is being used to generate a unique object key [here](https://github.com/GoogleContainerTools/kpt-functions-sdk/blob/master/ts/kpt-functions/src/types.ts#L322) so I'm not particularly hopeful - but any suggestions or potential work arounds are welcome.

**Comment by frankfarzan** [comment]
@monopole what's the reason kustomization manifest files do not conform to K8S API conventions? I think they are in fact implemented as Kubernetes Objects based on [1], so maybe it's just a short hand form? Use case is being able to treat them like any other KRM and manipulate them using configuration functions.


[1] https://github.com/kubernetes-sigs/kustomize/blob/master/api/types/kustomization.go#L15

**Comment by pwittrock** [comment]
Just add metadata to the kustomize toon.yaml

**Comment by artbegolli** [comment]
> Just add metadata to the kustomize toon.yaml

What version of kustomize are you using? Running `kustomize build` with the metadata field set fails.

**Comment by artbegolli** [comment]
Do we have any update here?

**Comment by mikebz** [comment]
Hi @artbegolli I think at one point in time we tracked some kustomize issues in this repo, but that's getting separated.  I wish GitHub had a way to copy that issue there.  @monopole has a similar issue been filed in the kustomize repo?  I don't want to leave this unanswered..

**Comment by monopole** [comment]
kustomize doesn't require apiversion/kind/metadata in a kustomization file, solely for reasons of brevity.

kustomize does allow it however, e.g. https://github.com/kubernetes-sigs/kustomize/blob/master/examples/helloWorld/kustomization.yaml
