### ISSUE TITLE
Composite Packages Umbrella issue

### ISSUE THREAD

**Issue by phanimarupaka** [GoogleContainerTools/kpt#715]
- [x] Gather requirements and define CUJs https://github.com/GoogleContainerTools/kpt/issues/716
- [ ] Design proposal
- [ ] Handle common setters across packages.

**Comment by mikebz** [comment]
thoughts on potentially linking to the other issues in the list?

**Comment by phanimarupaka** [comment]
Setters related part is addressed here. https://github.com/GoogleContainerTools/kpt/issues/859
