### ISSUE TITLE
Using Kpt as an SDK

### ISSUE THREAD

**Issue by cflewis** [GoogleContainerTools/kpt#722]
I would like to use Kpt programatically from my own Go code.

Almost all Kpt code is hidden behind `internal/` making it impossible to call into the libraries. I understand that this is to allow for making breaking changes whenever, but I would be happy to accept this contract and just pin the module version.

The Cobra commands are not hidden behind `internal/` and so I could call those, but that seems pretty wonky and I am guessing has no stability guarantee either. Calling the commands would be using strings for the args, so I'd lose type safety there.

I would prefer not to have to bundle the `kpt` binary and shell out to it if I can help it because, as with calling the Cobra commands, I lose any type safety :disappointed: 

What's the best course of action here?

**Comment by seans3** [comment]
@cflewis Just an acknowledgment that we've seen your question. I will get back to you shortly.

**Comment by seans3** [comment]
@cflewis 

1. For the `kpt live` code, you can go to the `cli-utils` repository: https://github.com/kubernetes-sigs/cli-utils

2. For the `kpt cfg` code, you can go to the `kustomize` repository: https://github.com/kubernetes-sigs/kustomize/tree/master/cmd/config

3.  For the `kpt fn` code, you can go to the `kustomize` repository: https://github.com/kubernetes-sigs/kustomize/tree/master/cmd/config

4. For the rest of the code there is currently no other option beyond getting the `cobra.Command` and running that.

**Comment by seans3** [comment]
If there is no further discussion on this issue, I will close it soon.

**Comment by cflewis** [comment]
SGTM, thank you 😀
