### ISSUE TITLE
kpt cfg create-setter should return a warning when it couldn't find any matching fields and/or values

### ISSUE THREAD

**Issue by nan-yu** [GoogleContainerTools/kpt#727]
I created a setter with a value that doesn't exist in the resources. I would expect a warning.
e.g.: `kpt cfg create-setter cluster-1 no_match foobar`

**Comment by nan-yu** [comment]
Similarly, if create-setter couldn't find any matching fields, it should return a warning.
`kpt cfg create-setter cluster-1/ unknow_field 3 --field "unknown"`

**Comment by phanimarupaka** [comment]
This has been addressed and released.
