### ISSUE TITLE
Improve output format from list-setters

### ISSUE THREAD

**Issue by mortent** [GoogleContainerTools/kpt#731]
- list-setters output seems polluted. Suggestion: Separate out subs and setters by a new line, and have headers for both.
- Can we simplify the sub list:
```
  SUBSTITUTION                       PATTERN                       REFERENCES
  image-tag-sub   gcr.io/kpt-dev/helloworld-gke:IMAGE_TAG_SETTER   [image-tag]
```
to 
```
  SUBSTITUTION                       PATTERN                      
  image-tag-sub   gcr.io/kpt-dev/helloworld-gke:[image-tag]
```
- list-setters also include substitutions when we have separate commands elsewhere.

**Comment by phanimarupaka** [comment]
We will be getting rid of substitutions soon. So we need not implement this.
