### ISSUE TITLE
Consider conflating the notions of setters and substitutions

### ISSUE THREAD

**Issue by mortent** [GoogleContainerTools/kpt#736]
As we’re still not 1.0, can we try harder to conflate the notions of Setter and Substitution?  make the former (Setter) a special (whole-field) case of the latter (Substitution)  instead of a different thing?  everyone wants to change the image tag, so introduce that - then introduce how much easier it is to set the whole field - i.e. change the replicas field.  If this cannot (or should not) be done, why?  that should be made clear in the Guide to Substitutions.

**Comment by phanimarupaka** [comment]
This is being tracked here. https://github.com/GoogleContainerTools/kpt/issues/1303
