### ISSUE TITLE
question regarding combined usage

### ISSUE THREAD

**Issue by MarcoSchaar** [GoogleContainerTools/kpt#740]
Hi,
searching for some documentation, whether advantages of kpt in updating packages could be combined with skaffold for deployment.
appreciate any hints.
Cheers
Marco

**Comment by seans3** [comment]
@MarcoSchaar Thanks for reaching out. I will research and get back to you.

**Comment by MarcoSchaar** [comment]
Hi,
based on some examples, found a working setup with setters and substitutions.
