### ISSUE TITLE
Provide a way to easily set prefix/infix/suffix for resources in a package

### ISSUE THREAD

**Issue by mortent** [GoogleContainerTools/kpt#742]
If the same package are going to be installed multiple times in the same namespace, it is important that the resources have unique names. Currently it is possible to do this with substitutions, but it gets hard to maintain as new resources are being added to the package. Basically, a new substitution will be needed for every resource in the package.

We should see if there is a better way to do this with kpt/kustomize.

**Comment by mortent** [comment]
An example of where substitutions are somewhat insufficient can be found at https://github.com/mortent/solutions-modern-cicd-anthos/tree/KptFunction/krm/kpt/cicd_cluster. In this case we require 10 substitutions to cover only 3 resources. 
This example is based on an exercise of turning this example https://github.com/janetkuo/solutions-modern-cicd-anthos/tree/krm-clusters/krm/cicd_clusters into a kpt package

**Comment by mikebz** [comment]
@mortent is this still relevant given the new designs?  If not please close.

**Comment by phanimarupaka** [comment]
@mikebz Yes. Search and Replace(https://github.com/GoogleContainerTools/kpt/issues/961) in combination with deprecating substitutions(https://github.com/GoogleContainerTools/kpt/issues/1303) would solve this.

**Comment by bgrant0607** [comment]
This issue is the same as the one that motivated the analogous feature in kustomize.
https://github.com/kubernetes/enhancements/blob/master/keps/sig-cli/0008-kustomize.md#long-standing-issues

The tricky part is finding references, which can't be done via naive search and replace. 
https://github.com/kubernetes-sigs/kustomize/blob/master/api/konfig/builtinpluginconsts/namereference.go

**Comment by phanimarupaka** [comment]
Search and Replace in kpt is more context aware of KRM resource files. That differentiates it from the native search and replace. It leverages syntax from [yq](https://mikefarah.gitbook.io/yq/) to find the references.
