### ISSUE TITLE
Function result suggested values cannot be object typed

### ISSUE THREAD

**Issue by dflemstr** [GoogleContainerTools/kpt#747]
In #291 it was discussed whether there would need to be support for object-typed suggested values.  We have now realized that it is quite common to want to suggest object-typed values, or really any JSON-structured value.

I suspect this should be an easy change, and I can submit PRs to the following locations if deemed appropriate:

  * https://github.com/kubernetes-sigs/kustomize/blob/a8952207438ca8ec985b902dd35cdeaf077c9db2/kyaml/kio/byteio_reader.go#L44
  * https://github.com/kubernetes-sigs/kustomize/blob/a8952207438ca8ec985b902dd35cdeaf077c9db2/kyaml/kio/byteio_reader.go#L92
  * https://github.com/GoogleContainerTools/kpt-functions-sdk/blob/e7187d05f14c9343d49754c8cce264344271063a/ts/kpt-functions/src/io.ts#L115

Please help me identify other affected locations

**Comment by prachirp** [comment]
@dflemstr Thanks for the SDK change, I also don't know of any other places that need to be updated.
