### ISSUE TITLE
Irrelevant global flags pollute `--help` output

### ISSUE THREAD

**Issue by frankfarzan** [GoogleContainerTools/kpt#749]
In latest release of kpt, there are some "global" flags that are not applicable to all commands:

```
Global Flags:
      --add_dir_header                   If true, adds the file directory to the header
      --alsologtostderr                  log to standard error as well as files
      --as string                        Username to impersonate for the operation
      --as-group stringArray             Group to impersonate for the operation, this flag can be repeated to specify multiple groups.
      --cache-dir string                 Default HTTP cache directory (default "/Users/frankf/.kube/http-cache")
      --certificate-authority string     Path to a cert file for the certificate authority
      --client-certificate string        Path to a client certificate file for TLS
      --client-key string                Path to a client key file for TLS
      --cluster string                   The name of the kubeconfig cluster to use
      --context string                   The name of the kubeconfig context to use
      --insecure-skip-tls-verify         If true, the server's certificate will not be checked for validity. This will make your HTTPS connections insecure
      --k8s-schema-path string           path to the kubernetes openAPI schema file (default "./openapi.json")
      --k8s-schema-source string         source for the kubernetes openAPI schema. Default is to first try to fetch it from the cluster given by the context and fall back to the builtin schema
      --kubeconfig string                Path to the kubeconfig file to use for CLI requests.
      --log-flush-frequency duration     Maximum number of seconds between log flushes (default 5s)
      --log_backtrace_at traceLocation   when logging hits line file:N, emit a stack trace (default :0)
      --log_dir string                   If non-empty, write log files in this directory
      --log_file string                  If non-empty, use this log file
      --log_file_max_size uint           Defines the maximum size a log file can grow to. Unit is megabytes. If the value is 0, the maximum file size is unlimited. (default 1800)
      --logtostderr                      log to standard error instead of files (default true)
      --match-server-version             Require server version to match client version
  -n, --namespace string                 If present, the namespace scope for this CLI request
      --password string                  Password for basic authentication to the API server
      --request-timeout string           The length of time to wait before giving up on a single server request. Non-zero values should contain a corresponding time unit (e.g. 1s, 2m, 3h). A value of zero means don't timeout requests. (default "0")
  -s, --server string                    The address and port of the Kubernetes API server
      --skip_headers                     If true, avoid header prefixes in the log messages
      --skip_log_headers                 If true, avoid headers when opening log files
      --stack-trace                      print a stack-trace on failure
      --stderrthreshold severity         logs at or above this threshold go to stderr (default 2)
      --token string                     Bearer token for authentication to the API server
      --user string                      The name of the kubeconfig user to use
      --username string                  Username for basic authentication to the API server
  -v, --v Level                          number for the log level verbosity
      --vmodule moduleSpec               comma-separated list of pattern=N settings for file-filtered logging
```

For example, there are API server-related flags that do not make sense for `kpt fn`. In addition, the kitchen sink of
flags obfuscate `--help` output.

**Comment by mortent** [comment]
So the flags here do actually apply to all commands, although for most users they are not relevant. The server-related flags allow users to use an openapi schema from a cluster instead of the schema complied into kpt.

But even among these flags, most of them will almost certainly never be used and are only available because they are available in the kubectl libraries we depend on. We can hide most of them. If someone asks for any of them in the future, we can consider making them visible again.

**Comment by frankfarzan** [comment]
How does server-related flags apply to e.g.:

kpt fn
kpt cfg tree

?

I don't think it generally applies to all commands.

**Comment by mortent** [comment]
We have the `--k8s-schema-source` global flag that can configure kpt to fetch the openapi schema from a k8s cluster. This is where the server-related flags can be relevant for many kpt commands and is why they are added at the top-level cobra command.

**Comment by frankfarzan** [comment]
Agree that some command will need this, but more important is that not every command needs this. So showing a kitchen-sink of irrelevant flags for those commands is confusing at worse and annoying at best.

Take, `kpt fn run` as an example. As a user, I'd be confused as to what providing `--kubeconfig` flag does (Nothing). It also forces us to prefix flags. Example is we want to have `--user` to mean the docker user:

https://github.com/kubernetes-sigs/kustomize/pull/2890#issuecomment-680301847

**Comment by mortent** [comment]
I agree this doesn't make sense for all commands. But it is a tradeoff between having a consistent set of global flags across all commands vs different flags for each command. Since we will need to have the `--user` flag for every command that might talk to the cluster, we should probably avoid that flag for `kpt fn run`.

`kpt fn run` is actually an example where I think the cluster flags could actually be pretty useful. While we haven't done the work on this yet, it would be pretty useful to be able to provide an openapi schema to the functions that are appropriate for the k8s version that are being used and includes the CRDs. https://github.com/kubernetes-sigs/kustomize/issues/2861 is an example of something we want to do which would be very helpful for https://github.com/GoogleContainerTools/kpt-functions-catalog/tree/master/functions/go/set-namespace

We can take a look a the help strings, but I think we should be careful about changing the help strings for the commands we inherit from kubectl.

**Comment by frankfarzan** [comment]
To clarify there are two problems today for `kpt fn run`:

1. Global flags don't do anything today, so they're misleading.
2. They're also polluting the help message for actual information the user cares about.

So it's a double whammy.

So I'm going to insist that at least #2 is addressed.

**Comment by mortent** [comment]
Most of the global flags were hidden with https://github.com/GoogleContainerTools/kpt/pull/888. All flags are documented in https://googlecontainertools.github.io/kpt/reference/#global-flags
Does that address #2?

So one option to remove most of the global flags, is to remove the option to let users fetch the openapi schema from the cluster. We had this as the default a while back, but changed the default to use the builtin schema pretty recently. We could require that users download the openapi schema from the cluster with the [fetch-k8s-schema](https://googlecontainertools.github.io/kpt/reference/live/fetch-k8s-schema/) command and then reference it on disk with the `--k8s-schema-source=file` flag.

**Comment by frankfarzan** [comment]
It's improved. Couple of things:

1. I'd assume that most of the flags (even the ones hidden in #888) are useful for `kpt live` commands that actually need to talk the API server? For example, does `kpt live apply --as Bob` do as you expect? Or do these flags only used for fetching OpenAPI document?
2. IMO, `PersistantFlags` is not what we want for a tool like `kpt`, but understand they're inherited from upstream so may be hard to change. What we actually want is for each command to conditionally add these flags (e.g. `addCommonAPIServerFlags) depending on whether they're applicable. That way, they're consistent and useful anywhere they're actually needed.

**Comment by Shell32-Natsu** [comment]
@frankfarzan @mortent If we want to use `--user` (or something else) in command `kpt fn run` we have to had a common understanding of these global flags at first. #933 #939 #945 #951 are blocked.

**Comment by phanimarupaka** [comment]
@mortent @frankfarzan @Shell32-Natsu kpt doesn't print global flags now. Can we close this.
