### ISSUE TITLE
Support custom ordering of resources during apply and prune

### ISSUE THREAD

**Issue by mortent** [GoogleContainerTools/kpt#756]
We currently do some ordering of resources before apply, but this is based on a static set of rules in kpt. We want to support custom ordering where users can specify dependencies between resources and kpt will build a plan for how to apply the resources according to those dependencies. 
There are at least three different types of ordering that we might want to support:
* Resource A must be applied before resource B is applied
* Resource A must be applied and be reconciled before resource B is applied
* Resource A must be applied before resource B and the value of a property on resource A must be used to set a property on resource B before B is applied.

**Comment by toumorokoshi** [comment]
Hi @mortent! Is it documented anywhere what the kpt apply ordering is?

While this feature is still landing, I'm looking at trying to order my applies by hand. Namely I have a namespace and object yaml that I'd like to apply namespace-first.
