### ISSUE TITLE
Align config functions SDKs

### ISSUE THREAD

**Issue by prachirp** [GoogleContainerTools/kpt#757]
The typescript, golang, and starlark SDKs have different functionality. We should add to the libraries to make building functions easy for users. Optimize user experience with the following:

- standardize if arguments belong in the data or spec fields of the function config
- generic struct for the function config and functions to get arguments from function config
- generic way to get environment variables or function config arguments
- standardize how config functions throw different types of errors: all errors should be to stderr, library function can throw errors that have similar structure and language
- write SDK documents that clarify how to do all of the above

**Comment by morgante** [comment]
I'd also suggest we should update the [examples](https://github.com/GoogleContainerTools/kpt-functions-sdk/blob/master/go/pkg/functions/gatekeeper/validate.go) to use a common framework.

**Comment by mikebz** [comment]
@mengqiy
