### ISSUE TITLE
Gatekeeper function should use the Go SDK

### ISSUE THREAD

**Issue by frankfarzan** [GoogleContainerTools/kpt#762]
Currently, Gatekeeper function:

https://github.com/GoogleContainerTools/kpt-functions-sdk/blob/master/go/pkg/functions/gatekeeper/validate.go

Doesn't use the Kpt Go SDK:

https://googlecontainertools.github.io/kpt/guides/producer/functions/golang/

It uses an early minimal Go library which was built to unblock Gatekeeper before an official SDK was released. We should refactor Gatekeeper function and delete that purpose-built library.

**Comment by prachirp** [comment]
Once it uses the Go SDK we can move it into kpt-functions-catalog repo

**Comment by mengqiy** [comment]
As other golang-based kpt functions, gatekeeper should use `sigs.k8s.io/kustomize/kyaml`.

**Comment by mengqiy** [comment]
Done in https://github.com/GoogleContainerTools/kpt-functions-catalog/pull/197
