### ISSUE TITLE
Unable to run kpt exec runtime

### ISSUE THREAD

**Issue by prachirp** [GoogleContainerTools/kpt#768]
I want to run the label namespace kpt function using the exec runtime but am unable to using the instructions [here](https://googlecontainertools.github.io/kpt/guides/producer/functions/exec/).

Steps to repro:
- Using kpt v0.30.1.
- Check out kpt-functions-sdk git repo.
- Run from sdk repo root directory: `kpt fn run example-configs --enable-exec --exec-path node ts/demo-functions/dist/label_namespace_run.js -- label_name=color label_value=orange`

I am able to source and execute the functions separately by running: `kpt fn source example-configs | node ts/demo-functions/dist/label_namespace_run.js -d label_name=color -d label_value=orange`

**Comment by mortent** [comment]
@prachirp Do we think this is a problem with the documentation being out-of-date, or is this functionality broken in the latest kpt release?

**Comment by prachirp** [comment]
This functionality is broken as I tried a lot of different variations of the command hoping it would work like building an executable file, putting quotes around "node ts/...", etc.

**Comment by prachirp** [comment]
This is a documentation issue. I had been trying to pass "node ts/demo-functions/dist/label_namespace_run.js" as the exec path and it wasn't able to run it, even after passing as a double-quoted string. I had to package the function into an executable to get it to work. Giving the steps below.

Still starting from sdk repo root dir:
1. `npm install -g pkg`
2. `npx pkg ts/demo-functions/dist/label_namespace_run.js`
3. `kpt fn run example-configs --enable-exec --exec-path ./label_namespace_run-macos -- label_name=color label_value=orange`

**Comment by mortent** [comment]
Sounds good. Can you create a PR with an update for the docs?

**Comment by prachirp** [comment]
Yea, I'm working on it.
