### ISSUE TITLE
Create a release workflow for catalog go functions

### ISSUE THREAD

**Issue by prachirp** [GoogleContainerTools/kpt#781]
Create a workflow to release catalog go functions to http://gcr.io/kpt-functions. This will be similar to https://github.com/GoogleContainerTools/kpt-functions-sdk/blob/master/.github/workflows/release-gatekeeper-function.yaml

**Comment by haiyanmeng** [comment]
If a kpt fn docker image (such as `set-namespace`) is implemented in different languages, will the GCR be able to differentiate them somehow?

**Comment by prachirp** [comment]
GCR won't differentiate between docker images. We don't have multiple functions in different languages yet, but we can probably give them different names to mark the difference.

**Comment by haiyanmeng** [comment]
https://github.com/GoogleContainerTools/kpt-functions-catalog/pull/72 should fix this.
I don't know why this is created under the kpt repo instead of `kpt-functions-catalog` repo.

**Comment by prachirp** [comment]
kpt-functions-catalog and kpt-functions-sdk both use kpt Github issue tracker for project management and kpt website for documentation so users have one place to file issues and search docs.

**Comment by prachirp** [comment]
This was fixed since https://github.com/GoogleContainerTools/kpt-functions-catalog/pull/76
