### ISSUE TITLE
Handle warnings/messages without printing to stdout

### ISSUE THREAD

**Issue by phanimarupaka** [GoogleContainerTools/kpt#782]
Currently we print warnings/messages to stdout which makes it hard to test. It is not appropriate way of doing it. Figure out a better way to handle them.

**Comment by phanimarupaka** [comment]
@mikebz @runewake2 This is a broader change which should be done across multiple commands. We are currently migrating code to kpt from kustomize and this can be taken care during that migration. I don't think we should invest time in refactoring code in kustomize for now. @runewake2 However, I am happy to give more context about this issue to follow better code hygiene for the commands one might develop in the future.

**Comment by mikebz** [comment]
Does this mean that this task can be decomposed and we can start chipping away at it?  Can some progress be made here?  Or does this message mean that we should punt on this and just focus on better architecture going forward?

**Comment by phanimarupaka** [comment]
`Focus on better architecture going forward` => yes. Progress is already being made in the new commands we are writing in kpt. Probably coming up with a doc which serves as a style guide for kpt developers would be a decent closure for this issue. Either I can do it or help @runewake2 write the doc.

**Comment by mikebz** [comment]
I think the doc is best written by someone who has already worked on some commands.  You can feel free to rename/reassign this and put it in the backlog or leave it here if this is an active task.

**Comment by runewake2** [comment]
Where do you envision this doc living? Should we add a section to `CONTRIBUTING.md` about Contributing Code? Or will this be a larger styles and practices guide?

Agree with @mikebz here as well. My coding experience has a lot more Java and C# influence than Go and my patterns reflect that. I'd likely inject some of that into docs still. Happy to advise on patterns I discover though and contribute sections for them.

**Comment by phanimarupaka** [comment]
Yes. `CONTRIBUTING.md` would be a better place to do so. I think we should add such best practices to `CONTRIBUTING.md` and this might be a good start for that. Other things I see we could add is guidelines around writing tests, command reference style guide etc.

**Comment by phanimarupaka** [comment]
This is no longer relevant as kpt v1 prints messages using a print layer.
