### ISSUE TITLE
`kpt cfg list-setters` don't show substitutions by default

### ISSUE THREAD

**Issue by pwittrock** [GoogleContainerTools/kpt#783]
The substitutions are not directly settable, and clutter the `list-setters` output.  Showing the substitutions should be off by default and enabled with a flag.

**Comment by prachirp** [comment]
cc @phanimarupaka Can you take a look at changing `list-setters`?

**Comment by phanimarupaka** [comment]
@pwittrock Agree. Raised a PR.
