### ISSUE TITLE
Typescript functions SDK 0.14.2 errors out on missing functionConfig

### ISSUE THREAD

**Issue by yhrn** [GoogleContainerTools/kpt#803]
Previously `Configs.getFunctionConfigValue()` would return undefined if a `functionConfig` was not provided when invoking a kpt function and this is still how it should behave according to the API comments but in 0.14.2 an error with the message "functionConfig expected, instead undefined" is raised instead.

**Comment by frankfarzan** [comment]
@prachirp This is probably related to your recent changes to getFunctionXXX family of functions.

**Comment by prachirp** [comment]
Hey @yhrn , I had done some refactoring to the sdk that caused this. Please upgrade to 0.14.3 for the fix.
