### ISSUE TITLE
When setter has same name as substitution set replaces entire value

### ISSUE THREAD

**Issue by ashlineldridge** [GoogleContainerTools/kpt#810]
When creating a substitution, my inclination was to create the substitution with the same name as the setter that it referenced. Kpt allows me to do this but when I call `kpt cfg set` the entire value is replaced by the setter rather than being substituted.

For example if I create a new substitution and setter:

```
 kpt cfg create-subst config tld --field-value https://google.com --pattern 'https://google.${tld}'
```

Kpt will create both substitution and setter with the name `tld` and the resource will look something like:

```
spec:
  url: https://google.com # {"$kpt-set":"tld"}
```

If I then call:

```
 kpt cfg set config tld io
```

The resource will be modified to:

```
spec:
  url: io # {"$kpt-set":"tld"}
```

I would have expected that either Kpt wouldn't allow me to create a substitution with the same name as a setter or (probably preferably) would use a different annotation for the substitution such as `# {"$kpt-subst":"tld"}`.

**Comment by mortent** [comment]
@ashlineldridge Thanks for reporting this. 
This is a bug. We don't allow having the same name on a substitution and a setter, but this isn't enforced properly when referencing a non-existent setter that ends up being created together with the substitution.

**Comment by phanimarupaka** [comment]
This issue has been addressed in the above PR. You can see this update in next kpt release.
