### ISSUE TITLE
Running kpt live apply in a non-initialized directory hangs

### ISSUE THREAD

**Issue by morgante** [GoogleContainerTools/kpt#825]
When I run `kpt live apply` in a package directory immediately after running `kpt pkg get` it hangs with no output.

The correct command is `kpt live apply .` but the behavior when a directory isn't provided is very confusing.

**Comment by phanimarupaka** [comment]
@mortent @seans3 I see that the live commands are waiting for stdin if there is no DIR specified which is confusing the user. What do you think is the UX for such cases?

**Comment by mortent** [comment]
So I think we have two options here if we want to address this. 

We can adopt the `-` convention used by kubectl to signal that we should read from stdin. I'm not crazy about this idea, and we would need to adopt it across all kpt commands to be consistent.

We can see if there is a way we can distinguish between `kpt live apply` and `kpt cfg cat /my-folder | kpt live apply` so we can exit with an error in the first situation. Just trying with the unix `less` command, it does actually handle this. Looks like there is a way we can check this with go: https://stackoverflow.com/a/26567513. We should try this out, although we need to make sure we don't break windows support by doing this.

**Comment by phanimarupaka** [comment]
This was in v0 and no longer an issue in kpt v1. Closing this. Please reopen if you have any concerns.
