### ISSUE TITLE
Behavior change 0.24.0 to 0.30.0 - are Kptfile's required?

### ISSUE THREAD

**Issue by jlewi** [GoogleContainerTools/kpt#831]
Our CI started picking up the latest kpt release 0.30.0 and we noticed this appears to have caused our existing configs to break. 
kubeflow/gcp-blueprints#89

The error is

```
INFO|2020-07-15T04:02:25|/workspace/testing-repo/py/kubeflow/testing/util.py|46| Running: kpt cfg set ./upstream/manifests/stacks/gcp gcloud.core.project kubeflow-ci-deployment 
cwd=/workspace/blueprint-repo/kubeflow
INFO|2020-07-15T04:02:25|/workspace/testing-repo/py/kubeflow/testing/util.py|61| Subprocess output:

INFO|2020-07-15T04:02:25|/workspace/testing-repo/py/kubeflow/testing/util.py|72| set 0 fields
INFO|2020-07-15T04:02:25|/workspace/testing-repo/py/kubeflow/testing/util.py|72| Error: stat upstream/manifests/stacks/gcp/Kptfile: no such file or directory
```

Are Kptfile's now required? Our packages don't have Kptfiles as of yet.

Furthermore, as the [logs show](https://github.com/kubeflow/gcp-blueprints/issues/89#issuecomment-658534964) previous invocations of the kpt command succeeded.

**Comment by jlewi** [comment]
My conjecture is that we have the old "partialSetters" method that didn't rely on Kptfile setters and substitutions and that is breaking things

**Comment by mortent** [comment]
@jlewi As part of a discussion around how we could deprecate the old style setters, we realized a few days ago that they have been broken since v0.27.0. 
We do plan on deprecating this soon, so I just want to get an idea about how much effort it is for you to migrate? We have been discussing providing a command for upgrading, but reality is that partial setters almost certainly will require some manual intervention as they can't be automatically be migrated to substitutions.

**Comment by jlewi** [comment]
@mortent Thanks for confirming. I already started upgrading our kptfiles. I don't think it will be too painful; I probably won't wait for any upgrading tool.

**Comment by jlewi** [comment]
@mortent Are previous releases available somewhere? It looks like the releases page doesn't include binary assets:
https://github.com/GoogleContainerTools/kpt/releases/tag/v0.24.0

**Comment by mortent** [comment]
@jlewi Yeah, old releases are available in the gcs bucket, but there is not link to it. The 0.24.0 release (for linux) is available at https://storage.googleapis.com/kpt-dev/releases/v0.24.0/linux_amd64/kpt_linux_amd64-v0.24.0.tar.gz

**Comment by phanimarupaka** [comment]
Old setters should work fine from next release.

https://github.com/kubernetes-sigs/kustomize/pull/2743
