### ISSUE TITLE
Document how to run privileged function docker containers

### ISSUE THREAD

**Issue by frankfarzan** [GoogleContainerTools/kpt#832]
For functions that need network or host access, we need to provide examples of how to use such flags:

kpt fn run local-configs --mount type=bind,src=$(pwd)/helloworld-chart,dst=/source
kpt fn run local-configs --network

We can point to examples functions in the catalog that need these.

**Comment by frankfarzan** [comment]
@prachirp This may be done already?

**Comment by prachirp** [comment]
Yes, these examples are in the `kpt fn run` reference doc https://googlecontainertools.github.io/kpt/reference/fn/run/
