### ISSUE TITLE
kpt became excruciatingly slow - due to problem contacting kube APIServer

### ISSUE THREAD

**Issue by jlewi** [GoogleContainerTools/kpt#834]
I was running `kpt cfg` commands and suddenly they started becoming painfully slow. `kpt version` was also very slow.

```
time kpt version
0.31.0

real	0m15.362s
user	0m0.056s
sys	0m0.030s
```

I than ran it with logs

```
kpt version -v 10
I0717 16:37:35.884974   31578 loader.go:375] Config loaded from file:  /home/jlewi/.kube/config
I0717 16:37:35.885453   31578 round_trippers.go:423] curl -k -v -XGET  -H "Accept: application/json" -H "User-Agent: kpt/0.31.0" 'https://34.73.245.80/openapi/v2'
I0717 16:37:51.261119   31578 round_trippers.go:443] GET https://34.73.245.80/openapi/v2  in 15375 milliseconds
I0717 16:37:51.261183   31578 round_trippers.go:449] Response Headers:
0.31.0
```

So it looks like the problem is that kpt is trying to contact the APIServer of my current K8s cluster and for whatever reason my current cluster wasn't very responsive.

When I switched my kube context to a working cluster it became response again.

This was very frustrating and took me a long time to figure out. 

It wasn't at all obvious to me that kpt would be making calls to my cluster and become unresponsive due to my master. 

I was in the midst of refactoring my KptFile to upgrade from legacy to new substitutions. My initial assumption was that I had added too many setters or created some sort of recursion that was causing problems. 

I understand this might not be a bug as there are valid use cases for pulling down the K8s openapi validation. Just wanted to provide feedback and provide a record in case others hit this as well.

**Comment by mortent** [comment]
@jlewi Thanks for reporting this. We put this in so kpt can use the openapi schema from the actual cluster rather than the one complied into kpt. But clearly 15 seconds delay each time is unacceptable. I will look into whether we can have a more aggressive timeout when the cluster is not responsive.

**Comment by mortent** [comment]
It is also possible to force kpt to use the built-in openapi schema rather than trying to contact the cluster by setting the flag `--k8s-schema-source=builtin`

**Comment by mortent** [comment]
We have changed the default in the v0.32.0 version of kpt, so it will no longer try to contact the APIServer unless the user specifies that the source for the openapi schema should be the kubernetes cluster with the `--k8s-schema-source=cluster` flag.
