### ISSUE TITLE
kpt pkg get should exit gracefully when it succeeds in getting a package

### ISSUE THREAD

**Issue by prachirp** [GoogleContainerTools/kpt#838]
Example:
```
$ kpt pkg get https://github.com/prachirp/kpt-functions-catalog/examples/helm-template@helm-template-example .
fetching package examples/helm-template from https://github.com/prachirp/kpt-functions-catalog to helm-template
Error: helm-template/helloworld-chart/templates/deployment.yaml: yaml: line 5: did not find expected node content
$ ls
helm-template
```
I ran `kpt pkg get` on a directory containing a helm chart and saw that the command exited with an error. But when I checked, I see that it kpt pkg got the directory correctly. The command should output a warning with the error but exit gracefully since it succeeded in getting the package.

**Comment by mortent** [comment]
@prachirp Is the repo in the example still available? It doesn't look like I have access. I would like to be able to reproduce it so I can understand why we get an error here.

**Comment by prachirp** [comment]
@mortent the code is at: https://github.com/GoogleContainerTools/kpt-functions-catalog/blob/master/tests/helm_template.sh#L81

**Comment by mortent** [comment]
The package at https://github.com/prachirp/kpt-functions-catalog/examples/helm-template contains files with `yaml` extension that are not actually valid yaml. In this case they are Helm templates. 
Kpt assumes that files in the package contain actual yaml files and will report an error if not. Kpt relies on being able to parse yaml in order to do support automatic setters and KRM-aware merging of resources during updates. 
Is there a way to either rename the extension of the Helm templates to something different than yaml or not include them directly in the kpt package?

**Comment by prachirp** [comment]
It's okay for kpt to warn if the files in the package are not valid yaml. My expectation on how kpt can handle helm template packages is to

- Ideally kpt gets the package and creates a new local directory containing invalid yaml files, throw a warning message about invalid yaml, and exit with exit code 0
- Alternately kpt fails to get the package, no new directories are created locally, throw an error message saying why the get command failed, exit with non-zero exit code.

Right now kpt does a mix of the above two scenarios, which gives users mixed messages. Can we move more towards the first scenario? Changing non-fatal errors to warnings which don't trigger non-zero exit code should fix this.

**Comment by frankfarzan** [comment]
@mortent We should think more generally about non-k8s yaml/json files in kpt packages. We've discussed an ignore list in the past. Mocking with permissions seems kind of hacky.

**Comment by mortent** [comment]
I agree. An ignore list sounds reasonable. I think we should use an `.kptignore` (or `.krmignore`) file that must exist on the root of the package (i.e. parallel to the Kptfile). The format will be the same as the `.gitignore` file and any files/folders added to the file will be ignored for all purposes in kpt, except it will be downloaded as part of the package from git.
@frankfarzan WDYT?

**Comment by mortent** [comment]
This issue seems very similar to https://github.com/GoogleContainerTools/kpt/issues/517 now. 
I have a PR to add support for `.krmignore`/`.kptignore` files: https://github.com/kubernetes-sigs/kustomize/pull/2898. I think that should address this issue.

**Comment by yuwenma** [comment]
Agree with what @mortent said. 
I'm cleaning up the kpt issue list and will close this one to defer https://github.com/GoogleContainerTools/kpt/issues/517 for the kpt ignorefile discussions.
