### ISSUE TITLE
kpt live diff errors out when (only) resource is deleted

### ISSUE THREAD

**Issue by vaseeharan** [GoogleContainerTools/kpt#842]
When following the example provided in `kpt guide Apply`, I ran `kpt live diff` after removing `helloworld/deploy.yaml`, expecting it to show the Deployment resource to be deleted in the diff output. 

```
rm helloworld/deploy.yaml
kpt live diff helloworld/
kpt live preview helloworld/
kpt live apply helloworld/ --reconcile-timeout=2m
```

However, the command errors out as follows:

```
kpt live diff helloworld/
error: You must provide one or more resources by argument or filename.
Example resource specifications include:
   '-f rsrc.yaml'
   '--filename=rsrc.json'
   '<resource> <name>'
   '<resource>'
```

`kpt live preview` and `kpt live apply` worked as expected.

**Comment by seans3** [comment]
`kpt live diff` command has been removed -- closing
