### ISSUE TITLE
Clearer error message when running kpt live apply

### ISSUE THREAD

**Issue by vaseeharan** [GoogleContainerTools/kpt#857]
when running `kot live apply` on an uninitiated target, the error messages says to please run the "init" command & the next line says "The package needs to be initialized". This confused me for a while, because I thought it meant running `kpt pkg init`. Of course I needed to run `kpt live init`

Could the error message be made more explicit? e..g please run "kpt live init" 

Thanks!

```
kpt live apply package-examples/helloworld/

Fatal error: Package uninitialized. Please run "init" command.

The package needs to be initialized to generate the template
which will store state for resource sets. This state is
necessary to perform functionality such as deleting an entire
package or automatically deleting omitted resources (pruning).
```

**Comment by mortent** [comment]
Next release of kpt will include a fix where the full `kpt live init` command is included in the error message.
