### ISSUE TITLE
Create a linter to remove status from configs 

### ISSUE THREAD

**Issue by prachirp** [GoogleContainerTools/kpt#876]
We need a setter or kpt function which can remove the status field for configs so that only the declarative configuration remains. This will allow users to follow GitOps principles by committing only the necessary configuration to a repository.

**Comment by prachirp** [comment]
Other fields like `creationTimestamp` and `selfLink` can also be auto-removed.

**Comment by phanimarupaka** [comment]
Is this issue still relevant ? You can develop a kpt function to do so.

**Comment by prachirp** [comment]
@phanimarupaka I made this issue as a good first issue to make our project more appealing to non-google contributors. Feel free to close it if you want.
