### ISSUE TITLE
Kustomize build fn errors 

### ISSUE THREAD

**Issue by prachirp** [GoogleContainerTools/kpt#879]
I've just tested it with the helm example. It works but I had to change paths in the example, because we can't have both relatively `helm-template/local-configs` and `(pwd)/helloworld-chart` at the same time in the second command. 

On the kustomize side (which was my first issue in https://github.com/GoogleContainerTools/kpt/issues/791), I still have some problem (with the image but not with the kustomize official binary). I don't think this is related to this but I prefer to share it:

```sh
Λ\: ./kpt pkg get "https://gitlab.com/davinkevin/Podcast-Server.git/distribution/kpt/podcast-server" podcast-server
fetching package /distribution/kpt/podcast-server from https://gitlab.com/davinkevin/Podcast-Server to podcast-server

/tmp/tmp-123 took 8s
Λ\: cat fn.yaml
───────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: fn.yaml
───────┼─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ # call `kpt fn run` on a directory containing this file, mounting the helm chart at /source
   2   │ apiVersion: v1
   3   │ kind: ConfigMap
   4   │ metadata:
   5   │   name: build
   6   │   annotations:
   7   │     config.kubernetes.io/function: |
   8   │       container:
   9   │         image: gcr.io/kpt-functions/kustomize-build
  10   │ data:
  11   │   path: /source
───────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

/tmp/tmp-123
Λ\: ./kpt fn run . --mount type=bind,src=(pwd)/podcast-server,dst=/source
[ERROR] Kustomize build command results in error: Error: accumulating resources: accumulateFile "accumulating resources from 'git::https://gitlab.com/davinkevin/Podcast-Server.git//distribution/kubernetes/base/': evalsymlink failure on '/source/git::https:/gitlab.com/davinkevin/Podcast-Server.git/distribution/kubernetes/base' : lstat /source/git::https:: no such file or directory", loader.New "stat /var/folders/z2/0d2vn4tn3_j7spd4v_t9y0s80000gn/T/: no such file or directory"

Error: exit status 1

/tmp/tmp-123
Λ\: kustomize build podcast-server/
apiVersion: v1
data:
  concurrent-download: "4"
...
```

Do you think we should open a new issue (or maybe the previous one) ?

PS: The binary of `kpt` hasn't be published on `brew` for the version `0.32.0` sadly 😓.

_Originally posted by @davinkevin in https://github.com/GoogleContainerTools/kpt/issues/587#issuecomment-663892463_

**Comment by prachirp** [comment]
Working command: `docker run --mount type=bind,src=$(pwd)/podcast-server,dst=/source gcr.io/kpt-functions/kustomize-build -d path=/source`.

The error is coming from here: https://github.com/kubernetes-sigs/kustomize/blob/master/api/internal/target/kusttarget.go#L393
I think it's mis-interpreting the git URL "git::https://gitlab.com/....." as a local file "/source/git::https:/gitlab.com/....." so it gave a "no such file or directory" error.

Possibly related: https://github.com/kubernetes-sigs/kustomize/issues/2538

Good next steps to debug: https://github.com/GoogleContainerTools/kpt/issues/856#issuecomment-663868434

**Comment by davinkevin** [comment]
Thanks for the answer @prachirp & @aodinokov … 

and I'm sorry, I totally forgot the network flag 😓.

I will add this to the project and see if all is ok as soon as possible. 

Thanks again 😉

**Comment by prachirp** [comment]
I just tried with `--network` and get the same error. 😓

**Comment by Shell32-Natsu** [comment]
Which version of kustomize are you using? I tried to build url `git::https://gitlab.com/davinkevin/Podcast-Server.git//distribution/kubernetes/base/` with latest version of kustomize and it works as expect.

**Comment by prachirp** [comment]
@Shell32-Natsu  It's using 3.6.1, let me update to 3.8.1.

**Comment by Shell32-Natsu** [comment]
How does kustomize-build container get the repo url `git::https://gitlab.com/davinkevin/Podcast-Server.git//distribution/kubernetes/base/`? I cannot find where is this url passed to the container.

**Comment by prachirp** [comment]
It's under `podcast-server/kustomization.yaml` resources

**Comment by Shell32-Natsu** [comment]
The issue should be permission issue inside the container.

```bash
❯ docker run -i -t --entrypoint sh --mount type=bind,src=(pwd)/podcast-server,dst=/source gcr.io/kpt-functions/kustomize-build
~/app $ cd /
/ $ ls -l source/
ls: can't open 'source/': Permission denied
total 0
/ $ ls -l | grep source
drwxr-x---    4 791935   89939         4096 Jul 29 19:36 source
/ $ kustomize build /source/
Error: unable to find one of 'kustomization.yaml', 'kustomization.yml' or 'Kustomization' in directory '/source'
/ $ whoami
node
```

If I use root user
```bash
❯ docker run -i -t --entrypoint sh --user root --mount type=bind,src=(pwd)/podcast-server,dst=/source gcr.io/kpt-functions/kustomize-build
/ # kustomize build /source
apiVersion: v1
data:
  concurrent-download: "4"
  database.url: jdbc:postgresql://database:5432/podcast-server
...
```

**Comment by prachirp** [comment]
I tried re-running using a new image at `gcr.io/kpt-functions/kustomize-build:dev` which uses the kustomize v3.8.1 and runs as `root` instead of as `node` user but get the same error.

@Shell32-Natsu why is kustomize looking for `/source/git::https:/gitlab.com` instead of just `git::https:/gitlab.com`? Do we need to change the formatting for go-getter to parse the resource correctly?

```
➜  sourceFn kpt version
0.32.0
➜  sourceFn ls
fn.yaml        podcast-server
➜  sourceFn cat fn.yaml 
apiVersion: v1
kind: ConfigMap
metadata:
  name: build
  annotations:
    config.kubernetes.io/function: |
      container:
        image: gcr.io/kpt-functions/kustomize-build:dev
        network:
          required: true
data:
  path: /source
➜  sourceFn kpt fn run . --mount type=bind,src=$(pwd)/podcast-server,dst=/source --network
[ERROR] Kustomize build command results in error: Error: accumulating resources: accumulateFile "accumulating resources from 'git::https://gitlab.com/davinkevin/Podcast-Server.git//distribution/kubernetes/base/': evalsymlink failure on '/source/git::https:/gitlab.com/davinkevin/Podcast-Server.git/distribution/kubernetes/base' : lstat /source/git::https:: no such file or directory", loader.New "stat /var/folders/jc/bvslddd177j4zlt93y1czw5h00nsnz/T/: no such file or directory"

Error: exit status 1
```

**Comment by Shell32-Natsu** [comment]
The error message is kind of misleading. Since kustomize has no idea what the input string is in `resources` in kustomization file (it can be a path, a directory or a remove repo) so it works in a heuristic way. It will try file path at first and then try directory.

`accumulating resources: accumulateFile "accumulating resources from 'git::https://gitlab.com/davinkevin/Podcast-Server.git//distribution/kubernetes/base/': evalsymlink failure on '/source/git::https:/gitlab.com/davinkevin/Podcast-Server.git/distribution/kubernetes/base' : lstat /source/git::https:: no such file or directory"` This part of error is error from file path attempt and it is expected. The real error is the last part `loader.New "stat /var/folders/jc/bvslddd177j4zlt93y1czw5h00nsnz/T/: no such file or directory"`

The codes are in `api/internal/target/kusttarget.go:273` in kustomize.

**Comment by Shell32-Natsu** [comment]
@prachirp Can you confirm that `/var/folders/jc/bvslddd177j4zlt93y1czw5h00nsnz/T/` is accessible from the container?

**Comment by prachirp** [comment]
No, there's only /var but no /var/folders inside the container.
```
docker run -i -t --entrypoint sh --mount type=bind,src=$(pwd)/podcast-server,dst=/source gcr.io/kpt-functions/kustomize-build
~/app $ cd /var/
cache/  empty/  git/    lib/    local/  lock/   log/    mail/   opt/    run/    spool/  tmp/
~/app $ cd /var/folders
sh: cd: can't cd to /var/folders: No such file or directory
```

If the last part is the main issue then #839 is a duplicate of this issue.

**Comment by Shell32-Natsu** [comment]
So now the problem is why does go-getter or kustomize cloner try to access this directory. I guess you are running container in macos so the temp directory is under `/var` instead of `/tmp`. This directory should be created before access but it looks that it doesn't. Maybe a compatibility issue between kustomize and docker.

**Comment by prachirp** [comment]
I looked more this afternoon. Kustomize calls `ioutil.TempDir` [here](https://github.com/kubernetes-sigs/kustomize/blob/e5c8b5ec8feafe90725825c492851c26846ef9ec/api/filesys/confirmeddir.go#L19) with an empty string as the dir parameter. According to `ioutil.TempDir` documentation, "If dir is the empty string, TempDir uses the default directory for temporary files (see os.TempDir)."
According to `os.TempDir` documentation, "On Unix systems, it returns $TMPDIR if non-empty, else /tmp." So I set the TMPDIR env variable in the kustomize-build docker container and got it working.

@davinkevin Please try the following, note using the gcr.io/kpt-functions/kustomize-build:dev image:
```
$cat fn.yaml 
apiVersion: v1
kind: ConfigMap
metadata:
  name: build
  annotations:
    config.kubernetes.io/function: |
      container:
        image: **gcr.io/kpt-functions/kustomize-build:dev**
        network:
          required: true
data:
  path: /source
```
```
$ mkdir sourceFn
$ ls
fn.yaml
$ kpt pkg get "https://gitlab.com/davinkevin/Podcast-Server.git/distribution/kpt/podcast-server" podcast-server
fetching package /distribution/kpt/podcast-server from https://gitlab.com/davinkevin/Podcast-Server to podcast-server
$ git init; git add fn.yaml podcast-server; git commit -m "Initial commit"
Initialized empty Git repository in /Users/prachirp/workspace/test-kpt-functions-sdk/sourceFn/.git/
...
$ kpt fn run . --network --mount type=bind,src=$(pwd)/podcast-server,dst=/source
$ git status
...
```

**Comment by prachirp** [comment]
@davinkevin I'm merging this fix and doing a release today so you'll be able to use gcr.io/kpt-functions/kustomize-build instead of dev tag.

**Comment by davinkevin** [comment]
I'm still facing the same issue. 

```shell
/tmp
Λ\: mkdir issue-879

/tmp
Λ\: cd issue-879/

/tmp/issue-879
✦ Λ\: docker image rm gcr.io/kpt-functions/kustomize-build
Error: No such image: gcr.io/kpt-functions/kustomize-build

/tmp/issue-879
Λ\: docker image rm gcr.io/kpt-functions/kustomize-build:dev
Error: No such image: gcr.io/kpt-functions/kustomize-build:dev

/tmp/issue-879
Λ\: kpt pkg get "https://gitlab.com/davinkevin/Podcast-Server.git/distribution/kpt/podcast-server" podcast-server
fetching package /distribution/kpt/podcast-server from https://gitlab.com/davinkevin/Podcast-Server to podcast-server

/tmp/issue-879 took 6s
Λ\: vim fn.yaml

/tmp/issue-879 took 3s
Λ\: kpt fn run . --network --mount type=bind,src=(pwd)/podcast-server,dst=/source
Unable to find image 'gcr.io/kpt-functions/kustomize-build:latest' locally
latest: Pulling from kpt-functions/kustomize-build
cbdbe7a5bc2a: Already exists
091983d60f65: Pulling fs layer
7bacc183740f: Pulling fs layer
c4a5a5d270d4: Pulling fs layer
0766adc612e0: Pulling fs layer
6dde5f6ac9f5: Pulling fs layer
c311ffaa7f1b: Pulling fs layer
4dd10fd13385: Pulling fs layer
0766adc612e0: Waiting
6dde5f6ac9f5: Waiting
c311ffaa7f1b: Waiting
4dd10fd13385: Waiting
c4a5a5d270d4: Verifying Checksum
c4a5a5d270d4: Download complete
7bacc183740f: Download complete
6dde5f6ac9f5: Verifying Checksum
6dde5f6ac9f5: Download complete
c311ffaa7f1b: Verifying Checksum
c311ffaa7f1b: Download complete
091983d60f65: Verifying Checksum
091983d60f65: Download complete
0766adc612e0: Verifying Checksum
0766adc612e0: Download complete
091983d60f65: Pull complete
7bacc183740f: Pull complete
c4a5a5d270d4: Pull complete
0766adc612e0: Pull complete
6dde5f6ac9f5: Pull complete
c311ffaa7f1b: Pull complete
4dd10fd13385: Verifying Checksum
4dd10fd13385: Download complete
4dd10fd13385: Pull complete
Digest: sha256:d38f2c08a24358044ec714cf9459acf35afaf03be3b79ca9378569c6e8629496
Status: Downloaded newer image for gcr.io/kpt-functions/kustomize-build:latest
[ERROR] Kustomize build command results in error: Error: accumulating resources: accumulateFile "accumulating resources from 'git::https://gitlab.com/davinkevin/Podcast-Server.git//distribution/kubernetes/base/': evalsymlink failure on '/source/git::https:/gitlab.com/davinkevin/Podcast-Server.git/distribution/kubernetes/base' : lstat /source/git::https:: no such file or directory", loader.New "stat /var/folders/z2/0d2vn4tn3_j7spd4v_t9y0s80000gn/T/: no such file or directory"

Error: exit status 1
```

I've tried the `git` operation like you did but this doesn't change anything. 

```log
Λ\: git init; git add fn.yaml podcast-server; git commit -m "Initial commit"
Initialized empty Git repository in /private/tmp/issue-879/.git/
[master (root-commit) daa5117] Initial commit
 10 files changed, 364 insertions(+)
 create mode 100644 fn.yaml
 create mode 100644 podcast-server/Kptfile
 create mode 100644 podcast-server/ingress/ingress.yaml
 create mode 100644 podcast-server/ingress/tls.crt
 create mode 100644 podcast-server/ingress/tls.key
 create mode 100644 podcast-server/inventory-template.yaml
 create mode 100644 podcast-server/kustomization.yaml
 create mode 100644 podcast-server/storage/backend.storage.yaml
 create mode 100644 podcast-server/storage/database.storage.yaml
 create mode 100644 podcast-server/storage/fs.storage.yaml

issue-879 on  master

Λ\: kpt fn run . --network --mount type=bind,src=(pwd)/podcast-server,dst=/source
[ERROR] Kustomize build command results in error: Error: accumulating resources: accumulateFile "accumulating resources from 'git::https://gitlab.com/davinkevin/Podcast-Server.git//distribution/kubernetes/base/': evalsymlink failure on '/source/git::https:/gitlab.com/davinkevin/Podcast-Server.git/distribution/kubernetes/base' : lstat /source/git::https:: no such file or directory", loader.New "stat /var/folders/z2/0d2vn4tn3_j7spd4v_t9y0s80000gn/T/: no such file or directory"

Error: exit status 1
```

Did I forget something ? I've removed all my containers to be sure to fetch the one you build recently. 

The `fn.yaml` file is the same you provide before: 

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: build
  annotations:
    config.kubernetes.io/function: |
      container:
        image: gcr.io/kpt-functions/kustomize-build
        network:
          required: true
data:
  path: /source
```

**Comment by prachirp** [comment]
@davinkevin Thanks for testing! Let me check further, I had tried some local changes like using root user which were not released.

**Comment by prachirp** [comment]
@davinkevin The issue comes from the TMPDIR env variable pointing to /var/folders/.... I ran `unset TMPDIR` or set `TMPDIR=/tmp` locally and saw it working. I'm not sure why it's still reading TMPDIR from the local file system after I set `ENV TMPDIR /tmp` in the docker image.

The git commands were just to see a diff before and after running `kpt fn run` and be able to undo those changes easily and rerun the command.

@Shell32-Natsu, @monopole : Can we modify the code [here](https://github.com/kubernetes-sigs/kustomize/blob/master/api/filesys/confirmeddir.go#L20) to call ioutil.TempDir("/tmp", "kustomize-")?

**Comment by Shell32-Natsu** [comment]
Using "/tmp" assumes the kustomize is running on *nix system.

**Comment by monopole** [comment]
That might cause trouble on windows.  

The info above
```
"stat /var/folders/z2/0d2vn4tn3_j7spd4v_t9y0s80000gn/T/: no such file or directory"
```
seems to imply that `ioutil.TempDir` is failing to provide a valid tmp dir on mac OS. (??)

A possible fix might be to call FileSystem.IsDir inside https://github.com/kubernetes-sigs/kustomize/blob/master/api/filesys/confirmeddir.go#L20
(after the call to TempDir) to confirm that the tmpdir exists, and if not, attempt /tmp, and if that fails, panic

**Comment by monopole** [comment]
related but closed issue: https://github.com/drud/ddev/issues/134

**Comment by monopole** [comment]
@prachirp something to try is make a small go program like
```
package main

import (
	"fmt"
	"io/ioutil"
	"os"
)

func main() {
	d, err := ioutil.TempDir("", "kustomize-")
	if err != nil {
		fmt.Println("ioutil.TempDir failure")
		panic(err)
	}
	fmt.Printf("Tmpdir: '%s'\n", d)
	info, err := os.Stat(d)
	if err != nil {
		fmt.Printf("'%s' does not exist\n", d)
		return
	}
	fmt.Printf("%s isDir=%v\n", info.Name(), info.IsDir())
}
```
and run it in a container on macos with and without
```
ENV TMPDIR /tmp
```
and see what happens

**Comment by monopole** [comment]
and throw a 
```
fmt.Printf("TMPDRI = '%s'\n", os.Getenv("TMPDIR"))
```
in there too

**Comment by davinkevin** [comment]
@prachirp The env `TMP` is overriden by the code launching the docker container in `kpt` (which is part of the `kyaml/kustomize` code): 

https://github.com/kubernetes-sigs/kustomize/blob/master/kyaml/fn/runtime/container/container.go#L196

This is why `kustomize` try to use unix `TMP` folder. 

Maybe, we should reset the env variable in the nodejs code or not append this variable in the first place… I let you choose 😉

**Comment by Shell32-Natsu** [comment]
@monopole Have tried on macOS and this little program works properly (as Go library documented).

@davinkevin Thanks for the investigation. That's the exact reason for this issue.

This is not the issue of function but the issue in kpt/kustomize. We should fix this in kpt/kustomize (by ignoring `TMPDIR` env) because this will happen in every go function that tries to use temp dir on macOS.

BTW, I believe explicitly `export TMPDIR=/tmp` before running function can bypass this issue.

**Comment by monopole** [comment]
`TMPDIR` is the env var in question here, not `TMP`.

KRM Config Functions written in Go and attempting to use `os.TempDir` or `ioutil.TempDir` should work as expected - they shouldn't have to do something special on macos.

**Comment by Shell32-Natsu** [comment]
@prachirp Please check with latest kyaml module.

**Comment by prachirp** [comment]
@Shell32-Natsu Can you do a release of kyaml? The last release was 2 wks ago.
Then we can update kpt's version of kyaml for the next kpt release.

**Comment by Shell32-Natsu** [comment]
I don't have push permission in kustomize repo. @monopole Would you like to do this?

**Comment by prachirp** [comment]
@davinkevin We released this with kpt 0.33.0 last week. Can you verify this works for you?

**Comment by prachirp** [comment]
@davinkevin I am closing this out. Please file a new issue if anything comes up.

**Comment by davinkevin** [comment]
I didn't have the previous error with the version 0.33.0 🎉. Thanks for your help/support.

When I run the command `kpt fn run . --network --mount type=bind,src=(pwd)/podcast-server,dst=/source`, the result is stored inside the previously downloaded folder. Is this normal? I though it should print all to the standard stdout?

**Comment by prachirp** [comment]
Hey @davinkevin, Running `kpt fn run` alone automatically sources and sinks from the provided DIR/, in this case `.`. Manually source from `.` and skip sink in order to print out the resources instead of writing them to file.
`kpt fn source . | kpt fn run --network --mount type=bind,src=$(pwd)/podcast-server,dst=/source`
You can also choose to sink them to a separate directory than where they were sourced
```
mkdir output
kpt fn source . | kpt fn run --network --mount type=bind,src=$(pwd)/podcast-server,dst=/source | kpt fn sink output
```
This will output the kustomized config to `output/podcast-server` instead of `./podcast-server`.

**Comment by davinkevin** [comment]
Perfect 👍. 

Thank your for your help and your time ❤️
