### ISSUE TITLE
`kpt fn run` produces unexpected results.

### ISSUE THREAD

**Issue by ZhuGongpu** [GoogleContainerTools/kpt#884]
```
kpt pkg get https://github.com/GoogleContainerTools/kpt/package-examples/function-export-blueprint example-package
cd example-package
git init && git add .
kpt fn run .
git diff
```
`ConfigMap` of `label-namespace` in `functions.yaml` is removed.

**Comment by ZhuGongpu** [comment]
@frankfarzan

**Comment by frankfarzan** [comment]
This file contains two ConfigMaps, both names are unspecified. So `kpt fn run` only keeps one of them.

kpt should flag these as validation issues instead of silently deleting one of them.

**Comment by droot** [comment]
We are introducing a better way of running functions in a declarative way in 1.0. Assigning this bug to 1.0 milestone to ensure we verify this use-case with 1.0 release.

**Comment by droot** [comment]
Thought some more and realize this bug will not be relevant with 1.0 because we will be moving away from the `ConfigMap` to specify which functions to run.

**Comment by phanimarupaka** [comment]
This is not relevant is kpt v1.
