### ISSUE TITLE
kpt pkg update -- incorrect git repo detection

### ISSUE THREAD

**Issue by MrTrustor** [GoogleContainerTools/kpt#885]
The `kpt pkg update` command, when run outside of the git repo, complains that my package is not in a git repo even if it is.
It correctly detects the git repo after cd-ing into it.

```bash
theochamley@cloudshell:~ (theochamley-tests)$ cd helloworld-set/
theochamley@cloudshell:~/helloworld-set (theochamley-tests)$ git init
Initialized empty Git repository in /home/theochamley/helloworld-set/.git/
theochamley@cloudshell:~/helloworld-set (theochamley-tests)$ git add .
theochamley@cloudshell:~/helloworld-set (theochamley-tests)$ git commit -m "First version of helloworld"
[master (root-commit) 226b399] First version of helloworld
 5 files changed, 202 insertions(+)
 create mode 100644 Kptfile
 create mode 100644 README.md
 create mode 100644 deploy.yaml
 create mode 100644 inventory-template.yaml
 create mode 100644 service.yaml
theochamley@cloudshell:~/helloworld-set (theochamley-tests)$ cd ..
theochamley@cloudshell:~ (theochamley-tests)$ kpt pkg update helloworld-set@v0.5.0 --strategy resource-merge
updating package helloworld-set to v0.5.0
Error: kpt packages must be checked into a git repo before they are updated: exit status 128
theochamley@cloudshell:~ (theochamley-tests)$ cd helloworld-set/
theochamley@cloudshell:~/helloworld-set (theochamley-tests)$ kpt pkg update .@v0.5.0 --strategy resource-merge
updating package . to v0.5.0
theochamley@cloudshell:~/helloworld-set (theochamley-tests)$ kpt version
v0.30.1
```

**Comment by phanimarupaka** [comment]
@MrTrustor Kpt relies heavily on git libraries to get/update packages. If you perform `git status hello-world-set` from the directory not tracked by git, it fails. kpt update also fails due to that. kpt update only accepts relative paths and the parent dir from where you are running the update command from should be tracked by git. 

cc @pwittrock

**Comment by MrTrustor** [comment]
> kpt update only accepts relative paths and the parent dir from where you are running the update command from should be tracked by git.
That would be a reasonable behaviour if kpt update didn't also ask me to provide a path as a parameter.
But since I do provide a path, I expect kpt to be able to figure that out. I've never used the Go Git library, but in pure Git, the GIT_DIR and GIT_WORK_TREE variables should help solve this.

**Comment by phanimarupaka** [comment]
@MrTrustor Agree. I have a PR to address it. Thanks for the issue.

**Comment by phanimarupaka** [comment]
@MrTrustor Per comment in the PR above, the current behavior is expected. Making parent directory tracked by git will help you from disaster recovery in case the package is deleted during failure cases. Is it a major UX concern for your use-case?

**Comment by MrTrustor** [comment]
> Making parent directory tracked by git will help you from disaster recovery in case the package is deleted during failure cases.

I don't understand why making the _parent_ directory of the package a git repo instead of the package itself directly would be better here. In both cases, my package is tracked in Git, and I can recover.
And if that's an assumption that kpt makes/wants to make, then it needs to be clearly documented.

> Is it a major UX concern for your use-case?

It's not a *major* problem, it's just completely illogical to me, and frankly looks and feels like a bug. It's also a complete departure from the UX of any other git-based tools that I can think of that usually either require your working directory to be the root of the git repo, or just don't care at all as long as you're in a git repo.

I can also think of a use-case where this would be a problem (it's just not _my_ current use-case): I'm a package developer, and I want to have one git repo per package to publish them. It means that I can just have my Kptfile at the root my repo: I need to create "artificially" a useless directory in my repo to actually host my package.
