### ISSUE TITLE
Docs for Kptfile schema is empty 

### ISSUE THREAD

**Issue by janetkuo** [GoogleContainerTools/kpt#921]
https://googlecontainertools.github.io/kpt/api-reference/kptfile/

**Comment by etefera** [comment]
Swagger and kpt file are referenced from a bad directory: this can be fixed by adding ```<script src="/kpt/js/swagger-ui-bundle.js"></script>
<script src="/kpt/js/swagger-ui-standalone-preset.js"></script>
{{< swaggerui src="/kpt/openapi/kptfile.yaml" >}}``` to https://github.com/GoogleContainerTools/kpt/blob/master/site/content/en/api-reference/kptfile/_index.md

However, the yaml file errors with `No operations defined in spec!` What's the expected output here?

**Comment by janetkuo** [comment]
Is it because kptfile doesn't have a `spec` field?

I'd expect something like this: https://skaffold.dev/docs/references/yaml/
