### ISSUE TITLE
SDK - How can I output non-yaml content from a kpt function

### ISSUE THREAD

**Issue by pyljain** [GoogleContainerTools/kpt#929]
I'm writing a function that will output a svg based on the existing KRM configuration.

```bash
kpt fn run DIR/ --image=payaljain/my-image-gen-function:0.1 -- output=out.svg
```

I couldn't find an example in the kpt docs or in the kpt functions catalog that would show me how this can be done (I'm using the go sdk). If I mount a local volume when running my function and try to write a file, I get the error "open /dest/out.svg: no such file or directory"

```bash
kpt fn run DIR/ --mount type=bind,src=$(pwd)/svg_output,dst=/dest --image=payaljain/my-image-gen-function:0.1 -- output=/dest/out.svg
```
I am able to write the svg data as a key in the output yaml that is saved to the results directory. However I want to be able to create a svg file directly instead.

**Comment by frankfarzan** [comment]
@prachirp Who's been working on the documentation for functions requiring host priviledges.

**Comment by prachirp** [comment]
Hey @pyljain Kpt mounts volumes as readonly by default. You can explicitly set kpt to mount a read-write volume by setting the argument. Then you can write a file directly to your mounted volume. See the example command here: https://googlecontainertools.github.io/kpt/reference/fn/run/#mounting-directories

**Comment by pyljain** [comment]
Thanks @prachirp! That worked for me. I had to upgrade from 0.27.0 -> 0.32.0 and use the rw option in the mount.
