### ISSUE TITLE
Provide a way to tag resources that should not be applied

### ISSUE THREAD

**Issue by mortent** [GoogleContainerTools/kpt#932]
`kpt live apply` will currently try to apply all manifests found in the package. But there are a few situations where it is useful to be able to tag resources that should be ignored. Some examples:
 * `Kustomization.yaml` files
 * Client-side CRDs that are used to generate other resources, but should themselves be applied
 * Kpt functions declared as annotations on a resource.

Using an annotation for this seems pretty reasonable. Maybe there already is prior art here we can use.

**Comment by mortent** [comment]
This is related to https://github.com/GoogleContainerTools/kpt/issues/755

**Comment by seans3** [comment]
Related PR for `no-process` annotation: https://github.com/kubernetes-sigs/kustomize/pull/2620

**Comment by frankfarzan** [comment]
There's already a `config.kubernetes.io/local-config: 'true'` annotation. Where's this consumed today?

**Comment by frankfarzan** [comment]
@seans3 could you follow up with a design proposal that takes `local-config` into account?

**Comment by mortent** [comment]
@frankfarzan Here is a short explanation of what how we can address this issue using the `local-config` anntation.

The proposal here is to use the `config.kubernetes.io/local-config` annotation that is defined as part of the kyaml module to allow users to tag resources that should be ignored by kpt live commands. The kpt documentation currently lack proper documentation on the purpose of this annotation, but the api-conventions doc in the cmd/config module actually explains the rationale for the annotation: https://github.com/kubernetes-sigs/kustomize/blob/master/cmd/config/docs/api-conventions/config-io.md#configkubernetesiolocal-config. This description pretty accurately describes what we want to achieve here.

Resources with this annotation should be excluded in all kpt live commands, including `kpt live init`. We will do this by implementing support for this in the `manifestreader` package which is used by most of the kpt live commands for reading the resources. We already have a PR for this: https://github.com/kubernetes-sigs/cli-utils/pull/226

We also need to update the documentation to cover this annotation.

**Comment by frankfarzan** [comment]
sgtm

**Comment by wpwoodjr** [comment]
It would be great if this could be used to prevent an optional resource from being deployed, which I think it could, for example to prevent an Ingress from being deployed:
```
$ kpt cfg create-setter . ingress-disabled --field metadata.annotations.config.kubernetes.io/local-config true
```
But one issue is, you can't specify that this setter be in the Ingress resource.  I'll open an issue for that.
