### ISSUE TITLE
Allow all kpt function run features to be run purely declaratively

### ISSUE THREAD

**Issue by prachirp** [GoogleContainerTools/kpt#933]
Quite a few kpt fn run features like environment variables require the user to imperatively set options. Few examples below:

Environment variables -  User has to export the local variable before running `kpt fn run`
Mounting volumes - User needs to imperatively set the absolute path of the volume being mounted
Network - Functions which require network need it enabled imperatively as part of the `kpt fn run` command

We should ease the story for users to use these features purely declaratively.

cc @frankfarzan

**Comment by Liujingfang1** [comment]
One idea is to allow specifying those flags in Kptfile. So that when users run `kpt fn run <DIR>`, all the needed flags are already included in the Kptfile.

**Comment by Shell32-Natsu** [comment]
@frankfarzan Could you make a comment about forbidding mounting declaratively?
