### ISSUE TITLE
Unable to run the kpt fn catalog `kutomize-build` following the example

### ISSUE THREAD

**Issue by yuwenma** [GoogleContainerTools/kpt#934]
I followed the [kpt fn doc](https://github.com/GoogleContainerTools/kpt-functions-catalog/tree/master/examples/kustomize-build/) to try out the kustomize-build kpt fn. 

I ran the following commands 
```bash
kpt pkg get https://github.com/GoogleContainerTools/kpt-functions-catalog.git/examples/kustomize-build .

kpt fn run kustomize-build/local-configs --mount type=bind,src="$(pwd)"/kustomize-build/kustomize-dir,dst=/source
``` 

And got the below error. 
```bash
[ERROR] Kustomize build command results in error: Error: Error creating new loader with git: uri looks like abs path: /source, dir: evalsymlink failure on '/source' : lstat /source: no such file or directory, get: invalid source string: /source
```

Since this may due to [an existing issue](https://www.google.com/url?sa=j&url=https%3A%2F%2Fgithub.com%2FGoogleContainerTools%2Fkpt%2Fissues%2F879&uct=1581463778&usg=KftXJHVCDKo_N0Sj0I5KZqlXGsE.&source=chat) (Thanks @prachirp for the pointer), I tried two alternatives, but both give the same error message

Alterantive 1:
export TMPDIR=/tmp

Alternative 2:
I built the kustomize-build from the kpt-funtions-catalog repo head since the latest code includes the fix to issue 879

```bash
cd ./kpt-functions-catalog/functions/ts
docker build . --file ./build/kustomize_build.Dockerfile
```
I pushed the new image to my own container registry `gcr.io/yuwenma-gke-playground/kustomize-build`, updated the kustomize-fn.yaml.

But still get the same error.

**Comment by prachirp** [comment]
I tried to duplicate this on Mac with `export TMPDIR=/tmp` but did not get any error so I suspect it may be some difference between our environments.

**Comment by prachirp** [comment]
@Shell32-Natsu can you reproduce this?
@monopole FYI

**Comment by yuwenma** [comment]
building kpt from the head solves the problem. Thanks @prachirp
