### ISSUE TITLE
Kpt fn creating duplicate resources

### ISSUE THREAD

**Issue by felixtran39** [GoogleContainerTools/kpt#938]
Example (recreate issue):
1. Create a kpt pipeline:
a)`gcr.io/kustomize-functions/example-nginx`
b) `gcr.io/kpt-functions/set-namespace`
2. Run `kpt fn run .` in the directory with the kpt pipeline twice.
3. View contents of either deployment_*.yaml or service_*.yaml.

You will see that the two configurations are really similar. The difference is in the ordering of the metadata section. One of the duplicates will have the metadata ordered as `[name, namespace, labels]` and the other will have `[name,labels,namespace]`.

The problem here is that the deployment and service yamls will store what is essentially the same configuration twice.

**Comment by seans3** [comment]
@felixtran39 So if I understand what you're saying: the `set-namespace` function is not idempotent. Is that correct?

**Comment by felixtran39** [comment]
@seans3 Not exactly. Based on my understanding, this is what I think is happening.
**The first time the pipeline runs:** deployment/service resources are generated and then transformed with `set-namespace`. However, since the generated configs don't specify the namespace, `set-namespace` will specify a namespace at the bottom of the metadata section even if this does not agree with the ordering that kpt uses.
**The second time the pipeline runs:** the deployment/service resources generated from the first run are out of order, so the ordering of namespace and labels is corrected. The actions from the pipeline are then repeated as in the first run. However, the output of the pipeline has "incorrect ordering" so it ends up concatenating this configuration to the deployment/service resources, causing duplicates.

**Comment by prachirp** [comment]
@felixtran39 What is your expectation for how kpt should behave on duplicate resources?

The example-nginx function is a [generator function](https://googlecontainertools.github.io/kpt/guides/consumer/function/catalog/#generators), so it creates new resources from templates each time it is run. If you create a kpt pipeline with only `gcr.io/kustomize-functions/example-nginx` and run it twice, do you expect to get duplicate resources or do you expect kpt to have de-duplicated the repeated resources?

**Comment by felixtran39** [comment]
@prachirp I expect kpt to de-duplicate the repeated resources.

**Comment by mikebz** [comment]
@droot interesting case to consider here

**Comment by droot** [comment]
@mikebz yes, this is going to be common occurrence if one is using generator function so de-duplication will address most of the cases we care about. Marking it 1.0 for now.

**Comment by droot** [comment]
Though this was reported for kpt alpha, we need to ensure behavior is clear for kpt v1.0.

**Comment by droot** [comment]
This is a duplicate of https://github.com/GoogleContainerTools/kpt/issues/2466 so closing this.
