### ISSUE TITLE
Permission denied in container when using kpt fn run with bind mount

### ISSUE THREAD

**Issue by Shell32-Natsu** [GoogleContainerTools/kpt#939]
If a user uses `kpt fn run` with bind type mount, the mount point inside the container is not accessible by `nobody`.

## How to reproduce

```bash
docker run --user nobody --rm -it --entrypoint sh --mount type=bind,src=(pwd),dst=/source,readonly alpine
~ $ cd /
~ $ ls -l
total 60
...
drwxr-x---    2 791935   89939         4096 Aug  7 19:28 source
...
~ $ ls /source
ls: can't open '/source': Permission denied
```

`--user nobody` is added by kpt and `USER` setting in Dockerfile is overwritten.

## What's the reason

The UID and GID for mount point in the container is still using the information from host system and they don't exist in the container.

I don't find an option for `--mount` to solve this problem.

## Work around

User needs to explicitly give permission to everyone for the directory in host system, e.g. `chmod a+rx .`

**Comment by frankfarzan** [comment]
By definition, nobody doesn't have host access. I think you want to specify a user id that exists on the host and has access to that directory.

**Comment by zhihansh** [comment]
As Donny said, kpt functions are all run as nobody. This is specified by command line options when kpt invokes docker so the settings in Dockerfile don't work. 

I did not find any way we change the user id.

**Comment by Shell32-Natsu** [comment]
@zhihansh is correct. kpt runtime will explicitly add a `--user nobody` when call docker.

https://github.com/kubernetes-sigs/kustomize/blob/8cd7c13faddf92926e29ce485db1c1fc275ed272/kyaml/fn/runtime/container/container.go#L184

@frankfarzan

**Comment by frankfarzan** [comment]
@prachirp can you provide an example (e.g. Helm) that successfully reads from a host volume?

**Comment by prachirp** [comment]
This is the blueprint shown [here](https://github.com/GoogleContainerTools/kpt-functions-catalog/tree/master/examples/helm-template)
```
kpt pkg get https://github.com/GoogleContainerTools/kpt-functions-catalog.git/examples/helm-template .
kpt fn run helm-template/local-configs --mount type=bind,src=$(pwd)/helloworld-chart,dst=/source
```

A different version depends on using helm CLI just in case `kpt pkg get` files have more permissive settings.
```
kpt pkg get https://github.com/GoogleContainerTools/kpt-functions-catalog.git/examples/helm-template/local-configs .
helm create helloworld-chart
kpt fn run local-configs --mount type=bind,src=$(pwd)/helloworld-chart,dst=/source
```

**Comment by frankfarzan** [comment]
It's world readable:

mount » ls -l helm



           <<<
total 16
-rw-------  1 frankf  wheel   297 Aug 13 16:14 Kptfile
-rw-r--r--  1 frankf  wheel  1282 Aug 13 16:14 README.md
drwxr-xr-x  6 frankf  wheel   192 Aug 13 16:14 helloworld-chart
drwxr-xr-x  3 frankf  wheel    96 Aug 13 16:14 local-configs
mount »



          <<<
mount »



          <<<
mount » ls -l helm/helloworld-chart



          <<<
total 16
-rw-r--r--  1 frankf  wheel   914 Aug 13 16:14 Chart.yaml
drwxr-xr-x  9 frankf  wheel   288 Aug 13 16:14 templates
-rw-r--r--  1 frankf  wheel  1563 Aug 13 16:14 values.yaml

**Comment by Shell32-Natsu** [comment]
I even cannot get the package.

```
kpt pkg get https://github.com/GoogleContainerTools/kpt-functions-catalog.git/examples/helm-template .
fetching package /examples/helm-template from https://github.com/GoogleContainerTools/kpt-functions-catalog to helm-template
Error: helm-template/helloworld-chart/templates/deployment.yaml: yaml: line 5: did not find expected node content
```

**Comment by Shell32-Natsu** [comment]
```
❯ chmod -R 0750 helm-template/

❯ kpt fn run helm-template/local-configs --mount type=bind,src=(pwd)/helm-template/helloworld-chart,dst=/source
[ERROR] Helm template command results in error: Error: validation: chart.metadata is required

Error: exit status 1

❯ chmod -R 0755 helm-template/

❯ kpt fn run helm-template/local-configs --mount type=bind,src=(pwd)/helm-template/helloworld-chart,dst=/source && echo $status
0

# I am using fish so I use $status instead of $?
```

The function doesn't work if I don't update the permission.

**Comment by frankfarzan** [comment]
Docker mount permissions are different on Linux and Mac:

**Comment by Shell32-Natsu** [comment]
Will that introduce security concerns? I am thinking about the reason for hardcoding nobody user in the implementation.

**Comment by frankfarzan** [comment]
@Shell32-Natsu Assigning this to you.
 
As it stands, this documentation is wrong:

https://googlecontainertools.github.io/kpt/reference/fn/run/#mounting-directories

Re security: if the personae running the CLI is explicitly allowing host access, then this is a reasonable behavior. Default is `nobody`, but by definition certain functions require privilege host access.

 As part of this, I like to revisit how various Docker flags are exposed:

- Through `kpt` CLI when running a single function imperatively (i.e. `kpt fn run --image`)
- Through `kpt` CLI when running multiple functions declaratively (i.e. `kpt fn run PKG`)
- Through function delcaration

**Comment by Shell32-Natsu** [comment]
Manually confirmed this has be fixed by https://github.com/kubernetes-sigs/kustomize/pull/2890.

User flag `--fn-user root` to avoid permission issue.

**Comment by Shell32-Natsu** [comment]
We still haven't had a final decision about the flag name, reopen this.

**Comment by Shell32-Natsu** [comment]
Fixed in https://github.com/kubernetes-sigs/kustomize/pull/2992
