### ISSUE TITLE
How to set a list setter to an empty list

### ISSUE THREAD

**Issue by alex-y-kozlov** [GoogleContainerTools/kpt#942]
run ` kpt cfg set helloworld/ list-val [] ` and observe that the setter value is 

    io.k8s.cli.setters.list-val:
      type: array
      x-k8s-cli:
        setter:
          name: list-val
          listValues:
          - "[]"
          isSet: true

and the same is in the target yaml file.

what's the right way to set empty list value?

**Comment by phanimarupaka** [comment]
Currently kpt doesn't support setting empty list values. This is essentially request to clear the list. Can you let us know your use case more as to why do you want to do that in your workflow to get better understanding.

**Comment by alex-y-kozlov** [comment]
The use case as follows:
to be able to customize command and/or ins arguments in the container. Its a very common requirement
Thanks in advance!

**Comment by phanimarupaka** [comment]
This was an issue in v0 and in v1 setters are just functions(https://catalog.kpt.dev/apply-setters/v0.1/) and you can set the value to empty list.

`kpt fn eval -i apply-setters:v0.1 -- foo=""`

Please reopen the issue if you have any concerns.

**Comment by tylerreidwaze** [comment]
I am encountering this issue as well.

For a resource definition, I would like the be able to specify the empty list as most of our resources will have nothing to be placed in that list.  However, some resource definitions will need to define them manually.

For example, most resources will look like

```
  gateways: []
```

however, some may be

```
gateways:
    - projects/XXX/locations/global/gateways/mesh-ingress-443
```

the config file would ideally look like the following

```
gateways: []
```
or 
```
gateways: |
     - projects/XXX/locations/global/gateways/mesh-ingress-443
```

The latter scenario works and sets the gateways field properly.  However, I am having issues setting the empty list.  Below are some of my attempts and the values it outputs.

```
gateways: []
=>
+  gateways: "" # kpt-set: ${gateways}
```
The above value fails as downstream the expected field is an array and this is null
```
gateways: "[]"
=>
+  gateways: "[]" # kpt-set: ${gateways}
```
The above value fails downstream as the expected field is an array and this is a string

**Comment by tylerreidwaze** [comment]
From the docs at https://catalog.kpt.dev/apply-setters/v0.1/

> Since the values of configMap in pipeline definition must be of string type, the array values must be wrapped into string. However, the rendered values in the resources will be array type.

I think this means that it is not currently supported.  Could we re-open this feature request?
