### ISSUE TITLE
Refactor catalog e2e tests

### ISSUE THREAD

**Issue by prachirp** [GoogleContainerTools/kpt#944]
Once other catalog-blocker bugs are fixed, we can make the following changes:
- convert `docker run` e2e tests to use `kpt fn run` after #823 #824 
- remove `|| true` from any `kpt pkg get` commands after #838
- add test running starlark script imperatively using `kpt fn run` after SDKs are aligned on using `data` field #757 
- modify source function blueprints to pull fn-config.yaml out of local-configs folder after #837

**Comment by mengqiy** [comment]
The e2e tests have been overhauled.
