### ISSUE TITLE
delete-setter doesn't properly clean up references

### ISSUE THREAD

**Issue by mortent** [GoogleContainerTools/kpt#947]
The delete-setter command doesn't properly clean up all the references to the setter in the manifests. To reproduce:
```
git clone git@github.com:mortent/kpt-packages.git
cd kpt-packages
git checkout 2278864213852e7d563b97cbea63267569efdbe6
cd kafka
kpt cfg delete-setter . replicas
cat statefulset.yaml
```
Notice that the StatefulSet manifest still contains references to the `replicas` setter in the env variables.

**Comment by phanimarupaka** [comment]
https://github.com/kubernetes-sigs/kustomize/pull/2855
