### ISSUE TITLE
Implement new feature kpt cfg search(replace)

### ISSUE THREAD

**Issue by phanimarupaka** [GoogleContainerTools/kpt#961]
Implement the new feature kpt cfg search which will help users to effectively search for fields in the yaml configs.

- [x] Search by value
- [x] Search by value regex
- [x] Put literal
- [x] Add non-existing fields
- [x] Support search by absolute paths
- [x] Support path expressions
- [x] Implement put pattern
- [x] Fishfood
- [x] Documentation

**Comment by phanimarupaka** [comment]
https://github.com/GoogleContainerTools/kpt/issues/248 is addressed with by this new feature and not with setters.

**Comment by mikebz** [comment]
copying the commentary from @bgrant0607 here https://github.com/GoogleContainerTools/kpt/issues/742#issuecomment-757046002

> This issue is the same as the one that motivated the analogous feature in kustomize.
> https://github.com/kubernetes/enhancements/blob/master/keps/sig-cli/0008-kustomize.md#long-standing-issues
> 
> The tricky part is finding references, which can't be done via naive search and replace.
> https://github.com/kubernetes-sigs/kustomize/blob/master/api/konfig/builtinpluginconsts/namereference.go

**Comment by phanimarupaka** [comment]
Search and Replace in kpt is more context aware of KRM resource files. That differentiates it from the native search and replace. It leverages syntax from yq to find the references.

**Comment by karlkfi** [comment]
How was this implemented? I don't see it in the kp v1 docs and none of the links here are to PRs that merged...

**Comment by karlkfi** [comment]
Ah, I see a function: https://catalog.kpt.dev/search-replace/v0.1/
