### ISSUE TITLE
Revisit `kpt fn run` sinking config

### ISSUE THREAD

**Issue by prachirp** [GoogleContainerTools/kpt#972]
Users are often confused where the `kpt fn run` command writes newly created configuration as it's not clear that it automatically sinks to the same directory it sourced configs from. Other tools like `sed` source and manipulate content but print it to console instead of writing to disk.

We should consider switching default behavior to only source and run functions and provide a --sink-dir flag to optionally write out configs.

cc @linde

**Comment by droot** [comment]
I agree: this has been reported quite often. Since this will involve breaking change, this makes it a good candidate for 1.0 milestone.

/cc @frankfarzan

**Comment by droot** [comment]
kpt v1 supports out-of-place mode in `fn render` and `fn eval`. We have improved the docs to explain the default behavior of `in-place` sink. I haven't seen any reports about the confusion since v1, so marking this closed.
