### ISSUE TITLE
Unclear what --namespace flag does or should do

### ISSUE THREAD

**Issue by wpwoodjr** [GoogleContainerTools/kpt#975]
Opening this issue per https://app.slack.com/client/T09NY5SBT/C0155NSPJSZ/thread/C0155NSPJSZ-1598299781.002600/1598330404.003800

I tried
```
kpt live apply . --namespace test
```
But it deployed to namespace `default`.

I've since added namespace as a setter.  This seems to be more in the spirit of kpt  if I'm honest, but still I wonder what the `--namespace` flag is for?

Should `--namespace` impact the inventory object used by kpt?

**Comment by mortent** [comment]
@wpwoodjr Thanks for creating an issue for this. I found another issue that seems similar and added a comment on it: https://github.com/GoogleContainerTools/kpt/issues/826
