### ISSUE TITLE
kpt cfg delete fails when setter name not equal to field name

### ISSUE THREAD

**Issue by wpwoodjr** [GoogleContainerTools/kpt#987]
Create the setter, give it a name that is different from the field name (`replica` vs `replicas`):
```
$ kpt cfg create-setter . replica --field spec.replicas 4
$ kpt cfg list-setters .
    NAME        VALUE     SET BY   DESCRIPTION   COUNT   REQUIRED
  image-tag   latest                             1       No
  image-url   test/test                          1       No
  replica     4                                  1       No
$ kpt cfg set . replica 5
set 1 fields
$ kpt cfg list-setters .
    NAME        VALUE     SET BY   DESCRIPTION   COUNT   REQUIRED
  image-tag   latest                             1       No
  image-url   test/test                          1       No
  replica     5                                  1       No
```
As expected, in the deployment yaml is now `  replicas: 5 # {"$kpt-set":"replica"}`.  Everything is good!  

Now delete the setter:
```
$ kpt cfg delete-setter . replica
$ kpt cfg list-setters .
    NAME        VALUE     SET BY   DESCRIPTION   COUNT   REQUIRED
  image-tag   latest                             1       No
  image-url   test/test                          1       No
```
Everything looks good, but wait... in the deployment yaml, is still `  replicas: 5 # {"$kpt-set":"replica"}`.

It would be very useful if this was supported because then the setter can be called something meaningful to the end user, not just the field name.  In the case of `replicas` it is ok but think about an annotation like `local-config` which makes no sense to the end user.

**Comment by phanimarupaka** [comment]
@wpwoodjr This issue has been fixed. You can expect the fix in the next kpt release.

https://github.com/kubernetes-sigs/kustomize/pull/2855
