### ISSUE TITLE
Restrict setter scope to specific resource kind

### ISSUE THREAD

**Issue by wpwoodjr** [GoogleContainerTools/kpt#988]
Per https://github.com/GoogleContainerTools/kpt/issues/932#issuecomment-683147303, there is no way to specify the `kind` of resource that a setter applies to, for example Ingress.  It would be nice if you could specify the `kind` in the field path:
```
$ kpt cfg create-setter . ingress-disabled --field Ingress.metadata.annotations.config.kubernetes.io/local-config true
```
Or else have a separate flag which specifies the `kind` that the setter applies to.

**Comment by phanimarupaka** [comment]
@wpwoodjr We are working in this direction to achieve more fine grained control for creating setters. Thanks for filing the issue.

**Comment by phanimarupaka** [comment]
Setters have gone through major transformation. Please try our the new way to [create](https://catalog.kpt.dev/search-replace/v0.1/?id=examples) and [apply](https://catalog.kpt.dev/apply-setters/v0.1/) setters and provide the feedback.

**Comment by phanimarupaka** [comment]
This issue has been fixed. Please go though https://kpt.dev/book/04-using-functions/02-imperative-function-execution?id=specifying-selectors for more information.
