### ISSUE TITLE
enable logging steps in `kpt fn run`

### ISSUE THREAD

**Issue by Liujingfang1** [GoogleContainerTools/kpt#995]
@ZhuGongpu added an option in kyaml to log which function is running ([PR](https://github.com/kubernetes-sigs/kustomize/pull/2826)) This is available since kyaml v0.6.1. `kpt fn run` need to have a flag to set this option.

cc @frankfarzan  @yuwenma  @Shell32-Natsu

**Comment by ZhuGongpu** [comment]
I'll do it.

**Comment by Shell32-Natsu** [comment]
@frankfarzan Should this be added to the UX design brief?

**Comment by frankfarzan** [comment]
Yes, it be good to briefly describe the flag and the output format.

**Comment by Shell32-Natsu** [comment]
@ZhuGongpu @Liujingfang1 Do you plan to support this flag in declarative file? or only in imperative way.

**Comment by frankfarzan** [comment]
This is not a per-function feature, but about orchestration of functions. So it doesn't make sense to be declared in each function

**Comment by Liujingfang1** [comment]
Agreed with Frank that it is only in imperative way as something like `kpt fn run . --log-steps`

**Comment by prachirp** [comment]
@Liujingfang1 Is this done?

**Comment by Liujingfang1** [comment]
@prachirp This is done. The flag `--log-step` is available from the kpt head.
