### ISSUE TITLE
Function catalog landing page blurbs

### ISSUE THREAD

**Issue by monopole** [GoogleContainerTools/kpt#999]
The [front page of the catalog](https://googlecontainertools.github.io/kpt/guides/consumer/function/catalog) should:

-  directly answer these questions with one sentence:
   - what is a function
   - who would use one
   - who would write one
- have a diagram (source->pipe->sink)

**Comment by frankfarzan** [comment]
Re "diagram", there's a concepts page:

https://googlecontainertools.github.io/kpt/concepts/functions/

Feel free to edit and link to it if needed.
